### ISSUE TITLE
Alexa per Sonoff ch4pro_dual R2_Rf bridge

### ISSUE THREAD

**Issue by Carmelo66** [xoseperez/espurna#1003]
Hi, I'm a beta tester of Alexa and with Sonoff basic with Espurna everything works ok and it's perfect, but with the sonch 4ch pro + Sonoff dua R2 and Rf Bridge the command is processed and confirmed but the relays are not activated.
How can I fix this?

**Comment by xoseperez** [comment]
Can you check the debug log to see if the commands are being received by the device? Does Alexa respond with an "ok"?

**Comment by Carmelo66** [comment]
The command is received and it is OK, but the relay always remains Off.
I tried to give the command to Alexa while the relay is access and she gives ok and always turns the relay off

**Comment by Carmelo66** [comment]
[953718] [ALEXA] Device #1 state: OFF

**Comment by Carmelo66** [comment]
Is Sonoff dual R2

**Comment by xoseperez** [comment]
Just checked with the RFBRidge and it's working fine for me... What Amazon device do you have? Current implementation might not be compatible with v2 devices.

**Comment by xoseperez** [comment]
Please, add some more line from the debug log, what happens before? and after?

**Comment by Carmelo66** [comment]
I have 6 devices Sonoff basic version 1, 2 devices Sonoff ch4pro version 1, 4 devices Sonoff Dual R2 version 1 and 1 device Sonoff Rf bridge version 2, all with Espurna 1.13.0 and all devices are detected by Alexa app with Echo device but only the  Sonoffs basic connected to the lights work.

**Comment by Carmelo66** [comment]
For Sonoff Basic the log is this:
[515739] [ALEXA] Device #0 state: ON
[515742] [RELAY] #0 scheduled ON in 0 ms
[515754] [RELAY] #0 set to ON
[515757] [MQTT] Sending Espurna_6/relay/0 => 1 (PID 1)
[515759] [MQTT] Sending domoticz/in => {"idx": 35, "nvalue": 1, "svalue": ""} (PID 1)
[515925] [MQTT] Received domoticz/out => {
   "Battery" : 255,
   "RSSI" : 12,
   "description" : "",
   "dtype" : "Light/Switch",
   "id" : "00014073",
   "idx" : 35,
   "name" : "Luce_Salotto",
   "nvalue" : 1,
   "stype" : "Switch",
   "switchType" : "On/Off",
   "unit" : 1
}

**Comment by Carmelo66** [comment]
All devices that have only one relay (type Sonoff Basic) with Alexa work perfectly, but devices that have 2 or more Alexa relays do not work, only reads the status of the relay if it is ON or OFF.
