### ISSUE TITLE
Rename Switch in Sonoff T1

### ISSUE THREAD

**Issue by seetendra** [xoseperez/espurna#1012]
Hello Everyone

Is there is away for me to rename the individual Switch in Esuprna
Iam referring to SonoffT1 3gang version
Right now Alexa is getting the names as SonoffT11_0 i want to rename is as may be Bedroom
How do i do that.

I see these right now

SonoffT11_2
SonoffT11_1
SonoffT11_0

**Comment by xoseperez** [comment]
Hi, there is no way at the moment, my solution is to use the Alexa web app to create a group with the name you want and with that single switch in it.

**Comment by xoseperez** [comment]
See #306

**Comment by seetendra** [comment]
@xoseperez any chance to have this in the roadmap?
I love Espurna and would like to use it on all the T1's that i have at home.
Please:)
