### ISSUE TITLE
Updating rfbridge from 1.12.6 to 1.13.0 does not change version number

### ISSUE THREAD

**Issue by alexyr** [xoseperez/espurna#1015]
After flashing espurna-1.13.0-itead-sonoff-rfbridge.bin from https://github.com/xoseperez/espurna/releases via web upgrade, still shows 1.12.6 in upper left corner.

**Comment by xoseperez** [comment]
It does change for me. Did the update succeed?

**Comment by alexyr** [comment]
1.12.6
Tried couple of times more.
On the third try it was updated to 1.13.0.
I am using AP mode and WIFI was loosing connection in about 80% of progress bar.
