### ISSUE TITLE
Get less RF code after hardware hack for Sonoff RF Bridge

### ISSUE THREAD

**Issue by hotsnow** [xoseperez/espurna#1019]
I installed binary firmware some time ago(version 1.12.5 or older) for my Sonoff RF Bridge, it works well. After I hack the hardware following by this wiki: https://github.com/xoseperez/espurna/wiki/Hardware-Itead-Sonoff-RF-Bridge---Direct-Hack, and install the latest version 1.13.0. It can't lean some 433 device code which can be leaned before the hack. It can still get some device code but some don't(They both work before hack). Is there some bug? 
RF Bridge R1 V2.0

**Comment by xoseperez** [comment]
The learning in the Direct mode is done using the RCSwitch library. You can try this build image by @wildwiz  here: https://github.com/xoseperez/espurna/pull/864 to get some info about the decoding.
