### ISSUE TITLE
CSS ON OFF Button all red-green

### ISSUE THREAD

**Issue by kiralikbeyin** [xoseperez/espurna#1028]
Safari all red or green
<img width="163" alt="screen shot 2018-07-05 at 16 50 48" src="https://user-images.githubusercontent.com/10079333/42327139-bb0e10c0-8073-11e8-9631-6ecdda42f259.png">
 
<img width="151" alt="screen shot 2018-07-05 at 16 53 14" src="https://user-images.githubusercontent.com/10079333/42327269-0303995e-8074-11e8-96e3-04ebe1d50f8f.png">

Mac Book

**Comment by swilson86** [comment]
Same glitch also on Google Chrome running on iOS

**Comment by xoseperez** [comment]
I have merged @mcspr PR into dev. Can you please check if his code fixes the issue?

**Comment by svwhisper** [comment]
The switch colours now appear correctly on MacOS Safari.
