### ISSUE TITLE
ON OFF switch in Microsoft Edge

### ISSUE THREAD

**Issue by mcspr** [xoseperez/espurna#1049]
Edge only supports clip-path in SVG.
https://caniuse.com/#feat=css-clip-path
https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/6519995-support-clip-path-property

https://github.com/xoseperez/espurna/issues/503#issuecomment-404587205 has an example of how WebUI looks, and I did just try running it in Edge myself with similar result:
![image](https://user-images.githubusercontent.com/132763/42658671-aa649922-862e-11e8-8563-7ae832c7764e.png)

**Comment by icevoodoo** [comment]
+1

**Comment by Valcob** [comment]
@xoseperez, fixed this one, will create a PR in the next couple of some time units.  In short brought back the pure CSS look for checkboxes/toggles and also made possible disabling a check box. Removed the js hacks for relay on change event.
