### ISSUE TITLE
TH10 temperature problems

### ISSUE THREAD

**Issue by drronnie85** [xoseperez/espurna#1061]
My TH10 configured to send temperature to MQTT topic flat/kitchen/device/th10/temperature in my software I subscribed to this topic. All works properly.
But when I publish new temperature to flat/kitchen/device/th10/temperature/set topic temperature in my room not changed. What is wrong?

**Comment by xoseperez** [comment]
I'm not sure I understand you. You can't `set` the value of a sensor, it's read-only so to say. Why do you want to publish the temperature to `flat/kitchen/device/th10/temperature/set`?

**Comment by drronnie85** [comment]
@xoseperez , this is only a joke) I'm so sorry.
