### ISSUE TITLE
Relay turns on at boot.

### ISSUE THREAD

**Issue by jchrzaniuk** [xoseperez/espurna#1073]
Hi,
I've noticed, that in this configuration (ITEAD_SONOFF_BASIC):
```
#define BUTTON1_PIN	0
#define BUTTON1_MODE	BUTTON_PUSHBUTTON | BUTTON_DEFAULT_HIGH
#define BUTTON1_RELAY	1
#define BUTTON2_PIN	14
#define BUTTON2_MODE	BUTTON_SWITCH | BUTTON_SET_PULLUP | BUTTON_DEFAULT_HIGH
#define BUTTON2_RELAY	1
```

if BUTTON2 is closed (BUTTON2_PIN is LOW) and Espurna reboots, then RELAY1 always turns on (even if the state before reset was off).

**Comment by BauerPh** [comment]
Try to change BUTTON_DEFAULT_HIGH to BUTTON_DEFAULT_LOW
Compile and upload

**Comment by BauerPh** [comment]
I have the same issue with BUTTON_MODE = BUTTON_SWITCH.
I think the button state should be read during setup and should not fire a Click event?
