### ISSUE TITLE
Single Sonoff Basic showing as 2 switches in Home Assistant

### ISSUE THREAD

**Issue by MaxiStarling56** [xoseperez/espurna#1074]
Hi,
if you read the title you know the problem, i used the code that Espurna gave me (home assistant discover, configuration code) but in the home assistant overview he show like if there were 2 lights (watch the immages).
I hope someon can help me and thank for the attention.

![hassoverview](https://user-images.githubusercontent.com/35599704/43174022-3fa290c4-8fb8-11e8-9f17-eeba311d4bc5.png)
![hassconfiguration yaml](https://user-images.githubusercontent.com/35599704/43174027-4652891a-8fb8-11e8-97c7-90d95af574fb.png)
![espurnahassdiscover](https://user-images.githubusercontent.com/35599704/43174028-49d1d8f2-8fb8-11e8-9e50-48203a953858.png)
![espurnamqttsettings](https://user-images.githubusercontent.com/35599704/43174029-4c45db6a-8fb8-11e8-99ce-14da948c7467.png)

**Comment by mcspr** [comment]
Configuration gets doubled :) Exact same config of `switch:` is also received by the mqtt discovery (`mqtt.discovery: true`). You might want to keep configuration.yaml entry and disable **Discover** on espurna side.

**Comment by xoseperez** [comment]
Yes, I would first check if you have Discovery mode enabled. The device is probably sending the configuration to HA and it gets doubled.

**Comment by Carmelo66** [comment]
It seems to me that a switch works and the other only reads the status if turned on or off
