### ISSUE TITLE
Support for BMP180?

### ISSUE THREAD

**Issue by jsponz** [xoseperez/espurna#1082]
There is support for BMP280, but is there any support for BMP180? It is the former sensor from Bosch.

Thanks!

**Comment by Schwenkner** [comment]
I'm using BMP180, unfortunately I adopted the code from Platform.IO to "real" C++.
Can provide the sources, if someone will do a PR for Platform.IO wtih this code. Contact me.

**Comment by xoseperez** [comment]
Added support for BMP085 and BMP180 sensors to `dev` branch.

**Comment by jsponz** [comment]
Thanks! Great.

**Comment by moddsson** [comment]
It is so great how dynamic this project is... I was just looking if the BMP180 had been added already and that was the case... 9 hours ago!  Thanks

**Comment by xoseperez** [comment]
Staged for release
