### ISSUE TITLE
Support publishing custom value for relay processing

### ISSUE THREAD

**Issue by InduPrakash** [xoseperez/espurna#1085]
It would be nice if on/off can be sent instead of 1/0. Incoming on/off messages are handled but only 1/0 get sent out. This will make interfacing and automating with Smartthings easier. I had prototyped introducing MQTT_TOPIC_RELAY_ON/MQTT_TOPIC_RELAY_OFF with default value 1/0 and custom value in hardware.h, and that seemed to work well.

**Comment by xbb1024** [comment]
hi, do you have a template smartthings device handler for espurna? I'm new to mqtt.

**Comment by InduPrakash** [comment]
SmartThings events have to through a SmartApp/DeviceHandler into MQTT world through a bridge (https://hub.docker.com/r/stjohnjohnson/smartthings-mqtt-bridge/) to interact with Espurna device. My device is just of the type "Virtual Switch". The ST MQTT messages just end with on/off to indicate the state as well as the action and I was able to get this working by defining "smartthings/Device Name/switch" as the grouper, this felt quite odd but works and adjusting switch in ST gets reflected in Espurna device. But now the other way around since the outgoing messages have 1/0. So I locally end up creating 2 defines MQTT_TOPIC_RELAY_ON/MQTT_TOPIC_RELAY_OFF and used it in homeassistant.ino and relay.ino. I can request a pull if you want to look at it.

**Comment by xoseperez** [comment]
You can use "ON" and "OFF" (and "TOGGLE") for incoming MQTT messages. If you also want it to output strings instead of 0/1 you can use the latest dev branch and change the RELAY_MQTT_ON and RELAY_MQTT_OFF settings in `general.h`

**Comment by InduPrakash** [comment]
Thank you, that is pretty much what I did. In addition, I also modified
homeassistant._haSendSwitch to use the same.

**Comment by xoseperez** [comment]
Good idea, but I'd prefer to use a different setting for that.
