### ISSUE TITLE
Feature Request: Set pulse length via MQTT

### ISSUE THREAD

**Issue by torwag** [xoseperez/espurna#1086]
Hi, 
I was wondering if we could implement an MQTT-based timer. Similar to #502 but yet different and with a real safety benefit behind it.

What I want would be an enhancement of the pulse action of a switch, however, with a via MQTT definable pulse length. 
As for the reason, if you have some critical devices connected to a relay (e.g. a water pump, valve, etc.), it would be fatal, if the unit get switched on and afterwards, for some reasons, the wifi connection, the home automation server, MQTT broker, etc. stops working. The pump would remain on until whatever kind of bad things happen. Maybe  "On MQTT disconnect" comes to the rescue but this is not for every failure (e.g. if the HA-server fails).
It would be much safer, if one could send "Device on for 30min" and espruna itself would take care, that the unit switches off at the right time, independent of the wifi/MQTT/smart-home server, etc. status.

As for know I realise this with a pulse mode of 1:30 min and repeatably sending new triggers every minute. However, this requires more complex logic on the sender side and many MQTT messages flooding the system.
 
There is "On MQTT disconnect" function. However, I would prefer the MQTT- configurable pulse length as frequent MQTT connection looses (e.g. due to every now and then a bit unstable wifi) can be fatal too, if the consequence is that almost no requested unit action runs to its final end. E.g. a pump turns on only for a few seconds or minutes instead of 1h as the wifi connections gets randomly lost every few minutes.

**Comment by mcspr** [comment]
Hello.

See https://github.com/xoseperez/espurna/issues/831#issuecomment-396718917, this is enabled since 1.13.0

> To toggle the relay and toggle it back after 2.5 seconds just send this request (notice times are in 
milliseconds):
>
> curl "http://192.168.1.123/api/pulse/0?apikey=AABBCCDDEEFF0011&value=2.5"
>
> or using MQTT:
>
> mosquitto_pub -t ESPURNA_001122/pulse/0/set -m 2.5

(endpoint is pulse/\<n-th relay\> if multiple relays are used)
