### ISSUE TITLE
RF433 bridge - LED Dimmer based on SYN480R

### ISSUE THREAD

**Issue by jankorr** [xoseperez/espurna#1087]
I'm using ESPurna Direct firmware on my Sonoff RF Bridge(1.13.1). It works with my RF wall switches without any problems.  Recently I bought a LED stripe dimmer 
![mini-single-color-led-strip-dimmer-with-rf-remote](https://user-images.githubusercontent.com/17709934/43367728-37ca39b8-9352-11e8-94a8-ac2e07808b77.jpg)
Inside there is a SYN480R chip receiver. Sadly, ESPurna doesn't recognise codes from remote ( there is nothing incoming). Can someone give me a hint what can I do, to make this device working?

**Comment by wildwiz** [comment]
Hi, I have a remote/dimmer pair that, at least for what I can see, should be exactly like yours (I didn't open it, so I cannot be 100% sure of the chip).

I have tested it against a sonoff bridge Rev2 with the rf-direct mod, 
and these are the codes I receive on MQTT for each key:
```
OFF:     C00100001800953001
LIGHT:   C00100001800953004
BRIGHT+: C00100001800953005
BRIGHT-: C00100001800953006
100%:    C00100001800953007
50%:     C00100001800953008
25%:     C00100001800953009
MODE+:   C0010000180095300B
MODE-:   C00100001800953011
SPEED-:  C0010000180095300D
SPEED+:  C0010000180095300F
