### ISSUE TITLE
[nodemcu-lolin] PlatformIO building

### ISSUE THREAD

**Issue by Danny89530** [xoseperez/espurna#1095]
Hi @xoseperez,
I'm trying to build your espurna on a NodeMCU Lolin.
What i want to obtain is a device with 2 Relays, 3 Switches, 1 Counter and a One Wire Temperature sensor.
In according with your Wiki, the Pins are selected using GPIO logic so, even in my case, I've selected Pins from D1 to D7 on the board and, using PlatformIO, I've to add several build flags like (in my case):

```
// For Relays
-DRELAY1_PIN=5 -DRELAY1_MODE=1 
-DRELAY2_PIN=4 -DRELAY2_MODE=1
// For Buttons
-DBUTTON1_PIN=0 -DBUTTON1_MODE=4
-DBUTTON2_PIN=2 -DBUTTON2_MODE=4
-DBUTTON3_PIN=14 -DBUTTON3_MODE=4
// For Counter and Temperature sensors
-DEVENTS_PIN=12
-DDALLAS_SUPPORT=1 -DDALLAS_PIN=13
```

After I've tested the environment, compiled and flashed a pure copy of your code successfully, I've tried to add the above flags and it goes to this exception:

```
.pioenvs/nodemcu-lolin/libFrameworkArduino.a(core_esp8266_main.cpp.o):(.text._ZL12loop_wrapperv+0x4): undefined reference to `setup'
.pioenvs/nodemcu-lolin/libFrameworkArduino.a(core_esp8266_main.cpp.o):(.text._ZL12loop_wrapperv+0x8): undefined reference to `loop'
.pioenvs/nodemcu-lolin/libFrameworkArduino.a(core_esp8266_main.cpp.o): In function `loop_wrapper':
/Users/danilodaloiso/.platformio/packages/framework-arduinoespressif8266/cores/esp8266/core_esp8266_main.cpp:110: undefined reference to `setup'
/Users/danilodaloiso/.platformio/packages/framework-arduinoespressif8266/cores/esp8266/core_esp8266_main.cpp:110: undefined reference to `loop'
collect2: error: ld returned 1 exit status
*** [.pioenvs/nodemcu-lolin/firmware.elf] Error 1
```

The only way I can flash the firmware is adding just the **_-DRELAY1_PIN=5_** but nothing happens when I try to click the switch button on Web interface.

What I'm doing wrong?

Thanx in advance.
Danny

**Comment by mcspr** [comment]
Hey Danny.

Assuming from the .pioenvs path in the log, env:nodemcu-lolin part was modified. I did the following changes to the 'code/platformio.ini' and it did build ok in Linux/Docker (running from the repo root: `cd code ; pio run -v -e nodemcu-lolin`)
```
[env:nodemcu-lolin]
platform = ${common.platform}
framework = ${common.framework}
board = ${common.board_4m}
board_build.flash_mode = ${common.flash_mode}
lib_deps = ${common.lib_deps}
lib_ignore = ${common.lib_ignore}
build_flags =
    ${common.build_flags_4m1m}
    -DNODEMCU_LOLIN
    -DRELAY1_PIN=5 -DRELAY1_MODE=1
    -DRELAY2_PIN=4 -DRELAY2_MODE=1
    -DBUTTON1_PIN=0 -DBUTTON1_MODE=4
    -DBUTTON2_PIN=2 -DBUTTON2_MODE=4
    -DBUTTON3_PIN=14 -DBUTTON3_MODE=4
    -DEVENTS_PIN=12
    -DDALLAS_SUPPORT=1 -DDALLAS_PIN=13
monitor_speed = ${common.monitor_speed}
extra_scripts = ${common.extra_scripts}
```

-D... flags listing above has // comments, that might cause problems if used in build_flags. Although this might be not related, I'd still remove them if they are actually there.

Because nodemcu-lolin build_flags has -DNODEMCU_LOLIN, -DRELAY1_PIN=5 gets overridden by `#define` in hardware.h. This is sort of hidden right now due to disabled compiler warnings (`-w` switch in common.build_flags).
https://github.com/xoseperez/espurna/blob/be7f535d149359763e62e2bd7f5943c31941270d/code/espurna/config/hardware.h#L76

Wiki should probably mention this... You can get rid of -DNODEMCU_LOLIN and instead do this:
```
build_flags =
  ${common.build_flags_4m1m}
  '-DDEVICE="MY_COOL_DEVICE"'
  '-DMANUFACTURER="DANNY"'
  ...rest of the flags...
```
(note single quotes)

**Comment by Danny89530** [comment]
Hi @mcspr and thanx for the faster response.
The comments you mention were just here on github for major readability.
Your instruction works like a charm: the compiling procedure goes well but only if i made a _**pio lib update**_ before every Build. I don't know why..
The last problem is the RELAY_MODE: it seems the compiler ignore it.

This is the new configuration:
```
build_flags = ${common.build_flags_4m1m}
              '-DDEVICE="MY_COOL_DEVICE"'
              '-DMANUFACTURER="DANNY"'
              -DDEBUG_FAUXMO=Serial
              -DNOWSAUTH
              -DRELAY1_PIN=5      -DRELAY1_MODE=1
              -DRELAY2_PIN=4      -DRELAY2_MODE=1
              -DBUTTON1_PIN=13    -DBUTTON1_MODE=4
              -DBUTTON2_PIN=15    -DBUTTON2_MODE=4
              -DBUTTON3_PIN=12    -DBUTTON3_MODE=4
              -DEVENTS_PIN=14
              -DDALLAS_PIN=0     -DDALLAS_SUPPORT=1
```

Thanx, again.
Danny

**Comment by Danny89530** [comment]
Hi agan..
I've changed the flag **-DRELAY1_MODE=1** with **-DRELAY1_TYPE=1** and everything works perfectly.

Sorry, my fault.
Thank you for the support!
