### ISSUE TITLE
xmw01esp & pl7211

### ISSUE THREAD

**Issue by gn0st1c** [xoseperez/espurna#1097]
inside the latest xiaomi enhanced power plug (with two usb ports), i see the following chips.

xmw01esp: esptool thinks it's a 8255 with 2mb flash. (the 25q16csig next to it is a  16mb flash)
pl7211: [2-Channel Power/Energy Metering Analog Front End](http://prolificusa.com/product/pl7211-2-channel-power-energy-metering-analog-front-end-afe/)

did anyone else has seen these before? 

----

![pl7211](https://user-images.githubusercontent.com/12406166/43572017-152c2266-9647-11e8-89f1-ea303ae71f09.jpg)
![xmw01esp](https://user-images.githubusercontent.com/12406166/43572018-1547bdaa-9647-11e8-9c42-d101c02521cb.jpg)

**Comment by xoseperez** [comment]
Wow, haven't seen these before. Do you have a link to the device page?

**Comment by gn0st1c** [comment]
[Mi Smart Socket Enhanced Edition](http://item.mi.com/1180800005.html)

**Comment by gn0st1c** [comment]
ok, found this post: [WHAT IS THE XMW01ESP IC?](https://www.esp8266.com/viewtopic.php?f=13&t=17294)

> I disassembled a xiaomi desk lamp and found an Espressif "XMW01ESP" inside.

----

it seems xiaomi is using esp chips now. maybe espressif is producing a special batch for mi devices.
i'll close this, as this is not an issue. i'll let you know when i know/test more.
