### ISSUE TITLE
New device: Homecube 16A

### ISSUE THREAD

**Issue by hyteoo** [xoseperez/espurna#1105]
I got these from Amazon: https://www.amazon.de/gp/product/B07D7RVF56/ref=oh_aui_detailpage_o00_s01?ie=UTF8&psc=1
![homecube](https://user-images.githubusercontent.com/1378206/43683857-938e1346-989d-11e8-9e8b-e45975a9017d.PNG)
Nice little sockets, they have the following features:
- extremely compact
- 16A relay
- 4x RGB LEDs
- energy monitoring with HLW8012

Tested them with espurna, created a new hardware profile, so far they work great. It is similar to Blitzwolf but some pins differ.
I'll submit a PR shortly

There are 3 boards, sandwiched together like a H.
The ESP8266 is on a board based on [WT8266-S1](https://www.seeedstudio.com/WT8266-S1-FCC%26amp%3BCE%26amp%3BRoHS%26amp%3B-Wi-Fi-Module-based-on-ESP8266-p-2521.html).
The outer ring is illuminated by the 4 RGB LEDs, making the whole socket look very nice. Maybe some PWM would work nice here.

Here are some internal shots:

![20180804_184041](https://user-images.githubusercontent.com/1378206/43684137-298fc8d0-98a3-11e8-8638-200db44792d5.jpg)
![20180804_184101](https://user-images.githubusercontent.com/1378206/43683870-c2c7ea38-989d-11e8-8f0d-059c087c8c62.jpg)
![20180804_184106](https://user-images.githubusercontent.com/1378206/43683871-c2e4745a-989d-11e8-98eb-1f1b58ee3d7d.jpg)
![20180804_184120](https://user-images.githubusercontent.com/1378206/43683872-c3041c24-989d-11e8-8ee8-ebf055b63f43.jpg)
![20180804_184129](https://user-images.githubusercontent.com/1378206/43683873-c321d7a0-989d-11e8-82a1-d6d85310c7d5.jpg)
![20180804_213827](https://user-images.githubusercontent.com/1378206/43683875-c3448ca0-989d-11e8-95d2-27a90eb8e0c4.jpg)
![20180804_213901](https://user-images.githubusercontent.com/1378206/43683876-c362bd7e-989d-11e8-8a80-2098f4a5ef5d.jpg)

**Comment by xoseperez** [comment]
Merged! I'm sure this is a great device.

**Comment by flashy02** [comment]
One question: How can I open this Device without damaging?

**Comment by hyteoo** [comment]
Just pop out the plastic ring with a cutter or a plastic pry tool. It should pop without too much effort.
There are no clips, just a small amount of glue.

**Comment by flashy02** [comment]
Thank you very much. The opening and flashing worked just fine but the first installation was a mess. Please look issue #1119

**Comment by hyteoo** [comment]
Hmm that is weird, I had 2 homecubes flashed with eapurna without issues.

**Comment by flashy02** [comment]
Perhaps my device has a problem. But at the moment everything works fine. Only the first installation was difficult. Which version of espurna have you flashed?

**Comment by hyteoo** [comment]
Latest master branch

**Comment by flashy02** [comment]
The same as I have used. I would try it again with an other homecube/device, soon. Perhaps it is a thing of this special device.

**Comment by hyteoo** [comment]
@ruimarinho I'm not sure what you mean
The usual suspects: Tx,Rx, GPIO0 for flashmode.
And the pinout
![317060019](https://user-images.githubusercontent.com/1378206/44506556-8e331480-a6af-11e8-99f2-9a98210f911b.png)

**Comment by andreasloe** [comment]
Regarding flashing: I do not see this chip on the picture above. Also, the pictures show the ESP8266, but you mention  WT8266-S1. Thanks in advance!

**Comment by hyteoo** [comment]
The picture above is the pinout
I never said the device has the [WT8266-S1](https://www.seeedstudio.com/WT8266-S1-FCC%26amp%3BCE%26amp%3BRoHS%26amp%3B-Wi-Fi-Module-based-on-ESP8266-p-2521.html), just that the pinout is the same. Even though it also has an ESP8266 inside, just rebranded the entire assembly.
Post a picture of your device to check out the differences then.

**Comment by andreasloe** [comment]
This is probably a misunderstanding: I am used to flash Sonoff and their pinouts are nicely labeled. I do not own a homecube yet but was wondering Howe to flash it - and looking and the above photographs I do not see any descriptions of pinouts.

**Comment by gretel** [comment]
@hyteoo 5V to `VCC` for flashing?

**Comment by gretel** [comment]
`GPIO0` needs to be grounded to enable flash. all four LEDs will light cyan.
had to flash twice to get it working. seems to auto-reset when flashing is done.

**Comment by janbernhardt** [comment]
This code seems to work pretty well with Gosund SP1 Switch. I was able to flash 3 devices without issues. Switch is working fine using button or with homeassistant (MQTT) integration.
One potential bug is that if I set the LED to "Always ON" the LED is off and if the set it to "Always OFF" the Button LED is on. So the behavior seems to be inverse. Power consumption looks fine as well.
