### ISSUE TITLE
Sonoff dual R2 can't hardreset after upgrade from 1.12.6 to 1.13.1

### ISSUE THREAD

**Issue by forast3r** [xoseperez/espurna#1111]
Aftet upgrading via web, device becomes responsiveness. 

Pushing button for 10+seconds does not hardreset.

What is the recommended procedure for upgrading via ota?

**Comment by xoseperez** [comment]
Check the wiki (https://github.com/xoseperez/espurna/wiki/OTA). but if the device is not responsive it could be a bad flash. Maybe the only option is to flash it wired again.

**Comment by forast3r** [comment]
Thanks, I'll solder a header and perform a reflash tomorrow
