### ISSUE TITLE
relay 01 does not work

### ISSUE THREAD

**Issue by bruno-wladimir** [xoseperez/espurna#1117]
I have two modules t1 and the firmware change relay 01 does not work, even with a simple code where you activate and deactivate the relay, it does not work. relay 2 works perfectly in both the espurna and a simple blink. Anyone have any idea what it can be?

**Comment by xoseperez** [comment]
Do you mean a simple sketch does not work? Maybe the GPIO is wrong?

**Comment by bruno-wladimir** [comment]
It worked before the same code, it suddenly stopped

**Comment by xoseperez** [comment]
Maybe a hardware issue, can you test the relay isolated?

**Comment by bruno-wladimir** [comment]
the relay will only work if you apply 5V to the power board pin

**Comment by xoseperez** [comment]
That's because the relay is a 5V relay. The microcontroller uses 3V3 but cannot switch the relay by its own, it needs an external line rated for the relay coil.
