### ISSUE TITLE
I like this item very much. Please help me. Does espurna support rotary encoder?

### ISSUE THREAD

**Issue by 1043717432** [xoseperez/espurna#1124]
I like this item very much. Please help me. Does espurna support rotary encoder?
![520px-rotary_encoder_001](https://user-images.githubusercontent.com/22461690/43874102-72c3c828-9bbc-11e8-8fe2-5dc877ac8309.jpg)

**Comment by xoseperez** [comment]
No, it doesn't.  But it eventually will if #884 goes through.

**Comment by 1043717432** [comment]
@xoseperez  Expect good news to come.
