### ISSUE TITLE
Sonoff relay status 

### ISSUE THREAD

**Issue by kfshome** [xoseperez/espurna#1127]
Hi i'm novice, 
I'm looking to retrieve the status of the relay with a JS script.

try {
    var obj = JSON.parse(trame);
} catch (e) {
    ldprint("Error parse JSON: " + e.message);
};

Stat = obj.properties.value;

but it doesn't work.

**Comment by mcspr** [comment]
Take a look here:
https://github.com/xoseperez/espurna/blob/82405617e4e0e9f08f8603bba25bb8b5fe3d7c00/code/html/custom.js#L1318-L1324

relayStatus is array of relay statuses. e.g. `[false, true, true]` for relay0 OFF, relay1 and relay2 ON. If modifying custom.js it is a likely place to modify.

To access just from browser you can use the same selector as above to get the data.  
e.g. `$("input[name='relay'][data='0']").prop("checked")` -> `true / false`
