### ISSUE TITLE
Support more than 16 codes in RF Bridge 

### ISSUE THREAD

**Issue by champikasam** [xoseperez/espurna#1138]
Hi,

Is there any way to support more than 16 codes in RF bridge? Does the direct hack (bypassing the auxiliary microcontroller) allow us to do that?

#1133 

Thanks!

**Comment by xoseperez** [comment]
The main issue is the memory. Right now there are a number of features that scale with the number of relays and eat up memory. With the latest version in `dev` branch you might want to disable API_SUPPORT to save some memory and it will allow you to go up to 24 codes, probably more. Same with any other feature you won't use.
