### ISSUE TITLE
no matching function for call to 'fauxmoESP::onSetState(alexaSetup()::__lambda1)'

### ISSUE THREAD

**Issue by xinuxnt** [xoseperez/espurna#1141]
after an Arduino IDE fresh install I got this error at compilation time.   Could be a bug or I am doing something wrong?

Arduino:1.8.5 (Windows Store 1.8.10.0) (Windows 10), Tarjeta:"WeMos D1(Retired), 80 MHz, 921600, 4M (1M SPIFFS)"

C:\Users\gabriel\Documents\Arduino\espurna\code\espurna\alexa.ino: In function 'void alexaSetup()':

alexa:71: error: no matching function for call to 'fauxmoESP::onSetState(alexaSetup()::__lambda1)'

     });

      ^

C:\Users\gabriel\Documents\Arduino\espurna\code\espurna\alexa.ino:71:6: note: candidate is:

In file included from C:\Users\gabriel\Documents\Arduino\espurna\code\espurna\alexa.ino:11:0:

C:\Users\gabriel\Documents\Arduino\libraries\xoseperez-fauxmoesp-39373c530a8f\src/fauxmoESP.h:78:14: note: void fauxmoESP::onSetState(TSetStateCallback)

         void onSetState(TSetStateCallback fn) { _setCallback = fn; }

              ^

C:\Users\gabriel\Documents\Arduino\libraries\xoseperez-fauxmoesp-39373c530a8f\src/fauxmoESP.h:78:14: note:   no known conversion for argument 1 from 'alexaSetup()::__lambda1' to 'TSetStateCallback {aka std::function<void(unsigned char, const char*, bool, unsigned char)>}'

alexa:73: error: 'class fauxmoESP' has no member named 'onGetState'

     alexa.onGetState([](unsigned char device_id, const char * name) {

           ^

exit status 1
no matching function for call to 'fauxmoESP::onSetState(alexaSetup()::__lambda1)'

**Comment by xoseperez** [comment]
You are using FauxmoESP 3.0 but ESPurna still uses 2.4 for `master` and `dev` branches. Go to the library manager and downgrade to 2.4.
