### ISSUE TITLE
Switch log in domoticz reports state change twice

### ISSUE THREAD

**Issue by miroslavpetrov** [xoseperez/espurna#1145]
Hello,

I am using domoticz 4.97 and espurna 1.13.1 on sonoff duals connected to a mqtt broker. When I change the state of a switch in domoticz the log of the switch reports the state change twice. I guess this is because domoticz sends a message in domoticz/out topic and then the sonoff reports the state change in domoticz/in topic. See the screenshot below. Do you have any idea on how to fix this?
![screen shot 2018-08-21 at 8 28 40](https://user-images.githubusercontent.com/25277610/44382434-85123e00-a51d-11e8-921e-85432ea7b766.png)

**Comment by Camposmansi** [comment]
Good, the same thing happens to me, I send from domoticz to espurna and espurna returns this value to home automation, which makes me a double change of state and a double message
Since I use it happens to me and I can not find how to solve it, what I found in the debug ...

[893767] [DOMOTICZ] Received value 1 for IDX 108
[893769] [RELAY] #0 scheduled ON in 0 ms
[893771] [RELAY] #0 set to ON
[893784] [MQTT] Sending domoticz/in => {"idx": 108, "nvalue": 1, "svalue": ""} (PID 1)

**Comment by Camposmansi** [comment]
by the way, with home assistant does not happen

**Comment by loglux** [comment]
It happens in Domoticz with ESPurna running firmware on Sonoff POW, Sonoff S20, Sonoff RF Bridge. I have the same POW switch with Tasmota, that does not happen.

**Comment by Camposmansi** [comment]
Yes, I just tried it with tasmota and it does not happen.
I've tried all kinds of settings and I do not know why, do I have to wait for an update?

**Comment by loglux** [comment]
I think so. It is obvious. We should wait for 1.14

**Comment by loglux** [comment]
Along with this I can see On On and then Off Off in a Switch's statistics in Domoticz at the same time, for example at 07:25:41 but Domoticz log show that nothing had happened at this time.

**Comment by loglux** [comment]
it's maybe a time synchronisation issue as well

**Comment by Camposmansi** [comment]
If they do not fix it I'm sorry but I have to leave ESPurna and pass to tasmota, but I love ESPurna and I would be very sorry

**Comment by Camposmansi** [comment]
> Along with this I can see On On and then Off Off in a Switch's statistics in Domoticz at the same time, for example at 07:25:41 but Domoticz log show that nothing had happened at this time.

Yes of course, the same thing happens to me but only in domoticz in home assistant does not happen

**Comment by loglux** [comment]
Trust me, Tasmota is a bigger crap. It can show that POW is Off while it's continuing to be On.

**Comment by loglux** [comment]
be patient

**Comment by ColinShorts** [comment]
@loglux  it might be worth mentioning the corresponding issue at domoticz... https://github.com/domoticz/domoticz/issues/2175

**Comment by Camposmansi** [comment]
The problem they have is the same but it happens to me through MQTT and not through API

**Comment by Camposmansi** [comment]
Is this close and not found

**Comment by JPasa** [comment]
Hello, this error persists.

I am using domoticz 4.97 and espurna 1.13.1 on sonoff duals connected to a mqtt broker. When I change the state of a switch in domoticz the log of the switch reports the state change twice.

**Comment by xoseperez** [comment]
This has been fixed with #1536. Will be released with 1.13.4.
