### ISSUE TITLE
WPS not works

### ISSUE THREAD

**Issue by serra82** [xoseperez/espurna#1146]
I'm unable to use wps, I added -DJUSTWIFI_ENABLE_WPS and changed #define BUTTON1_LNGCLICK BUTTON_MODE_WPS. After triple click led blink faster, but in Access point log I don't see that the wps process starts.
I tested the wps example in JustWiFi and works correctly, in Access Point log I see the wps association process and my sonoff pow stay connected.
Activating debug in JustWiFi the only difference that I notated is:
WiFi.getMode(): 1 in wps example
WiFi.getMode(): 3 in espurna

**Comment by xoseperez** [comment]
It should leave AP mode before running WPS discovery... fixed in `dev`
