### ISSUE TITLE
MQTT topic for RF switch on/off

### ISSUE THREAD

**Issue by vaidyasr** [xoseperez/espurna#1153]
What will be the availability/command/state MQTT topic for RF Bridge switches?. From the web ui of ESPurna, I can't find out. The HASS show button is not working.

**Comment by hyteoo** [comment]
Did you read the wiki?...
https://github.com/xoseperez/espurna/wiki/MQTT#sonoff-rf-bridge

**Comment by vaidyasr** [comment]
Thank you. I overlooked the Wiki.
