### ISSUE TITLE
Motion sensor with Sonoff Bridge

### ISSUE THREAD

**Issue by vaidyasr** [xoseperez/espurna#1156]
I have a motion sensor configured in espurna web page. When I monitor the MQTT values, the input rfin is different at each time and randomly the code I have learned via the web is found. What could be the issue?. The last 6 digits are always same.

**Comment by xoseperez** [comment]
The RF Bridge codes are 9 bytes long, represented as 18 hex-chars. They are as follow:
* 2 bytes for the sync time
* 2 bytes for the long time
* 2 bytes for the short time
* 3 bytes for the unique code itself

Basically: the last 3 bytes (6 hex-chars) are the actual code whilst the other 6 bytes will be slightly different from one message to another. To compare codes use just the last 6 hex-chars.

**Comment by vaidyasr** [comment]
Thank you.
