### ISSUE TITLE
RF Bridge -- missing "RF" item if I add a BME280 sensor

### ISSUE THREAD

**Issue by kuppe234** [xoseperez/espurna#1157]
Hello,
If I add a BME280 sensor to the RFBridge, the menu item "RF" will be lost. How can I fix this?
My build flags:
  _build_flags = ${common.build_flags_1m0m} -DITEAD_SONOFF_RFBRIDGE -DRFB_DIRECT -DBMX280_SUPPORT=1 -DI2C_SDA_PIN=14 -DI2C_SCL_PIN=12_
It still worked in 1.13.0, not anymore in 1.13.1 and 1.13.2b.

Greetings, kuppe

**Comment by xoseperez** [comment]
There was an issue in the web UI image inclusion that was introduced about a week ago and solved just yesterday in the `dev` branch. Check #1142. Update your copy and reflash.

**Comment by kuppe234** [comment]
Sorry, but it does not work. I have the current dev branch (5104b4ce), but the RF menu item does not exist.

**Comment by kuppe234** [comment]
`INFO` return: 
....
[923395] [INIT] BOARD: ITEAD_SONOFF_RFBRIDGE
[923399] [INIT] SUPPORT: BROKER BUTTON DEBUG_SERIAL DEBUG_TELNET DEBUG_WEB HOMEASSISTANT I2C LED MDNS_SERVER MQTT NTP SCHEDULER SENSOR TELNET TERMINAL WEB 
[923413] [INIT] SENSORS: BMX280 
[923415] [INIT] WEBUI IMAGE: FULL
....

**Comment by xoseperez** [comment]
I see. The full webUI image was not including the RFBridge code. I didn't foresee that anyone would add sensors to the RFBRIDGE... I have fixed it now (it adds ~800bytes to the full image). Can you please test the latest version in `dev`?

**Comment by kuppe234** [comment]
Great, it works, all menu items are present.
I have no problem with the size of the full image (476832 bytes for rfbridge-direct without API, with SENSORS)
Thank you, kuppe.

**Comment by xoseperez** [comment]
Cool, I think I will release 1.13.2 now.
Thak you!
