### ISSUE TITLE
Issues with special characters in MQTT password

### ISSUE THREAD

**Issue by xoseperez** [xoseperez/espurna#116]
Originally reported by: **Nuno Sousa (Bitbucket: [nunofgs](https://bitbucket.org/nunofgs), GitHub: [nunofgs](https://github.com/nunofgs))**

----------------------------------------

I changed my MQTT password to a more secure, auto-generated password.

After that, I noticed that my espurna devices were not connecting to MQTT. Here's the output from MQTT logs:

```
3/26/2017 6:17:09 PM1490548629: New connection from 192.168.1.8 on port 1883.
3/26/2017 6:17:09 PM1490548629: Socket error on client <unknown>, disconnecting.
```

I then removed special characters from the password and found that the devices are now able to connect again.

**Comment by xoseperez** [comment]
@nunofgs So long... it would be great to know what character caused problems.

**Comment by Javerre** [comment]
I can't get ESPurna to connect to my MQTT server. I have a QiOT-generated password for my NQTT server that is something like:

`r:32ee11cf57a72276eef9327514df6193`

It seems as though ESPurna is constantly trying to connect and failing. The MQTT status on the device webpage flashes CONNECTED for about 100ms and then goes back to NOT CONNECTED for 10s.this is repeated indefinitely.

I can connect to the test mosquito MQTT service no problem. HASS can connect to the QiOT MQTT server no problem.

**Comment by Javerre** [comment]
Scratch that. Just checked the MQTT logs and my problem was with the root topic being incorrect. Password in the above format works fine.

**Comment by xoseperez** [comment]
Cool. I'm going to close this issue.
