### ISSUE TITLE
USE_CORE_VERSION_H and "core_version.h" header

### ISSUE THREAD

**Issue by mcspr** [xoseperez/espurna#1162]
Maybe this should be removed?
https://github.com/xoseperez/espurna/blob/f840a5420f702475b02bbc0127e90450f8f13112/code/espurna/config/all.h#L39-L41

Looking at git history this was only useful for `feature/stage` when core_version header is like this:
https://github.com/esp8266/Arduino/blob/master/cores/esp8266/core_version.h
And because platformio does not generate it like ArduinoIDE does: https://github.com/esp8266/Arduino/blob/85e68093e94b4e5c5e711888b8b5facee1bd4f9f/platform.txt#L73-L79
*I need to check how [platformio/platform-espressif8266](https://github.com/platformio/platform-espressif8266) would do it...*

**Comment by xoseperez** [comment]
Yes, this was kind of a hack to get the SDK version and revision when using PlatformIO. It would be better to add the proper flags in the `extra_scripts.py` file but I failed back then, can't remember why...
