### ISSUE TITLE
Support Robotdyn MEGA+WiFi R3 ATmega2560+ESP8266

### ISSUE THREAD

**Issue by henkiejan1** [xoseperez/espurna#1174]
Hi all,

First of all i know not really much about developing of the Espurna firmware or something. Maybe there is a way of support.

A short time ago i buyed a Robotdyn MEGA+WiFi R3 ATmega2560+ESP8266. As in the name it's a combination of a regular Arduino Mega R3 board but also with a build in ESP8266. In this way i can use the Arduino Mega wirelessly with my RFLink board. Therefore it was needed to install ESPEasy on the ESP8266 and adding a virtual serial port in ESPEasy. You can find more information about this board here: https://robotdyn.com/mega-wifi-r3-atmega2560-esp8266-flash-32mb-usb-ttl-ch340g-micro-usb.html Under the tab 'Documents' on this page you will find more information.

But off course i like the Espurna firmware a lot more. It's more clear, simple etc I hope there could be support for this board in the future. :)

**Comment by xoseperez** [comment]
This is a pretty specific development board. There are similar devices in the market, like the 4Duino or the SonoffSC which might be supported shortly, check the `sonoffsc` branch.

**Comment by henkiejan1** [comment]
Thank you for your anwser. I see on your site the Sonoff SC has indeed also a atmega chip on it.

**Comment by grittisemper** [comment]
> Hi all,
> 
> First of all i know not really much about developing of the Espurna firmware or something. Maybe there is a way of support.
> 
> A short time ago i buyed a Robotdyn MEGA+WiFi R3 ATmega2560+ESP8266. As in the name it's a combination of a regular Arduino Mega R3 board but also with a build in ESP8266. In this way i can use the Arduino Mega wirelessly with my RFLink board. Therefore it was needed to install ESPEasy on the ESP8266 and adding a virtual serial port in ESPEasy. You can find more information about this board here: https://robotdyn.com/mega-wifi-r3-atmega2560-esp8266-flash-32mb-usb-ttl-ch340g-micro-usb.html Under the tab 'Documents' on this page you will find more information.
> 
> But off course i like the Espurna firmware a lot more. It's more clear, simple etc I hope there could be support for this board in the future. :)

Hi,
for anyone interested, I have found an integration solution to build a RFLink Wi-Fi Gateway board.

You can find the project here: https://gitlab.com/rrenato/rflink-wi-fi-gateway-board

The solution uses both the robotdyn mega-wifi-r3-atmega2560-esp8266-flash-32mb-usb-ttl-ch340g-micro-usb board and the ESPurna firmware.

Gritti
