### ISSUE TITLE
help me to understand the code that how node js server is conating with espurna firmware

### ISSUE THREAD

**Issue by Rohank752** [xoseperez/espurna#1185]
[quaki-cordova-master.zip](https://github.com/xoseperez/espurna/files/2362986/quaki-cordova-master.zip)
[quaki-firmware-master.zip](https://github.com/xoseperez/espurna/files/2362987/quaki-firmware-master.zip)
[quaki-server-master.zip](https://github.com/xoseperez/espurna/files/2362988/quaki-server-master.zip)

**Comment by xoseperez** [comment]
I'm sorry this goes far beyond what an issue is.
