### ISSUE TITLE
Not reconnecting WiFi after losing WiFi connection. 

### ISSUE THREAD

**Issue by jsponz** [xoseperez/espurna#1190]
I have a sonoff with the latest version. 

If the device loses the WiFi connection (i.e. router is switched off), when the WiFi connection is already available (i.e. router is switched on) the device does not connect automatically. It starts AP mode. 

Is there any way to automatically force the connection?

**Comment by seetendra** [comment]
Just did a test on the Sonoff's that i have they did connect after 3 minutes.

**Comment by JohnOH** [comment]
In your wifi settings what is "Scan networks" set to?

**Comment by jsponz** [comment]
yes, of course. 

It does not connect... Any idea?

**Comment by wasiflaeeq** [comment]
same issue here on sonoff pow r2

**Comment by kiralikbeyin** [comment]
Same problem with rfbridge. I am using commit 820d8c4.
