### ISSUE TITLE
REST API changes values on GET

### ISSUE THREAD

**Issue by Cabalist** [xoseperez/espurna#1192]
Currently the RESTFUL API will respond to GETs as if they were PUTs.    For example:

This python code toggles the relay on my device:

```python
r = requests.get("http://192.168.4.1/api/relay/0", params={'apikey': MY_APIKEY,
                                                           'value': 2})
```

This should not happen as a GET request is 'supposed' to be read only and a [Safe Method](https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol#Safe_methods)

Tested on 1.13.2 with a Sonoff B1.

**Comment by xoseperez** [comment]
I agree this breaks the REASTFUL API. It was requested to easy access from certain clients. Maybe it should be disabled by default..

**Comment by xoseperez** [comment]
Changed the default behaviour so now the API is restful "compliant". It can be changed from the web UI.

**Comment by Cabalist** [comment]
Thank you!
