### ISSUE TITLE
[suggestion] imgbot app

### ISSUE THREAD

**Issue by gn0st1c** [xoseperez/espurna#1199]
[suggestion] installing [ImgBot](https://github.com/apps/imgbot) for ESPurna repo

> **Description**
Optimizing images yourself is time consuming, let ImgBot do all the heavy lifting for you. You just sit back and review the PRs :)

> Every bit counts while your project is loading and your users are waiting.

> Once installed, ImgBot will crawl through all of your image files in GitHub and losslessly compress them. This will make the file size go down, but leave the dimensions and quality untouched. Once it's done, ImgBot will open a pull request for you to review and merge.

----
and maybe [Synk](https://github.com/marketplace/snyk), too?

**Comment by xoseperez** [comment]
I enabled ImgBot on ESPurna repo. I think it would be interesting to enable it also on the wiki, but so far I couldn't find a way to do it...
About Synk, it will only be useful for the small javascript and python code in the repo, right. Don't know if it's worth it for ESPurna.

**Comment by xoseperez** [comment]
Run on the main repository with a size reduction of 22% (see #1202).
