### ISSUE TITLE
Not reporting Switch status 0 to ThingSpeak

### ISSUE THREAD

**Issue by JohnOH** [xoseperez/espurna#1213]
When ThingSpeak is enabled the value of Switch (on) is reported to ThingSpeak correctly as a value 1, however Switch (off) is not reported when it should be reported as a value 0.

**Comment by JohnOH** [comment]
Unit is now reporting Switch 0 to ThinkSpeak. I may have reported this as an issue to early or there is some initialisation issue.

**Comment by xoseperez** [comment]
I have sometimes seen the message fail with a return payload of "0" instead of the current dataset index. I have added code to the thingspeak module to try up to 3 times to send the message if the return code is not right.

**Comment by xoseperez** [comment]
The POST is done to the `update` URL also (the last update clarifies that too), the only difference is the api key parameter. In the documentation they state it must be `api_key` (https://www.mathworks.com/help/thingspeak/writedata.html)
