### ISSUE TITLE
Support for Power Factor

### ISSUE THREAD

**Issue by JohnOH** [xoseperez/espurna#1215]
Might it be possible to support power factor statistics alongside the voltage, current, power and energy currently supported?

**Comment by lesleypersyn** [comment]
For the Sonoff POW it's supported. (HL8012 chip)

**Comment by JohnOH** [comment]
My units are POW2, equipped with the CSE7759 measurement chips.

**Comment by xoseperez** [comment]
Yes, the CSE7759 provides enough info to support power factor calculation.
