### ISSUE TITLE
Support for EXS Relay V50 ?

### ISSUE THREAD

**Issue by cheise** [xoseperez/espurna#1218]
I have testing the new ESX Relay V50. Here is a snipped from my "hardware.h", support it in your next release, please?

#elif defined(EXS_WIFI_RELAY_V50)

    // Untested

    // Info
    #define MANUFACTURER        "EXS"
    #define DEVICE              "WIFI_RELAY_V50"

    // Buttons
    #define BUTTON1_PIN         5
    #define BUTTON2_PIN         4
    //#define BUTTON3_PIN         2
    //#define BUTTON4_PIN         0
    #define BUTTON1_RELAY       1
    #define BUTTON2_RELAY       2
    #define BUTTON1_MODE        BUTTON_SWITCH | BUTTON_DEFAULT_HIGH | BUTTON_SET_PULLUP
    #define BUTTON2_MODE        BUTTON_SWITCH | BUTTON_DEFAULT_HIGH | BUTTON_SET_PULLUP

    // Relays
    #define RELAY1_PIN          14
    #define RELAY1_TYPE         RELAY_TYPE_LATCHED
    #define RELAY1_RESET_PIN    16
    #define RELAY2_PIN          13
    #define RELAY2_TYPE         RELAY_TYPE_LATCHED
    #define RELAY2_RESET_PIN    12

    // LEDs
    #define LED1_PIN            15
    #define LED1_PIN_INVERSE    0
![img_3804_pin](https://user-images.githubusercontent.com/43306023/45931924-7fbd6e80-bf75-11e8-8028-5a6386243f2e.jpg)

Thanks..... :)

**Comment by xoseperez** [comment]
Added. Thank you!

**Comment by cheise** [comment]
![wifiv5](https://user-images.githubusercontent.com/43306023/46174673-f4f8ae80-c2a9-11e8-9d02-befa412f8515.PNG)
