### ISSUE TITLE
Remember form state - sensors

### ISSUE THREAD

**Issue by inverse** [xoseperez/espurna#1229]
I notice that on the sensors tab the form does not remember what the device has been set to.

 For example I changed the energy unit from the default J to kWh but visiting the tab again it still shows J.

**Comment by Valcob** [comment]
Duplicate of [#1177](https://github.com/xoseperez/espurna/issues/1177) please close it and use search ;)

**Comment by inverse** [comment]
I did use search ;) Obviously the wrong keywords ;)
