### ISSUE TITLE
MQTT call multi time on big message 

### ISSUE THREAD

**Issue by phuonglm** [xoseperez/espurna#1234]
Follow this [document](https://github.com/marvinroger/async-mqtt-client/blob/master/docs/3.-Memory-management.md) of async MQTT library, big message will be split to multi small MQTT message with difference start index. The library will call our handler multi time with payload is small message. 

I think the best logic here is our `_onMessage` handler will check the message length, total length, start index, allocate the buffer to catch the all message before dispatch it to our `_mqtt_callbacks`.  

I don't tested with pubsub lib but since pubsub don't give me any parameter like that so I disabled that code with pubsub library.

**Comment by abmantis** [comment]
@xoseperez I've seen some messages fail to send (the mqtt publish method returns zero) while adding some more HA discovery features, because the messages where big.

**Comment by mcspr** [comment]
@abmantis This issue is dealing with receiving big messages.
As you may have noticed, HA discovery messages are getting stuck on initial connection when there are many of them. See PR #1370 and the related issue.

**Comment by mcspr** [comment]
long-time-no-see, but this seems to be already handled by the mqtt buffer size setting circa this commit
https://github.com/xoseperez/espurna/commit/43c2c41cba95c1fd8e702f4bf1609b6e4d10936e#diff-adf1d7b355d1037ad971dd9bf6ca48bce5d8d033d2f1e77073951c5553a2997c
https://github.com/xoseperez/espurna/blob/a69a705cdc9a28b096916d0cec87a4af13a1b1e1/code/espurna/mqtt.cpp#L1004
and the actual message is assembled from multiple onMessage calls

sure, this does not handle binary payloads, but none of the mqtt module funcs actually work with that. that may be another issue, but imo we also want to move away from the multiple-clients paradigm and just use a single one
