### ISSUE TITLE
Blitzwolf BW SHP2 / TFLAG (ASIN B07D2Z3YVM) / TECKIN (ASIN B07D5V139R)

### ISSUE THREAD

**Issue by pilzandreas** [xoseperez/espurna#1238]
https://github.com/xoseperez/espurna/wiki/Hardware-BLITZWOLF-BW-SHP2

Here is how to connect as USB Serial converter (FT232RL FT232 USB 3.3v/5,5v).
Remember to jumper 3,3V !

![screenshot](https://user-images.githubusercontent.com/9336296/46261929-df2df800-c4fa-11e8-894b-a0c4acce1de2.jpg)

(1) pins:
DTR - nc
RX - orange
TX - yellow
VCC - green
CTS - nc
GND - brown
(2) splitting GND (brown) to blue and black cable
(3) blue - GND (from splitter pin)
(4) orange - RX
(5) green - VCC
(6) yellow - TX
(7) tip with black (from splitter pin) on boot to init flash mode - note: there is one free pin between (6) and (7) even if it seems the black wire would be connected the pin next to (6) - its just hanging loosely on my photo.

You will find these power plugs being sold under various labels - i bought a pack of 4 and another with 2 labeld TFLAG (ASIN B07D2Z3YVM) and TECKIN (ASIN B07D5V139R).

Using windows flashing the compiled images offered here worked well doing:
(reboot, short (7) with black, red light dims as you release the pin)
esptool.py --port COM8 erase_flash
(reboot, short (7) with black, red light dims as you release the pin)
esptool.py --port COM8 write_flash --flash_mode dout 0x00000 espurna-1.13.1-blitzwolf-bwshp2.bin
(reboot)
=> connect wifi to test 'espurna_xxxxx' pw fibonacci
http://192.168.4.1 admin/fibonacci
=> logged in

Hope its useful to someone.

Andi

**Comment by xoseperez** [comment]
Great, I have added it to the wiki page.
Thank you!
