### ISSUE TITLE
Wemos D1 mini & D3/GPIO0 as output

### ISSUE THREAD

**Issue by lblabr** [xoseperez/espurna#1243]
i defined GPIO 0 as output, it does not seem to work, does anybody has some hints ?

```
// 	Buttons
//    #define BUTTON1_PIN         0
//    #define BUTTON1_MODE        BUTTON_PUSHBUTTON | BUTTON_DEFAULT_HIGH
// 	LEDs
//    #define LED1_PIN            2
//    #define LED1_PIN_INVERSE    1
//    #define BUTTON2_PIN         2
//    #define BUTTON2_MODE        BUTTON_PUSHBUTTON | BUTTON_DEFAULT_LOW

	#define EVENTS_SUPPORT      1
	#define EVENTS_PIN          16
	#define EVENTS_TRIGGER      1
	#define EVENTS_INTERRUPT_MODE     RISING

    // Relays
    #define RELAY1_PIN          2
    #define RELAY1_TYPE         RELAY_TYPE_NORMAL
    #define RELAY2_PIN          0
    #define RELAY2_TYPE         RELAY_TYPE_NORMAL
    #define RELAY3_PIN          4
    #define RELAY3_TYPE         RELAY_TYPE_NORMAL
    #define RELAY4_PIN          5
    #define RELAY4_TYPE         RELAY_TYPE_NORMAL
```

thanks in advance Lars

**Comment by xoseperez** [comment]
There is no reason why this configuration shouldn't work. Are you sure the relay is on GPIO 0?

**Comment by lblabr** [comment]
yes i´m sure. i also measured the voltage level on the pin it does not change from 3,3 V to 0 if i switch the relay from UI. 
Today i will test with another wemos, maybe there is something on the board

**Comment by xoseperez** [comment]
GPIO0 usually has an external pull-up to enter normal mode on boot. You must pull it low to enter programming mode. But after that, you should be able to pull it low from software.

**Comment by lblabr** [comment]
so far i understud, to define GPIO 0 as output should do that !?

**Comment by xoseperez** [comment]
Yes. Other boards already use GPIO 0 for relay management, so there should be no problem with it...

**Comment by lblabr** [comment]
i tried with second board, voltage level (D3) does not change with the above configuration

**Comment by lblabr** [comment]
btw. its not orig. wemos

**Comment by lblabr** [comment]
i did some measuremnt also an ESP itself the voltage does not change
do you have some hints how can i test whats wrong ?

**Comment by lblabr** [comment]
https://phone-china.en.made-in-china.com/product/vqAnyKkWMdtO/China-Esp8266-Esp-12-Wemos-D1-Mini-WiFi-4m-Bytes-Development-Board-Module.html

**Comment by lblabr** [comment]
adding:

pinMode(0,OUTPUT);
digitalWrite(0,LOW);

in Setting changed the voltage level to "0"

**Comment by lblabr** [comment]
after adding:

pinMode(0,OUTPUT);

in setup procedure it works as expected... maybe the boundaries are somewhere wrong ... GPIO "**0**"

**Comment by xoseperez** [comment]
Setting the pinMode of the relays is done in the _relayConfigure method:

https://github.com/xoseperez/espurna/blob/acf68ac5c8dbf09473b359d94792dda51201913b/code/espurna/relay.ino#L518-L531

**Comment by lblabr** [comment]
i already have seen that, but it seem not to work... i will remove my additional pinMode in the end of the setup() and try again...

i use GPIO 0 and 2 as relay one of  relays is switching during boot precedure,, i think it shouldn´t

**Comment by lblabr** [comment]
verified: 

GPIO 0 does not work as output without an additional 

pinMode(0,OUTPUT); 

at the end of the setup function, i did not tested somewhere in the middle

**Comment by xoseperez** [comment]
It's got to be a hardware-related issue. I just tested with an (original) Wemos D1 mini and it works as expected without changes in the code.

**Comment by lblabr** [comment]
how do i cover my device ? any suggestion ?

**Comment by Misiu** [comment]
@lblabr I'm connecting 4 relays right now (using D0, D5, D6 and D7) pins because when I used D3 and D4 (GPIO0 and GPIO2) they turned on for a short time when boot.
Tomorrow I'll try uploading a custom build with a similar config You posted. I have original Wemos D1 and couple of cheap non-original.
@xoseperez did You have an issue with relays connected to D3, D4 or D8 (as I remember correct D3 and D4 must be high and D8 must be low to start)? Do You have an idea how this problem can be solved (if not by software then maybe hardware)?
