### ISSUE TITLE
Magic Home  IR controller with rotary encoder

### ISSUE THREAD

**Issue by lj502** [xoseperez/espurna#1250]
First off, Espurna is great. I used the rotary encoder code from the Xiaomi Smart desk lamp and made a new device with 3 rgb outputs, IR control, and added a rotary encoder that allows local on/off/dim control. It works great and makes this so much more useful. The encoder uses gpio's 1,3 with 0 as the button, this keeps gpio 4 for IR and all is good. Wow I had a question but I'm blank now, I'll be back

John

**Comment by xoseperez** [comment]
No worries! Come back when you remember the question. :smile:

**Comment by xoseperez** [comment]
Implemented with latest `dev` commit. You can use with the `BUTTON_MODE_DIM_DOWN` and `BUTTON_MODE_DIM_UP` actions.:

```
#elif defined(WEMOS_D1_MINI)

    // Info
    #define MANUFACTURER        "WEMOS"
    #define DEVICE              "D1_MINI"
    #define RELAY_PROVIDER      RELAY_PROVIDER_LIGHT
    #define LIGHT_PROVIDER      LIGHT_PROVIDER_DIMMER
    #define DUMMY_RELAY_COUNT   1

    // Buttons
    #define BUTTON1_PIN         12
    #define BUTTON1_MODE        BUTTON_PUSHBUTTON | BUTTON_DEFAULT_HIGH
    #define BUTTON1_CLICK       BUTTON_MODE_DIM_UP

    #define BUTTON2_PIN         14
    #define BUTTON2_MODE        BUTTON_PUSHBUTTON | BUTTON_DEFAULT_HIGH
    #define BUTTON2_CLICK       BUTTON_MODE_DIM_DOWN

    // Light
    #define LIGHT_CHANNELS      1
    #define LIGHT_CH1_PIN       4
    #define LIGHT_CH1_INVERSE   0
```
