### ISSUE TITLE
Electrodragon relays not working after update to 1.13.3

### ISSUE THREAD

**Issue by skyynet** [xoseperez/espurna#1256]
I did an update from 1.13.2 to 1.13.3. Afterwards switching my relays vie HTTP Get did not work anymore.

I set Restful API to off, saved and rebooted. The Restful API setting in the GUI was again set to on.
Switching relays neither works via GET commands nor the ESPurna GUI.

Reverting to 1.13.2 fixes the issue. So there seems to be a problem in the 1.13.3 version.

**Comment by mcspr** [comment]
I couldn't reproduce this. Saving from web did work and after rebooting `apiRestFul` setting was still there.
Does it always reset settings for you via web? And what does the output of `crash` terminal command looks like? (preferably using telnet / serial instead of Debug panel)

**Comment by xoseperez** [comment]
Version 1.13.3 uses a RESTFUL approach, so changing relays must be done using PUT requests. If you want to revert to the previous usage you can change it from the ADMIN tab in the Web UI or settin the `apiRestFul` setting to 0:

```
set apiRestFul 1
reload
```

**Comment by xoseperez** [comment]
Nonetheless, I agree this change shouldn't have gone into a minor release.

**Comment by skyynet** [comment]
I just reinstalled the 1.13.3 version and today I could save the RESTFUL API to no and use my electrodragon via ESPurna Web Intercace and from my WebApp. Dunno why it didn't work yesterday. Closed.
