### ISSUE TITLE
Restore Sonoff POW Wiki Article

### ISSUE THREAD

**Issue by seetendra** [xoseperez/espurna#1257]
Hello Xose

Could you please restore the Sonoff POW article in the Wiki
I did make some edits to it and iam not able to access it anymore
Sorry for the mess

**Comment by mcspr** [comment]
You can checkout wiki as git repo locally and see old version that way:
```
git clone https://github.com/xoseperez/espurna.wiki.git
```

**Comment by xoseperez** [comment]
Done
