### ISSUE TITLE
Update config changes

### ISSUE THREAD

**Issue by inverse** [xoseperez/espurna#1261]
I updated my devices to the latest version and so far have noticed two changes.

- Energy units got reset to J 
- Energy count got reset

I'm using my own build based on the same tag as current just with the custom.h to disable alexa + provide default configurations.

Performed update via: https://gist.github.com/inverse/ebea0e04db4d27f76cd8a9c21dd46d5a

**Comment by xoseperez** [comment]
The latest version added option to store energy count in flash and changed the energy unit setting name. So it's is normal that count got reset but it should have kept the units. 

Unfortunately, I cannot reproduce this now. I can see that the setting name was correctly migrated so there is no reason to think it was an omission...

**Comment by inverse** [comment]
Thanks for the update and thanks for making this awesome project!
