### ISSUE TITLE
Add dusk and dawn to schedule

### ISSUE THREAD

**Issue by DaNii78** [xoseperez/espurna#1263]
Hi, It would be nice to set the schedule of a relay regarding to dusk or dawn, because the daylight it's constantly growing or decreasing depending on the season of the year. So you wouldn't need to worry about changing the schedule every X days.

**Comment by DaNii78** [comment]
Thanks you, but, I prefer to use this official version.

**Comment by poulch74** [comment]
you can try cherry-pick it into this original version. i make some pull request for this project needed for my custom board, but i am  very lazzy... so  i make custom firmware fork for me/

**Comment by lbdroid** [comment]
@poulch74 : If you have this feature implemented, how's about a PR?

@DaNii78 : If your objective here is to obtain the functionality, you can use a home automation server to implement it. Domoticz, for instance. When you define your switch, you can add timers to it to the effect of "turn ON 30 minutes before sunset" and "turn OFF 30 minutes after runrise". It calculates sunset and sunrise based on the coordinates you configure it with. Domoticz is light enough to run on your router, and is even packaged by OpenWRT (as well as mosquitto, which you will also need).

**Comment by DaNii78** [comment]
@lbdroid I know that I can use HA, but, I wouldn't like to deploy this framework only to use this option. The same way that exists schedules nativelly in espurna's firmware, I think that add this option would be nice, even more when there are other firmwares that already do that.

**Comment by mcspr** [comment]
Closing via https://github.com/xoseperez/espurna/commit/8edb7b633369cd04151525066ab0f8b512da7702 and since #2127 & #2417 are also closed
