### ISSUE TITLE
Double entry for ON switch from Domoticz

### ISSUE THREAD

**Issue by Camposmansi** [xoseperez/espurna#1264]
After talking with the people of Domoticz, it is concluded that domoticz works perfectly, this being ESPurna's problem:
https://github.com/domoticz/domoticz/issues/2175#issuecomment-428463680

It happens to all of us who use espurna with domoticz, you can see all the tests in the link above.

It is clearly seen "Espurna" echoes again what it receives, when domoticz sends, it receives this, well, but why does this have to be send back to domoticz?

the developer says that they can contact him without problems is @gizmocuz

-----------------------------------------------------------------------------------------------------------------

Despues de hablar con la gente de Domoticz, se llega a la conclusion que domoticz funciona a perfecto, siendo esto problema de ESPurna:
https://github.com/domoticz/domoticz/issues/2175#issuecomment-428463680

Nos pasa a todos los que utilizamos espurna con domoticz, pueden ver todas las pruebas en el enlace de arriba.

Se ve claramente "Espurna" se hace eco de nuevo lo que recibe, cuando domoticz envia, recibe este, bien, pero ¿por qué esto tiene que ser enviar de vuelta a domoticz?

el desarrollador comenta que se pueden poner en contacto con el sin problemas es @gizmocuz

**Comment by mcspr** [comment]
Long-overdue... Having tried out approach in #1368, I am not a big fan of having a single place where all the "relay" modules are described preemptively. Trying to avoid it, two possible implementations:
1. combine all "external" relay switch methods (mqtt groups, domoticz, thingspeak) under broker module and just track local state. if switch came on from domoticz, store it as locally set and pass to the relays to switch it on. notification coming back checks local state and does nothing.
2. have broker remember it's caller [like this](https://gist.github.com/mcspr/a627ea626775b5a6dcc6fb1aa8561979) (and possibly extend to make delayed calls, keeping events in the queue and launching them inside loop) and rework relay processing to interact with it.

I do have a prototype with both combined, but will also probably try to work it out keeping the current broker.

**Comment by Camposmansi** [comment]
If you want me to try something, I have no problem

**Comment by mcspr** [comment]
after long clean-up, prototype now lives at https://github.com/mcspr/espurna/tree/broker/events
only briefly tested with domoticz in/out
