### ISSUE TITLE
Amazon Echo doesn't see devices after update to 1.13.3 from 1.13.2 on a range of Sonoff devices. 

### ISSUE THREAD

**Issue by aroslanov** [xoseperez/espurna#1268]
Flashed binary firmware through admin menu. Rollback to .12 helps. Basic, TH, Slampher...

**Comment by skorokithakis** [comment]
Are they still connected to the WiFi? I'm having some disassociation issues.

**Comment by aroslanov** [comment]
BTW, S20 stopped responding at all after the update. I'll probably have to reflash it over UART.

**Comment by xoseperez** [comment]
Does it work if you downgrade to 1.13.2?

**Comment by coatbrigand** [comment]
Yes, it works after a downgrade.

**Comment by swilson86** [comment]
Confirmed. I downgraded to 1.13.2 and it works again. Here is a clue on 1.13.3 when Alexa is discovering new devices... on the iTead RGBW bulbs she discovers the bulb itself and another device for R, G, B, and W. Thus 5 devices discovered for each bulb. Really bizarre!

**Comment by aroslanov** [comment]
> Does it work if you downgrade to 1.13.2?
Yes, it does

**Comment by Gtlng** [comment]
On a Shelly1 I can confirm that problem. Espurna 1.13.2 (with fauxmoESP 2.4.2) works like a charm. Espurna 1.13.3 (fauxmo 3.0.1) is not working; Alexa doesn't detect the device.

**Comment by kerk1v** [comment]
Same problem here. Alexa tries to tetect them through Web API, debug window shows the calls but complains about missing API key :(

**Comment by Wikibear** [comment]
Sonoff Basic and experience same issue.

**Comment by fragolinux** [comment]
sonoff rf bridge with "direct" hack: confirmed working on 1.13.1, upgraded to 1.13.3 directly and it didn't work anymore (could't find devices already recognized), went back to 1.13.2 and devices are available and working again

**Comment by DaNii78** [comment]
Same happens to me

**Comment by Tsuyoshi-Moriyama** [comment]
ESPurna 1.1.3.3 was detected as Philips HUE Bridge 2012 when I search the network using Fing APP.
![fing](https://user-images.githubusercontent.com/35362114/49910086-c52e6f80-fec4-11e8-9291-cf922a05b784.jpg)
![espuna](https://user-images.githubusercontent.com/35362114/49910097-cbbce700-fec4-11e8-8d12-838de58ee55e.jpg)

**Comment by fragolinux** [comment]
> ESPurna `dev` branch has been updated to use fauxmoESP 3.1.0 which fixed several issues and provides compatibility with gen3 devices. Maybe you can give it a try and report back?

hi, any premade binary firmware available? I can test it on my "direct" sonoff rf bridge :)

**Comment by xoseperez** [comment]
Not yet. Maybe tomorrow you will be able to download a nightly build from @mcspr repo (https://github.com/mcspr/espurna-nightly-builder/releases).

**Comment by fragolinux** [comment]
ok, i'll wait and try tomorrow, thanks

**Comment by mcspr** [comment]
@xoseperez from fauxmo readme:
> fauxmoESP 3.X.X: When using Arduino Core for ESP8266 v2.4.X, double check you are building the project with LwIP Variant set to "v1.4 Higher Bandwidth". You can change it from the Tools menu in the Arduino IDE or passing the -DPIO_FRAMEWORK_ARDUINO_LWIP_HIGHER_BANDWIDTH build flag to PlatformIO.

1. Comment should also be?
https://github.com/xoseperez/espurna/blob/2ffb7de4d7752b503501307afad4b2db2b9d7402/code/espurna/config/general.h#L1152-L1155
2. Does this still apply for current 2.5.0 beta builds with lwip2.1 (-feat variant, default one)?
3. General fauxmo question, bc I cannot login to bitbucket for some reason: does lwip2 break the tcp or udp part?

**Comment by xoseperez** [comment]
It doesn't show up in the app but you can interact with it via voice.

**Comment by Wikibear** [comment]
It's not the best way, but its ok. Voice works, that is the important think. But would be great to have back the switch to control it via App as before. Are Bulbs now get a better support???

**Comment by Wikibear** [comment]
I use Lohas Bulb E27 W9 with last dev and Alexa found this device six times... 

https://i.imgur.com/r5FHGVz.png

Deckenlampe is missing in this list but it's there, too. Must rename it to Deckenlampe 0 and only this will switch on off. The others maybe fake or the other channels?

**Comment by xoseperez** [comment]
It will create one to turn the bulb on and off and one for each channel. We certainly need custom names here.

**Comment by oscarsan1** [comment]
It is also important the app control for example to turn off and on remotely, outside the house, with alexa app. Aslo for control if the light are on or off outside the house.

**Comment by tji100** [comment]
I didn’t post there because there are already a couple of active issues about Alexa gen 3. Do you suggest I should start a new one for this specific case?

**Comment by xoseperez** [comment]
Yes, I do think it's worth opening a new issue with this report.
