### ISSUE TITLE
ESPurna and ARILUX_AL_LC01

### ISSUE THREAD

**Issue by dertinu** [xoseperez/espurna#1272]
Hi,

i successful flashed an ARILUX_AL_LC01 with ESPurna. In the Status Tab of the WebUi i am able to set the colours of my LED strip etc. Everything works fine but....

Where ist the MQTT Tab in the WebUI? 
![screen](https://user-images.githubusercontent.com/3651561/46885045-0cfa3180-ce57-11e8-8832-659825a112af.jpg)

Thanks for any Idea how to fix.

dertinu

**Comment by xoseperez** [comment]
I can't reproduce this issue. Building Arilux LC-01 image for 1.13.3 with Core 2.4.2. Everything is in place. 

I can tell that you have a custom build so maybe there was something missing in your configuration? Default configuration also has schedule, thinkspeak,...
