### ISSUE TITLE
Change hostname in config

### ISSUE THREAD

**Issue by vaidyasr** [xoseperez/espurna#1274]
My RF Bridge randomly reset to factory defaults. I thought of checking via homeassistant probably twice a day and upload the settings in case of factory defaults. For that I have changed the general.h with all Wifi, MQTT values. I was looking was changing the hostname and found defaults.h. Tried changing, but still the hostname is 'ESPURNA-XXXXX'. How to change the hostname as static like 'SONOFF-BRIDGE'

And is there a way to restore the settings via command line or MQTT?.

**Comment by mcspr** [comment]
Hostname is persisted to settings on first boot so you'd still see it when flashing new .bin with new HOSTNAME set - it'll use the one from live settings first. see `keys` command and `hostname` value
Although it is confusing and it should not store default one for cases like this.

See https://github.com/xoseperez/espurna/issues/751#issuecomment-378590742 - /config will dump device settings as json and also accept PUT request to replace them
