### ISSUE TITLE
Enable Restful API is always on after power off

### ISSUE THREAD

**Issue by cracautanu** [xoseperez/espurna#1280]
- go to admin and set Enable HTTP API to OFF
- power off device
- power on
=> Enable HTTP API is now again on. 

I have issues with the CORS requests and this was a solution to me till I found this
I used Sonoff 4 channel PRO with release 1.13.3

**Comment by mcspr** [comment]
Did you "Save" before rebooting? See side menu. This is expected behaviour for web.
If saving does not work for release, you might want to try building .bin yourself from 'dev' and try that.

**Comment by cracautanu** [comment]
I saved it of course. The setting also seems to be saved ok in eeprom. After running the reload command in terminal the setting is loaded ok

**Comment by spike411** [comment]
I'm seeing the same thing. Only with the 'Restful API' option. Others, such as the 'HTTP API' option, seem to work as expected.

1. Set 'Restful API' to 'No.
2. Save the settings.
3. Verify HTTP GET works in the web browser: http://ip_address/api/relay/0?apikey=api_key&value=2 toggles the switch indeed!
4. Reboot the device using the Reboot button in the menu.
5. HTTP GET no longer works and the 'Restful API' option is set to 'Yes' again.

Hardware:
https://github.com/xoseperez/espurna/wiki/Hardware-NEO-COOLCAM-NAS-WR01W
Firmware:
espurna-1.13.3-neo-coolcam-power-plug-wifi.bin

**Comment by mcspr** [comment]
Ok, got it. See https://github.com/xoseperez/espurna/pull/1288

**Comment by cracautanu** [comment]
@ Thanks for correcting, I meant to say  Restful API.. I realized the mistake, corrected the title but forgot the body :) Cheers!
