### ISSUE TITLE
Sonoff reboots after 1.12.6

### ISSUE THREAD

**Issue by Interpyme** [xoseperez/espurna#1281]
Hi, I have been using espurna for almost a year now. I´ve noticed a recurrent problem with all my devices.

Right now I´m using version 1.12.6 in all of them because when I update to any version >1.13.x they seem to have the same bug, they reboot. Sometimes it happens after a few hours, sometimes after a couple of days.

I´ve tried sonoff duals, sonoff basics, relays, power sockets, pow.... And with all of them seems to happen exactly the same problem. Uptime is never more than a few days. With 1.12.6 some of them are running for several months already and no reboots.

Thanks for your great efforts!!

**Comment by jsponz** [comment]
Yes, that happens also to me :-( 

I have just found it out some hours ago. 

Any help? Any idea?
