### ISSUE TITLE
CR: Make WEB_REMOTE_DOMAIN configurable from admin console

### ISSUE THREAD

**Issue by cracautanu** [xoseperez/espurna#1289]
HTTP Api/Restful Api are not usable by custom web clients because of the CORS error. I tried ASP MVC 5 and Angular 6 but couldn't pass it. I also tried jsonp ajax get requests - they work to set a switch status, but it's really hard to get a response since they expect to set a callback and always throw an error. 
From my point of view this is a big limitation especially for those who don't want to get their hands dirty and rebuild/flash everything when taking a custom app online.

Playing with a restful extension for Chrome will work because the browser doesn't set the origin in the header...

**Comment by mcspr** [comment]
\-> https://github.com/xoseperez/espurna/pull/1789

`webDomain` setting now handles this in addition to the WEB_REMOTE_DOMAIN define
