### ISSUE TITLE
I can,t connect dashboard

### ISSUE THREAD

**Issue by jotamayo** [xoseperez/espurna#1291]
Hello

I have two sonoff with espurna, with one i don,t problemas but with other i can,t open http Page configuration.

This device has Ping but when i put http:IP i can,t arrive any idea?

Thk you

**Comment by xoseperez** [comment]
Sonoff Basic devices have a poor wifi range. Test them close to your router and open a terminal to see what's going on when you try to open an HTTP connection.

**Comment by jotamayo** [comment]
Hello

Thaks for replay me, i closed router Andrés i cant arrive way http, when i put  IP in the navigation, this return can,t Connect. I selected the wifi generated by device

**Comment by xoseperez** [comment]
What IP address are you using? If you are connected to the device AP, the IP of the device will be 192.168.4.1.

**Comment by jotamayo** [comment]
i am putting the ip 192.168.1.201. i just i installed app fing and it didn,t find any service. but in the another sonoff with spurna yes finded two services, http and telnet

**Comment by xoseperez** [comment]
I understood you were connected to "the wifi generated by device". In this case, the device will be in 192.168.4.1.

**Comment by jotamayo** [comment]
I can,t arrive ip 192.168.4.1, mac laptop connected wth wifi device but not response for navigation with ip 192.168.4.1

**Comment by jotamayo** [comment]
i don,t know how do this action. do i have to  install again firmware?

**Comment by ColinShorts** [comment]
It might be quicker to flash the device again. Normally you would flash the device using the serial connection, and you should then be able to connect to the device with the same connection using minicom, hyperterminal, or putty, etc.

Please do not connect to the serial port if the device is plugged into the mains power supply!

**Comment by xoseperez** [comment]
Good!
