### ISSUE TITLE
Quinled brightness vs MQTT vs HA

### ISSUE THREAD

**Issue by adrianmihalko** [xoseperez/espurna#1292]
First, thank you for making this great firmware. I want to use it with Quinled. I am happy to see it's supported.

There are small issue what I found:

- Brightness control is not added when I use auto discovery in Home Assistant, this part:

```
    brightness: true
    brightness_scale: 255
    brightness_command_topic: 'QUINLED-BED/brightness/set'
    brightness_state_topic: 'QUINLED-BED/brightness'
```

And I have one more question: what's the difference between setting brightness trough Brightness command vs. Channel #? Or I should leave both channels at maximum 255, then adjust brightness only with Brightness command?

<img width="523" alt="screenshot 2018-10-20 at 14 46 46" src="https://user-images.githubusercontent.com/733361/47255850-fd8e7000-d476-11e8-87a1-30579fe59934.png">

Thank you,
Adrian

**Comment by ColinShorts** [comment]
This might be related to #1222

**Comment by adrianmihalko** [comment]
One more question/problem:

If I unplug espurna device, in HA device newer goes into unavailable state, and if was turned on it stay in state on. And this is problem. Is there any way to stay in sync?

**Comment by 1043717432** [comment]
> 正如你所写，有2个频道，＃0和[＃1](https://github.com/xoseperez/espurna/issues/1)：
> 
> <img alt="截图2018-11-13 at 12 26 00" width="585" src="https://user-images.githubusercontent.com/733361/48410609-58964880-e73f-11e8-9557-a7b4b1bf3aad.png">
> 
> 我想要的就是将两个通道都放在255（100％）上并使用亮度命令调整亮度（图片上的底部滑块）。
> 
> 这是不可能的？

This is my need. Have you solved the problem? Can you share the yaml file?

**Comment by mcspr** [comment]
> All what I want is to leave both channels on 255 (100%) and adjust brightness with the Brightness command (bottom slider on the picture).
>
> This is not possible?

IMO the color check should just be removed. webui already exposes the slider and _generateBrightness handles it by setting all channels to the same value.

Not sure how second channel can be described through [HA mqtt.light](https://www.home-assistant.io/components/light.mqtt/) logic

**Comment by copyrights** [comment]
BTW: <root>/brightness is already published, only subscription to <root>/brightness/set is missing

here is what mosquitto logs after mqtt.reset:
```
1558352737: Received UNSUBSCRIBE from ESPURNA-XXXXXX
1558352737: 	#
1558352737: ESPURNA-XXXXXX #
1558352737: Sending UNSUBACK to ESPURNA-XXXXXX
1558352737: Received SUBSCRIBE from ESPURNA-XXXXXX
1558352737: 	QuinLED2/channel/+/set (QoS 0)
1558352737: ESPURNA-XXXXXX 0 QuinLED2/channel/+/set
1558352737: Sending SUBACK to ESPURNA-XXXXXX
1558352737: Received SUBSCRIBE from ESPURNA-XXXXXX
1558352737: 	QuinLED2/relay/+/set (QoS 0)
1558352737: ESPURNA-XXXXXX 0 QuinLED2/relay/+/set
1558352737: Sending SUBACK to ESPURNA-XXXXXX
1558352737: Received SUBSCRIBE from ESPURNA-XXXXXX
1558352737: 	QuinLED2/pulse/+/set (QoS 0)
1558352737: ESPURNA-XXXXXX 0 QuinLED2/pulse/+/set
1558352737: Sending SUBACK to ESPURNA-XXXXXX
1558352737: Received SUBSCRIBE from ESPURNA-XXXXXX
1558352737: 	QuinLED2/led/+/set (QoS 0)
1558352737: ESPURNA-XXXXXX 0 QuinLED2/led/+/set
1558352737: Sending SUBACK to ESPURNA-XXXXXX
1558352737: Received SUBSCRIBE from ESPURNA-XXXXXX
1558352737: 	QuinLED2/action/set (QoS 0)
1558352737: ESPURNA-XXXXXX 0 QuinLED2/action/set
1558352737: Sending SUBACK to ESPURNA-XXXXXX
```
