### ISSUE TITLE
PLUGIN REST API

### ISSUE THREAD

**Issue by lblabr** [xoseperez/espurna#1299]
in documentation of REST API is written:

Since version 1.6.4 you can also change the relay value via a GET request.

$ curl "http://192.168.1.108/api/relay/0?apikey=C62ED7BE7593B658&value=2"
relay0 => 0
$ curl "http://192.168.1.108/api/relay/0?apikey=C62ED7BE7593B658&value=2"
relay0 => 1

where and how this is done ? I can't find how the relay ist set with get_function (api_regsiter) .... in relay.ino ....

I would like to set ouptut in my plugin with GET command. PUT is working ....

thanks in advance

Lars

**Comment by mcspr** [comment]
It is disabled by default, see https://github.com/xoseperez/espurna/issues/1192
And https://github.com/xoseperez/espurna/pull/1288/files to fix value not restoring after reboot

**Comment by lblabr** [comment]
thank you very much! works!

just one question, why is POST not supported ?

**Comment by skyynet** [comment]
Thanks. Solved the problem of my board loosing its setting, too.
