### ISSUE TITLE
WebUI first init problem

### ISSUE THREAD

**Issue by lcdkk** [xoseperez/espurna#1316]
hi;

when i was flash the new sonoff bridge rf , and then find espruna ssid, and login see the
change admin password screen, and generate the new password then save,
but now lost connection wifi, and unable to login.

any on can assist this ?

thanks.
neo

**Comment by mcspr** [comment]
Use the new password. It is shared between web and wifi.

**Comment by pit001** [comment]
Here also. 
This is new (not with FW 12) and surpricing  - I also need 3 reflashing loops.

**Comment by seetendra** [comment]
Is there a way by which I can build a bin file with my Wifi Password integrated into it.

**Comment by lucaberta** [comment]
> Is there a way by which I can build a bin file with my Wifi Password integrated into it.

@seetendra look for the default wifi credentials in general.h:

https://github.com/xoseperez/espurna/blob/dev/code/espurna/config/general.h

**Comment by seetendra** [comment]
@lucaberta Thanks a lot for your reply.
Can you please help me with the Sonoff POW as well. If you have tried Tasmota it has the option to look for the Total Power consumption (Sonoff POW) and Daily Consumption as well.
Is there a Way we can see that with Espurna ?

**Comment by lucaberta** [comment]
> @lucaberta Thanks a lot for your reply.
> Can you please help me with the Sonoff POW as well. If you have tried Tasmota it has the option to look for the Total Power consumption (Sonoff POW) and Daily Consumption as well.
> Is there a Way we can see that with Espurna ?

@seetendra you might want to direct this sort of questions to the Gitter channel dedicated to discussing ESPurna like Xose says in the README file:

> Please use the [gitter ESPurna channel](https://gitter.im/tinkerman-cat/espurna) for support and questions, you have better chances to get fast answers from me or other ESPurna users. Open an issue here only if you feel there is a bug or you want to request an enhancement. Thank you.

**Comment by seetendra** [comment]
Ok will do

**Comment by mcspr** [comment]
Initial screen should have ssid/pass entries for a single network. OSes make it non-trivial to instantly forget the network ssid when it changes. Windows 10, for example, will refuse connection without any warning and requires manually "forgetting" the network before second connection by closing-opening wifi listing.

This also can be mitigated by removing wifi settings reload, which restarts AP immediately when user changes password. WebUI can then reload and ask new password, allowing to change settings as usual. Next settings reload can drop the connection
