### ISSUE TITLE
Last state option at startup

### ISSUE THREAD

**Issue by jimmyh98** [xoseperez/espurna#1318]
First of all I would like to thank you for this project that is helping with my residential automation project and then I would like to ask a question. I'm still new to mqtt, esp8266 and plataformio. But this question is about the light, I wonder if it has any function to turn the lamp off (by the switch) back to the previous state (or a user defined state)?

**Comment by mcspr** [comment]
Hello.

If by startup you mean restoring last state when power goes down - see 'Boot mode' option in Switches panel.

**Comment by jimmyh98** [comment]
Thanks @mcspr helped me but I would still like an option where I could select a color to start at boot. maybe @xoseperez can cast on v2 of espurna

**Comment by xoseperez** [comment]
The idea would be to "freeze" the current color value in the config so it will get that on boot instead of the last color. It's actually simpler than what it is doing atm but the tricky part is how to make it work from the webUI (mostly a UX issue).

**Comment by jimmyh98** [comment]
Yes it's more or less this, only that would be a fixed color chosen to start at boot. For I have a wifi lamp and I would like it to start white all the time because I imagine in a situation where my mqtt broker stopped responding and so the light would be just a common light when I turned off the power.

**Comment by jimmyh98** [comment]
Sorry, I closed it unintentionally.🤗
