### ISSUE TITLE
Question: Own HW (like Enocean, KNXRF, RS232, 886MHz)

### ISSUE THREAD

**Issue by pit001** [xoseperez/espurna#1330]
Hi. I learned the the Espurna FW is a very stable and function rich system. 
But only used to replace the FW of other Vendors. 

So, is there the interest in a own HW ?
Of course not the next type of relay switch, but maybe a not existing GW something like Enocean, KNXRF, RS232 in general, 886MHz, ...

Or a driver for a 7-segment/matrix Clock, a WORD Clock with ws2812b, ...

Peter

**Comment by xoseperez** [comment]
Well, ESPurna was born to be flashed on smart switches. With time it has evolved to something more general but it still focuses on something we could call domotics (switches, lights, sensors,...).

I don't think it should go further and become a general purpose firmware. Although some of its features actually do what you suggest (like the RFM69 gateway). But there is a lot of work to do and adding new features outside the scope of the firmware is not in my mind atm.

Of course, it is (somewhat) modular or at least that is the intention, so you could use bits from here and there as the foundation for other projects.
