### ISSUE TITLE
Having to enter the password twice on iOS

### ISSUE THREAD

**Issue by mrwee** [xoseperez/espurna#1341]
Using v1.13.3 .bin version on both a Sonoff Dual & H801, I experience that after changing the default password, I need to enter the new one twice ('admin' + new password) before gaining access to the webinterface. Using a complex password, makes this part very annoying on e.g. an iPhone. Don't know if it's an iOS or Espurna issue.

**Comment by mcspr** [comment]
Hello.

My understanding is Safari on iOS has some weird behaviour when dealing with HTTP Authorization (Basic or Digest), compared to form handling. Two options:
- "App & Website Passwords" in the system Settings has per-domain passwords, which *should* help with this
- build the firmware yourself and disable password altogether
