### ISSUE TITLE
rfbridge only sending first 8 relays via MQTT for auto-discovery

### ISSUE THREAD

**Issue by peterhoeg** [xoseperez/espurna#1346]
While setting ```#define DUMMY_RELAY_COUNT 16``` in ```custom.h``` makes additional 8 relays available in the UI, only the first 8 are submitted to home assistant for auto-discovery.

Further to #1133.

Additional reference: #1308 

Cc: @mcspr @vogelfreiheit

**Comment by peterhoeg** [comment]
Bump to keep this alive.

**Comment by mcspr** [comment]
Closing via #1969
