### ISSUE TITLE
Sonof Basic Add Network

### ISSUE THREAD

**Issue by spenjt** [xoseperez/espurna#1353]
I have just added a second router to make connections to my Sonoffs better. I want 2 SSID added to the Sonoffs so that it can be configured using one of the routers and then moved later.
When adding a second network SSID it is changing the first SSID to match the second and therefore there is only one SSID that can be used.

**Comment by spenjt** [comment]
Sorry, this is with a Sonoff Basic with the most recent version 1.13.3

**Comment by spenjt** [comment]
I have made the SSIDs separate so that our phones don't connect to the other router. It's just that the after configuring Espurna with two separate SSIDs and rebooting., both SSID entries have the same SSID.

**Comment by xoseperez** [comment]
Do you mean you stored two different SSIDs in ESPurna and, after rebooting, they are not the same?

**Comment by spenjt** [comment]
As I understand it, you can enter multiple WIFI connections and it picks the strongest connection. I had entered details for two different routers (i.e. two different SSIDs). When I rebooted  one of the SSIDs had been renamed, so that both entries had the same SSID.

**Comment by spenjt** [comment]
It's not important to me at all. Just thought I would make you aware of it.

**Comment by xoseperez** [comment]
Does it always happen? Can you reproduce the issue (configure two different SSID, reboot and check the configuration)?
