### ISSUE TITLE
Smart Dual Plug reference support

### ISSUE THREAD

**Issue by jaimemrjm** [xoseperez/espurna#1358]
> Other supported boards (beta): KMC 4 Outlet, Gosund WS1, **Smart Dual Plug**, MakerFocus Intelligent Module LM33 for Lamps

`README` says that Smart Dual Plug is supported (beta) but I have not found any additional reference. Which model and vendor are you talking of? I'm searching for a dual or double smart plug ESP8266 based-on.

**Comment by xoseperez** [comment]
I'm afraid that was a wrong reference... There is no such device in the list of supported devices. I'm removing it now.

**Comment by samuelnygaard** [comment]
Hi @xoseperez, i can't find any reference for LM33 (MakerFocus), can you point in the right direction?
