### ISSUE TITLE
Thingspeak. Updates not following settings correctly

### ISSUE THREAD

**Issue by Wisnaeme** [xoseperez/espurna#1369]
Thingspeak data uploads are missing fields in the data packet.

Settings are as follows.; Three fields enabled as "1=Switch, 2=Temp, 3=Humidity"
Switch#0 1
Temperature#0 2 DHT22 @ GPIO14
Humidity#0 3 DHT22 @ GPIO14

Data upload is as follows: (Missing field 1 for no obvious reason)
Connected to api.thingspeak.com:80
POST /update?field2=15.4&field3=61&api_key=<MY KEY>

Any suggestions?

![thing1](https://user-images.githubusercontent.com/15055735/48962327-55d4f800-ef76-11e8-9ff2-aedd6f8c2779.PNG)
![thing2](https://user-images.githubusercontent.com/15055735/48962328-566d8e80-ef76-11e8-9a1c-29f6061f5752.PNG)

Update:
Changing to fields 4,2,3 has no fix. Field 4 is also missing:
POST /update?field2=15.5&field3=60&api_key=IP....

Running version 1.13.3 from the prebuilt files on a Sonoff Basic with added DHT22.

Totally disabling Thingspeak and setting all fields to 0 does not stop the sending of 2,3.
Reflashing the same firmware over didn't fix this.

**Comment by Wisnaeme** [comment]
Update:
Totally disabling Thingspeak and setting all fields to 0 does not stop the sending of 2,3.

**Comment by Wisnaeme** [comment]
![image](https://user-images.githubusercontent.com/15055735/48965997-5c885d00-efc0-11e8-9e18-0eb1d77607a2.png)

Without any changes since I went to bed last night, the "field1" seems to have appeared in the Thingspeak data.
![image](https://user-images.githubusercontent.com/15055735/48966049-12ec4200-efc1-11e8-9fbd-1cff29dfc445.png)
![image](https://user-images.githubusercontent.com/15055735/48966064-40d18680-efc1-11e8-87a0-c342462e906f.png)

Maybe I'm wrong, but is Espurna only sending the column if the data has changed form the last send? It appears to have only sent the data after a clicked the switch a couple of times. If that's the way it's designed to be it's a bit bad in my opinion. This will lead to missing data in the fields and confusion. It'd be better always sending the value.

**Comment by mcspr** [comment]
Sorry for delay, I had missed the second message.

So do you mean it should it relay in the same way as sensors? i.e. just send current value periodically?
(which does happen for mqtt platform via "heartbeat" mechanism)

<details>
<summary>*Reading .ino / .h to understand tspk flow here:*</summary>

Thingspeak module limits itself to 1 POST per 15 seconds
https://github.com/xoseperez/espurna/blob/de7ff7722c2c0eccd34ae0d7b08005fe38720b66/code/espurna/config/general.h#L1027
Temperature is sent when "sensor report event" happens - 5 minutes in your case (`snsReport` / `snsRead` combination / their defined defaults)
https://github.com/xoseperez/espurna/blob/de7ff7722c2c0eccd34ae0d7b08005fe38720b66/code/espurna/sensor.ino#L1460
Relay report happens on switching only. If thingspeak does not send immediately (15 sec window) - only latest value is stored.
https://github.com/xoseperez/espurna/blob/de7ff7722c2c0eccd34ae0d7b08005fe38720b66/code/espurna/relay.ino#L200-L201
https://github.com/xoseperez/espurna/blob/de7ff7722c2c0eccd34ae0d7b08005fe38720b66/code/espurna/thinkspeak.ino#L308-L309

</details>

**Comment by Wisnaeme** [comment]
It would certainly prefer that all states be sent when an update is required to Thing speak.
If it's current form the line of data sent is "The relay changed" which is less useful than "The relay status at every temperature/humidity event was xxx"

I just find it troublesome for what is a sheet of data to have missing fields in the data. Missing data means you need to search back and forth for the status of the missing data which isn't always practical.
If there's space to do it, having a toggle for this could be good.

I'm fairly new to this stuff so I've used a prebuilt code. I will maybe build one later on for very specific custom cases.

Thanks for the reply!

**Comment by mcspr** [comment]
[API docs](https://www.mathworks.com/help/thingspeak/readfield.html) describe individual field export:
`https://api.thingspeak.com/channels/<channel>/fields/field1.csv` (adding `?api_key=<key>` and etc.)
to fetch similar date/number/field_value. even additional params like `start` & `end` for specific time or `days` for data older than one day (default is 1)
I feel like this is better solution than to add additional entries.

ofc you *can* change the module to keep the data in the queue (see _tspkClearQueue()) and send everything. Field value is recorded by the thingspeak.com each time with timestamp and will not be  filtered when it is the same as the last time, so watch out for that.

**Comment by xoseperez** [comment]
I have added an option in the web interface to avoid clearing the cache after each POST to thingspeak.com (as suggested by @mcspr). This way you will receive all fields with every POST. It's in the `dev` branch now.
