### ISSUE TITLE
Create CONTRIBUTING file

### ISSUE THREAD

**Issue by mcspr** [xoseperez/espurna#1371]
See https://help.github.com/articles/setting-guidelines-for-repository-contributors/
Wiki already contains https://github.com/xoseperez/espurna/wiki/PullRequests, adapting it here would make it visible in the repo UI.

**Comment by xoseperez** [comment]
I have created a `contributing.md` page under .github (not sure this is the best place). Also added templates for issue reporting. Comments welcome.

**Comment by mcspr** [comment]
It can be in the root directory: https://github.com/atom/atom/blob/master/CONTRIBUTING.md

Going to the atom/atom and trying to do things, CONTRIBUTING.md link is shown:
"New Issue" has it to the side (screenshot in the doc)
Going to the **Issues** or **Pull requests** tab shows it at the top
So it can have some short info about issues (labels, duplicates, stale), prs (what it is now) and documentation (per-device quirks, building in ide / pio i.e. link to the wiki pages)?

Another thing I noticed: when doing "New Issue" it also links to SUPPORT.md if it is present
["Looking for help? Check out the project’s instructions for getting support."](https://github.com/atom/atom/blob/master/SUPPORT.md)

**Comment by xoseperez** [comment]
Moved to root folder and added a preliminary SUPPORT.md page.
