### ISSUE TITLE
GPIO 14 push buttom

### ISSUE THREAD

**Issue by eduardocanton** [xoseperez/espurna#1376]
Hello
The espurna uses gpio0 to change the relay status.

I would like use GPIO14 to change the relay status... I would like when I push GPIO14 the relay changes if the status of GPIO14 changes. Why? To avoid quick changes (reset) if you turn on a light in your room.

is it possible?

**Comment by xoseperez** [comment]
ESPurna uses GPIO0 for the relay if the device is configured that way. There are many devices that have the relay attached to other GPIOs. Check the `hardware.h` file under the `config` folder to see the devices configuration.
