### ISSUE TITLE
Specify NTP and DNS servers

### ISSUE THREAD

**Issue by xoseperez** [xoseperez/espurna#138]
Originally reported by: **treowayne (Bitbucket: [treowayne](https://bitbucket.org/treowayne), GitHub: Unknown)**

----------------------------------------

I like to use my router to prevent IoT devices from having internet access. I have several Espurna Sonoff devices that I funnel through a reverse proxy for access from the outside world. 

It would be great to be able to specify my router (or some other device or IP) as the NTP and DNS server so I can block all WAN traffic to/from my Espurna devices. As for the DNS, it would be neat to just get through DHCP.

**Comment by eramanaraju** [comment]
HI HOW TO ENABLE NTP SUPPORT OPTION IN ESPURNA
