### ISSUE TITLE
Nonsequential sensor _IDs

### ISSUE THREAD

**Issue by mcspr** [xoseperez/espurna#1384]
https://github.com/xoseperez/espurna/blob/9f1429c441d2c241f979d8a763ef876460b6f9fd/code/espurna/config/types.h#L290-L294
(0x9 -> 9, 0x10 -> 16)

Same for both `v2` and `dev`
This either should be decimal or use enum instead

**Comment by xoseperez** [comment]
This was fixed with the last merge from the `sensors` branch.
