### ISSUE TITLE
Sonoff RF Bridge - worth to do the hardware hack?

### ISSUE THREAD

**Issue by vampywiz17** [xoseperez/espurna#1391]
Hello there,

I use my RF Bridge to Tasmota+ Portisch RF Firmware.

I read this wiki that possible to do a hardware hack that is able to access wider range of coding/decoding. I want to use a Kinetic Doorbell ([KERUI F56](https://goo.gl/GP9wub))

Now, if i try to  catch the signal nothing happened. (really nothing, the red LED is not blinking, not see any RF signal) If i try a other type of doorbell (a regular, battery powered one) i able to catch it, and the led is blinking.

My question is that the hardware hack is help me? My problem is not that cant decode the signal, my problem that i not see any signal at all.

If mean that RF led is not blink that it use a bit different  freq and the RF Bridge not see it and the hardware hack not help, or worth to try it?

**Comment by xoseperez** [comment]
@jackwilsdon is right. If you have the chance, test if your device frames are decoded by the rc-switch library using a development board and a 433MHz radio link.
