### ISSUE TITLE
Nofuss missing

### ISSUE THREAD

**Issue by schweini** [xoseperez/espurna#1393]
I just compiled the dev branch, and have define NOFUSS_SUPPORT defined in general.h, but I can't seem to find the relevant options in the UI?

**Comment by mcspr** [comment]
See "Admin" panel, right above Upgrade:
<img src="https://user-images.githubusercontent.com/132763/49513584-897f1e80-f8a2-11e8-9468-325b63f7f60d.png" width="50%"/>

Although, I agree that it is tough to find. It should be in a separate panel like NTP, HASS and Thingspeak are.
