### ISSUE TITLE
eepromRotate(false) is missing from Nofuss

### ISSUE THREAD

**Issue by arihantdaga** [xoseperez/espurna#1396]
As mentioned in eepromRorate library we need to take precaution with OTAs. I see that its there in ArduinoOta and Terminal OTAs but not in nofuss.
Should we keep that ? I can do a PR..

**Comment by xoseperez** [comment]
Yes, NoFUSS is supported and used so this should be fixed. 
If you want to do the PR go head.

**Comment by xoseperez** [comment]
Merged!
