### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by miscmail23** [xoseperez/espurna#1405]
Hi

I got issue with this error message, can anyone help me? I updated FauxMo library already.

Error message below the line.

----------------------------------------------

C:\Users\X220\Desktop\arduino-1.8.7\CODE\FauxMo_ESP8266_01_bibi\FauxMo_ESP8266_01_bibi.ino: In function 'void geraete()':

FauxMo_ESP8266_01_bibi:256:40: error: no matching function for call to 'fauxmoESP::onSetState(void (&)(unsigned char, const char*, bool))'

   alexawifi.onSetState(callbackSetState);

                                        ^

C:\Users\X220\Desktop\arduino-1.8.7\CODE\FauxMo_ESP8266_01_bibi\FauxMo_ESP8266_01_bibi.ino:256:40: note: candidate is:

In file included from C:\Users\X220\Desktop\arduino-1.8.7\CODE\FauxMo_ESP8266_01_bibi\FauxMo_ESP8266_01_bibi.ino:1:0:

C:\Users\X220\Documents\Arduino\libraries\xoseperez-fauxmoesp-3b05b7b7f111\src/fauxmoESP.h:78:14: note: void fauxmoESP::onSetState(TSetStateCallback)

         void onSetState(TSetStateCallback fn) { _setCallback = fn; }

              ^

C:\Users\X220\Documents\Arduino\libraries\xoseperez-fauxmoesp-3b05b7b7f111\src/fauxmoESP.h:78:14: note:   no known conversion for argument 1 from 'void(unsigned char, const char*, bool)' to 'TSetStateCallback {aka std::function<void(unsigned char, const char*, bool, unsigned char)>}'

FauxMo_ESP8266_01_bibi:257:13: error: 'class fauxmoESP' has no member named 'onGetState'

   alexawifi.onGetState(callbackGetState);

             ^

exit status 1
no matching function for call to 'fauxmoESP::onSetState(void (&)(unsigned char, const char*, bool))'

**Comment by xoseperez** [comment]
First, I think this issue should go to the fauxmoESP library repository, and not here.
Second, it looks like the code you are using is not up-to-date since the fauxmoESP library v3 is not compatible with v2 code.
