### ISSUE TITLE
Feature Request: Transition Time

### ISSUE THREAD

**Issue by wildewuzz** [xoseperez/espurna#1412]
Is it possible to change the transition time between 2 colors from the api or mqtt ?

That would be perfect 👍

**Comment by xoseperez** [comment]
Pushed to `dev` branch. Can you check this?

Via MQTT:
```
mosquitto_pub -t ESPURNA_XXXXXX/transition/set -m 1000
```

Via API (with RESTFUL API disabled):
```
curl "http://192.168.1.20/api/transition?apikey=0123456789ABCDEF&value=500"
```

You can set the transition time to 0 to disable color transitions.

**Comment by wildewuzz** [comment]
that works perfectly ... thx a lot
