### ISSUE TITLE
Relay copies button state

### ISSUE THREAD

**Issue by pilotak** [xoseperez/espurna#1427]
Hi,
is it possible to configure relay to copy button state? ie I press button and as long as i keep it pressing, relay is on and as soon as i release the button, relay goes off?

Thank you

**Comment by ColinShorts** [comment]
You could set the relay to normally off with a setting of, for example, 0.1s. you'll also need to change the settings for what happens for each of the various length of presses. From a quick look you'll find them in buttons.ino, but I think you override then elsewhere. Keep in mind that some devices might have additional functionality for long presses, like adding an RF remote to a button, etc.

**Comment by pilotak** [comment]
ok i will give i try, thank you

**Comment by xoseperez** [comment]
@ColinShorts is right. You can change the actions for each of the button events to match your requirements, either in the `hardware.h` file section for your specific device or in a `custom.h` file.
A starting point (not tested) could be:

```
    #define BUTTON1_MODE            BUTTON_PUSHBUTTON | BUTTON_SET_PULLUP | BUTTON_DEFAULT_HIGH
    #define BUTTON1_PRESS           BUTTON_MODE_ON
    #define BUTTON1_CLICK           BUTTON_MODE_OFF
    #define BUTTON1_DBLCLICK        BUTTON_MODE_NONE
    #define BUTTON1_LNGCLICK        BUTTON_MODE_NONE
    #define BUTTON1_LNGLNGCLICK     BUTTON_MODE_NONE
```

`BUTTON1_CLICK` happens on the release event.

**Comment by ColinShorts** [comment]
Thanks Xose!

I did mention the RF codes, but I should probably give specific examples, i.e. sonoff T1's have this built in with (I believe) no way of overriding it, and I think the sonoff touch switches are the same. I'm not sure if the sonoff RF is also like this, but I suspect it might be.

@pilotak - what devices are you trying this with?

**Comment by pilotak** [comment]
thanks @xoseperez 
@ColinShorts i would like to have it in Sonoff touch T1 2ch

**Comment by ColinShorts** [comment]
It might still work, but I don't think there is a way of disabling the RF functionality in software, so the T1 would still do the RF learn/forget process as per the sonoff manual.

**Comment by pilotak** [comment]
well if i can do it SW i might do HW disabling

**Comment by ColinShorts** [comment]
It looks to be the same chip as the rf bridge, so possibly a case of cutting a trace or two. I don't know if anyone else would have tried this yet?

**Comment by pilotak** [comment]
Here is configuration:
```cpp
#define BUTTON1_MODE        BUTTON_PUSHBUTTON | BUTTON_DEFAULT_HIGH
#define BUTTON1_PRESS       BUTTON_MODE_ON
#define BUTTON1_CLICK       BUTTON_MODE_OFF
#define BUTTON1_DBLCLICK    BUTTON_MODE_OFF
#define BUTTON1_LNGCLICK    BUTTON_MODE_OFF
#define BUTTON1_LNGLNGCLICK BUTTON_MODE_OFF
```

to disable RF you need to desolder R15 (0Ω) near SYN470R chip and to disable buzzer you need to desolder R10 (2kΩ) from power board near buzzer otherwise if you hold the finger down for a long time it beeps.

`LNGLNGCLICK` is bit acquard, you will get an event `BUTTON1_LNGLNGCLICK` even if you have still have finger on the button after 10s. Changing `BUTTON_LNGLNGCLICK_DELAY` doesn't help. @ColinShorts any thoughts?

**Comment by pilotak** [comment]
i changed 10s to 20s in`general.h#287` and after "itself event of releasing" the type was `LNGCLICK` which makes sense cause it was too early for `LNGLNGCLICK`.
When i disable `LNGLNGCLICK event` after "itself event of releasing" relay stays on and there is no event when i put the finger off after that time.

I was just think if this can be because ESP doesn't read the touch chip but the co-processor does and has internal limit?
