### ISSUE TITLE
Reboot if KASA App is startet

### ISSUE THREAD

**Issue by werde45** [xoseperez/espurna#1428]
When i start the KASA App (https://www.tp-link.com/us/kasa-smart/kasa.html) in the same WLAN to setup my Powerswitch, all my espurna devices are offline. Powercycle is needed.

**Comment by mcspr** [comment]
Hey,
See https://github.com/esp8266/Arduino/issues/4720

Sadly, just MDNS_SERVER_SUPPORT=0 does not cut it. mDNS is implicitly enabled when using Core's ArduinoOTA library, and no obvious way to disable it without manually editing it out / not using ArduinoOTA includes and startup code.

Future Core version 2.5.0 provides replacement mDNS library that fixes this.
*(Wonder if it is compatible with the old ones. Have not tested it)*

**Comment by davebuk** [comment]
I think I have just run into this issue. I'm using the KASA app with one of their WiFi cameras. All of my various esp hardware devices (except one), all running espurna reboot when I'm switching the camera OFF/ON from the app. They crash due to Hardware Watchdog.

It's there something I can do or try to stop it happening? Is it the app or the camera causing the issue?

**Comment by mcspr** [comment]
@davebuk We can disable mDNS usage. `-DMDNS_SERVER_SUPPORT=0` will disable our own entries, `-DOTA_ARDUINOOTA_SUPPORT=0` will disable ArduinoOTA discovery.

**Comment by davebuk** [comment]
What size do the .bin files come to with 2.5.2 core? All my devices are 1MB boards. Is this the best fix? I guess I'd have to start using 2 step OTA updates if using the newer core?

**Comment by mcspr** [comment]
platform.io releases build a testing nodemcu-lolin-252 board to track than. Default configuration bumps the size +61KB (62432 B)
```
espurna-1.13.6-dev.nightly20191001+gitbd385f9f-nodemcu-lolin-252.bin
528 KB (540912 B)
espurna-1.13.6-dev.nightly20191001+gitbd385f9f-nodemcu-lolin.bin
467 KB (478480 B)
```

mDNS implementation is the issue, see the referenced discussion at the esp8266/Arduino. Whenever esp8266 receives multicast packets from KASA app it stops working, so another practical solution is to isolate either one on a network level e.g. put them into a different subnets.

**Comment by davebuk** [comment]
I think I'll look to go down the larger core route as I guess that's the way espurna is going. 

The issue I have is with getting the larger firmware installed OTA without having the web interface. After installing a 1MB core .bin, i've tried with the platformio upload command to the device IP but get an authentication error. I think the device has died for some reason as I can't talk to it using serial either. It's a sonoff basic that I had issues with before and has been sat in a cupboard. The espurna firmware that was on it and used to upload the 1MB core .bin was working beforehand though. 

Should the command `platformio run -e itead-sonoff-basic-ota -t upload --upload-port=192.168.1.115` work and not need any authentication? I was using the command `platformio run -e itead-sonoff-basic -t upload --upload-port=192.168.1.115` without the '-ota' would that make a difference?

**Comment by mcspr** [comment]
It could. Why I mentioned mDNS is because it adds up 40KB (yes), so disabling both ArduinoOTA and mDNS announces saves a lot. You can also strip terminal / telnet debug messages on top of that (~12...30KB)

**Comment by davebuk** [comment]
Using the 1MB core and the following build defined, my .bin comes out at 382KB. I was then able to flash a 508KB, 2.5.2 core based normal image. I tend to use a custom build for my devices leaving out parts I do not use like Alexa, thingspeak and home assistant support.

I guess with a basic 382KB build I could then flash up to around 600KB as a second step, or does the file storage on the ESP limit the space to less than 600KB with 382KB already used?

```
#elif defined(ESPURNA_CORE)

    // This is a special device targeted to generate a light-weight binary image
    // meant to be able to do two-step-updates:
    // https://github.com/xoseperez/espurna/wiki/TwoStepUpdates

    // Info
    #define MANUFACTURER            "ESPRESSIF"
    #define DEVICE                  "ESPURNA_CORE"

    // Disable non-core modules
    #define ALEXA_SUPPORT           0
    #define API_SUPPORT             0
    #define BROKER_SUPPORT          0
    #define DOMOTICZ_SUPPORT        0
    #define DEBUG_SERIAL_SUPPORT    0
    #define DEBUG_TELNET_SUPPORT    0
    #define DEBUG_WEB_SUPPORT       0
    #define HOMEASSISTANT_SUPPORT   0
    #define I2C_SUPPORT             0
    #define MQTT_SUPPORT            0
    #define NTP_SUPPORT             0
    #define SCHEDULER_SUPPORT       0
    #define SENSOR_SUPPORT          0
    #define THINGSPEAK_SUPPORT      0
    #define WEB_SUPPORT             1

    // Extra light-weight image
    #define BUTTON_SUPPORT          0
    #define LED_SUPPORT             0
    #define MDNS_SERVER_SUPPORT     0
    #define TELNET_SUPPORT          0
    #define TERMINAL_SUPPORT        0
```

**Comment by davebuk** [comment]
Can I define `platform = ${common.arduino_core_2_5_2}` in the `custom.h` file rather than putting it in the `platformio.ini` file?

**Comment by mcspr** [comment]
Yes, just subtract the available space with the base sketch size + 20KB - 16KB reserved by the SDK and 4KB by settings. Also see the output of `info`, I think it uses the method from Core classes to give the real available space (which knows about reserved space + is rounding the result to a nearest 4KB)

No, platform is a separate thing altogether. `platform = ... ` setting controls which toolchain, Core version and uploader tool it will use to build the app.
But, you can use [`src_build_flags`](https://docs.platformio.org/en/latest/projectconf/section_env_build.html#projectconf-src-build-flags) to add `-Dkey=value` / `-Ddefinetoken` instead of modifying the header.

I think we are getting really off-topic here... but it is probably a useful reference for someone searching for the KASA issue.

**Comment by davebuk** [comment]
Yeah sorry, it was relevant to building with core 2.5.2 for the KASA issue but the OTA is a bit off topic. ;-) I have managed to flash a 528KB .bin after a 2.3.0 core version from the web GUI.

Just to update, all my sonoff basics, SWA1 WiFi switches and Teckin power monitoring switches are stable with the 2.5.2 core and the KASA app. Just need to get my TUYA dimmer updated.
