### ISSUE TITLE
how to contribute device images / avatar smart plug with power meter

### ISSUE THREAD

**Issue by lblabr** [xoseperez/espurna#1434]
i flashed espurna to:

http://www.avatarcontrols.com/index.php?ac=article&at=read&did=181

i would like to share the informations an pictures...

thanks in advance

**Comment by mcspr** [comment]
You can use this issue or prepare it using local markdown editor:
https://help.github.com/articles/adding-and-editing-wiki-pages-locally/

Images are drag-n-drop here in the issues and can be later copied in the wiki repo manually.
