### ISSUE TITLE
Sonoff basic new board

### ISSUE THREAD

**Issue by ralias** [xoseperez/espurna#1444]
There are a new board for the Sonoff Basic Model. In the board we see it labeled with the name of "SONOFF RF R2 POWER v1.0". Here you are pictures about the board. The problem is that I want a basic model to measure temperature in GPIO14 but there isn't free pin. Instead we have a GPIO2 pin prepared for use. I think that the binary espurna-1.13.3-itead-sonoff-basic-dht.bin by default doesn't work in this model. I should to modify the code to replace GPIO14 to GPIO2. Right?

![img_20181221_201834](https://user-images.githubusercontent.com/1614670/50360070-17bff980-055f-11e9-8bb2-9db764129182.jpg)
![img_20181221_201852](https://user-images.githubusercontent.com/1614670/50360072-17bff980-055f-11e9-9af8-b01a0aa63741.jpg)
![img_20181221_201822](https://user-images.githubusercontent.com/1614670/50360074-18589000-055f-11e9-8a99-e5a68b18dfa5.jpg)

**Comment by nelim** [comment]
Yes, just change DHT_PIN before compile, I'm using NodeMCU with DHT on GPIO2 / D4 instead of default GPIO14.

**Comment by Niek** [comment]
@ralias where did you buy this board from? I'd like to order a unit to test

**Comment by ivanmarban** [comment]
@Niek I bought one of this new board from [this](https://www.ebay.es/itm/Sonoff-Basic-Smart-Home-WiFi-Wireless-Switch-Module-For-IOS-Android-APP-Ctrl/323575676326?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2057872.m2749.l2649) seller on eBay.

**Comment by Niek** [comment]
Thanks, I bought one 👍

**Comment by Guillermoto** [comment]
Is there a compiled binary to use gpio2 as before as if it were gpio14?

**Comment by xoseperez** [comment]
Just pushed the configuration to build the images... will be available with 1.13.4 or in the nightly builds.

**Comment by nikopolllx** [comment]
> Quizás esta imagen sea más clara:
> ![img_20181231_142632](https://user-images.githubusercontent.com/1614670/50561157-53e61d80-0d08-11e9-967b-647b816c4eeb.jpg)

hola buenas amigo  dañe el boton de este modulo y ya no puedo ponerlo en modo flash como puedo puentiar el gpo0 para ponerlo a  funcionar de nuevo gracias 
![IMG_0268](https://user-images.githubusercontent.com/41267456/55051848-dab74780-5024-11e9-9448-aafb3d66b73a.JPG)

**Comment by Guillermoto** [comment]
No veo la imagen, pero se puede hacer un puente con un trozo de cable

 

De: nikopolllx [mailto:notifications@github.com] 
Enviado el: miércoles, 27 de marzo de 2019 6:12
Para: xoseperez/espurna <espurna@noreply.github.com>
CC: Guillermo <guillermoto@ono.com>; Comment <comment@noreply.github.com>
Asunto: Re: [xoseperez/espurna] Sonoff basic new board (#1444)

 

Quizás esta imagen sea más clara:
 <https://user-images.githubusercontent.com/1614670/50561157-53e61d80-0d08-11e9-967b-647b816c4eeb.jpg> 

hola buenas amigo dañe el boton de este modulo y ya no puedo ponerlo en modo flash como puedo puentiar el gpo0 para ponerlo a funcionar de nuevo gracias
 <https://user-images.githubusercontent.com/41267456/55051848-dab74780-5024-11e9-9448-aafb3d66b73a.JPG>
