### ISSUE TITLE
Blitzwolf SHP2 or Teckin SP22 Circuit Board Schematics (EU)

### ISSUE THREAD

**Issue by Sp34rmint** [xoseperez/espurna#1446]
Hi,

i am planing to design my own smart plug board which should be compatible with espurna and which is so small that it could be placed in the wall behinde the socket.
So my idea is to use the circuit board schematics form the Blitzwolf SHP2 or the Teckin SP22 because these schematics are compatible with espurna.

My very simple question is, does anyone have these schematics?

**Comment by xoseperez** [comment]
AFAIK those devices are not OSHW so you will probably have to reverse engineer their schematic. Anyway it should not be very different from other similar OSHW devices, like [ESPurna board itself](https://github.com/xoseperez/espurna-board).
