### ISSUE TITLE
Subscribe to multiple MQTT topics

### ISSUE THREAD

**Issue by xoseperez** [xoseperez/espurna#145]
Originally reported by: **Paul C (Bitbucket: [fourfootpaul](https://bitbucket.org/fourfootpaul), GitHub: Unknown)**

----------------------------------------

I'd like to be able to subscribe to a second MQTT topic - specifically a group topic so I can control devices individually by specifying the device name or together with a single command by specifying the group name, would something like this be possible?

For example:
Currently:
The device is only subscribed to "/switch/{deviceName}/"
"/switch/{deviceName}/relay/0 1" turns on relay 0 on this device
"/switch/{deviceName}/relay/0 0" turns off relay 0 on this device

Add the ability to:
Subscribe to a second "group" topic "/switch/AllDevices/"
"/switch/AllDevices/relay 1" would turn on all relays
"/switch/AllDevices/relay 0" would turn off all relays

**Comment by abmantis** [comment]
I was about to create a feature request for group topics, but found this.
I see group topics as being useful to configure multiple devices at once. For example, getting the state from all espurna devices at once by doing something like espurna/cmd/State (where "espurna" is the group topic).
