### ISSUE TITLE
AllJoyn Support

### ISSUE THREAD

**Issue by debarko** [xoseperez/espurna#1453]
**AllJoyn Support on ESP8266.**
*ESPurna supports multiple service discovery protocols like mDNS, LLMNR, NETBIOS and SSDP. Moving forward towards a AllJoyn based service discovery helps create a much needed definition for such services and a more stable discovery protocol. AllJoyn with it's intention for IOT service discovery and Qualcomm backing would really be stable and future proof. This would also help in reducing the number of libraries used for all the above protocols since, AllJoyn support is pretty widespread and all of them are native by nature. So multiple requests like [here](https://github.com/xoseperez/espurna/issues/282) wouldn't be required. *

**Describe the solution you'd like**
*Create an thin AllJoyn client so that it can respond to all the queries for such service discoveries. Something similar to [this](https://github.com/esp8266/Arduino/tree/master/libraries/ESP8266mDNS) would really be helpful*

**Additional context**
[AllJoyn](https://en.wikipedia.org/wiki/AllJoyn)

**Comment by debarko** [comment]
Seems like alljoyn developers dropped the ball and nothing is moving on their repos. Windows 10 IOT has dropped their support. In fact currently their website's SSL certificate is also expiring. Now I am not sure as to whether this support is needed or not.

But this protocol is really good.

**Comment by xoseperez** [comment]
There has been no real activity for more than a year. It doesn't either look "simple" to implement. I don't think this is worth it.

**Comment by mcspr** [comment]
Little sidenote:
AllJoyn is merged with IoTivity project, but HW page suggest the most support is given for much faster platforms than ESP8266 https://wiki.iotivity.org/hardware
WIP support (arduino core based as it seems?) for esp was suggested, but no movement there: https://gerrit.iotivity.org/gerrit/#/c/13315/
One can go around implementing protocol without their's SDK, but not that is not as "simple" as with it.
