### ISSUE TITLE
Any IOS app form manage the devices?

### ISSUE THREAD

**Issue by seritos** [xoseperez/espurna#1464]
Good Morning, 

Is there any IOS app compatible with ESPurna? I know that for Tasmota is possible to use "YETI", but I haven't found anyone for the rest. 

Thanx a lot

**Comment by Misiu** [comment]
@seritos ESPurna has a nice web interface that can be accessed by IOS, Android or any device via web browser.
What particular feature are You looking for?

**Comment by xoseperez** [comment]
No, there are no native apps support for ESPurna atm.
