### ISSUE TITLE
Alexa no encuentra sonoff basic con espurna 1.13.2

### ISSUE THREAD

**Issue by Guillermoto** [xoseperez/espurna#1466]
He instalado la versión 1.13.2 de espurna a un sonoff basic y he activado la integración con alexa pero no no lo encuentra, tengo un echo dot gen 2 y un echo gen3.
Todo lo demás esta funcionando, MQTT ok y Domoticz ok

**Comment by xoseperez** [comment]
Prueba con la versión en `dev`, debería reconocer los dispositivos como Hue Light Bulbs.
