### ISSUE TITLE
renaming switch names

### ISSUE THREAD

**Issue by Chrisogea** [xoseperez/espurna#1476]
*Before creating a new feature request please check that you have searched the existing [issues](https://github.com/xoseperez/espurna/issues) (both open and closed)*

*Fulfilling this template will help developers and contributors evaluating the feature. If the information provided is not enough the issue will likely be closed.*

*You can now remove this line and the above ones. Text in italic is meant to be replaced by your own words. If any of the sections below are not relevant to the request then you can delete them.*

**Is your feature request related to a problem? Please describe.**
*A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]*

**Describe the solution you'd like**
*A clear and concise description of what you want to happen.*

**Describe alternatives you've considered**
*A clear and concise description of any alternative solutions or features you've considered.*

**Additional context**
*Add any other context or screenshots about the feature request here.*

**Comment by xoseperez** [comment]
See #714, #758 and #1354. It's scheduled for 1.14.0
