### ISSUE TITLE
Counter sensor freeze

### ISSUE THREAD

**Issue by pkedvessy** [xoseperez/espurna#1483]
Hi,

Using counter sensor gets freeze my SONOFF Dual R2 device after a while when sending singlan frequently to the board. Seems like the variable to measure ticks is overflowing or something like that.

I'm on the master branch, environment is itead-sonoff-dual-r2-ota and additional build flags are the followings:
`-DEVENTS_SUPPORT=1 -DEVENTS_PIN=3 -DEVENTS_PIN_MODE=INPUT -DEVENTS_INTERRUPT_MODE=RISING`

Without having any sensor connected to the board I don't experience any issue.

**Comment by pkedvessy** [comment]
Debug is turned off by default for Sonoff Dual R2 by default. Isn't is?

**Comment by mcspr** [comment]
Nope. See
https://github.com/xoseperez/espurna/blob/9dbd14e38892ee2d0c901406e65050a462b5f855/code/espurna/config/hardware.h#L487-L512

**Comment by pkedvessy** [comment]
Ok, I had a try with the suggested build flag, but the result is the same.

**Comment by mcspr** [comment]
...which is? does it reboot or stops responding? "count" reported will reset each report, this is expected

you can also try setting `EVENTS_TRIGGER=0` to avoid reporting individual events

**Comment by pkedvessy** [comment]
Which is `-DDEBUG_SERIAL_SUPPORT=0`
It stops responding and WIFI status led stops blinkink.

**Comment by xoseperez** [comment]
Do you have the chance to monitor the debug log to see what happens?
