### ISSUE TITLE
Magichome 20 Binary

### ISSUE THREAD

**Issue by chr2002qw** [xoseperez/espurna#1488]
Hello,

i flashed a Wemos D1 Mini with the Magichome 2.0 prebuilt binary, brutforced the R G B Gpio Pins and got my LED Strip working with OpenHab2.

Now i want to use the Switch feature (GPIO0) i connected a switch to this GPIO Pin, setup MQTT but nothing happens. Theres no output about a pressed button in the Debug screen in the Espurna Web interface.
If i connect the switch to GPIO2, the onbord Led of my Wemos lits up upon pressing the button until i release it again.

Why theres no info about the button event in the debug screen ? What iam doing wrong ?
I tested it with high and low signals.

**Comment by ColinShorts** [comment]
Could you try using another gpio pin instead of 0/2?

**Comment by chr2002qw** [comment]
I just tested every GPIO with high 3,3V and Low GND without sucess. Theres no info about a button event in the Debug screen.
