### ISSUE TITLE
Smartplug Blitzwolf BW-SHP4/UK-BW-SHP4, is it the same as BLITZWOLF BW-SHP2

### ISSUE THREAD

**Issue by loglux** [xoseperez/espurna#1492]
I'm worried about BlitzWolf Smart Plug UK version. Is it the same as SHP2?

https://www.amazon.co.uk/BlitzWolf-Compatible-Monitoring-Function-Anywhere/dp/B07GJ26TCQ/ref=sr_1_1?s=diy&ie=UTF8&qid=1547590335&sr=1-1&keywords=blitzwolf

**Comment by mcspr** [comment]
Looks like it. Source:
https://github.com/arendst/Sonoff-Tasmota/wiki/BlitzWolf-BW-SHP4-(UK-Version) 
https://github.com/arendst/Sonoff-Tasmota/issues/4398

ref: #1429 , this hardware might as well be called blitzwolf shp246

**Comment by xoseperez** [comment]
With 1.13.4 this is called `BLITZWOLF_SHPX`.
