### ISSUE TITLE
Sonoff LED: Set ColorTemperature and Brightness over MQTT

### ISSUE THREAD

**Issue by jbaumann** [xoseperez/espurna#1501]
Sonoff LED contains a warm and cold white led strip which can currently be controlled independently via MQTT. It would be nice to have an integrated control method that allows to change brightness (works already using the web interface) and the color temperature instead of fiddling with the different channels.

**Comment by copyrights** [comment]
This would be useful for QuinLED boards, too.

**Comment by copyrights** [comment]
I just had a look. while brightness is already partially working (see #1292), color temperature will be a larger change. Current implementation uses RGB leds. While we use two types of white leds. Mine are warm white (approx. 2700-3000 °K) and cold white (approx. 6000 °K).
