### ISSUE TITLE
Arduino IDE / ino into subfolder

### ISSUE THREAD

**Issue by lblabr** [xoseperez/espurna#1507]
i tried to follow [https://github.com/xoseperez/espurna/issues/764](url) for using plugins.

it does not work with arduino ide. ino-files from subfolders are not used for compilation. or do i something wrong ?

1)
espurna / libs / mylib

2)
espurna
lib/ mylib

how do io have to handle subfolders in arduino ide ?

thanks in advance

Lars

**Comment by rafael-sanz** [comment]
Hi, I just landing at same problem. The embebed instruction not work for me too.

In my custom.h file placed in /config  I've replaced:
 #include <pluging.h> ==>  #include "../libs/plugin1.h"

And the plugin1.ino must be together the all *.ino files (spurna main folder).

Regards

**Comment by mcspr** [comment]
This comment suggests that `src/*` would be searched for the source files, but only .cpp
https://github.com/arduino/arduino-builder/issues/89#issuecomment-215333954
And I think that .cpp in the same dir as .ino should do the exact same thing, compiling separately (because .c files do)

Another option is to put all the relevant code into a library e.g. `#include <MyLibrary.h>` to have the code separately, so it will be properly included in the build process by the IDE

**Comment by lblabr** [comment]
sketch\src\mcp4725\mcp4725.cpp.o: In function `extraSetup()':

sketch\src\mcp4725\../../config/custom.h:161: multiple definition of `extraSetup()'

sketch\espurna.ino.cpp.o:sketch\config/custom.h:161: first defined here

sketch\src\mcp4725\mcp4725.cpp.o:(.bss.EEPROMr+0x0): multiple definition of `EEPROMr'

sketch\espurna.ino.cpp.o:C:\Users\Lars Bretschneider\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.4.1\cores\esp8266/Stream.h:91: first defined here

sketch\src\mcp4725\mcp4725.cpp.o:(.text._ZZ19_pluginInitCommandsvENUlP7EmbedisE_4_FUNES0_+0x28): undefined reference to `bool setSetting<bool>(String const&, bool)'

sketch\src\mcp4725\mcp4725.cpp.o: In function `_pluginInitCommands()::{lambda(Embedis*)#1}::_FUN(Embedis*)':

mcp4725.cpp:(.text._ZZ19_pluginInitCommandsvENUlP7EmbedisE_4_FUNES0_+0x97): undefined reference to `bool setSetting<bool>(String const&, bool)'

collect2.exe: error: ld returned 1 exit status

**Comment by lblabr** [comment]
sketch\src\mcp4725\mcp4725.cpp.o:(.bss.EEPROMr+0x0): multiple definition of `EEPROMr'

sketch\espurna.ino.cpp.o:\ArduinoData\packages\esp8266\hardware\esp8266\2.4.1\cores\esp8266/Stream.h:91: first defined here

collect2.exe: error: ld returned 1 exit status

exit status 1


how do i avoid this ??

thanks in advance

Lars

**Comment by mcspr** [comment]
> sketch\src\mcp4725../../config/custom.h:161: multiple definition of `extraSetup()'

both src/mcp4725.cpp (or something it includes) and espurna code have `void extraSetup() {}`, so it cannot decide which to pick.

*.ino can have espurna functions / objects like getSetting, setSetting etc.
src/*.cpp should be treated as separate library e.g you should probably do src/mylib/*.cpp. no espurna things should be here, only your code
