### ISSUE TITLE
Platform.io. one task for each device?

### ISSUE THREAD

**Issue by oscarsan1** [xoseperez/espurna#1515]

**Comment by oscarsan1** [comment]
I do OTA download with platform.io folow the instructions in the wiki. Finaly my task.json is:

    "version": "2.0.0",
    "tasks": [
        {
            "type": "PlatformIO",
            "label": "Upload Arbol",
            "task": "Upload (itead-sonoff-basic-ota)",
            "options": {
                "env": {
                    "ESPURNA_IP": "192.168.1.200",
                    "ESPURNA_AUTH": "-----"
                },
            },
            "problemMatcher": [
                "$platformio"
            ]
        }
    ]
can I define more tasks, one for each device sonoff basic I have, with diferents  IP each device but the same task "Upload (itead-sonoff-basic-ota)"?

**Comment by mcspr** [comment]
*note: not a heavy vscode user*

I did try adding multiple tasks referencing `task: upload (...)` but it just lists the last one 🤷‍♂️ 
Possible solution: use `type: shell` and manually type out required `platformio command`, check out [tasks.json docs](https://code.visualstudio.com/docs/editor/tasks)
e.g. new task should have `"type": "shell", "command": "platformio run -e itead-sonoff-basic-ota -t upload"`

**Comment by oscarsan1** [comment]
That's works.  Thank you. 
I do in task.jsom:

        {
            "label": "PlatformIO: Arbol1",
            "type": "shell",
            "command": "platformio run -e itead-sonoff-basic-ota -t upload",
            "options": {
                "env": {
                    "ESPURNA_IP": "192.168.1.200",
                    "ESPURNA_AUTH": "---"
                },
            },
            "problemMatcher": [
                "$platformio"
            ],
        },
        {
            "label": "PlatformIO: Light1",
            "type": "shell",
            "command": "platformio run -e itead-sonoff-basic-ota -t upload",
            "options": {
                "env": {
                    "ESPURNA_IP": "192.168.1.201",
                    "ESPURNA_AUTH": "---"
                },
            },
            "problemMatcher": [
                "$platformio"
            ],
        }

With this I can execute each task "Arbol1" and "Ligth1" for OTA download code to each device.
