### ISSUE TITLE
Enhanced TimeZone support

### ISSUE THREAD

**Issue by drc38** [xoseperez/espurna#1517]
Would it be possible to incorporate the following library or similar to increase timezone support, or have a flag in current DST for the Southern hemisphere?
https://github.com/JChristensen/Timezone
Thanks

**Comment by mcspr** [comment]
See #1295 and #1380 , proposing timezone via TZ=... variable syntax. 2 problems though: how to tell the user about them and how to avoid unreasonably increasing binary size when you only need only one timezone

**Comment by mcspr** [comment]
Closing via #2132
