### ISSUE TITLE
ESP-01 + 2CH 5V RELAY LC EXCLUSIVE RELAY ON

### ISSUE THREAD

**Issue by clabnet** [xoseperez/espurna#1519]
**Bug description**
*When using the switches configuration "Zero or one switches active" the serial init are not full recognized by this relay board. The result is two relays on ON status.*

![5v-esp8266-esp-01-2-channel-wifi-relay](https://user-images.githubusercontent.com/6067610/52163355-1860b980-26e1-11e9-9595-505234b88d74.png)

**Steps to reproduce**
*I have [this ](https://www.aliexpress.com/item/5V-ESP8266-ESP-01-2-Channel-WiFi-Relay-Module-2-Channel-Relay-Module-For-IOT-Smart/32843798205.html)relay module 5V-ESP8266-ESP-01-2-Channel-WiFi with RELAY_PROVIDER == RELAY_PROVIDER_STM.
	When trying to ON the relays clicking Switch#0 ON, and then Switch#1 ON, and viceversa, there are many cases with two relay ON status.*

**Expected behavior**
*Step to reproduce :
	Switch 0 : OFF
	Switch 1 : OFF
	When I click Switch#0 ON, and then Switch#1 ON, I need FIRST the relay 0 to OFF, and THEN relay 1 to ON, and viceversa.*

**Screenshots**

**Device information**
*Manufacturer STM_RELAY*
*Device 2CH*
*Chip ID 3EE5E3*
*SDK version 1.5.3(aec24ac9)*
*Core version 2.3.0*
*Firmware name ESPURNA*
*Firmware version 1.13.4-dev*

**Tools used**
* *WIN 10*
* *FF 64.0 *
* *IDE & version*

* *Platform IO*

**Comment by mcspr** [comment]
Closing via #1520
