### ISSUE TITLE
Shield DHT22 con ESp8266 - ESP01

### ISSUE THREAD

**Issue by pablopescador** [xoseperez/espurna#1522]
Hola que tal, 
Quisiera saber si es que puedo usar su Firmware para el siguiente Shield
![dsc_1902](https://user-images.githubusercontent.com/34184065/52228684-44cc2f80-28b3-11e9-9cda-4783a9b000a2.JPG)

Estoy sufriendo con el platformio.ini 
para declarar algo asi por ejemplo? env_default = generic-esp01s-dht22-22
y el en sensor.h

#ifndef DHT_SUPPORT
#define DHT_SUPPORT                     1
#endif

#ifndef DHT_PIN
#define DHT_PIN                         2
#endif

#ifndef DHT_TYPE
#define DHT_TYPE                        DHT_CHIP_DHT22
#endif

lo he puesto asi. 
pero cuando "build" me sale error.
Si uso el el nombre aceptado por defecto en platformio.ini
como env_default = generic-esp01s-dht11-11
va todo bien, pero no lee el sensor y me sale esto
![image](https://user-images.githubusercontent.com/34184065/52229052-37637500-28b4-11e9-9ffc-3811390ea1f4.png)

Muchas gracias por compartir @xoseperez.
Un saludo desde Alemania.

**Comment by xoseperez** [comment]
Es un DHT22, no un DHT11, la imagen que has utilizado es para el DHT11.
Deberás compilarlo tal como has definido arriba, qué error te da?

**Comment by pablopescador** [comment]
Hola Xose, muchas gracias por tu tiempo. Ya lo podido compilar. Va de lujo tu firmware. Ahora estoy peleando con mqtt broker en un 8266 a ver que sale ;) ...

**Comment by gregoriohc** [comment]
Hola @pablopescador. ¿Tienes de casualidad por ahí el bin para el DHT22? Me ahorrarías el trabajo de tener que instalar todo lo necesario para compilarlo yo y te estaría eternamente agradecido, jeje.
Mil gracias y también a @xoseperez por el gran trabajo en su firmware!

**Comment by pablopescador** [comment]
Hola Gregorio,
Lo siento pero lo logre hacer funcionar y lo borre :(
Saludos.

**Comment by gregoriohc** [comment]
Gracias @pablopescador. Me pondré a ello entonces :-)
