### ISSUE TITLE
I'm tired of everything being Arduino-Specific...

### ISSUE THREAD

**Issue by e-music** [xoseperez/espurna#1525]
This is an awesome project and exactly what I've been looking for, yet it also targets Arduino, which is not my preferred platform. I was wondering if there's any quick way to get started on an STM32F4 and ESP8266 module. I have a project designed around the STM32F407 and I need to add connectivity by adopting the ESP8266 module. The only feature needed is to be able to upgrade the firmware (for the STM32 not the ESP itself) over internet. Of course, a web interface is needed to configure AP credentials initially by customers. Espurna seems to do the job, and way more, but not sure where to get started as this is not intended for Arduino.

By the way, what are those different BIN releases used for?

**Comment by xoseperez** [comment]
I know what you mean but I think you missed the point. This project is not meant to be used on an "arduino" uC (whatever that is: avr, samd,..) but to be flashed directly on an ESP8266, so no need to have a second uC like a atmega328 or a stm32. ESPurna uses a "port" of the Arduino framework for the ESP8266 platform. So this is not what you are looking for.

The bins are targeted to different devices since we still do not support hardware configuration on the fly.

**Comment by e-music** [comment]
Thank you, and I guess I just started to get the hang of it. Since most of these custom firmwares are designed to be flashed directly to an ESP8266 board, then I believe the ESP8266 itself is the target MCU for that firmware. So far, I have tested several firmwares and I guess that's what I want to do myself, but with only a fraction of the functionality implemented. 

Anyways, if I remember well, last time I flashed my ESP8266 with one of the BIN releases, but the device doesn't boot into AP mode and I do not see it among available wifi networks. It would be very nice if you can suggest a BIN to flash and experiment with. 

And by the way, I have followed your advice and already downloaded PlatformIO as an extension to VSCode. This is a great tool that makes developer's life much easier, so thank you again for your great advice.

**Comment by ColinShorts** [comment]
There are a few "generic" devices, you might want to start with one of those, but double check the flash size of the device you are using.

I don't see any mention of what you are looking to achieve, but there is plenty of support for sensors, lights, and relays.
Take some time to read through the wiki before you jump in.
