### ISSUE TITLE
DS18B10 ROM

### ISSUE THREAD

**Issue by scargill** [xoseperez/espurna#1531]
I have installed a DS19B20 on GPIO2 on a new Sonoff Basic R2 (the one with 2 thick mains wires and only 4 pins - and a pad for GPIO2) (GPIO14 no longer easily available). I upgraded Espurna to the correct ROM - but checking all mqttmessages periodically goping to MQTT I'm seeing nothing about temperature? Any pointers? 

espurna-1.13.2-itead-sonoff-basic.bin

**Comment by xoseperez** [comment]
The proper image would be espurna-X.XX.X-itead-sonoff-basic-dallas.bin, but anyway that image assumes the Dallas sensor is on GPIO14, so it would not work either. For the time being, you will have to build it youself by enabling Dallas support (DALLAS_SUPPORT=1 in `arduino.h`) and setting the proper GPIO (DALLAS_PIN=2 in `sensors.h`).
