### ISSUE TITLE
BLITZWOLF BWSHP2 V23 & V24

### ISSUE THREAD

**Issue by AlbertWeterings** [xoseperez/espurna#1532]
BLITZWOLF_BWSHP2_V23 is already supported in hardware.h but a line to enable it in arduino.h is missing.
BLITZWOLF_BWSHP2_V23 setup is also working for V24 board.

//#define BLITZWOLF_BWSHP2_V23

**Comment by xoseperez** [comment]
But maybe it should be changed to BLITZWOLF_BWSHP2_V2X

**Comment by AlbertWeterings** [comment]
Might be but it is not sure it will also work for 2.1, 2.2 and possible revisions 2.5 and higher so not sure this good to do.

**Comment by xoseperez** [comment]
True, anyway this naming convention is a problem.

**Comment by AlbertWeterings** [comment]
I agree, also tried to figure out a different way as  I think in the future we are going to see more and more hardware with different revisions. So maybe breaking up the naming like ((general devicename)(revision)) is an option and then a structure with sub parts in hardware.h is an option.
