### ISSUE TITLE
Ports 80 and 23 filtered

### ISSUE THREAD

**Issue by CarrilloKH** [xoseperez/espurna#1548]
Hello,

After using its software in a ZLD-EU44-W and turning the power on / off through HTTP, suddenly the following problem has arisen: ports 23 and 80 appear as filtered. Any idea what it could be?

![captura de pantalla de 2019-02-13 11-24-58](https://user-images.githubusercontent.com/47594718/52704982-1b319900-2f82-11e9-8e0b-8926f9709a4c.png)

**Comment by CarrilloKH** [comment]
Update: This is the info of crash after reboot it manually
![captura de pantalla de 2019-02-13 11-38-05](https://user-images.githubusercontent.com/47594718/52705712-e292bf00-2f83-11e9-8eb9-57efe94fbf74.png)

**Comment by mcspr** [comment]
What version of ESPurna do you use?

**Comment by CarrilloKH** [comment]
I was using version 1.13.1. Update it to the latest versionntwo days ago. It seems that there was the problem.

In any case, I will continue testing the power strip during the weekend and report the results. Thanks for the help!

**Comment by mcspr** [comment]
Any luck reproducing this with latest version?

**Comment by CarrilloKH** [comment]
Sorry for the delay in answer, I've been busy. With 1.31.4 version with I have left the power strip continuously for 2 full days and the problem has not been repeated. Everything solved seems. Thanks you for the help.

**Comment by mcspr** [comment]
Nice. Closing.
