### ISSUE TITLE
Generic Relay v4.0 invert relay option 

### ISSUE THREAD

**Issue by virgil-av** [xoseperez/espurna#1554]
Hi,

On the market there are 2 versions of this relay, a normal version and an inverted version.
ESPurna works very nice with the normal version, but the inverted version is well inverted, web admin says off but relay is actually on and vice versa.
You can read about it here: https://github.com/xoseperez/espurna/issues/1504

Feature request:
In Switch / relay configuration tab please add an option to chose from normal and inverted.

Thank you.

**Comment by xoseperez** [comment]
The feature you request is a work in progress (see branch `v2`). Next release will include binaries for both types.
