### ISSUE TITLE
Use SDcard for settings

### ISSUE THREAD

**Issue by akadlec** [xoseperez/espurna#1556]
Is there some easy way how to use sd card for storing settings instead of flash memory? I am building small gateway on top of the espurna and i am going to store a lot of configs.

**Comment by xoseperez** [comment]
No support for SD for the moment, but doable, of course. Have you tried/thought about using SPIFFS? It's already available and there is plenty of space if you are using a 4MB module...

**Comment by akadlec** [comment]
on, spiffs sounds ok
