### ISSUE TITLE
Multiple Event Sensors not working

### ISSUE THREAD

**Issue by DougTheHandyman** [xoseperez/espurna#1557]
I have defined multiple Event Sensors, following the method illustrated in sensor.ino for replicating a DHT Sensor. What I'm seeing in the startup log and on the web interface, is that the sensors get defined. However, only the last one defined actually works. This was on Arduino core 2.4.2 and Espurna 1.13.3

Raised this on gitter and @mcspr identified probable bug in that the definition 
"static unsigned char _interrupt_gpio = GPIO_NONE;" at line 148 in EventSensor.h 
will be common to all defined  Event Sensors and suggested moving that definition further down the code to be in wider scope.

that worked for me

**Comment by mcspr** [comment]
Note that was merely a suggestion of minimal-viable-fix :)

Looking at the [Core code](https://github.com/esp8266/Arduino/blob/044568c220ae3a0ad6f151611ba834f9b3e1402e/cores/esp8266/core_esp8266_wiring_digital.cpp#L173), I think there is no need to track GPIO at all. Interrupt handler can only reference one function, it will use the last one attached. Need to check with live board though, if it does something bad instead.
