### ISSUE TITLE
mqtt unable to connect causes reboot

### ISSUE THREAD

**Issue by wired-dev** [xoseperez/espurna#1560]
on the latest dev branch; I'm having issues with the bulb reseting if mqtt is enabled and the bulb is unable to connect. once I disabled it it became stable.

**Comment by mcspr** [comment]
@wired-dev with mqtt server set to non-existent address i could reporoduce this on current dev
can you verify fix in #1563?

**Comment by wired-dev** [comment]
I applies the patch; and it does appear to resolve the issue.

**Comment by 0anton** [comment]
Could it be also related to my case: all my sonoff switches start flapping if the wifi is not available. Switches have also MQTT configured and obviously the MQTT server address becomes invalid as soon as the network disappears. Badly, once the router is itself on the sonoff switch, switch flapping never allow the router to boot and switch never find the network again...

How can I apply the fix to my switches?

**Comment by wired-dev** [comment]
yes 0anton; I do think this is your issue. need to build it from source and apply the mod the your mqtt.ino file

**Comment by 0anton** [comment]
May be Max @mcspr can integrate the fix into dev code line since wired-dev has already tested and confirmed the fix is working? I don't have dev environment unfortunately for ESPxxx to provide the second test. Already running switches on latest 1.13.3 build.

**Comment by 0anton** [comment]
Hi Xose @xoseperez, thank you for merging Max patch! That was fast! Do you have an automatic build of the dev codeline somewhere? I could test it, if I get the image.

**Comment by mcspr** [comment]
@0anton see https://github.com/mcspr/espurna-nightly-builder/releases , it should build another one in about ~7 hours from now.

**Comment by 0anton** [comment]
Thank you, @mcspr Max! I uploaded dev build to 3 sonoff POW switches and looking for their behavior.
