### ISSUE TITLE
SonOff Pow R2 does not connect

### ISSUE THREAD

**Issue by decibelio99** [xoseperez/espurna#1577]
Hi there,
First of all, I'd like to thank your work, I have all my electrical gadgets connect with your firmware. Even, I have made a dry contact with a Sonoff basic that works perfectly.
Well, all less one, a sonoff Pow r2; every time I upload the firm, it works fine, but when I reboot for a second time, the pow becomes a brick. I have waitted for more than 3 minutes and I have tried with the 3 last releases of Espurna.
PS. The pow r2 works fine with Trasmota firm, but I prefer to use Espurna.
Thanks in advance

**Comment by dreamfalcon** [comment]
Version 1.13.4?
If yes check this issue #1574

**Comment by decibelio99** [comment]
I have the same problem with all versions, 1.13.2, 1.13.3 and 1.13.4

**Comment by xoseperez** [comment]
Same problem since 1.13.2? Does it default to AP mode or do you have to flash it again?

**Comment by decibelio99** [comment]
I've tried the three versions, but after setting up it, it didn't make anything, so I had to flash it to tasmota :(

**Comment by xoseperez** [comment]
I have a POW R2 at home monitoring the washer machine and it works great... recovered fine after power cuts. I'm sorry I can't help without further info. If you ever give ESPurna a chance again please reopen if it keeps on failing.
