### ISSUE TITLE
SonOff pow R2 - Unable to compile 1.13.4

### ISSUE THREAD

**Issue by AlbertWeterings** [xoseperez/espurna#1579]
When compiling for SonOff POW R2 I get this error:
`sensor:106: error: 'T' has not been declared

 void _sensorWebSocketMagnitudes(JsonObject& root, T prefix) {

                                                   ^

exit status 1
'T' has not been declared`

**Comment by xoseperez** [comment]
It compiles fine for me, both on PlatformIO and Arduino IDE 1.8.6 under Linux.
Notice `T` is a templated variable defined just one line before... maybe your IDE/OS is not getting that, try removing the line break:

```
template<typename T> void _sensorWebSocketMagnitudes(JsonObject& root, T prefix) {
```

**Comment by AlbertWeterings** [comment]
removing the line break is fixing the issue in Windows Arduino IDE.

**Comment by mcspr** [comment]
@AlbertWeterings do you have git with autocrlf=true? may be related to https://github.com/xoseperez/espurna/issues/1205

.gitattributes to the rescue, `*.ino text eol=lf` && `*.h text eol=lf` should override autocrlf settings for users. but i need to check how it will behave with *.gz.h beforehand

**Comment by AlbertWeterings** [comment]
I don't use git, i just download the repository as zip and open it Arduino IDE on Windows.

**Comment by mcspr** [comment]
That's strange. I can build it using Arduino IDE 1.8.8, from Windows Store.
I tried downloading espurna-dev.zip but it does not convert line endings for Windows crfl, so not that either. Hm.

**Comment by AlbertWeterings** [comment]
I'm at Arduino IDE 1.8.5, for Windows there might be the difference
