### ISSUE TITLE
Can't connect to AP mode

### ISSUE THREAD

**Issue by clabnet** [xoseperez/espurna#1587]
Hi,
I can't connect to AP mode after a successfully flashing a SONOFF BASIC.

I cloned your latest dev branch (AND latest tag 1.13.4, same issue), on WIN 10, and uploaded  using Platform.IO. The led is blinking. Pressing the button I can see the events on terminal window. 
The wi-fi on my machine running fine. Selecting the AP ESPURNA-xxxx, I can insert the password "fibonacci", waiting,  but I can't connect to this network.

First I have erased the original SONOFF firmware:

> C:\ESP8266\nodemcu-pyflasher>esptool.py --port COM3 erase_flash
> esptool.py v2.2.1
> Connecting....
> Detecting chip type... ESP8266
> Chip is ESP8266EX
> Uploading stub...
> Running stub...
> Stub running...
> Erasing flash (this may take a while)...
> Chip erase completed successfully in 0.0s
> Hard resetting...
> 

Then I sended the commands FACTORY.RESET and ERASE.CONFIG through terminal.
This is the log.  Any help ?

> [001029] [MAIN] ESPURNA 1.13.4
> [001029] [MAIN] xose.perez@gmail.com
> [001029] [MAIN] http://tinkerman.cat
> [001029] [MAIN] CPU chip ID: 0x0E0B1F
> [001032] [MAIN] CPU frequency: 80 MHz
> [001036] [MAIN] SDK version: 1.5.3(aec24ac9)
> [001040] [MAIN] Core version: 2.3.0
> [001043] [MAIN] Core revision: 159542381
> [001046]
> [001047] [MAIN] Flash chip ID: 0x146085
> [001051] [MAIN] Flash speed: 40000000 Hz
> [001054] [MAIN] Flash mode: DOUT
> [001057]
> [001058] [MAIN] Flash size (CHIP)   :  1048576 bytes /  256 sectors (   0 to  255)
> [001065] [MAIN] Flash size (SDK)    :  1048576 bytes /  256 sectors (   0 to  255)
> [001072] [MAIN] Reserved            :     4096 bytes /    1 sectors (   0 to    0)
> [001080] [MAIN] Firmware size       :   473968 bytes /  116 sectors (   1 to  116)
> [001087] [MAIN] Max OTA size        :   548864 bytes /  134 sectors ( 117 to  250)
> [001094] [MAIN] EEPROM size         :     4096 bytes /    1 sectors ( 251 to  251)
> [001101] [MAIN] Reserved            :    16384 bytes /    4 sectors ( 252 to  255)
> [001108]
> [001110] [MAIN] EEPROM sectors: 251, 250
> [001113] [MAIN] EEPROM current: 250
> [001116]
> [001117] [MAIN] EEPROM:  4096 bytes initially |    72 bytes used ( 1%) |  4024 bytes free (98%)
> [001126] [MAIN] Heap  : 35144 bytes initially |  5328 bytes used (15%) | 29816 bytes free (84%)
> [001134] [MAIN] Stack :  4096 bytes initially |   768 bytes used (18%) |  3328 bytes free (81%)
> [001142]
> [001143] [MAIN] Boot version: 31
> [001145] [MAIN] Boot mode: 1
> [001148] [MAIN] Last reset reason: Reboot from terminal
> [001153]
> [001154] [MAIN] Board: ITEAD_SONOFF_BASIC
> [001158] [MAIN] Support: ALEXA API BROKER BUTTON DEBUG_SERIAL DEBUG_TELNET DEBUG_WEB DOMOTICZ HOMEASSISTANT LED MDNS_SERVER MQTT NTP SCHEDULER TELNET TERMINAL THINGSPEAK WEB
> [001173] [MAIN] WebUI image: SMALL
> [001176]
> [001391] [MAIN] Firmware MD5: c856eafebb429ae841d840ab30d4805c
> [001392] [MAIN] Power: 3066 mV
> [001392]
> [001397] [TELNET] Listening on port 23
> [001399] [WEBSERVER] Webserver running on port 80
> [001401] [RELAY] Retrieving mask: 255
> [001402] [RELAY] Relay #0 boot mode 0
> [001405] [RELAY] #0 set to OFF
> [001408] [RELAY] Number of relays: 1
> [001411] [BUTTON] Number of buttons: 2
> [001414] [LED] Number of leds: 1
> [001417] [MQTT] Async ENABLED, SSL DISABLED, Autoconnect ENABLED
> [001428] [THINGSPEAK] Async ENABLED, SSL DISABLED
> [001672] [WIFI] Creating access point
> [002736] [WIFI] Captive portal enabled
> [002737] [RELAY] Setting relay mask: 0
> [002738] [WIFI] -------------------------------------- MODE AP
> [002738] [WIFI] SSID  ESPURNA-0E0B1F
> [002741] [WIFI] PASS  fibonacci
> [002743] [WIFI] IP    192.168.4.1
> [002746] [WIFI] MAC   xxxxxxxxxxxxxxxxxxxxx
> [002750] [WIFI] ----------------------------------------------
> [002756] [MDNS] OK
> [060001] [MAIN] System OK
> 

Thank's
Claudio

**Comment by xoseperez** [comment]
See #1574. We are about to release a version to fix that.
