### ISSUE TITLE
Dallas 18D20 not working in parasite power mode

### ISSUE THREAD

**Issue by einnordlicht** [xoseperez/espurna#1605]
Hi, I had a set of temperature sensor chains (upto 8 Dallas 18D20) running on a NodeMCU with self written shield and later with Tasmota, However when I changed firmware to ESPURNA (1.13.4) I only get temperatures on the dallas of  85 or the sensors are not detected). I setup a breadboard for tests and in no case (VCC 5V or 3.3 with 5.6k on data) i ever succeeded to get data. As soon as I not pull Vcc to GRD anymore (needed for parasite mode) all sensors (3 tested so far) are detected and data is shipped.

Can it be that parasite mode is not supported by Espurna?

**Comment by AlbertWeterings** [comment]
I have tested a lot with these DS18D20 sensors on ESPURNA and know these sensors can be a pain in the ass. What I in your case would try is have a look at the file DallasSensor.h in the sensor folder. At line 22 you see: #define DS_PARASITE                 1 try to change it to 0. I would not be surprised if it helps but unfortunately can't confirm it will.
