### ISSUE TITLE
NTP error on version 1.13.5

### ISSUE THREAD

**Issue by jorgebnunes** [xoseperez/espurna#1608]
Hi Xosé.

**I have this bug after upgrade to the last version 1.13.5 - [NTP] Error: NTP server not reachable**
After upgrade, this error shows up and on itead S20 never works again.

Thank you!

**Comment by icevoodoo** [comment]
I have this issue also on my Sonoff-TH. To bypass this, I have configured a time server on my RPI3 and use it with my device to synchronize the clock.
I don't know if this help, but for me is working till this will be fixed in the future...
