### ISSUE TITLE
MQTT groups become out of sync

### ISSUE THREAD

**Issue by Fusseldieb** [xoseperez/espurna#1612]
**Bug description**
ESPurna doesn't manage MQTT groups very well. If I put two switches in the same group and switch one, the other sometimes doesn't switch (lost packet?) and then when I press again, it switches, causing both switches to be desynchronised (one on and the other off). It basically inverts. The switches have a good WiFi signal and are reachable in the web interface just fine. I believe it's a software issue. 

If possible, the sync command should contain if the switch was on or off too, so that the other can accurately replicate it.

**Steps to reproduce**
Put two switches in the same MQTT group in "Switches > MQTT group", press one switch a couple of times, then the other and slowly but surely the "sync" will get inverted and messed up.

**Expected behavior**
That it accurately represents the synced switch(es), if it's on or off.

**Device information**

> Manufacturer: ITEAD
> Device: SONOFF_T1_3CH
> Chip ID: 972DE9
> Wifi MAC: DC:4F:22:97:2D:E9 (Why hide it? Why would anyone clone a switch MAC?)
> SDK version: 1.5.3(aec24ac9)
> Core version: 2.3.0
> Firmware name: ESPURNA
> Firmware version: 1.13.5
> Firmware revision: 83195fd
> Firmware build date: 2019-02-27 00:24:54
> Firmware size: 473872 bytes
> Free space: 552960 bytes

>Channel: 12
>RSSI: -59
>IP: 192.168.2.21 (telnet)
>Free heap: 22080 bytes
>Load average: 2%
>VCC: 3164mV
>MQTT Status: CONNECTED
>NTP Status: SYNC'D

**Comment by tonymerce** [comment]
Yo tengo el mismo problema con 4 interuptores sincronizados.
