### ISSUE TITLE
MQTT messages get sent, but never arrive?

### ISSUE THREAD

**Issue by schweini** [xoseperez/espurna#1619]
I have two Sonoff POW (R1) connected to the same wifi router. They both connect to a mosquitto server on the internet.

One of them works great, but the other one is giving me strange headaches:
It DOES connect correctly to the MQTT server. I can see the mqtt pings in mosquitto's logs. I can even toggle the  relay via MQTT.

I have MQTT and 'send as JSON' enabled.

on the debug console, I get he clear indication that it is sending the messages:
`[MQTT] Sending ESPURNA-1A71A0/data => {"temperature":23.7,"humidity":61,"current":0.32,"voltage":216,"power":24,"reactive":62,"apparent":69,"factor":36,"energy":185435,"mac":"2C:3A:E8:1A:71:A0","host":"ESPURNA-1A71A0","ip":"192.168.0.100","id":4035}
`

but the messages never arrive, and there is no indication at all in the mosquitto logs that anything has ever been received.

I have re-flashed the unit, toggled all options on and off (with saving), but can't get it to work. THe other unit, with the same sensor, same wifi network, etc.

**Comment by mcspr** [comment]
Does the `[MQTT] Sending ...` log ends with `(PID 0)`?
Do you use acl rules with mosquitto? Maybe the problem is there?
