### ISSUE TITLE
How to add sensors to Nodemcu?

### ISSUE THREAD

**Issue by scarecrow2k6** [xoseperez/espurna#1622]
Hello everyone, I am sure some of you guys have used ESPurna with Nodemcu-12E. I was wondering how I could effectively use ESPurna with Nodemcu? I'm brand new to Espurna (coming from ESPEasy), I did some searching but couldn't find anything solid. The pre-built Nodemcu Lolin fw only acts like a switch, but I would like to add sensors, in my case, BME280 for now. I can't find any sensor section on the right pane. Did some digging, somewhere I read that the fw should auto detect sensors and somewhere I read that to use sensors, I would have to manually build the fw from master files. I don't know any coding but flashed several 3d printer fws in Arduinos, what I'm trying to say is that I know the basics. My problem is, every time I try to build the fw I get a lot of errors. Tried Platformio (with both Atom and VSC) and tried the Ardino IDE, nothing works and full of errors even with all the Libraries installed.

The reason for me to try ESPurna is built-in InfluxDB, Alexa support etc. which are missing from ESPEasy but then again it has an easier sensor adding page. I would really appreciate if someone could tell me what to do to build my own fw or point me to the right direction. Thanks.

**Comment by scarecrow2k6** [comment]
Anyone?

**Comment by ColinShorts** [comment]
If there isn't a suitable firmware that matches your use case then you'll need to roll your own firmware.

The pre-built firmware specifies which pin the sensor should be connected to. The pin can be changed by editing the code of you need to, but you will need to build the code in that event.

Read through some of the code, you'll find code/espurna/config/hardware.h most helpful. Sensors are well documented in the code and in https://github.com/xoseperez/espurna/wiki/Sensors

The are instructions in the wiki for setting up Arduino and platformio. Xose recommend platformio, and that is what I use and would recommend as it resolves the library dependencies. Try getting it working from the command line first.

If you still run into errors, try posting the error output here, or ask for help in gitter - use pastebin/similar for passing the full command and output there.

**Comment by InduPrakash** [comment]
There is support for BME280/BMP280 sensors, take a look at https://github.com/xoseperez/espurna/wiki/Sensors.

**Comment by scarecrow2k6** [comment]
> If there isn't a suitable firmware that matches your use case then you'll need to roll your own firmware.
> 
> The pre-built firmware specifies which pin the sensor should be connected to. The pin can be changed by editing the code of you need to, but you will need to build the code in that event.
> 
> Read through some of the code, you'll find code/espurna/config/hardware.h most helpful. Sensors are well documented in the code and in https://github.com/xoseperez/espurna/wiki/Sensors

**Comment by scarecrow2k6** [comment]
> If there isn't a suitable firmware that matches your use case then you'll need to roll your own firmware.
> 
> The pre-built firmware specifies which pin the sensor should be connected to. The pin can be changed by editing the code of you need to, but you will need to build the code in that event.
> 
> Read through some of the code, you'll find code/espurna/config/hardware.h most helpful. Sensors are well documented in the code and in https://github.com/xoseperez/espurna/wiki/Sensors

This is super valuable information! Ok I looked into hardware.h file and see that the I2C_SDA_PIN (D2) and I2C_SCL_PIN (D1) are defined for Wemos and some other boards, but not for Nodemcu. I'm guessing it should be the same as I used the same pins with ESPEasy and it worked there. I know the BME280 requires both in general. I plugged it but still can't see any sensor section on the left hand side. What am I missing? Thanks.

**Comment by ColinShorts** [comment]
Did you flash a different binary? If so, which one, what version, have you tried a shift-refresh in the browser?

There is a template for opening issues for a reason 😉

**Comment by scarecrow2k6** [comment]
> Did you flash a different binary? If so, which one, what version, have you tried a shift-refresh in the browser?
> 
> There is a template for opening issues for a reason 😉

I installed "espurna-1.13.5-nodemcu-lolin.bin" for my no brand Nodemcu-Lolin (clone?). I didn't want to open an issue because I didn't know if it is an actual issue.

**Comment by ColinShorts** [comment]
I don't think the lolin bin file was built with sensors built in, so you'll likely need to build your own binary.

Try setting up platformio and follow the wiki page:
https://github.com/xoseperez/espurna/wiki/PlatformIO

It's honestly the best thing you'll ever do 🙂

**Comment by InduPrakash** [comment]
You can watch debug out on the serial monitor. I was once having trouble with a DHT sensor and turned out that the sensor was not connected properly due to which the sensor module was not initializing which in turn led to MAGNITUDE_NONE being returned from type() which prevented the section from being made visible in the browser. The BMX sensor will bail out if I2C initialization fails.
