### ISSUE TITLE
The Total Energy read on the POW R2 resets if the switch looses power, but the date does not change

### ISSUE THREAD

**Issue by MaliMrav** [xoseperez/espurna#1625]
![Screen Shot 2019-03-10 at 1 57 16 pm](https://user-images.githubusercontent.com/6211939/54080065-76b23500-433c-11e9-9efe-51b8dd57b180.png)

**Comment by AlbertWeterings** [comment]
This is normal. Under sensors you have a option to save the total energy value to the eeprom then it remember the value after power loss. Downside of saving to eeprom is this will wear out the flash memory as it can not be written unlimited times.
