### ISSUE TITLE
Magic Home ZJ-WFMN-A 1.1 - White always on 

### ISSUE THREAD

**Issue by Kerwood** [xoseperez/espurna#1635]
I flashed my Magic Home RGBW LED Controller with `espurna-1.13.5-magichome-zj-wfmn-a-11.bin` pre-built binary, from the releases page.
I am not able to control White, I'm guessing that's channel 3. It is just constantly on.
![IMG_20190311_215754070](https://user-images.githubusercontent.com/4029521/54379266-5d392200-4689-11e9-8c46-5daf1d606abe.jpg)
![IMG_20190311_215732385_HDR](https://user-images.githubusercontent.com/4029521/54379288-6629f380-4689-11e9-95e5-520890d7a5f5.jpg)

Any ideas ?

**Comment by ColinShorts** [comment]
Try 1.13.5-magichome-zj-wfmn-b-11.bin.

There are a couple of revisions of hardware for some devices, this one has white on a different channel.

**Comment by Kerwood** [comment]
Thanks.. Will give it a shot

**Comment by Kerwood** [comment]
Nope.. the "b" version did not do the trick.

**Comment by ColinShorts** [comment]
I guess you'll need to figure out which gpio pin is connected to the white channel. If you've got access to a multimeter you'll probably be able to figure out which pin on the chip is connected to the transistor that's driving the white channel.

Failing that, you might be able to use an alternative firmware that allows you to change the gpio on the fly, you already know which pins drive RGB, so not too much trial and error required.

The last scenario is a hardware fault, but hopefully not that.

**Comment by MonsieurBibo** [comment]
hey, I found that the gpio 15 turns the white LEDs on/off.

**Comment by MonsieurBibo** [comment]
> hey, I found that the gpio 15 turns the white LEDs on/off.

Unfornately, I think we can just on/off the white LEDs.

**Comment by Kerwood** [comment]
How exactly ?

**Comment by MonsieurBibo** [comment]
> How exactly ?

if you use the debug terminal with the command "gpio 15 0" or "gpio 15 1" you can turn on/off the white LEDs.
