### ISSUE TITLE
compiling firmware with max6675 support

### ISSUE THREAD

**Issue by tibi03** [xoseperez/espurna#1646]
hello,

i am trying to compile the firmware with max6675 sensor support but its failing, i am using the dev code : 

In file included from espurna\config/sensors.h:1029:0,
from espurna\config/all.h:36,
from D:/Tibi/ESP8266/espurna-dev/code/espurna/espurna.ino:22:
espurna\config/../sensors/MAX6675.h:140:32: error: 'MAX6675_CS_PIN' was not declared in this scope
unsigned int _pin_cs = MAX6675_CS_PIN;
^
espurna\config/../sensors/MAX6675.h:141:32: error: 'MAX6675_SO_PIN' was not declared in this scope
unsigned int _pin_so = MAX6675_SO_PIN;
^
espurna\config/../sensors/MAX6675.h:142:33: error: 'MAX6675_SCK_PIN' was not declared in this scope
unsigned int _pin_sck = MAX6675_SCK_PIN;
^
Compiling .pioenvs\nodemcu-lolin\lib000\ESP8266WiFi\ESP8266WiFiSTA.cpp.o
D:/Tibi/ESP8266/espurna-dev/code/espurna/sensor.ino: In function 'void _sensorLoad()':
D:/Tibi/ESP8266/espurna-dev/code/espurna/sensor.ino:778:23: error: 'MAX6675_CS_PIN' was not declared in this scope
sensor->setCS(MAX6675_CS_PIN);
^
D:/Tibi/ESP8266/espurna-dev/code/espurna/sensor.ino:779:23: error: 'MAX6675_SO_PIN' was not declared in this scope
sensor->setSO(MAX6675_SO_PIN);
^
D:/Tibi/ESP8266/espurna-dev/code/espurna/sensor.ino:780:24: error: 'MAX6675_SCK_PIN' was not declared in this scope
sensor->setSCK(MAX6675_SCK_PIN);
^
Compiling .pioenvs\nodemcu-lolin\lib000\ESP8266WiFi\ESP8266WiFiScan.cpp.o
Compiling .pioenvs\nodemcu-lolin\lib000\ESP8266WiFi\WiFiClient.cpp.o
Compiling .pioenvs\nodemcu-lolin\lib000\ESP8266WiFi\WiFiClientSecure.cpp.o
Compiling .pioenvs\nodemcu-lolin\lib000\ESP8266WiFi\WiFiServer.cpp.o
*** [.pioenvs\nodemcu-lolin\src\espurna.ino.cpp.o] Error 1

any idea what can be wrong ?

thank you

**Comment by mcspr** [comment]
MAX6675 requires 3 definitions to work: `MAX6675_CS_PIN`, `MAX6675_SO_PIN` and `MAX6675_SCK_PIN`
https://github.com/xoseperez/espurna/blob/edef1631df4d4f1f0eb09b79265e58fdb1a1d2fc/code/espurna/sensor.ino#L790-L794

you can modify method params above directly with proper gpio numbers or instead, add `#define MAX6675_CS_PIN 4` etc. in header files.
also see [`code/espurna/config/all.h`](https://github.com/xoseperez/espurna/blob/edef1631df4d4f1f0eb09b79265e58fdb1a1d2fc/code/espurna/config/all.h#L10) comment about 'custom.h'.
