### ISSUE TITLE
Dhcp lease only follow first after boot

### ISSUE THREAD

**Issue by pabloalcantara** [xoseperez/espurna#1651]
I'm changing my network tô use dhcp, and in the mean time I put the lease on my server tô 5 minutes. After all the changes, I changed tô 8 days. Tô my surprise all my espurna devices (15) stills asking for lease after 5 minutes. Only after rebooting e ache one The started tô get the New lease time. I think that espurna is using the first lease time after boot and ignoring when receiving The changed lease time.

**Comment by xoseperez** [comment]
I'm not 100% sure but I'd say this is handled internally by the lwip library... I think this question should go to the ESP8266 Core for Arduino project...
