### ISSUE TITLE
mqtt LWT

### ISSUE THREAD

**Issue by CrispinP** [xoseperez/espurna#1652]
Could you please implement LWT for mqtt?

A separate topic and message (both static) config world work.

I use sonoff to tell me if a circuit is energised. Having a lwt allows quicker response than scheduled ping. 

Thanks.

**Comment by jackwilsdon** [comment]
The devices publishes a LWT on the `/status` topic, with a `1` being published by the device when it is online and a LWT of `0`.

**Comment by CrispinP** [comment]
I'm seeing the 1 but when I drop the power to sonoff it does not change to zero.
I had a look at the $sys topic as well and see that it does not change when the sonoff drops. Why might that be? Obviously the LWT will not get sent it Mosqiutto does not see it drop.

![image](https://user-images.githubusercontent.com/27884877/54885670-cb929700-4e76-11e9-8782-5544786ba894.png)

None of the values there change when the sonoff is on or off (unclean shutdown)

**Comment by flashy02** [comment]
I'm using the LWT for monitoring all devices and can say, it works fine. Additionally I control with the LWT the automated garagedoor with no problems. You can config the LWT in the UI. Since some versions of espurna, the time constant is 300s, that means at least after 300s being offline the broker sends the LWT. I'm using normally 30s or 10s for the garagedooropener.

**Comment by xoseperez** [comment]
@CrispinP: As @flashy02 says the keep alive (`MQTT_KEEPALIVE`) time by default is 300s. Please allow 5 minutes to receive the LWT message or change the keep-alive value for a faster response.

**Comment by CrispinP** [comment]
Thanks both. I realised I was not waiting very long. Did not know
until @flashy02 mentioned the 300s that there was a delay.

Could I change the topic then to make the time shorter? 300s is an eternity
:)

Regards

**Comment by flashy02** [comment]
You have to change the time in the UI. The topic is still to find under ".../status".
![MQTT](https://user-images.githubusercontent.com/35804771/54932675-7eb4cc00-4f1b-11e9-8960-de1559beb705.png)

**Comment by CrispinP** [comment]
I'm getting old. I did not check :(

**Comment by CrispinP** [comment]
Thanks both, this works as expected :)
