### ISSUE TITLE
Menu entries are missing

### ISSUE THREAD

**Issue by kuppe234** [xoseperez/espurna#1654]
Hello,
in firmware revision 0987e019 some menu entries are missing:

>   HASS
>   MQTT
>   NTP
>   SCHEDULE
>   SENSORS

Only the new entry LED is visible.
My buildflags:
>  build_flags = ${common.build_flags_1m0m} -DITEAD_S20 -DDALLAS_SUPPORT=1 -DBMX280_SUPPORT=1

What´s wrong?
Greetings kuppe.

**Comment by Alferez** [comment]
I have same problem. In chrome debug show this:

Uncaught ReferenceError: line is not defined
    at (index):1
    at Array.forEach (<anonymous>)
    at processData ((index):1)
    at WebSocket.onmessage ((index):1)

**Comment by InduPrakash** [comment]
This is a duplicate of #1653.

**Comment by xoseperez** [comment]
Fixed in dev.
