### ISSUE TITLE
htmllinting setting in gulpfile.js

### ISSUE THREAD

**Issue by InduPrakash** [xoseperez/espurna#1657]
Currently gulpfile.js has not setting for line-end-style and by default lf is used. 

This generates tons of following errors when trying to build web images -
"index.html [1474,93]: (E015) line ending does not match format: lf".

Since all the white spaces seems to be trimmed when the images are build so can the rule be suppressed ? 

`'line-end-style': false`

I am using Visual Code on Win10.

**Comment by xoseperez** [comment]
Done in `dev`
