### ISSUE TITLE
3rd party libraries usage for sensors

### ISSUE THREAD

**Issue by berezovskyi-oleksandr** [xoseperez/espurna#1668]
Hi! 

I want to implement support of Bosch BME680 sensor support. I took a brief look on datasheet and current implementation of BMX280 and there are lots of different things over there.

Bosch provide ready-to-use library for this sensor and it used in Adafruit library for Arduino.

Is it ok to add 3rd party library and implement just bindings for sensor support?

**Comment by mcspr** [comment]
Sorry for delayed response.

I don't think that would be a problem, unless there are some catastrophic issues with the way it works. 
Also note that Adafruit library implicitly pulls Adafruit_Sensor library as a dependency:
https://github.com/adafruit/Adafruit_BME680
https://github.com/adafruit/Adafruit_Sensor

Judging from https://github.com/adafruit/Adafruit_BME680/pull/22, there's also a problem with async reading when `millis()` timer overflows (49 days uptime)
Which it a likely way to make readings work here.
