### ISSUE TITLE
Transitions how to disable and hide in web ui?

### ISSUE THREAD

**Issue by wired-dev** [xoseperez/espurna#1670]
okay I'm adding a new bulb type altogether works via the uart; when transitions are enabled it causes freezing and bad behavior. disabling it resolves the issues; and it appears they do the transition in it's own.

**Comment by mcspr** [comment]
Common way to hide things in UI is to use `module-some` element classes and send `someVisible` with 0 (disable) or 1 (enable)

You can also just forcibly `setSetting("useTransitions", 0)` when such hardware is enabled. Or override `lightUpdate` to ignore transition setting (transition time in that case) altogether.
