### ISSUE TITLE
¿Como se pueden sincronizar 2 Sonoff T1?

### ISSUE THREAD

**Issue by Adri-Dax** [xoseperez/espurna#1689]
Muy buenas, he visto que con ewewlink crenado unas escenas puedes sincronizar 2 Sonoff T1 para un pasillo, minpregunta es ¿Con Espurna como se puede hacer esto? Agradeceria una explicación soy nuevo en esto y no tengo ni idea gracias
*Before creating a new issue please check that you have:*

* *searched the existing [issues](https://github.com/xoseperez/espurna/issues) (both open and closed)*
* *searched the [wiki](https://github.com/xoseperez/espurna/wiki)*
* *asked for help in the [chat](https://gitter.im/tinkerman-cat/espurna)*
* *done the previous things again :)*

*Fulfilling this template will help developers and contributors help you. Try to be as specific and extensive as possible. If the information provided is not enough the issue will likely be closed.*

*You can now remove this line and the above ones. Text in italic is meant to be replaced by your own words. If any of the sections below are not relevant to the issue (for instance, the screenshots) then you can delete them.*

**Question**
*A clear and concise description of what the problem/doubt is.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Device information**
*Copy-paste here the information as it is outputted by the device. You can get this information by typing `info` via serial, terminal or in the debug tab in the web UI. The relevant information is that surrounded by the scissors-cut lines (`---8<-------`).*
*If you cannot get this info from the device, please answer this questions:*
* *Arduino Core version*
* *ESPurna version*
* *Flash mode*
* *Device brand, model and version*

**Tools used**
* *Desktop operating system*
* *Browser & version*
* *IDE & version*
* *Compiler & version (if not embedded in IDE)*

**Additional context**
*Add any other context about the problem here.*

**Comment by xoseperez** [comment]
Con eWeLink haces la sincronización a través del cloud del fabricante. Con ESPurna, ya que no hay cloud, debes tener un broker MQTT en local (en una Raspberry Pi, por ejemplo) y sincronizar los dispositivos vía MQTT. En la página de configuración de los SWITCHES tienes la opción "MQTT Group" para cada interruptor. Solo tienes que poner el mismo topic en los 2 (o 3, 4,...) disposivitos que quieras sincronizar.
