### ISSUE TITLE
PWM Fan Control

### ISSUE THREAD

**Issue by mlfactory** [xoseperez/espurna#1691]
Hey,

with what libary is the PWM controlled?

I mean

`control?cmd=PWM,12,1000
`
Cheers and Thanks,
Michael

**Comment by mcspr** [comment]
Closing as ESPeasy question: https://github.com/letscontrolit/ESPEasy/issues/2442
Just FYI, pwm here is based on https://github.com/StefanBruens/ESP8266_new_pwm, not implementation from Core.
