### ISSUE TITLE
espurna trouble with RAW payalod

### ISSUE THREAD

**Issue by puyoo** [xoseperez/espurna#1694]
HI 
i have sonoff bridge  connected to a raspberry PI  end hadle all over node-red 

my node red  is working fine with for openMQTTgateway this handle RAW payload

home/OpenMQTTGateway/SRFBtoMQTT/Raw XXXX0ZZZ0YYY044A81
home/OpenMQTTGateway/SRFBtoMQTT 629377   (RF code device)
home/OpenMQTTGateway/SRFBtoMQTT/Tsyn  XXXX
home/OpenMQTTGateway/SRFBtoMQTT/Thigh YYY
home/OpenMQTTGateway/SRFBtoMQTT/Tlow ZZZ

over espurna i receve only RAW payload ,im interesed only for the RF code from my device 
in the sample matches witch the 2 last byte (hex) , how i can solve this over NODE-RED ?

**Comment by mcspr** [comment]
Just to verify, I think it is solvable by NodeRED itself via new output node cutting to the last 6 chars?

General solution is to make and option for rfin topic to send out only the last 6 chars
