### ISSUE TITLE
Build 1.13.5 not have fix bug for ntp time year 2036?

### ISSUE THREAD

**Issue by cent0** [xoseperez/espurna#1695]
Build 1.13.5 not have fix bug for ntp time year 2036? 
I have tested and have same problem. Long time for connection, and connection result work with 2036 07 02 ☹️

**Comment by mcspr** [comment]
No, it does not. Not yet, anyways.
ref:
xoseperez/NtpClient#2
#1380 

For now you can replace this line with `https://github.com/mcspr/NtpClient#763b1cbf`
https://github.com/xoseperez/espurna/blob/1f1f226cb713d9079c8728f227cdc7a0eb8df591/code/platformio.ini#L96
Or use this repo's branch for ArduinoIDE (manually replacing current library):
https://github.com/mcspr/NtpClient/tree/espurna/fixes
