### ISSUE TITLE
Disable the switch option

### ISSUE THREAD

**Issue by goatchurchprime** [xoseperez/espurna#1697]
We use the Sonoff POWs to measure power on devices **that we never want to turn off**.  

Can we have an option in the Switches menu that is "I really mean Always ON!" instead of just being on at boot mode.  I don't want it ever to go off if someone taps the switch or sends an MQTT relay/off message to this device.  

We already have other ways of turning our machines off, like kill switches and a separate power unit that turns a whole lot of other machines off at the same time.  

Having this easy off switch in the Sonoff is a liability.  But I want it to be easy to read the power and do the other config features.  

Adding this lockin feature into the Boot mode option would be the minimum to achieve this.  But you could add a new thing on the API that locks or unlocks the switch remotely.  

But the really main thing is we'd like to easily disable that button as a switch.

**Comment by mcspr** [comment]
> But the really main thing is we'd like to easily disable that button as a switch.

I remember button control was proposed as https://github.com/xoseperez/espurna/pull/1322
But i think this should be resolved via [v2 branch](https://github.com/xoseperez/espurna/tree/v2) / current #1680 , since we will be able to remove relayID<->button association at runtime

**Comment by xoseperez** [comment]
Even after removing the association between buttons (physical or virtual) and relays there will be ways to toggle the relay (terminal, MQTT, API...). For me the proposed lock option in #1705 makes sense...

**Comment by markusrudolf** [comment]
I also want to have an option to disable the physical switch via web interface since our triplets are starting to exploring our flat and pressing all buttons that are in range :-)
