### ISSUE TITLE
Thingspeak Sonoff Pow R2

### ISSUE THREAD

**Issue by serestre** [xoseperez/espurna#1706]
<Hello, I would appreciate a lot of help. I could not read the Sonoff Pow R2 information in Thingspeak>

Hola, agradecería mucho algo de ayuda

No he podido leer la información del Sonoff Pow R2 en Thingspeak. 

Deshabilité el Firewall. 
El rele lo puedo accionar (encender-apagar) desde la aplicación del navegador Google Chrome en Windows 10
Tambien lo he intentado con Mozilla Firefox

Tengo la siguiente configuración en el canal de Thingspeak:

![image](https://user-images.githubusercontent.com/11726268/56818051-739bd700-680c-11e9-8bd0-d1a6306e39ab.png)
![image](https://user-images.githubusercontent.com/11726268/56817424-2ec37080-680b-11e9-8e2b-69ad82de68f3.png)

----------------------------------------------------------------------------------------------------------
El Sonoff esta flasheado con ESPURNA 1.13.5

![image](https://user-images.githubusercontent.com/11726268/56817547-6b8f6780-680b-11e9-8fa7-576ffe039a64.png)
----------------------------------------------------------------------------------------------------------
La configuración del sensor es la siguiente

![image](https://user-images.githubusercontent.com/11726268/56817754-c628c380-680b-11e9-8fae-65f4e7427899.png)
----------------------------------------------------------------------------------------------------------
asi esta configurada la conexion a Thingspeak

![image](https://user-images.githubusercontent.com/11726268/56817809-e3f62880-680b-11e9-9839-e3d6bedf1486.png)
----------------------------------------------------------------------------------------------------------
Debug Log

![image](https://user-images.githubusercontent.com/11726268/56818129-9928e080-680c-11e9-8806-d36f27345ded.png)
----------------------------------------------------------------------------------------------------------

**Comment by serestre** [comment]
Solucionado, el problema estaba en la configuracion que habia establecido en la red WiFi. No conozco mucho ese mundo del router

Inicialmente lo había configurado con una IP fija. 
Luego le quite todo eso y ya envía datos a ThingSpeak

Antes & Despues
![image](https://user-images.githubusercontent.com/11726268/56988077-cb13ad00-6b54-11e9-88ea-92bca2b342ea.png)

**Comment by mcspr** [comment]
No hablo español, sólo para que lo sepa. 🤐

So you changed from static IP config to DHCP, and now it works? You can close the issue if that is correct.
