### ISSUE TITLE
[1.13.5]Sonoff basic won't go to AP mode or connect to router

### ISSUE THREAD

**Issue by cracautanu** [xoseperez/espurna#1718]
[Reproduce steps]
- Flash sonoff basic with  **espurna-1.13.3-itead-sonoff-basic.bin**
- After flash, connect to it in ap mode, change password, enable http api and add 1 wifi router
=> setup ok, device connected to router and http api works fine
- Double press gpio0, set it to AP mode, and update the version to **espurna-1.13.5-itead-sonoff-basic.bin**. I did this because every 2 days the device was turning unresponsive with v1.13.3
=> Update done, device reboots but doesn't connect to router. I also checked the router interface for connected devices and it wasn't on the list. Led flashes faster than it would when it is connected to router. 
=> Press twice GPIO 0 => goes to AP mode but authentification fails on both laptop and mobile with message "authentification failure" or "password incorrect". I tried the password I set on v1.13.3 and fibonacci. None of them worked. I reseted the device by long pressing the button more than 10 seconds. Same problem after reboot=>it goes to ap mode but doesn't accept fibonacci as a password neither the old one. 

I reproduced this issue with this procedure 3 times in a row 
I reflashed the device with 1.13.2 and it works fine now

**Comment by mcspr** [comment]
Please see https://github.com/xoseperez/espurna/issues/1631 and https://github.com/xoseperez/espurna/issues/1699
In the meantime, current `dev` builds have this fix included:
https://github.com/mcspr/espurna-nightly-builder/releases
