### ISSUE TITLE
LED Status reverts to default after power cycle or reboot.

### ISSUE THREAD

**Issue by davebuk** [xoseperez/espurna#1719]
I have a Sonoff basic V2 and am running 1.13.6-dev. I can change the LED status function, save, and that new function works correctly.

If I power cycle using the mains or reboot using the web interface, the LED status reverts back to the default, 'wifi status'.

**Comment by mcspr** [comment]
Led initial setup was overwriting both mode and relay from header defaults. Fixed in #1724

**Comment by davebuk** [comment]
Working, thanks.
