### ISSUE TITLE
Sonoff Basic R2, which binary?

### ISSUE THREAD

**Issue by darkoddio** [xoseperez/espurna#1760]
Which binary do I need to use to flash a Sonoff Basic R2 if I don't want to use any sensor?
![image](https://user-images.githubusercontent.com/22075319/58964506-4e0cd080-87af-11e9-9981-68251d07cee2.png)

**Comment by davebuk** [comment]
I'm pretty sure the standard Sonoff-basic will work. I think the only difference is the GPIO pin assignment is different if you want to use the internal solder pads for an external switch (IO 2 instead of 14).

**Comment by xoseperez** [comment]
@davebuk is right. The only difference is where the sensor is attached so in your case you can safely flash the standard sonoff basic image.

**Comment by darkoddio** [comment]
thanks guys, that's exactly what I did few days ago :)
I don't plan to connect any sensor/switch to it

**Comment by clueo8** [comment]
I successfully got Espurna on one of these new Sonoff Basic units, but when I tried to connect a Dallas temp sensor to the IO 2 pad, it doesn't power on any more, it seems like its dead... Won't power on anymore... Any idea what could have happened or how to diagnose?

**Comment by davebuk** [comment]
My guess is you've bridged the pad to another line causing a short? Or maybe the sensor is holding IO2 to ground and forcing boot mode.

You could take the sensor off and see if it starts working again.

**Comment by clueo8** [comment]
I did remove the sensor, but it fails to power on anymore with mains and FTDI doesn't recognize it anymore.  Didn't know if it's stuck in a strange mode? Or dead...

**Comment by davebuk** [comment]
I guess you have soldered header pins to the board. Make sure they haven't joined together with a stray bit of solder. 

If the LED is not coming on at all, powered either from your FTDI or mains power, it might unfortunately be dead. I don't recommended it but it if you have the technical knowledge you could check if the mains supply is being converted to 3v DC. SAFETY NOTICE! Obviously remember mains voltage can kill. 

I had one device once that powered up but wouldn't run or flash a firmware. I left it in a cupboard for a few weeks and when I came to try it again it worked and could flash it. 😁
