### ISSUE TITLE
Incompatibilidad con algunos routers

### ISSUE THREAD

**Issue by xoseperez** [xoseperez/espurna#178]
Originally reported by: **Asociacion Helianto (Bitbucket: [helianto](https://bitbucket.org/helianto), GitHub: [helianto](https://github.com/helianto))**

----------------------------------------

(Este problema no es propio de espurna, pues en algunos equipos con firmware sonoff tambien me resultaba imposible conectar).

Despues de diversas pruebas que he podido realizar con diversos equipos, parece que existe algun tipo de incompatibilidad entre algunos routers (fundamentalmente instalados por compañias como ONO-Vodafone) y los equipos sonoff.  En algunos casos se puede solventar con la instalacion de una ip fija en el espurna (equipo CBN nuevo), en otros no hay forma de solucionarlo (equipos CBN antiguos CG6640E y equipos netgear CG3100D).  Desconozco donde estara el problema (al principio pensaba que era de dhcp... pero no), he probado todas las combinaciones posibles de seguridad, canales, etc, sin exito.

**Comment by xoseperez** [comment]
@Cesarma @helianto

El ESP8266 no puede con cualquier cifrado. Ver https://github.com/esp8266/Arduino/issues/2795. 
De todas maneras no parece ser un problema del firmware. You probaría con un sketch básico que solo realice la conexión y ver qué configuració da problemas.
Yo no puedo probar desde aquí porque parece estar relacionado con un hardware específico.

Cierro el issue. Si en algún momento alguno de los dos llega a alguna conclusión, reabrid el issue sin problema.

Gracias

**Comment by zotix** [comment]
I try to connect to my router ZTE F668 (Not working)

Core Version: Lib 2.4.1
Board: NodeMCU 0.9

iPhone and xiaomi redmi S2 can connect without problem.
ZTE F668 cannot connect all modes include open system. -_-
