### ISSUE TITLE
Devices don't record last state after reboot or recovering from power lost

### ISSUE THREAD

**Issue by rmcbc** [xoseperez/espurna#1819]
**Bug description**
I facing a problem with 1.13.6-dev and don't have the same problem with 1.13.2
In SWITCHES, I put Boot mode: Same as before.
And it always restart off.
It appens with SonOff BASIC and Shelly 1.

**Steps to reproduce**
Build with default_envs = itead-sonoff-basic or default_envs = allterco-shelly1

**Expected behavior**
If I put same as before it should be same as before.

**Tools used**
Visual Code with Platform IO core 4.0.0

![imagem](https://user-images.githubusercontent.com/16247792/61165160-9472ef00-a514-11e9-9713-8080b5056587.png)

![imagem](https://user-images.githubusercontent.com/16247792/61165166-aa80af80-a514-11e9-8255-2697968ca802.png)
![imagem](https://user-images.githubusercontent.com/16247792/61165175-c71ce780-a514-11e9-816b-1ce6a0d7cc86.png)

**Comment by rmcbc** [comment]
ITEAD_SONOFF_BASIC
==================

    // Info
    #define MANUFACTURER        "ITEAD"
    #define DEVICE              "SONOFF_BASIC"

    // Buttons
    #define BUTTON1_PIN         0
    #define BUTTON1_MODE        BUTTON_PUSHBUTTON | BUTTON_DEFAULT_HIGH | BUTTON_SET_PULLUP
    #define BUTTON1_RELAY       1
    #define BUTTON1_PRESS       BUTTON_MODE_TOGGLE
    #define BUTTON1_CLICK       BUTTON_MODE_NONE
    #define BUTTON1_DBLCLICK    BUTTON_MODE_NONE
    #define BUTTON1_LNGCLICK    BUTTON_MODE_NONE
    #define BUTTON1_LNGLNGCLICK BUTTON_MODE_NONE   

	#define BUTTON2_PIN         3
	#define BUTTON2_MODE        BUTTON_PUSHBUTTON | BUTTON_DEFAULT_HIGH | BUTTON_SET_PULLUP
	#define BUTTON2_RELAY       1   
	#define BUTTON2_PRESS       BUTTON_MODE_TOGGLE
	#define BUTTON2_CLICK       BUTTON_MODE_NONE
	#define BUTTON2_DBLCLICK    BUTTON_MODE_NONE
	#define BUTTON2_LNGCLICK    BUTTON_MODE_NONE
	#define BUTTON2_LNGLNGCLICK BUTTON_MODE_NONE

    // Relays
    #define RELAY1_PIN          12
    #define RELAY1_TYPE         RELAY_TYPE_NORMAL

    // LEDs
    #define LED1_PIN            13
    #define LED1_PIN_INVERSE    1

    // Non-core modules
    #define ALEXA_SUPPORT               1
    #define DOMOTICZ_SUPPORT            1
    #define HOMEASSISTANT_SUPPORT       1
    #define I2C_SUPPORT                 0
    #define SCHEDULER_SUPPORT           1
    #define SENSOR_SUPPORT              0
    #define THINGSPEAK_SUPPORT          0
	
ALLTERCO_SHELLY1
================

	// Info
	#define MANUFACTURER        "ALLTERCO"
	#define DEVICE              "SHELLY1"

	// Buttons
	#define BUTTON1_PIN         5
	#define BUTTON1_MODE        BUTTON_PUSHBUTTON // | BUTTON_DEFAULT_HIGH | BUTTON_SET_PULLUP
	#define BUTTON1_RELAY       1

	#define BUTTON1_PRESS       BUTTON_MODE_TOGGLE
	#define BUTTON1_CLICK       BUTTON_MODE_NONE
	#define BUTTON1_DBLCLICK    BUTTON_MODE_NONE
	#define BUTTON1_LNGCLICK    BUTTON_MODE_NONE
	#define BUTTON1_LNGLNGCLICK BUTTON_MODE_NONE

	// Relays
	#define RELAY1_PIN          4
	#define RELAY1_TYPE         RELAY_TYPE_NORMAL

	// Non-core modules
	#define ALEXA_SUPPORT               1
	#define DOMOTICZ_SUPPORT            1
	#define HOMEASSISTANT_SUPPORT       1
	#define I2C_SUPPORT                 0
	#define SCHEDULER_SUPPORT           1
	#define SENSOR_SUPPORT              0
	#define THINGSPEAK_SUPPORT          0

**Comment by rmcbc** [comment]
Debug when I turn the relay on:

![imagem](https://user-images.githubusercontent.com/16247792/61165230-ac973e00-a515-11e9-91f3-cb3144298ad7.png)

After reboot:
![imagem](https://user-images.githubusercontent.com/16247792/61165241-e5371780-a515-11e9-92a3-ae02b0f7d52d.png)
![imagem](https://user-images.githubusercontent.com/16247792/61165235-d3ee0b00-a515-11e9-9a4b-a934add46b49.png)

**Comment by mcspr** [comment]
Between reboots, what does the `get relayBoot0`, `rtcmem.dump` show and `info` part say about the last boot status?

**Comment by mcspr** [comment]
...and can you please try with DEBUG_SERIAL_SUPPORT 0 in defines for Basic?

**Comment by rmcbc** [comment]
@mcspr one thing I can say the modules that doesn't work ok with "Same as Before", became ok if I put "Toggle Before".
I'm going to DEBUG and them show the results.

**Comment by mcspr** [comment]
Thanks! If you can, can you try recording boot log with one of the units? We can then see what boot status it uses or if anything else breaks it. Only-3v3 powered, ofc.

**Comment by rmcbc** [comment]
@mcspr I can't reproduce the problem with the module that I describe this problem, because I erase the flash and write the new one with debug active, and now it's working ok.
There is another with the same problem I'm going to try to get it out and upgrade firmware using webpage.
Meanwhile I send you the current log file.
[log.txt](https://github.com/xoseperez/espurna/files/3393633/log.txt)

**Comment by rmcbc** [comment]
Sorry, it was my problem, how could I miss it. The press button was always pressed and when we release it when we pressed. So it was inverted.
Going to close this one.
