### ISSUE TITLE
TX T1UK Support

### ISSUE THREAD

**Issue by DJBenson** [xoseperez/espurna#1838]
Has anybody attempted to flash (or even know if it's possible to do so) the new TX T1 switches? I've opened up the board and can see the headers but the board layout is significantly different from the existing T1's.

**Front**:
![1F521494-E001-45D6-BB02-D7331B622C20](https://user-images.githubusercontent.com/1013909/62374778-96890600-b534-11e9-815f-31a2cab216da.jpeg)

**Rear**:
![0733F758-FE3E-4C78-AD56-9794991ABAF9](https://user-images.githubusercontent.com/1013909/62374889-df40bf00-b534-11e9-9c87-36cb7eb29981.jpeg)

**Box Front**:
![A5A71CEE-E181-4BA9-81C4-183E114C87ED](https://user-images.githubusercontent.com/1013909/62375237-be2c9e00-b535-11e9-84c7-8deaa69466c1.jpeg)

**Box Rear**:
![7F4148AB-E023-4BF4-AAC2-7D9054748955](https://user-images.githubusercontent.com/1013909/62375262-cab0f680-b535-11e9-8553-0ed7b0471ccd.jpeg)

**Front Profile**:
![7D13DF6D-E4E3-43DE-A6DC-287CE0B7E13B](https://user-images.githubusercontent.com/1013909/62375278-d6042200-b535-11e9-8d4f-e2e75ba9a5ca.jpeg)

**Rear Profile**:
![8456C4D3-AD99-4684-8A30-F34213AA2F91](https://user-images.githubusercontent.com/1013909/62375287-ddc3c680-b535-11e9-800e-f63545ef72b3.jpeg)

**Rear**:
![CBCAD534-F6F7-4750-A12B-7D83B02D7FF8](https://user-images.githubusercontent.com/1013909/62375456-3eeb9a00-b536-11e9-86b7-3885486661b6.jpeg)

**Comment by ColinShorts** [comment]
It should work fine with the T1 binaries. I picked a T3 up last week, which is supposed to be just a different colour (black versus white) than the T2.

That said, I'm only using mine as a remote, so I haven't tested that the correct relay switches on/off, but they do switch on and off.

My only grumble is that they glow way too brightly to be used in a bedroom, and it's a bit shiny in my living room as the TV reflects on the surface.

It's a much nicer looking unit than the old T1 though!

Ground the right hand side of R19 (in the top left section, it's the top right resistor), flash as normal.

**Comment by DJBenson** [comment]
Thanks @ColinShorts, I'll give it a go tonight when the kids are asleep.

**Comment by ColinShorts** [comment]
No worries, I actually found the info on the tasmota GitHub:

https://github.com/arendst/Sonoff-Tasmota/issues/5918

**Comment by ColinShorts** [comment]
Hey, not sure how you got on, but I just noticed that I'm actually using the "yjzk switch_3ch" binary and not the t1. I've set the wifi status led to always on and it's actually off, which is the only difference between the two configs as far as I'm aware. The T1 config /should/ work correctly.

**Comment by Tofandel** [comment]
The T1/2/3 have an RF chip (bottom right of the first screen) it's the same as the sonoff bridge

Could you try adding these lines to hardware.h for the T1 and compiling?

See if the RF chip works if you have some 433Mhz remotes

```
    #define RF_SUPPORT          1

    // Only used when RFB_DIRECT=1
    #define RFB_RX_PIN          4
    #define RFB_TX_PIN          5

    // When using un-modified harware, ESPurna communicates with the secondary
    // MCU EFM8BB1 via UART at 19200 bps so we need to change the speed of
    // the port and remove UART noise on serial line
    #if not RFB_DIRECT
    #define SERIAL_BAUDRATE         19200
    #define DEBUG_SERIAL_SUPPORT    0
```

**Comment by Tofandel** [comment]
For the flashing it's not too hard and doesn't require soldering (at least if you have some stable pins)

You attach the serial pins normally and add a wire from ground to GPIO 0 on the back hold it by hand plug the usb and you can release it, if the wifi led is not flashing you are in flash mode

So you can flash from there (I use platformio)

![IMG_20190806_170328](https://user-images.githubusercontent.com/6115458/62551714-c7d34000-b86c-11e9-8899-2431e83e9054.jpg)

**Comment by DJBenson** [comment]
I actually managed to flash espurna a couple of days ago but didn't get round to updating this post. The T1 binaries are indeed compatible but I found a more fundamental issue which I should have perhaps spotted prior to ordering, our house does not have a neutral wire to the switch so this is completely useless 😄Thankfully they are cheap enough for me to not bother so much about that small fact.

**Comment by ColinShorts** [comment]
Well that sucks... I'm lucky enough to be in a new build, where the only place I didn't have a neutral was on the intermediate switches either end of the stairs or rooms with two entrances. That was easy enough to overcome with a bit of blue sheathing over one of the wires. It was the only way I was going to be able to put up an external light at the backdoor without making big holes in the ceiling/walls. :)
