### ISSUE TITLE
Sonoff TX series

### ISSUE THREAD

**Issue by Tofandel** [xoseperez/espurna#1842]
Hi, I have a question regarding sonoff switch T1 and T0

I just got my hands on the new series of T0 which doesn't have an RF chip and I will flash it with the T1 env 

It got me wondering, does espurna support the RF chip that comes with the sonoff T1/T2/T3 switch (but not the T0)? Like the RF bridge? I didn't see the entry in the hardware file but I guess it could be as simple as adding the lines and see if it works

```
    #define RF_SUPPORT          1
    #define SERIAL_BAUDRATE         19200
    #define DEBUG_SERIAL_SUPPORT    0
```

I was planning to get some T1 switch for the garage so you can turn on the light with simple click, open the garage door with long click and also open the garage door with RF

**Comment by ColinShorts** [comment]
I believe that the touch button's are connected to both the esp and the rf chip (ref: [Tasmota issue 5226](https://github.com/arendst/Sonoff-Tasmota/issues/5226#issuecomment-463860006)

It might be possible to do, but it would likely involve cutting traces and adding wires for a serial connection between the rf chip and esp module, and possibly flashing the rf chip with new firmware too.
