### ISSUE TITLE
Sonoff RF bridge ESPurna with "svalue" : "" 

### ISSUE THREAD

**Issue by electrosystems1** [xoseperez/espurna#1844]
Hi to evererybody

I ´ve got a sonoff RF bridge flashed with the last verson o ESPurna (1.13.5)

I use Domoticz and in the log I need a valid svalue to make a script of a magnetic/pir sensors

this an example of the log....

2019-08-07 17:55:30.422 MQTT: Topic: domoticz/in, Message: {"idx": 6, "nvalue": 1, "svalue": ""}
2019-08-07 17:55:30.438 Status: Warning: Expecting svalue with at least 1 elements separated by semicolon, 0 elements received (""), notification not sent (Hardware: 4 - MQTT, ID: 00082006, Unit: 1, Type: F3 - General, SubType: 29 - kWh)

The ESPurna log writes the same error...

[525780] [MQTT] Sending domoticz/in => {"idx": 6, "nvalue": 1, "svalue": ""} (PID 1)

I´m newbie in this things and I don´t know where the problem is

Many thanks to help

**Comment by mcspr** [comment]
Can you please explain why it needs svalue in particular? nvalue is there. Some Domoticz documentation on this would be helpful.
Or the issue is that we only need to send `{"idx":6,"nvalue":1}`, without svalue as empty string?

**Comment by electrosystems1** [comment]
Hi Max, thanks to answer,

I wouldlike integrate sonoff bridge with MG and PIR sensors into domoticz. The idea is to make something like a burglar alarm.
I red someone who made scripts to trigger a syren or send  mails
To make this scrips "I think" I need a svalue. 
I´m following this thread https://www.domoticz.com/forum/viewtopic.php?t=27284
I´m trying with domoticz in win 7 pc to learn/test and them on raspi

I´m no idea in programming....I copy examples to adapt to my needs...

regards



I red in domoticz and tutorials,

**Comment by mcspr** [comment]
Tasmota sends full RF code in the svalue, which we don't do. What you are receiving is a switch status, either 0 or 1, which will change when the associated RF code is received. Note that this approach means that you would need some other RF code (or pulse timer) to turn the relay off to trigger the other state.

As for code itself, ESPurna sends out all of them to the `<root>/rfin` topic:
https://github.com/xoseperez/espurna/wiki/RFBRIDGE#mqtt
And also... maybe we can add special domoticz index for just RF data? But, if domoticz can already subscribe to an arbitrary topic, this may not be needed.

**Comment by electrosystems1** [comment]
Ok Max,

Thanks so much for the support.

I will follow you say...
The espurna project is great.
