### ISSUE TITLE
Firmware for ITEAD SONOFF RE5V1C - 5V Wifi Inching/Selflock Relay Module

### ISSUE THREAD

**Issue by Guindillas** [xoseperez/espurna#1872]
There is some compatible firmware for Itead SONOFF RE5V1C - 5V Wifi Inching/Selflock Relay Module

https://www.itead.cc/sonoff-re5v1c.html

Thanks in advance

**Comment by jonferreira** [comment]
@Guindillas any luck? Wondering how you've flashed them too BTW
