### ISSUE TITLE
Do I need an environment variable to enable features (InfluxDB) with PlatformIO?  (re: Visual Studio Code)

### ISSUE THREAD

**Issue by sofakng** [xoseperez/espurna#1890]
I'm using Visual Studio Code and PlatformIO to compile espurna and it works fine.  I use the task [env:itead-sonoff-pow-r2] and it compiles without any errors.

However, I'd like to enable InfluxDB support so I need to add the build flag INFLUXDB_SUPPORT.  According to the documentation I need to set an environment variable but is there a cleaner way to do this on Windows?  I only know how to set Windows system level environment variables but I was hoping for something I can set specifically with Espurna?

What's the cleanest way to enable this (and other) features with Windows Visual Studio Code + PlatformIO and not having to modify any espurna source files?

**Comment by mcspr** [comment]
See https://github.com/xoseperez/espurna/wiki/Build-and-update-from-Visual-Studio-Code-using-PlatformIO#environment-variables-for-ota-uploads
for an example of adding environment variables to a task

As for build flags, see https://docs.platformio.org/en/latest/projectconf/section_env_build.html#src-build-flags
[PLATFORMIO_SRC_BUILD_FLAGS](https://docs.platformio.org/en/latest/envvars.html#envvar-PLATFORMIO_SRC_BUILD_FLAGS) env value is passed directly to the compiler, so you can add `-DINFLUXDB_SUPPORT=1` that way
