### ISSUE TITLE
4CH relay module ESP

### ISSUE THREAD

**Issue by z4rn0x** [xoseperez/espurna#1908]
Hello guys,
I'd like to use a 4 channels relay for my garage door, and I'm wondering if this type of equipment could work with the ESPURNA firmware: 
[https://www.aliexpress.com/item/32963978306.html?spm=a2g0o.cart.0.0.6e493c00j8HIRV&mp=1](url)
I haven't ordered it yet...

**Comment by ColinShorts** [comment]
It looks like it's using an [external chip](https://community.home-assistant.io/t/4-channel-relay-esp8266-wifi-board-working-with-esphome/120594) to drive the relays. I suspect that the RELAY_PROVIDER_STM with 4 dummy relays **_might_** just work.

**Comment by z4rn0x** [comment]
Sounds good... I ordered one, hopefully I'll be able to make it through...
