### ISSUE TITLE
LED flickering when saving settings to flash

### ISSUE THREAD

**Issue by xoseperez** [xoseperez/espurna#191]
Originally reported by: **GaelZorro1980 (Bitbucket: [GaelZorro1980](https://bitbucket.org/GaelZorro1980), GitHub: Unknown)**

----------------------------------------

Hi, I successfully flashed the last version 1.9.0 of the firmware to my Magic Home Led Controller (RGBW version) by setting esptool to DOUT mode. QIO, DIO or QOUT did not work.
When the light turns on, I can see flickering and flashes, right after it turns on and about every minute afterwards. Upon more investigation, I noticed it happens when the settings are saved to the flash. In the terminal it says "[SETTINGS] Saving".
I guess writing to the flash causes disruption with the PWM output.
Have you already seen this, is there an adjustment to make to prevent it?

**Comment by Emmegiemme** [comment]
Hello,
sorry but I'm still having this issue (flickering leds) with the latest FW 1.12.3; what am i doing wrong?
