### ISSUE TITLE
Teckin SP22 new layout

### ISSUE THREAD

**Issue by rikthefrog** [xoseperez/espurna#1912]
Hi,

I have a Teckin SP22 with a new board layout. It is the EU version and bought by Amazon the 12th of September.
![IMG_2062](https://user-images.githubusercontent.com/7111547/64926744-6609dc80-d801-11e9-9c9e-2ab357fb7753.JPG)

I'm really curios to find the pin layout. Is there any way I can check/test it?
![IMG_2067](https://user-images.githubusercontent.com/7111547/64926753-833eab00-d801-11e9-8542-6d43a4688684.jpg)

The back of the TYWE2S board looks like this 
![IMG_0257](https://user-images.githubusercontent.com/7111547/64926766-b123ef80-d801-11e9-87cb-ccda19d306c3.JPG)

This is maybe a beter layout picture.
![IMG_0254](https://user-images.githubusercontent.com/7111547/64926777-c731b000-d801-11e9-80ba-52208fee3233.JPG)

Does anyone an idea or can give me tips?

**Comment by mcspr** [comment]
Have you removed the shield from the Tuya module? The crab on the chip means it is Realtek:
https://www.realtek.com/en/products/communications-network-ics/item/rtl8710bn
And Tuya does indeed manufacture boards based on RTL8710BN too, in addition to the ESP8266, supplying manufactures with an app SDK
https://fccid.io/2ANDL-WR4/User-Manual/User-Manual-4015611 (also named WR2 and WR3)

But, we can't run espurna on Realtek hardware if that's the case :/

**Comment by Blackest-Nighthawk** [comment]
Look at this:
https://github.com/ct-Open-Source/tuya-convert/issues/269

Maybe it helps.

**Comment by chetank288** [comment]
bps101 carkit bord
