### ISSUE TITLE
NodeMCU ESP8265 Input issues

### ISSUE THREAD

**Issue by alexliit** [xoseperez/espurna#1917]
Hello

I'm flashing Espurna 1.13.5 to a NodeMCU ESP8265 dev. board with Arduino IDE.
But I'm facing strange behaviurs on when using the inputs: when use the pin, it provoke boots, flashing, factory resets. 
Only the relay (output) pin works without issues.

I did few changes to the "hardware.h" in order to match my needs
- defined NODEMCU_LOLIN
- one botton as input, with relay, at GPIO 4 (D2 on the board)
- one relay at GPIO12

This is the point where I did the changes:

 ```
   // Buttons
    #define BUTTON1_PIN         **D5** 
    #define BUTTON1_MODE        BUTTON_PUSHBUTTON ||BUTTON_SET_PULLUP 
    #define BUTTON1_RELAY       1

    // Hidden button will enter AP mode if dblclick and reset the device when long-long-clicked
    #define RELAY1_PIN          12
    #define RELAY1_TYPE         RELAY_TYPE_NORMAL

    // Light
    #define LED1_PIN            2
    #define LED1_PIN_INVERSE    1

	// ----
   #define ALEXA_SUPPORT           0
    #define I2C_SUPPORT             0
    #define SENSOR_SUPPORT          0
    #define HOMEASSISTANT_SUPPORT   0
    #define MDNS_SERVER_SUPPORT     0
    #define NTP_SUPPORT             0
    #define SENSOR_SUPPORT          0
    #define THINGSPEAK_SUPPORT      0
```
Changing input or board does not remove the issue.

Any suggestion?

Thanks!

**Comment by mcspr** [comment]
Closing via https://gitter.im/tinkerman-cat/espurna?at=5d8a6e2cc77f285fb1d7e817

```diff
-  #define BUTTON1_MODE        BUTTON_PUSHBUTTON || BUTTON_SET_PULLUP 
+  #define BUTTON1_MODE        BUTTON_PUSHBUTTON | BUTTON_SET_PULLUP 
```
