### ISSUE TITLE
SONOFF POW cant calibrate power settings

### ISSUE THREAD

**Issue by xoseperez** [xoseperez/espurna#194]
Originally reported by: **Trevor (Bitbucket: [nightone](https://bitbucket.org/nightone), GitHub: Unknown)**

----------------------------------------

I have just upgraded from 1.8.3 to 1.9.1 and I can no longer set the calibration of the POWER sensor.... I have the numbers from a mulitimeter and after filling in the values and clicking update I get a popup box that says saved... when I click on status and check MQTT I still get the old values?

The only difference between the two firmware builds is that 1.8.3 i did from the arduino IDE and uploaded though serial... 1.9.1 i cheated a bit and just downloaded your bin file and updated though the web interface.... (it wiped all the settings and I have to reconfigure from scratch)... Would that make a difference to the ability to calibrate the power?

**Comment by gibbo520** [comment]
Same problem in 1.12.4 again!
