### ISSUE TITLE
Sonoff mini switch group

### ISSUE THREAD

**Issue by JulioSDDR** [xoseperez/espurna#1976]
playing with the nightly release of the sonoff mini, i have found something weird. At the switches category, you can not select the "button" at pin 4, only the one at pin 12. If only one button is sported, maybe it should be the one at pin 4? That is the one that is exposed once the sonoff mini is installed.

EDIT:
I have just swapped the button pin vars to get my expected result:
btnGPIO0 => "4"
btnGPIO1 => "0"

Seems that the pushbutton works just fine after this changes, can someone that did not desolder his try?

**Comment by mcspr** [comment]
Switches == Relays
Also note that if you hold gpio0 low and reboot / powercycle the device, it will then reboot into boot-loader mode
