### ISSUE TITLE
small firmware package

### ISSUE THREAD

**Issue by lblabr** [xoseperez/espurna#2008]
i switched to arduino ide 1.8.10 how do i get small firmware images ? the arduino ide takes core 2.6.1, in my opinon the files are larger as before

are there any hints to have imgae sizes < 500k

i would like to have: MQTT_SUPPORT, WEB_SUPPORT, DEBUG_WEB_SUPPORT, ALEXA_SUPPORT, SCHEDULER_SUPPORT, LED_SUPPORT, BUTTON_SUPPORT, SENSOR_SUPPORT

thanks in advance

Lars

**Comment by mcspr** [comment]
Besides disabling some default modules, also see `MDNS_SERVER_SUPPORT` and `OTA_ARDUINOOTA_SUPPORT`, on latest Core it takes ~35KB by using those features. If web server is still around, OTA could be done through web or [`/upgrade`](https://github.com/xoseperez/espurna/wiki/OTA#updating-via-http)

**Comment by lblabr** [comment]
thank you very much!
how do i may switch between core libraries, depending on device ?

**Comment by mcspr** [comment]
Look up platformio env: stuff, all build configuration is easily changed with a single .ini file
At the top of ours there a comments regarding `platform = …` setting

**Comment by lblabr** [comment]
i'm working with arduino ide, are there similar settings ?
