### ISSUE TITLE
OTA with core image

### ISSUE THREAD

**Issue by lblabr** [xoseperez/espurna#2027]
i flashed my smart bulb two-step update, started with espurna core... i'm not able to update with ota and WebUI is not accessable, how do i perform the second step ?

Arduino IDE:
Authenticating...OK
20:24:11 [ERROR]: No response from device

thanks in advance

Lars

**Comment by mcspr** [comment]
No WiFi connection and no AP present too?
Have you built the espurna-core or used stable / dev release .bin?

**Comment by lblabr** [comment]
OTA did not worked with arduino ide, with espota it worked ....
