### ISSUE TITLE
BROKER_REAL_TIME=1 causes crashes in the INFLUXDB module

### ISSUE THREAD

**Issue by mcspr** [xoseperez/espurna#2044]
The problem is with POW R2, it crashes few minutes after reboot when BROKER_REAL_TIME is set to 1. In web debug i see INFLUXDB messages in every 5-6 seconds.

_Originally posted by @MihataBG in https://github.com/xoseperez/espurna/issues/1968#issuecomment-562615803_

---

90% certain this is related to the issue with ESPAsyncTCP, fixed by the https://github.com/me-no-dev/ESPAsyncTCP/commit/75c2513c57ac8415eab3670dba5c64e73090f5ee

I don't really remember why exactly I skipped the update, besides the ASYNC SSL build problem. Need to reassess this again.
Or, do things like https://github.com/xoseperez/espurna/pull/1806 and just use AsyncClient directly.

**Comment by MihataBG** [comment]
Also have a problem with INFLUXDB on "magichome-led-controller". I tried with BROKER_REAL_TIME=0 but module restart itself every time when do INFLUXDB message.

**Comment by kordian-kowalski** [comment]
Same here, enabling InfluxDB will crash a Wemos D1 mini after sending a couple of measurements.

**Comment by mcspr** [comment]
Right, previous version only sent influx message each sensor report, while BROKER_REALTIME=1 now makes it every reading.
Considering I already broke broker apart, I wonder if it is also viable to just remove REALTIME flag altogether and just have SensorReportBroker and SensorReadingBroker and make influx subscribe to report one.

Problem with SyncClient that I mentioned previously I quite random and depends on how well network behaves. But it is thoroughly broken, as discovered in the https://github.com/me-no-dev/ESPAsyncTCP/pull/115. We need to throw out old SSL stuff first though

**Comment by mcspr** [comment]
#2061 reverts to the old behaviour and sends data every report, please check again with the current `dev` build

There are also two additional changes:
- string measurements are quoted
- http request now sends multiple measurements instead of one at a time.
