### ISSUE TITLE
Compiling Older firmware fails

### ISSUE THREAD

**Issue by JHatter55** [xoseperez/espurna#2045]
I can only compile the latest firmware that isn't working with Alexa properly.  I need to be able to redefine a button on GPIO 14 on a Sonoff Basic.  I know Firmware 1.13.1 still works with Alexa but when I try to compile it I get lots of errors.  I have updated Platformio and it's libraries.  I have tried all of the version 1.13.xx firmware but they all get errors like it can't find where to download certain parts from possibly.  I can edit hardware.h and compile on 1.14.0 but then Alexa won't discover it.  Is there a way to edit a pre-built binary for this GPIO change?  I can flash that from the webpage but I need to be able to edit it first.  Or can I edit from telnet somehow for these features:

    #define BUTTON2_PIN         14
    #define BUTTON2_MODE        BUTTON_PUSHBUTTON | BUTTON_DEFAULT_HIGH
    #define BUTTON2_RELAY       0

I also just noticed that the MQTT button topic isn't updating every time the sensor goes on and off.  I only saw it update in the debug log once.  On older firmware it updates on every state change.  I'm using this device to open my garage door and have a reed switch sensor to report if the door is open or not.

UPDATE: By defining the BUTTON2_PRESS and BUTTON2_CLICK values as BUTTON_MODE_TOGGLE I got it to start publishing both button states via MQTT.  I had done this in the past on old firmware but that was 2 1/2 years ago and I didn't remember.  So I'm down to just the Alexa control problem and not being able to compile old firmware.  Alexa does accept the voice command to open the garage door it just doesn't show the button in the app to do it.  If I need to control the door remotely I can do it from the Home Assistant App.

Thanks for any assistance. I have also read where someone is trying to move Alexa control from  fauxmoESP to Espalexa which may help the current version work for me.

**Comment by mcspr** [comment]
See https://github.com/xoseperez/espurna/commit/4405b419e12d8a713fcf886ab364680db045cc53 and #1993 

Note that HomeAssistant can emulate things too:
https://www.home-assistant.io/integrations/emulated_hue/
