### ISSUE TITLE
Problems with Sonoff touch devices

### ISSUE THREAD

**Issue by tonymerce** [xoseperez/espurna#2085]
Hello, lately I have problems with the latest sonoff touch devices that I have acquired. After putting Spurna on them and signing up for home automation, homebridge, etc. they work, but every time they reset and turn on by themselves, leaving them on until I realize, I have other sonoff touch that do not have this problem. Does this problem happen to someone? Thanks in advance.

**Comment by mcspr** [comment]
*ping*
Could it be built-in RF? When button is held, it will learn any incoming 433 RF code after the beep, causing button press whenever it receives that code again. I think the on-board "reset" button removes any codes.... Or holding the button for even more time and repeating the code.

**Comment by tonymerce** [comment]
No, the ones that fail me are the touch ones, those don't have RF. I also have T1 but those don't fail. I fail 2 of 20. I will change them to see if it is solved. Thank you.
