### ISSUE TITLE
Add homekit support

### ISSUE THREAD

**Issue by xoseperez** [xoseperez/espurna#21]
Originally reported by: **Neg kel (Bitbucket: [Negativekelvin0](https://bitbucket.org/Negativekelvin0), GitHub: Unknown)**

----------------------------------------

Not trivial, but could be interesting

https://github.com/HomeACcessoryKid/ESP8266-HomeKit

**Comment by joriskdzaack** [comment]
I just found this library on GitHub. Perhaps it is of interest for this project!

https://github.com/maximkulkin/esp-homekit

**Comment by DanTheMan827** [comment]
@xoseperez was this closed by mistake?

it seems that commit auto-closed this issue

**Comment by ollieatkinson** [comment]
Apple recently open-sourced their HomeKit ADK implementation: https://github.com/apple/HomeKitADK

Will this further help the development of HomeKit support in ESPurna?
