### ISSUE TITLE
Problem after Flash "magic-home-led-controller"

### ISSUE THREAD

**Issue by xoseperez** [xoseperez/espurna#210]
Originally reported by: **Christian Schäfer (Bitbucket: [themaster999](https://bitbucket.org/themaster999), GitHub: Unknown)**

----------------------------------------

Hello i used the todo from "http://tinkerman.cat/magic-home-led-controller-espurnad/"

But i could not make the Controller work. I dont get a wlan to login into espurna and no serial Log at reboot. No Problem with my Sonoffs.

Here is my Flash log.
Bought RGB with IR at Ali:"https://de.aliexpress.com/item/16Million-colors-Wifi-RGB-RGBW-led-controller-smartphone-control-music-and-timer-mode-magic-home-wifi/32755262961.html"

**Comment by choriz80** [comment]
Hi 
I have same issue with magic home.
Firmware flash ok, after restart non wifi.
I erased and reflash with esptool with success, flash again but same result no wifi.

So i 'm a bit lost... could you help me ?

information on magicHome : Model ESP8285MOD Vendor : ESP-M2
I tried with success with Tasmota (unfortunaltly not interresting)

Regards
