### ISSUE TITLE
Sonoff Touch y Alexa

### ISSUE THREAD

**Issue by tonymerce** [xoseperez/espurna#2102]
Hi, I have a sonoff touch test device at my father's house. My father has an Alexa dot and alexa does not discover my device named COMEDOR. My question is:
To work with alexa, is it necessary to activate the mqtt broquer? Or just connecting to Wi-Fi is enough? Another question, are the devices in the alexa application of the smartphone even if you don't have alexa dot or echo?
Thanks in advance.

**Comment by mcspr** [comment]
Alexa operates through this lib, independent of MQTT:
https://bitbucket.org/xoseperez/fauxmoesp

Which allows devices to be discovered on LAN via multicast announces and handles specific HTTP requests from alexa when it wants to control it. No idea how smartphone app operates.
Also see #1904 and #1993, it may not work at all :(
