### ISSUE TITLE
Add option to connect GSM module like Sim800L

### ISSUE THREAD

**Issue by ghost** [xoseperez/espurna#2111]
Hi, it's possible to implement this feature, using tinyGSM or other implementation?
i have a lot of devices that need to work where i don't have wifi coverage.
best regards

**Comment by mcspr** [comment]
ATM one option is to use common Arduino Core API that has a generic Client class which is supposed to provide such custom connectivity option:
https://github.com/vshymanskyy/TinyGSM/blob/6770614e7633e32c0847bd0aae3fb3b380de037c/src/TinyGsmClientESP8266.h#L47
For example, ESP8266 implements WiFiClient and WiFiClientSecure based on Client.
https://github.com/esp8266/Arduino/blob/00440cd84a4ed9467de6305cb768875e09c12303/libraries/ESP8266WiFi/src/WiFiClient.h#L45

While any consumer of the Client must receive this specific custom implementation:
https://github.com/xoseperez/espurna/blob/e638aaba35dcb9c516efb13aab19856ba8a40403/code/espurna/mqtt.ino#L192
(example for PUBSUBCLIENT mqtt)

General problem with that is unlike original Arduino we do have an actual network stack running, so it is not super efficient abstraction to have. There are some developments for external Ethernet boards that integrate more closely into base WiFiClient, but I am not aware of any other drivers that will do similar thing for any other networking (GSM or any other radio):
https://github.com/d-a-v/W5500lwIP
https://github.com/esp8266/Arduino/pull/6680
