### ISSUE TITLE
Com ligar e desligar um rele pelo navegador

### ISSUE THREAD

**Issue by remruggiero** [xoseperez/espurna#2119]
Boa tarde
gostaria de saber  como ligar e desligar os contatos do rele pelo navegador, colocar o IP e o Comando para ligar e desligar o Rele.
exemplo http: //192.168.10.1/rele1xxxxxxxxxxxxxxxxxxxxxxx.
consigo fazer isso pelo Tasmota, gostaria de fazer o mesmo pelo ESPurna.
Grato pela ajuda.

**Comment by trafoman2004** [comment]
https://github.com/xoseperez/espurna/wiki/RESTAPI
