### ISSUE TITLE
Noduino, and variants (Tuya, Jinvoo, Voion, Xenon)

### ISSUE THREAD

**Issue by xoseperez** [xoseperez/espurna#212]
Originally reported by: **Seth Cohn (Bitbucket: [sethcohn](https://bitbucket.org/sethcohn), GitHub: [sethcohn](https://github.com/sethcohn))**

----------------------------------------

I bought a few items including an SM-PW702 single smart plug and a smart wifi power strip with 4 outlets and usb (4 ports).  All of these can be controlled by the many variations of software (Tuya smart, Jinvoo smart), and they all seem to be variations on Noduino boards.

The smart strip is quite nice with ability to turn all on/off, each socket on/off and all usb at once.  But really I'd prefer to run them on Espurna, like the Sonoffs I bought. (These cost a bit more, compared to just attaching a Sonoff to a strip or a single plug, but then again, to control 4+ outlets independently on same strip, the price is right).

Is there any support or plans for support of these Noduino clones?
If not, suggestions for best open source, Alexa/ifttt/etc, mqtt, supportive firmware to try?

**Comment by Zixim** [comment]
> _Original comment by_ **Seth Cohn (Bitbucket: [sethcohn](https://bitbucket.org/sethcohn), GitHub: [sethcohn](https://github.com/sethcohn))**:
> 
> https://github.com/icamgo/Noduino-iBaihe-Shield/blob/master/README.md
> 
> Lists pinouts for v2 and v1 of 5 relay board (and repo has boards,.etc)
> 
> I suspect v2 is the board in use, based on the status lights, etc.
> 
> This takes a ota firmware, I wonder if the ota methods used in other cases would work here, or.if I'd need to pop it open and use a ftdi

@xoseperez could you please explain that last phrase ?
Specifically, what do you mean with "the ota methods used in other cases"  ?
