### ISSUE TITLE
Sonoff RF bridge can read remote control with 434.42 MHZ?

### ISSUE THREAD

**Issue by ghost** [xoseperez/espurna#2125]
hi, i have remote control like this:
![image](https://user-images.githubusercontent.com/20506433/73135340-9d0ebb00-4049-11ea-8a81-2b9154b61be6.png)
![image](https://user-images.githubusercontent.com/20506433/73135342-a009ab80-4049-11ea-9190-5b8a36df5ed5.png)
i cannot read it! direct mode can resolve this? 
best regards.

**Comment by mcspr** [comment]
Have you tried https://github.com/Portisch/RF-Bridge-EFM8BB1?

**Comment by ghost** [comment]
> 
> 
> Have you tried https://github.com/Portisch/RF-Bridge-EFM8BB1?


Hi, your firmware will be read 434.42 MHZ?
if yes, i will flash it, i read datasheet for EFM8BB1, and i don't saw nothing about chip working frequency ( maybe because this chip is universal?)
my question is, if RF bridge can work for this range too?

**Comment by mcspr** [comment]
It is not specifically about the frequency, but the protocol. Only recognisable one is 3-byte PT2262 (or sort-of compatible chips like EV1527).

EFM8BB1 refers to the secondary MCU on rfbridge, it handles rf decoding / encoding and communicates with esp8266 through UART.

**Comment by trafoman2004** [comment]
sonoff rf bridge frequency is 433,92 so, no deal.
