### ISSUE TITLE
Request: Seconds in schedule

### ISSUE THREAD

**Issue by rmcbc** [xoseperez/espurna#2138]
It was nice to have seconds in schedule, for example to open shades/blinds, it takes 14 seconds to open half, so I could start at 08:00:00 and stop at 08:00:14.

Thanks for the good job.

**Comment by mcspr** [comment]
Pulse timer already does that? When:
- Schedule is set to 8:00
- `relayPulse0` set to normally off (RELAY_PULSE_OFF)
- `relayTime0` set to 14

Relay will turn on at 8:00, wait 14 seconds, and turn off.
MQTT / HTTP api also accept `/pulse/0` with seconds value to override it temporarily e.g. when relay is off, sending 10 to either endpoint will turn it on and wait 10 seconds to turn off.

Also see https://github.com/xoseperez/espurna/pull/1962#issuecomment-568948940 ?
