### ISSUE TITLE
web page doesn't save IP addresses

### ISSUE THREAD

**Issue by rmcbc** [xoseperez/espurna#2150]
With ESPURNA 1.14.2-dev the web page doesn't save the IP addresses.

I change the IP address save it, then it restarts and is back in the original.

**Comment by mcspr** [comment]
Please follow the issue template and include more info than "web page doesn't save", maybe some screenshots?

**Comment by rmcbc** [comment]
![1st](https://user-images.githubusercontent.com/16247792/74581959-d3d35380-4fad-11ea-8543-59216940ee2e.png)
![2nd](https://user-images.githubusercontent.com/16247792/74581961-d6ce4400-4fad-11ea-9b91-32bfe7087ad6.png)
![3rd](https://user-images.githubusercontent.com/16247792/74581963-d8980780-4fad-11ea-990e-068ddc9d80f5.png)
![4th](https://user-images.githubusercontent.com/16247792/74581966-da61cb00-4fad-11ea-9282-4d267486fed7.png)
![5th](https://user-images.githubusercontent.com/16247792/74581967-dc2b8e80-4fad-11ea-9c60-98d1ebbc2b71.png)
![6th](https://user-images.githubusercontent.com/16247792/74581969-dd5cbb80-4fad-11ea-93d3-b608654e05ac.png)

**Comment by rmcbc** [comment]
@mcspr above you can see the sequence, I don't know a better way to show.
Thanks.

**Comment by mcspr** [comment]
What does `get ip0` show in the Debug?

**Comment by rmcbc** [comment]
![Screenshot 2020-02-15 at 04 54 32](https://user-images.githubusercontent.com/16247792/74582106-4b55b280-4faf-11ea-8165-23e6d40a9dd1.png)

**Comment by rmcbc** [comment]
@mcspr This was after upgrading from 1.14.1 to 1.14.2-dev.

**Comment by mcspr** [comment]
I see, thanks.
What I am thinking now is when on Debug:
- `set ip0 192.168.1.9`
- `get ip0` will show `192.168.1.9`
- `reload`
- `get ip0` will show nothing
I missed settings eraser checking for hardcoded settings

**Comment by rmcbc** [comment]
This is my custom.h file:

`// -----------------------------------------------------------------------------
// -----------------------------------------------------------------------------
//                                 defaults.h
// -----------------------------------------------------------------------------
// -----------------------------------------------------------------------------

// -----------------------------------------------------------------------------
// General
// -----------------------------------------------------------------------------

// Default hostname will be ESPURNA-XXXXXX, where XXXXXX is last 3 octets of chipID
#define HOSTNAME                "SonoffBasic09"

// -----------------------------------------------------------------------------
// -----------------------------------------------------------------------------
//                                  general.h
// -----------------------------------------------------------------------------
// -----------------------------------------------------------------------------

//------------------------------------------------------------------------------
// HEARTBEAT
//------------------------------------------------------------------------------

#define HEARTBEAT_INTERVAL          900000    // 15 min. // Interval between heartbeat messages (in ms)

// Values that will be reported in heartbeat
#define HEARTBEAT_REPORT_STATUS     1
#define HEARTBEAT_REPORT_SSID       0
#define HEARTBEAT_REPORT_IP         0
#define HEARTBEAT_REPORT_MAC        0
#define HEARTBEAT_REPORT_RSSI       0
#define HEARTBEAT_REPORT_UPTIME     0
#define HEARTBEAT_REPORT_DATETIME   0
#define HEARTBEAT_REPORT_FREEHEAP   0
#define HEARTBEAT_REPORT_VCC        0
#define HEARTBEAT_REPORT_RELAY      1
#define HEARTBEAT_REPORT_LIGHT      0
#define HEARTBEAT_REPORT_HOSTNAME   0
#define HEARTBEAT_REPORT_DESCRIPTION 0
#define HEARTBEAT_REPORT_APP        0
#define HEARTBEAT_REPORT_VERSION    0
#define HEARTBEAT_REPORT_BOARD      0
#define HEARTBEAT_REPORT_LOADAVG    0
#define HEARTBEAT_REPORT_INTERVAL   0

// -----------------------------------------------------------------------------
// WEBSOCKETS
// -----------------------------------------------------------------------------

// This will only be enabled if WEB_SUPPORT is 1 (this is the default value)
#define WS_AUTHENTICATION           0           // WS authentication ON by default (see #507)

// -----------------------------------------------------------------------------
// ALEXA
// -----------------------------------------------------------------------------

// This setting defines whether Alexa support should be built into the firmware
#define ALEXA_SUPPORT               1               // Enable Alexa support by default (10.84Kb)

// This is default value for the alexaEnabled setting that defines whether
// this device should be discoberable and respond to Alexa commands.
// Both ALEXA_SUPPORT and alexaEnabled should be 1 for Alexa support to work.
#define ALEXA_ENABLED               0

//------------------------------------------------------------------------------
// GENERAL
//------------------------------------------------------------------------------

#define USE_PASSWORD            0               // Insecurity caution! Disabling this will disable password querying completely.

//------------------------------------------------------------------------------
// BUTTON
//------------------------------------------------------------------------------

#define BUTTON_DBLCLICK_DELAY       10000       // Time in ms to wait for a second (or third...) click
#define BUTTON_LNGCLICK_DELAY       11000       // Time in ms holding the button down to get a long click
#define BUTTON_LNGLNGCLICK_DELAY    12000       // Time in ms holding the button down to get a long-long click

//------------------------------------------------------------------------------
// RELAY
//------------------------------------------------------------------------------

#define RELAY_BOOT_MODE             RELAY_BOOT_SAME
#define RELAY_SYNC                  RELAY_SYNC_NONE_OR_ONE
#define RELAY_PULSE_MODE            RELAY_PULSE_NONE
#define RELAY_PULSE_TIME            0

//------------------------------------------------------------------------------
// WIFI
//------------------------------------------------------------------------------

#define WIFI_FALLBACK_APMODE        0

#define WIFI1_SSID                  "HomeWIFIP2"
#define WIFI1_PASS                  ""
#define WIFI1_IP                    "192.168.1.9"
#define WIFI1_GW                    "192.168.1.1"
#define WIFI1_MASK                  "255.255.255.0"
#define WIFI1_DNS                   "192.168.1.1"

#define WIFI2_SSID                  "HomeWIFIP1"
#define WIFI2_PASS                  ""
#define WIFI2_IP                    "192.168.1.9"
#define WIFI2_GW                    "192.168.1.1"
#define WIFI2_MASK                  "255.255.255.0"
#define WIFI2_DNS                   "192.168.1.1"

#define WIFI3_SSID                  "HomeWIFIP0"
#define WIFI3_PASS                  ""
#define WIFI3_IP                    "192.168.1.9"
#define WIFI3_GW                    "192.168.1.1"
#define WIFI3_MASK                  "255.255.255.0"
#define WIFI3_DNS                   "192.168.1.1"

#define WIFI4_SSID                  "HomeWIFIP3"
#define WIFI4_PASS                  ""
#define WIFI4_IP                    "192.168.1.9"
#define WIFI4_GW                    "192.168.1.1"
#define WIFI4_MASK                  "255.255.255.0"
#define WIFI4_DNS                   "192.168.1.1"

// -----------------------------------------------------------------------------
// WEB
// -----------------------------------------------------------------------------

#define WEB_FORCE_PASS_CHANGE       0           // Force the user to change the password if default one

// -----------------------------------------------------------------------------
// MQTT
// -----------------------------------------------------------------------------

#define MQTT_SUPPORT                1                       // MQTT support (22.38Kb async, 12.48Kb sync)


#define MQTT_ENABLED                1                       // Do not enable MQTT connection by default

#define MQTT_SERVER                 "192.168.1.220"         // Default MQTT broker address
#define MQTT_USER                   "mosquitto"             // Default MQTT broker usename
#define MQTT_PASS                   ""                      // Default MQTT broker password
#define MQTT_PORT                   1883                    // MQTT broker port
#define MQTT_TOPIC                  "espurna/{hostname}"    // Default MQTT base topic

// -----------------------------------------------------------------------------
// NTP
// -----------------------------------------------------------------------------

#define NTP_TIME_OFFSET             0           // Default timezone offset (GMT+0)

// -----------------------------------------------------------------------------
// API
// -----------------------------------------------------------------------------

#define API_SUPPORT                 1           // API (REST & RPC) support built in

// This will only be enabled if WEB_SUPPORT is 1 (this is the default value)
#define API_ENABLED                 0           // Do not enable API by default

#define API_RESTFUL                 0           // A restful API requires changes to be issued as PUT requests
                                                // Setting this to 0 will allow using GET to change relays, for instance

// -----------------------------------------------------------------------------
// -----------------------------------------------------------------------------
//                                  hardware.h
// -----------------------------------------------------------------------------
// -----------------------------------------------------------------------------

// -----------------------------------------------------------------------------
// Configuration HELP
// -----------------------------------------------------------------------------
//
// MANUFACTURER: Name of the manufacturer of the board ("string")
// DEVICE: Name of the device ("string")
// BUTTON#_PIN: GPIO for the n-th button (1-based, up to 4 buttons)
// BUTTON#_RELAY: Relay number that will be bind to the n-th button (1-based)
// BUTTON#_MODE: A mask of options (BUTTON_PUSHBUTTON and BUTTON_SWITCH cannot be together)
//   - BUTTON_PUSHBUTTON: button event is fired when released
//   - BUTTON_SWITCH: button event is fired when pressed or released
//   - BUTTON_DEFAULT_HIGH: there is a pull up in place
//   - BUTTON_SET_PULLUP: set pullup by software
// RELAY#_PIN: GPIO for the n-th relay (1-based, up to 8 relays)
// RELAY#_TYPE: Relay can be RELAY_TYPE_NORMAL, RELAY_TYPE_INVERSE, RELAY_TYPE_LATCHED or RELAY_TYPE_LATCHED_INVERSE
// LED#_PIN: GPIO for the n-th LED (1-based, up to 8 LEDs)
// LED#_PIN_INVERSE: LED has inversed logic (lit when pulled down)
// LED#_MODE: Check types.h for LED_MODE_%
// LED#_RELAY: Linked relay (1-based)
//
// Besides, other hardware specific information should be stated here

// -----------------------------------------------------------------------------
// Itead Studio boards
// -----------------------------------------------------------------------------

#if defined(ITEAD_SONOFF_BASIC)

    // Info
    #define MANUFACTURER        "ITEAD"
    #define DEVICE              "SONOFF_BASIC"

    // Buttons
    #define BUTTON1_PIN         0
    #define BUTTON1_MODE        BUTTON_PUSHBUTTON | BUTTON_DEFAULT_HIGH | BUTTON_SET_PULLUP
    #define BUTTON1_RELAY       1
    #define BUTTON1_PRESS       BUTTON_MODE_TOGGLE
    #define BUTTON1_CLICK       BUTTON_MODE_NONE
    #define BUTTON1_DBLCLICK    BUTTON_MODE_NONE
    #define BUTTON1_LNGCLICK    BUTTON_MODE_NONE
    #define BUTTON1_LNGLNGCLICK BUTTON_MODE_NONE   
  
    //  0 - No external switch or button
    //  1 - External switch (RX)
    //  2 - Button contact (RX) normaly open
    //  3 - Button contact (TX) normaly open
    //  4 - Button contact (RX) normaly open, 1K external pull up
    //  5 - Button contact (TX) normaly open, 1K external pull up
    #define EXTERNAL_BUTTON_TYPE    2


    #if EXTERNAL_BUTTON_TYPE == 1

        // External switch (type 1)
        #define BUTTON2_PIN         3 // RX 
        #define BUTTON2_MODE        BUTTON_SWITCH | BUTTON_SET_PULLUP | BUTTON_DEFAULT_HIGH
        #define BUTTON2_RELAY       1

    #endif

    #if EXTERNAL_BUTTON_TYPE == 2

        // External press button (type 2)
        // Button contact normaly open (When button pressed only PRESS event)
        #define BUTTON2_PIN         3 // RX 
        #define BUTTON2_MODE        BUTTON_PUSHBUTTON | BUTTON_DEFAULT_HIGH | BUTTON_SET_PULLUP
        #define BUTTON2_RELAY       1   
        #define BUTTON2_PRESS       BUTTON_MODE_TOGGLE
        #define BUTTON2_CLICK       BUTTON_MODE_NONE
        #define BUTTON2_DBLCLICK    BUTTON_MODE_NONE
        #define BUTTON2_LNGCLICK    BUTTON_MODE_NONE
        #define BUTTON2_LNGLNGCLICK BUTTON_MODE_NONE

    #endif

    #if EXTERNAL_BUTTON_TYPE == 3

        // External press button (type 3)
        // Button contact normaly open (When button pressed only PRESS event)
        #define BUTTON2_PIN         1 // TX 
        #define BUTTON2_MODE        BUTTON_PUSHBUTTON | BUTTON_DEFAULT_HIGH | BUTTON_SET_PULLUP
        #define BUTTON2_RELAY       1   
        #define BUTTON2_PRESS       BUTTON_MODE_TOGGLE
        #define BUTTON2_CLICK       BUTTON_MODE_NONE
        #define BUTTON2_DBLCLICK    BUTTON_MODE_NONE
        #define BUTTON2_LNGCLICK    BUTTON_MODE_NONE
        #define BUTTON2_LNGLNGCLICK BUTTON_MODE_NONE

    #endif

    #if EXTERNAL_BUTTON_TYPE == 4

        // External press button (type 4)
        // Button contact normaly open, 1K external pull up
        #define BUTTON2_PIN         3 // RX 
        #define BUTTON2_MODE        BUTTON_PUSHBUTTON | BUTTON_DEFAULT_HIGH
        #define BUTTON2_RELAY       1   
        #define BUTTON2_PRESS       BUTTON_MODE_TOGGLE
        #define BUTTON2_CLICK       BUTTON_MODE_NONE
        #define BUTTON2_DBLCLICK    BUTTON_MODE_NONE
        #define BUTTON2_LNGCLICK    BUTTON_MODE_NONE
        #define BUTTON2_LNGLNGCLICK BUTTON_MODE_NONE

    #endif

    #if EXTERNAL_BUTTON_TYPE == 5

        // External press button (type 5)
        // Button contact normaly open, 1K external pull up
        #define BUTTON2_PIN         1 // TX 
        #define BUTTON2_MODE        BUTTON_PUSHBUTTON | BUTTON_DEFAULT_HIGH
        #define BUTTON2_RELAY       1   
        #define BUTTON2_PRESS       BUTTON_MODE_TOGGLE
        #define BUTTON2_CLICK       BUTTON_MODE_NONE
        #define BUTTON2_DBLCLICK    BUTTON_MODE_NONE
        #define BUTTON2_LNGCLICK    BUTTON_MODE_NONE
        #define BUTTON2_LNGLNGCLICK BUTTON_MODE_NONE

    #endif

    // Relays
    #define RELAY1_PIN          12
    #define RELAY1_TYPE         RELAY_TYPE_NORMAL

    // LEDs
    #define LED1_PIN            13
    #define LED1_PIN_INVERSE    1

    // Non-core modules
    #define ALEXA_SUPPORT               1
    #define DOMOTICZ_SUPPORT            1
    #define HOMEASSISTANT_SUPPORT       1
    #define I2C_SUPPORT                 0
    #define SCHEDULER_SUPPORT           1
    #define SENSOR_SUPPORT              0
    #define THINGSPEAK_SUPPORT          0

#elif defined(ITEAD_SONOFF_DUAL_R2)

    #define MANUFACTURER        "ITEAD"
    #define DEVICE              "SONOFF_DUAL_R2"

    // Buttons
    #define BUTTON1_PIN         3       // Button RX on header
    //#define BUTTON1_PIN       0       // Button 0 on header
    #define BUTTON2_PIN         9       // Button 1 on header
    #define BUTTON3_PIN         10      // Physical button
    #define BUTTON1_RELAY       1
    #define BUTTON2_RELAY       2
    #define BUTTON3_RELAY       1
    #define BUTTON1_MODE        BUTTON_PUSHBUTTON | BUTTON_DEFAULT_HIGH | BUTTON_SET_PULLUP
    #define BUTTON2_MODE        BUTTON_PUSHBUTTON | BUTTON_DEFAULT_HIGH | BUTTON_SET_PULLUP
    #define BUTTON3_MODE        BUTTON_PUSHBUTTON | BUTTON_DEFAULT_HIGH

    #define BUTTON1_PRESS       BUTTON_MODE_TOGGLE
    #define BUTTON1_CLICK       BUTTON_MODE_NONE
    #define BUTTON1_DBLCLICK    BUTTON_MODE_NONE
    #define BUTTON1_LNGCLICK    BUTTON_MODE_NONE
    #define BUTTON1_LNGLNGCLICK BUTTON_MODE_NONE

    #define BUTTON2_PRESS       BUTTON_MODE_TOGGLE
    #define BUTTON2_CLICK       BUTTON_MODE_NONE
    #define BUTTON2_DBLCLICK    BUTTON_MODE_NONE
    #define BUTTON2_LNGCLICK    BUTTON_MODE_NONE
    #define BUTTON2_LNGLNGCLICK BUTTON_MODE_NONE

    #define BUTTON1_PRESS       BUTTON_MODE_TOGGLE
    #define BUTTON1_CLICK       BUTTON_MODE_NONE
    #define BUTTON1_DBLCLICK    BUTTON_MODE_NONE
    #define BUTTON1_LNGCLICK    BUTTON_MODE_NONE
    #define BUTTON1_LNGLNGCLICK BUTTON_MODE_NONE  

    // Relays
    #define RELAY1_PIN          12
    #define RELAY2_PIN          5
    #define RELAY1_TYPE         RELAY_TYPE_NORMAL
    #define RELAY2_TYPE         RELAY_TYPE_NORMAL

    // LEDs
    #define LED1_PIN            13
    #define LED1_PIN_INVERSE    1

    // Non-core modules
    #define ALEXA_SUPPORT               1
    #define DOMOTICZ_SUPPORT            1
    #define HOMEASSISTANT_SUPPORT       1
    #define I2C_SUPPORT                 0
    #define SCHEDULER_SUPPORT           1
    #define SENSOR_SUPPORT              0
    #define THINGSPEAK_SUPPORT          0

 #elif defined(ITEAD_SONOFF_4CH)

        // Info
        #define MANUFACTURER        "ITEAD"
        #define DEVICE              "SONOFF_4CH"

        // Buttons
        #define BUTTON1_PIN         0
        #define BUTTON2_PIN         9
        #define BUTTON3_PIN         10
        #define BUTTON4_PIN         14

        #define BUTTON1_MODE        BUTTON_PUSHBUTTON | BUTTON_DEFAULT_HIGH
        #define BUTTON2_MODE        BUTTON_PUSHBUTTON | BUTTON_DEFAULT_HIGH
        #define BUTTON3_MODE        BUTTON_PUSHBUTTON | BUTTON_DEFAULT_HIGH
        #define BUTTON4_MODE        BUTTON_PUSHBUTTON | BUTTON_DEFAULT_HIGH

        #define BUTTON1_RELAY       1
        #define BUTTON2_RELAY       2
        #define BUTTON3_RELAY       3       
        #define BUTTON4_RELAY       4

        #define BUTTON1_PRESS       BUTTON_MODE_TOGGLE
        #define BUTTON1_CLICK       BUTTON_MODE_NONE
        #define BUTTON1_DBLCLICK    BUTTON_MODE_NONE
        #define BUTTON1_LNGCLICK    BUTTON_MODE_NONE
        #define BUTTON1_LNGLNGCLICK BUTTON_MODE_NONE

        #define BUTTON2_PRESS       BUTTON_MODE_TOGGLE
        #define BUTTON2_CLICK       BUTTON_MODE_NONE
        #define BUTTON2_DBLCLICK    BUTTON_MODE_NONE
        #define BUTTON2_LNGCLICK    BUTTON_MODE_NONE
        #define BUTTON2_LNGLNGCLICK BUTTON_MODE_NONE

        #define BUTTON3_PRESS       BUTTON_MODE_TOGGLE
        #define BUTTON3_CLICK       BUTTON_MODE_NONE
        #define BUTTON3_DBLCLICK    BUTTON_MODE_NONE
        #define BUTTON3_LNGCLICK    BUTTON_MODE_NONE
        #define BUTTON3_LNGLNGCLICK BUTTON_MODE_NONE

        #define BUTTON4_PRESS       BUTTON_MODE_TOGGLE
        #define BUTTON4_CLICK       BUTTON_MODE_NONE
        #define BUTTON4_DBLCLICK    BUTTON_MODE_NONE
        #define BUTTON4_LNGCLICK    BUTTON_MODE_NONE
        #define BUTTON4_LNGLNGCLICK BUTTON_MODE_NONE

        // Relays
        #define RELAY1_PIN          12
        #define RELAY2_PIN          5
        #define RELAY3_PIN          4
        #define RELAY4_PIN          15

        #define RELAY1_TYPE         RELAY_TYPE_NORMAL
        #define RELAY2_TYPE         RELAY_TYPE_NORMAL
        #define RELAY3_TYPE         RELAY_TYPE_NORMAL
        #define RELAY4_TYPE         RELAY_TYPE_NORMAL

        // LEDs
        #define LED1_PIN            13
        #define LED1_PIN_INVERSE    1

        // Non-core modules
        #define ALEXA_SUPPORT               1
        #define DOMOTICZ_SUPPORT            1
        #define HOMEASSISTANT_SUPPORT       1
        #define I2C_SUPPORT                 0
        #define SCHEDULER_SUPPORT           1
        #define SENSOR_SUPPORT              0
        #define THINGSPEAK_SUPPORT          0

        #define BUTTON5_PIN         3       // Button RX on header
        #define BUTTON6_PIN         2       // IO2

        #define BUTTON5_RELAY       3       
        #define BUTTON6_RELAY       4

        #define BUTTON5_MODE        BUTTON_PUSHBUTTON | BUTTON_DEFAULT_HIGH | BUTTON_SET_PULLUP
        #define BUTTON6_MODE        BUTTON_PUSHBUTTON | BUTTON_DEFAULT_HIGH | BUTTON_SET_PULLUP

        #define BUTTON5_PRESS       BUTTON_MODE_TOGGLE
        #define BUTTON5_CLICK       BUTTON_MODE_NONE
        #define BUTTON5_DBLCLICK    BUTTON_MODE_NONE
        #define BUTTON5_LNGCLICK    BUTTON_MODE_NONE
        #define BUTTON5_LNGLNGCLICK BUTTON_MODE_NONE

        #define BUTTON6_PRESS       BUTTON_MODE_TOGGLE
        #define BUTTON6_CLICK       BUTTON_MODE_NONE
        #define BUTTON6_DBLCLICK    BUTTON_MODE_NONE
        #define BUTTON6_LNGCLICK    BUTTON_MODE_NONE
        #define BUTTON6_LNGLNGCLICK BUTTON_MODE_NONE

    #elif defined(ALLTERCO_SHELLY1)

        // Info
        #define MANUFACTURER        "ALLTERCO"
        #define DEVICE              "SHELLY1"

        // Buttons
        #define BUTTON1_PIN         5
        //#define BUTTON1_MODE        BUTTON_SWITCH
        #define BUTTON1_MODE        BUTTON_PUSHBUTTON // | BUTTON_DEFAULT_HIGH | BUTTON_SET_PULLUP
        #define BUTTON1_RELAY       1

        #define BUTTON1_PRESS       BUTTON_MODE_TOGGLE
        #define BUTTON1_CLICK       BUTTON_MODE_NONE
        #define BUTTON1_DBLCLICK    BUTTON_MODE_NONE
        #define BUTTON1_LNGCLICK    BUTTON_MODE_NONE
        #define BUTTON1_LNGLNGCLICK BUTTON_MODE_NONE

        // Relays
        #define RELAY1_PIN          4
        #define RELAY1_TYPE         RELAY_TYPE_NORMAL

        // Non-core modules
        #define ALEXA_SUPPORT               1
        #define DOMOTICZ_SUPPORT            1
        #define HOMEASSISTANT_SUPPORT       1
        #define I2C_SUPPORT                 0
        #define SCHEDULER_SUPPORT           1
        #define SENSOR_SUPPORT              0
        #define THINGSPEAK_SUPPORT          0

#endif`

**Comment by rmcbc** [comment]
If I do a Factory reset it show work, the ip0, ip1, ip2 and ip3 show be corrected but is not.

**Comment by mcspr** [comment]
I mean, can you repeat command sequence from above? Storing `ip0` value, `reload` and checking if it is still there via `get`

**Comment by rmcbc** [comment]
![Screenshot 2020-02-15 at 05 05 58](https://user-images.githubusercontent.com/16247792/74582216-00d53580-4fb1-11ea-9f0f-61698496f79d.png)
![Screenshot 2020-02-15 at 05 06 31](https://user-images.githubusercontent.com/16247792/74582218-029ef900-4fb1-11ea-9922-1c3af0f488cb.png)

**Comment by rmcbc** [comment]
@mcspr in the first screen I did the set then the get
in the second reload and get again

**Comment by mcspr** [comment]
So I see the issue then.

*Also a nice reminder that we probably should show the typed command in the webui debug log :)*

**Comment by mcspr** [comment]
cc @Tofandel , as it is somewhat related to the previous discussion related to wifi settings ui

`_wifiClean(num)` does it's thing based on the old assumption that empty setting string should be removed. The issue is when `WIFI1_SSID` is set to something, that means that `ssid0` is never created. Changing `ip0` (static IP) causes settings reload and a call to `_wifiClean()`, which sees that `ssid0` is empty and unintentionally removes `ip0` (with every other network setting index 0).
