### ISSUE TITLE
Add support for Si7021

### ISSUE THREAD

**Issue by xoseperez** [xoseperez/espurna#216]
Originally reported by: **Sven Kopetzki (Bitbucket: [TriCX](https://bitbucket.org/TriCX), GitHub: [TriCX](https://github.com/TriCX))**

----------------------------------------

Pleae add support for Itead's Sonoff Si7021 sensor:
https://www.itead.cc/wiki/Sonoff_Sensor_Si7021

The sensor is not being detected.

The sensor itself provides an I2C interface, but this interface is not routed towards the connector.
https://www.itead.cc/wiki/images/7/7c/Sonoff_Si7021_Sensor_Schematic.pdf

There is an MCU (EFM8BB10F2G-A) in between.
https://www.silabs.com/documents/public/data-sheets/efm8bb1-datasheet.pdf
The MCU is connected to the 2.5mm audio male plug connector.
Itead's wiki page named it "Single bus, data port ". Whatever this is.
It might be an UART or a 1-wire bus, but I'm not sure.

Thanks in advance!

**Comment by AlwinHummels** [comment]
What's the correct setting/build for this to work? I can't get it work on my Sonoff TH16

**Comment by xoseperez** [comment]
SI7021 is supported via the I2C interface. But Sonoff's SI7021 sensor is behind a microcontroller that makes it behave like a DHT22 so you have to enable DHT22 support, not SI7021 support and point it to GPIO14.
