### ISSUE TITLE
espurna-1.14.1-itead-sonoff-pow

### ISSUE THREAD

**Issue by ghost** [xoseperez/espurna#2171]
i take a update to espurna-1.14.1-itead-sonoff-pow.bin

Influxdb:
is not more present, removed?

NTP:
Device Current Time stay clean. Debug log writes 
> [014033] [NTP] Error: NTP server not reachable
same result for any NTP server.

Sensors:
> Save every (aggregated data to EEPROM)
what is the unit?

HASS via MQTT:
since days has frozen values in HA, don't become fresh, but debug log says to send it out
> [561168] [MQTT] Sending sonoffpow/current => 1.762 (PID 1)
> [561170] [MQTT] Sending sonoffpow/voltage => 205 (PID 1)
> [561171] [MQTT] Sending sonoffpow/power => 366 (PID 1)
> [561175] [MQTT] Sending sonoffpow/reactive => 19 (PID 1)
> [561179] [MQTT] Sending sonoffpow/apparent => 361 (PID 1)
> [561184] [MQTT] Sending sonoffpow/factor => 100 (PID 1)
> [561189] [MQTT] Sending sonoffpow/energy => 9.299 (PID 1)

Sensors:
my calibrated values for power consumpting are lost and/or reseted
eg. voltage is now 205

**Comment by mcspr** [comment]
> Influxdb: is not more present, removed?

If was never the default option. Perhaps you were using a custom built .bin before that?

> NTP: Device Current Time stay clean. Debug log writes

Existing release might have problems with slow / high latency servers. If that is not the case (server is on lan), consider switching to the platform_latest in the platformio.ini, it will use a different NTP library.

> Save every (aggregated data to EEPROM)

Energy. Existing feature is however limited, one pending issue is to correctly count kwh.

> HASS via MQTT: since days has frozen values in HA, don't become fresh, but debug log says to send it out

I think you are missing some important info about how HA works with the data. Do you have it configured to read those topics? Either through discovery or manually.
