### ISSUE TITLE
switch at adjustable temperature

### ISSUE THREAD

**Issue by ghost** [xoseperez/espurna#2179]
With a DS18B20 sensor I measure temperature and make this temperature visible in Domoticz.
Now I want to switch a relay at a pre-adjustable temperature.
Is this possible??

**Comment by mcspr** [comment]
ref https://gitter.im/tinkerman-cat/espurna?at=5e6adfb3d243a00174087203
> Max Prokhorov @mcspr March 13 04:19
@HilverinkJ see https://github.com/xoseperez/espurna/wiki/RPN-Rules#rule-execution, hope that's what you mean

**Comment by ghost** [comment]
Thanks man,
I did not activate that part until now.
That's OK.
