### ISSUE TITLE
BMP280 humidity not visible

### ISSUE THREAD

**Issue by ghost** [xoseperez/espurna#2188]
From BMP280 sensor is humidity not visible on the Status page.
How can I solve this.

![Knipsel](https://user-images.githubusercontent.com/33230021/76960966-c860a880-691c-11ea-9596-d331abd09e35.PNG)

**Comment by mcspr** [comment]
See
https://www.bosch-sensortec.com/products/environmental-sensors/humidity-sensors-bme280/
https://www.bosch-sensortec.com/products/environmental-sensors/pressure-sensors/pressure-sensors-bmp280-1.html

BM**P**280 does not have it :)

**Comment by ghost** [comment]
Sorry ordered the wrong ones (BME280). 


Op 20 mrt. 2020 om 07:06 heeft Max Prokhorov <notifications@github.com> het volgende geschreven:
