### ISSUE TITLE
Install Tasmota 8.2.0 with Tasmotizer on an Magic Home ESP-12S

### ISSUE THREAD

**Issue by Robert126** [xoseperez/espurna#2193]
I'm trying to flash my Magic Home ESP-12S RGB led driver with Tasmota 8.2.

1) I downloaded Tasmota.bin (version 8.2.0 Elliot) file from https://github.com/arendst/Tasmota/releases
2) followed installation instructions https://github.com/tasmota/tasmotizer#installation-and-how-to-run and installed Tasmotizer. 
pip3 install Tasmotizer
run Tasmotizer.py

3) Run Tasmotizer 
select port: tty.usbserial-1420
BIN file open tasmota.bin
select Backup original firmware
select Erase before flashing

4) Follow instructions https://github.com/arendst/Tasmota/wiki/MagicHome-LED-strip-controller

5) after: 
Connect the 12V power supply to MagicHome. As GPIO00 is connected to GND, board will go into flash mode. Disconnect GPIO00 after few seconds.

I'm receiving the following errors:
With tasmota-lite.bin: Failed to write to target RAM (result was 0107)
With tasmota.bin: Failed to connect to ESP8266: Invalid head of packet (0xE0)
With tasmota.bin: Failed to write compressed data to flash after seq 0 (result was C100)

Robert@Macintosh ~ % tasmotizer.py
esptool.py v2.8
Serial port /dev/tty.usbserial-1420
Connecting........_____....._____....._____....._____....._____....._____....._____
QThread: Destroyed while thread is still running
zsh: abort      tasmotizer.py
Robert@Macintosh ~ % tasmotizer.py
esptool.py v2.8
Serial port /dev/tty.usbserial-1420
Connecting........___
Chip is ESP8266EX
Features: WiFi
Crystal is 26MHz
MAC: a0:20:a6:0d:27:d0
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Auto-detected Flash size: 1MB
Erasing flash (this may take a while)...
Chip erase completed successfully in 2.9s
Compressed 591504 bytes to 410198...
QThread: Destroyed while thread is still running
zsh: abort      tasmotizer.py
Robert@Macintosh ~ % 

Hopefully someone can help me out?
Robert

**Comment by Robert126** [comment]
I changed to tasmota-lite.bin (version 8.2.0 Elliot)

Robert@Macintosh ~ % tasmotizer.py
esptool.py v2.8
Serial port /dev/tty.usbserial-1420
Connecting........_
Chip is ESP8266EX
Features: WiFi
Crystal is 26MHz
MAC: a0:20:a6:0d:27:d0
Uploading stub...
esptool.py v2.8
Serial port /dev/tty.usbserial-1420
Connecting...
Chip is ESP8266EX
Features: WiFi
Crystal is 26MHz
MAC: a0:20:a6:0d:27:d0
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Auto-detected Flash size: 1MB
Erasing flash (this may take a while)...
Chip erase completed successfully in 2.9s
Compressed 477328 bytes to 332518...

Message is:
Failed to write compressed data to flash after seq 0 (result was C100)

Any suggestions?

**Comment by mcspr** [comment]
No idea, you should probably ask on Tasmota discord instead?
