### ISSUE TITLE
Conversion from joules to kwh gives always zero

### ISSUE THREAD

**Issue by dreamfalcon** [xoseperez/espurna#2196]
Hi,

I updated all my devices to 1.14.1 and started having a problem with the Total Energy value.
In some devices if I select kWh the value is always zero. On most devices is displaying the correct decimal value.
Tried reseting the energy value, but no luck.

![image](https://user-images.githubusercontent.com/5775148/77549355-a2508080-6ea7-11ea-8cca-39592954b8d9.png)

![image](https://user-images.githubusercontent.com/5775148/77549400-b1373300-6ea7-11ea-924a-fca3f69764d8.png)

**Comment by dreamfalcon** [comment]
Rebooting the devices solved the problem.

**Comment by mcspr** [comment]
Should be fixed in dev btw. The specific issue was with decimal places and unit conversion not being properly reloaded from runtime settings.
