### ISSUE TITLE
Blitzwolf BW-SHP6 new pin for HLW8012_CF1_PIN?

### ISSUE THREAD

**Issue by oscarsan1** [xoseperez/espurna#2206]
Hi, 
I just bought a SHP6 and I have to change the HLW8012_CF1_PIN from 14 to 4 in order to get information for V and I. 
I use BLITZWOLF_BWSHPX model in hardware.h
I don't know if it is a bug or a new version of SHP6. 
After this change and calibration of V, I and P the measurements are correct. 
Before calibration V was 270v instead 236v, and power was about 15% bigger thar real power.

**Comment by mcspr** [comment]
See https://github.com/xoseperez/espurna/blob/49995d92d10b88ad7d085a587bef1c25716a5073/code/espurna/sensor.ino#L1317-L1319
You can set the runtime setting instead of rebuilding.

SHP-6 was mentioned here previously: https://github.com/xoseperez/espurna/issues/1998
