### ISSUE TITLE
Supporting the upcoming Sonoff ZigBee bridge?

### ISSUE THREAD

**Issue by Moonbase59** [xoseperez/espurna#2218]
Any plans on supporting the upcoming Sonoff ZigBee bridge? Looks like the RF bridge, seems hackable, uses EFR32MG21 chipset.

Check out https://notenoughtech.com/home-automation/sonoff/sonoff-zigbee-bridge-preview/

**Comment by mcspr** [comment]
Some discussion already happened at the #2224 , closing in favour of the other one.

Review in question does not specify it, but we assume that Itead used the same USART interface as the previous model. So, Zibgee chip talks with the ESP via EmberZ (EZSP) protocol, which is sort-of described in the public documentation
*ESP8285 tx+rx are bottom <s>left</s> right on the picture? going somewhere, not hanging? if not, it might be SPI connection* 
Referencing pdf, there is an example EmberZ host app that can talk with an arbitrary tty device. It needs SimplicityStudio install, though.

As some intermediate solution we can send raw data from the EFR32MG21 via TCP / WS / HTTP longpoll stream and do decoding elsewhere. Possibly, using some existing libraries that can work out the protocol.
