### ISSUE TITLE
Domoticz sensors invalid values

### ISSUE THREAD

**Issue by ghost** [xoseperez/espurna#2223]
![Aantekening 2020-04-14 100052](https://user-images.githubusercontent.com/33230021/79201251-0f688d80-7e38-11ea-87fe-d07d8953f974.png)
![Aantekening 2020-04-14 100053](https://user-images.githubusercontent.com/33230021/79202022-43907e00-7e39-11ea-9509-52115308ddbc.png)
![Aantekening 2020-04-14 100054](https://user-images.githubusercontent.com/33230021/79202185-818da200-7e39-11ea-9cbb-6b19ad8f33aa.png)

- BME280 Pressure, not (correct) displayed anymore (IDX 233). 
- BME280 Humidity, nvalue is integer value, in domoticz log; MQTT invalid data recieved (IDX 235).
- BME280 UV, inserted the following code:
file domoticz.ino

   ` // svalue = UV;TEMP. Temperature (only for UV subtype TFA (3), else specify 0) Don't loose the `                                        `                                                             ";0" at the end - without it Domoticz database may corrupt.`
 `   } else if (MAGNITUDE_UVI == type) {`
`        String svalue = buffer;`
 `       svalue += ";0";`
 `       domoticzSend(key, 0, svalue.c_str());`

- Switch #0/1 nvalue is 0:1 svalue is empty (IDX 218/69)

![Aantekening 2020-04-14 100055](https://user-images.githubusercontent.com/33230021/79204645-2cec2600-7e3d-11ea-914c-fa4db16203b1.png)

**Comment by mcspr** [comment]
Humidity values are mixed up :( svalue -> nvalue. domiticzSend should have values swapped, `nvalue` string first for the type and then `buffer` for the real sensor value.

Pressure thing is weird, does the `magnitudes` command output the correct value for reported & last?

**Comment by mcspr** [comment]
Or not weird at all:
https://github.com/xoseperez/espurna/blob/2dcf1b2bd80ea2474275254bec722aa8905bf6c5/code/espurna/sensor.ino#L521-L523
This part causes pressure to be between 0 and 100, thus always displaying 100. Block can be safely removed

**Comment by ghost** [comment]
OK. pressure issue solved now.

**Comment by ghost** [comment]
> Humidity values are mixed up :( svalue -> nvalue. domiticzSend should have values swapped, nvalue string first for the type and then buffer for the real sensor value.

No not in this case. You have to convert nvalue to integer.

**Comment by ghost** [comment]
> Humidity values are mixed up :( svalue -> nvalue. domiticzSend should have values swapped, nvalue string first for the type and then buffer for the real sensor value.

Not in this case.
This part is causing the trouble in both cases switch and humidity.

![image](https://user-images.githubusercontent.com/33230021/79226236-55384c80-7e5e-11ea-893e-a5b201b27216.png)

**Comment by ghost** [comment]
![InkedAantekening 2020-04-12 202616_LI](https://user-images.githubusercontent.com/33230021/79227716-9af61480-7e60-11ea-94ac-31e0ff2f418e.jpg)

**Comment by mcspr** [comment]
What is the problem with empty svalue for the switch? I though domoticz does not care about it, ignoring any sent contents and only using nvalue.

And yeah, humidity is actually in the right place. I missed my own comment above, we do things differently than every other sensor output :/
```diff
@@ -227,7 +228,7 @@ void domoticzSendMagnitude(unsigned char type, unsigned char index, double value
             HUMIDITY_DRY
         );
         char svalue[2] = {status, '\0'};
-        domoticzSend(key, buffer, svalue);
+        domoticzSend(key, static_cast<int>(value), svalue);
     // Otherwise, send char string (nvalue is only for integers)
     } else {
         domoticzSend(key, 0, buffer);
```

**Comment by ghost** [comment]
> What is the problem with empty svalue for the switch? I though domoticz does not care about it, ignoring any sent contents and only using nvalue.

Nothing, my mistake.

**Comment by ghost** [comment]
You made me happy.
