### ISSUE TITLE
ITEAD_SONOFF_RFBRIDGE compilation problem (rfbridge.cpp)

### ISSUE THREAD

**Issue by reaper7** [xoseperez/espurna#2234]
I try to compile espurna with last update https://github.com/xoseperez/espurna/pull/2228
for ITEAD SONOFF RFBRIDGE (only #define ITEAD_SONOFF_RFBRIDGE uncommented)
and I get this error message:
```
sketch\rfbridge.cpp: In function 'void _rfbSend(uint8_t*)':

rfbridge.cpp:286:24: error: '_rfbSendRaw' was not declared in this scope

     _rfbSendRaw(message);
```

Win10, Arduino IDE 1.8.12, esp8266 latest git, board Generic 8285

**Comment by mcspr** [comment]
Can you check out 1d79855b7daaee6ac94905a256c37d1a547a1bbe?

**Comment by reaper7** [comment]
it's working now 👍
