### ISSUE TITLE
Multiple Sonoff Basics can't be added to Alexa group - 1.14.1

### ISSUE THREAD

**Issue by sysgen** [xoseperez/espurna#2280]
This could be a reoccurrence of #1738.  Running 1.14.1.  Create a group, add two Sonoffs and only one appears.  Sometimes the one appears is a different device.  Cannot add two or more to the group.  Presuming its some form of less than unique id the devices are being indexed within the group set?

Can wireshark the network and packet capture discovery, etc if required.

Tx

**Comment by mcspr** [comment]
Duplicate of #1904 and #1993?
