### ISSUE TITLE
Support for Litesun LA-WF7 ?

### ISSUE THREAD

**Issue by zuberio** [xoseperez/espurna#2281]
CE Smart Home Wi-Fi Smart Plug with Energy Monitoring, 2-pack sold by Costco in Canada for $20.
https://www.costco.ca/ce-smart-home-wi-fi-smart-plug-with-energy-monitoring%2C-2-pack.product.100476838.html

Tuya Device, compatible with Tuya-Convert (if you've never paired with the app).

code/espurna/config/arduino.h:
`//#define LITESUN_LA-WF7`

code/espurna/config/hardware.h:
```
// -----------------------------------------------------------------------------
// LITESUN LA-WF7
// https://www.costco.ca/ce-smart-home-wi-fi-smart-plug-with-energy-monitoring%2C-2-pack.product.100476838.html
// -----------------------------------------------------------------------------

#elif defined(LITESUN_LA-WF7)
    // Info
    #define MANUFACTURER                "LITESUN"
    #define DEVICE                      "LA-WF7"

    // Buttons
    #define BUTTON1_PIN                 3
    #define BUTTON1_MODE                BUTTON_PUSHBUTTON | BUTTON_DEFAULT_HIGH
    #define BUTTON1_RELAY               1

    // Relays
    #define RELAY1_PIN                  14
    #define RELAY1_TYPE                 RELAY_TYPE_NORMAL

    // LEDs
    #define LED1_PIN                    13
    #define LED1_PIN_INVERSE            1
    #define LED1_MODE                   LED_MODE_FINDME_WIFI

    // HJL01 / BL0937
    #ifndef HLW8012_SUPPORT
    #define HLW8012_SUPPORT             1
    #endif
    #define HLW8012_SEL_PIN             12
    #define HLW8012_CF1_PIN             5
    #define HLW8012_CF_PIN              4

    #define HLW8012_SEL_CURRENT         LOW
    #define HLW8012_CURRENT_RATIO       21683
    #define HLW8012_VOLTAGE_RATIO       262278
    #define HLW8012_POWER_RATIO         2714640
    #define HLW8012_INTERRUPT_ON        FALLING
```

code/espurna/migrate.ino:
```
        #elif defined(LITESUN_LA-WF7)

            setSetting("board", 79);
            setSetting("ledGPIO", 0, 13);
            setSetting("ledLogic", 0, 1);
            setSetting("ledMode", 0, LED_MODE_FINDME_WIFI);
            setSetting("btnGPIO", 0, 3);
            setSetting("btnRelay", 0, 0);
            setSetting("relayGPIO", 0, 14);
            setSetting("relayType", 0, RELAY_TYPE_NORMAL);
            setSetting("selGPIO", 12);
            setSetting("cf1GPIO", 5);
            setSetting("cfGPIO", 4);
            setSetting("pwrRatioC", 21683);
            setSetting("pwrRatioV", 262278);
            setSetting("pwrRatioP", 2714640);
            setSetting("hlwSelC", LOW);
            setSetting("hlwIntM", FALLING);
```

code/platformio.ini:
```
[env:litesun-la-wf7]
extends = env:esp8266-1m-base
src_build_flags = -DLITESUN_LA_WF7

```

![IMG_20200122_130725](https://user-images.githubusercontent.com/6553824/85027514-05208380-b148-11ea-85ca-71367bda814e.jpg)
![IMG_20200122_130739](https://user-images.githubusercontent.com/6553824/85027520-05b91a00-b148-11ea-8e12-9f5e676137b8.jpg)
![IMG_20200521_131441](https://user-images.githubusercontent.com/6553824/85027522-05b91a00-b148-11ea-8628-b2cd75d9097e.jpg)
![IMG_20200521_131449](https://user-images.githubusercontent.com/6553824/85027524-0651b080-b148-11ea-8954-58c8ba7dab99.jpg)

IF you made the mistake (like me) of pairing these devices with the CE Smart Home app & also 'upgrading' the device WiFi firmware via said app (like me) - then Tuya-Convert won't work. So I measured out where to drill into the device casing in order to reach the TYWE2S: GPIO0, 3V3, GND, RX and TX pins for physical flashing.

![IMG_20200529_163632](https://user-images.githubusercontent.com/6553824/85027525-06ea4700-b148-11ea-8b9a-339cdc2232a6.jpg)
![IMG_20200529_163645](https://user-images.githubusercontent.com/6553824/85027527-06ea4700-b148-11ea-975c-f2612900d34b.jpg)
![IMG_20200529_163840](https://user-images.githubusercontent.com/6553824/85027528-06ea4700-b148-11ea-8cf5-b3a58cffa19f.jpg)
![IMG_20200530_175013](https://user-images.githubusercontent.com/6553824/85027529-06ea4700-b148-11ea-9782-3f85bb32af4b.jpg)
![IMG_20200530_175045](https://user-images.githubusercontent.com/6553824/85027531-0782dd80-b148-11ea-8745-799d27dc8d05.jpg)
![IMG_20200530_175624](https://user-images.githubusercontent.com/6553824/85027532-0782dd80-b148-11ea-8971-f29e262e356b.jpg)
![IMG_20200601_094253](https://user-images.githubusercontent.com/6553824/85027534-0782dd80-b148-11ea-84a3-cb8345667a06.jpg)
![IMG_20200601_142253](https://user-images.githubusercontent.com/6553824/85027535-081b7400-b148-11ea-8d29-4ec6ea01ab12.jpg)

**Comment by mcspr** [comment]
Thanks!

Based on https://templates.blakadder.com/ce_smart_home_LA-WF7.html, we already have something like it via SPHX_V23. Ratios for power measurement are different though.
https://github.com/xoseperez/espurna/blob/7aec0c57eb18070e08082d3feebcabea1459ab62/code/espurna/config/hardware.h#L3124-L3163
You might want to follow the button config with pull-up and disable serial output, this may cause some minor issues.

**Comment by zuberio** [comment]
Oh! Thank you! I based my config on the BLITZWOLF_BWSHPX, instead of the BLITZWOLF_BWSHPX_V23 - silly me!

**Comment by wipeout666** [comment]
Thanks @zuberio for this post, was able to recover my failed OTA flashing of my LA-WF7 without blowing up the whole case: 

![image](https://user-images.githubusercontent.com/71163149/99208334-1d93d900-278e-11eb-8605-c8053700ef16.png)

**Comment by zuberio** [comment]
@wipeout666 glad I could help!

**Comment by mcspr** [comment]
Closing via https://github.com/xoseperez/espurna/wiki/Hardware-Litesun-LA-WF7
I edited the https://github.com/xoseperez/espurna/wiki/Hardware back in June but forgot to commit images as well... Thanks!

**Comment by LexxM3** [comment]
I just wanted to say thank you for this by describing a technique that allows these plugs to be opened without destroying the case and allowing "as good as factory" resealing after flashing.

See pics attached.  The basic process (and one that can be used on many glued products) is to use a heat gun and (sacrificial) plastic guitar picks.  Hold the heat gun around 1ft from the plug so as not to burn the plastic and have patience.  Heat around the sides and on the top.  Find a slight gap on one of the two long sides and insert a fine guitar pick as a wedge.  Slide the guitar picks firmly through the gap, gradually opening up more and more of the cover.  The corners are the hardest and the key to success -- when you've slid through all 4 corners, you know it's going to work.  Reheat if needed. Once you can slide the picks all the way around, if it hasn't popped off yet, just keep on going around and apply firm pressure down -- it will pop off within a couple of passes.  I used two thicknesses of guitar picks: 0.58mm as a starter and 0.73mm as a finisher.  Once the cover is off, the PCB is just pushed out by applying pressure to the prongs against a hard surface.  Once reprogramming is finished, a little glue seals it all up.

**DO NOT PLUG INTO AC MAINS WHILE OUT OF THE CASE!!!**

![2021-02-23 16 55 05](https://user-images.githubusercontent.com/55937877/108927208-daa79400-760d-11eb-84b7-b92edcf8053e.jpg)
![2021-02-23 16 56 39](https://user-images.githubusercontent.com/55937877/108927223-ded3b180-760d-11eb-87bb-6ea418c5326b.jpg)
![2021-02-23 16 56 53](https://user-images.githubusercontent.com/55937877/108927228-e2673880-760d-11eb-893c-e700497b82cc.jpg)
![2021-02-23 16 57 30](https://user-images.githubusercontent.com/55937877/108927237-e6935600-760d-11eb-9a2c-271ae44bafbb.jpg)
![2021-02-23 16 58 10](https://user-images.githubusercontent.com/55937877/108927241-e98e4680-760d-11eb-81c7-c82237b736ff.jpg)
![2021-02-23 17 02 39](https://user-images.githubusercontent.com/55937877/108927248-ed21cd80-760d-11eb-8bc2-78ba36662054.jpg)
![2021-02-23 17 02 52](https://user-images.githubusercontent.com/55937877/108927272-f448db80-760d-11eb-86df-95eebebd36b4.jpg)
![2021-02-23 17 02 55](https://user-images.githubusercontent.com/55937877/108927367-265a3d80-760e-11eb-82b4-43b4b5b23228.jpg)
![2021-02-23 17 03 12](https://user-images.githubusercontent.com/55937877/108927375-29edc480-760e-11eb-8076-d14ab98e5c8d.jpg)
![2021-02-23 17 03 45](https://user-images.githubusercontent.com/55937877/108927384-2e19e200-760e-11eb-9164-626768ce2526.jpg)
![2021-02-23 17 04 11](https://user-images.githubusercontent.com/55937877/108927395-3245ff80-760e-11eb-883a-0f90fb39e897.jpg)
![2021-02-23 17 04 20](https://user-images.githubusercontent.com/55937877/108927399-34a85980-760e-11eb-9e69-9d881c43840a.jpg)
![2021-02-23 17 05 21](https://user-images.githubusercontent.com/55937877/108927409-36721d00-760e-11eb-92c0-6921e653cf46.jpg)
![2021-02-23 19 51 20](https://user-images.githubusercontent.com/55937877/108929030-493a2100-7611-11eb-8294-e8d66572060e.jpg)
![92811179-6522-44BE-9FA2-8E8442242F13](https://user-images.githubusercontent.com/55937877/112710237-e8169f00-8e95-11eb-98b6-dd5c73b7209c.jpeg)
![F39446D0-CA97-4E69-8F97-B8FC5E274BE0](https://user-images.githubusercontent.com/55937877/112710238-eb118f80-8e95-11eb-890c-82c57cdc56c0.jpeg)

**Comment by zuberio** [comment]
Nice! Do you also find that the button doesn't feel the same once the cover has been popped off?

**Comment by LexxM3** [comment]
> Nice! Do you also find that the button doesn't feel the same once the cover has been popped off?

That’s a good question. First, there is a trick to putting the plastic plunger back in: use tape on top of the cover to hold it by the sticky side in place against the back when installing the cover carefully back on. Second, yes, it does feel a little different, just a little less travel, but still works fine.
