### ISSUE TITLE
Feature Request: Make schedules available via REST API

### ISSUE THREAD

**Issue by sychron** [xoseperez/espurna#2288]
When using the schedule option, every change has to be done in the web interface.

Is it possible to make this function available via the rest API as well?

For example, something like
GET /API/schedule/list             get list of schedules
GET /API/schedule/{number}  get info about this schedule
PUT /API/schedule/{number}  put 0, 1 or 2 like for relays to turn schedule on or off
DELETE /API/schedule/{number}  remove schedule
POST /API/schedule/{number}  add new schedule

data could look like

time: string in format hh:mm like n web interface
days: string of numbers like in web interface
utc: 0 or 1
state: 0 or 1
relay: number of relay to affect
switch: 0, 1 or 2 (switch relay to ...)

**Comment by mcspr** [comment]
> When using the schedule option, every change has to be done in the web interface.

Not necessarily true, as you can change the corresponding settings key-values. Check out:
- [\<host\>/config](https://github.com/xoseperez/espurna/wiki/Configuration#direct-http-settings-api)
- `keys` command in the [terminal](https://github.com/xoseperez/espurna/wiki/Terminal)

/config will instantly reload the schedule configuration, terminal's `set key value` command needs a `reload` right after
