### ISSUE TITLE
Feature request for tuya-convert users. 

### ISSUE THREAD

**Issue by tonyfitzs** [xoseperez/espurna#2307]
First let me say, I really love what you have done here fantastic project great work! But I would like to make a request to help support those of us who are using tuya-convert (which is a large community). 

One of the challenges we face using the tuya based hardware is the hardware is built to a budget and can sometimes have unknown faults. Because the process to install Espurna using tuya-convert recommends NOT initially connecting the unit to the Tuya app as this may make it impossible to update, you don’t discover any issues until it’s too late and have installed the new firmware.

The problem then is you can not return the device under warrantee because it no longer has the original firmware. So you need to roll the firmware back first. The only method I have seen to do this is not helpful in the use case I am describing because it relies on the user rolling back the original dumped firmware via a serial connection.

The challenge here is that not all the Tuya devices allow you to do this easily, so you may need to modify the internal circuit board (at least solder some connections) to achieve this. The problem here is that just as upgrading the firmware makes it challenging to return, modifying the hardware is even worse. 

So this got me thinking. It would be great if there were a way to install OTA a firmware stub that doesn’t do anything other than allow tuya-convert to connect to the device.

**To add to this because it may not be as clear as I hoped it would be.** 

I have also sent more or less the same request to tuya-convert as well as to Tasmota, so let me try to explain more clearly why this is a correct request for the firmware side and not the firmware delivery side. 

Based on the title, my request could be interpreted as only relating to tuya-convert. Tuya-convert is a firmware delivery process, whereas both Tasmota and ESPurna are actually firmware. 

For what I am suggesting to work, it would require a change on the firmware side. **Not** so much the firmware delivery side. That's because my suggestion only impacts tuya devices that **ALREADY** have Tasmota or ESPurna firmware installed, and the only way to roll them back would be to re-apply the firmware via serial connection or some type of OTA method. 

What I am requesting is a very small firmware package that has the bare minimum code to enable a tuya device to boot up in pair mode to allow tuya-convert to connect so you can re-deploy the original firmware. 

I hope that is more clear. Just in case a member of the development community is tempted to close this request without fully understanding it.

So what I mean in more detail. After updating the device to Espurna, you use OTA support to load a firmware shell onto the device that just turns on the WIFI pair mode the same as if it was getting ready to receive the firmware from tuya-convert. 
Then in tuya-convert, you connect to the device but rather than deploy Tasmota you use the original dump file to send back to the device. This would effectively enable the capability to re-flash the OG firmware OTA thereby solve the challenge of what to do when you need to roll back the firmware for any reason. 

I would love to help out in any way I can, but I would not have a clue where to start. Thanks for your indulgence.

**Comment by mcspr** [comment]
I believe this was already answered in the https://github.com/ct-Open-Source/tuya-convert/issues/707
Unless we could run such intermediate firmware with WiFi drivers purely from IRAM...
