### ISSUE TITLE
Create a metrics page for prometheus scraping

### ISSUE THREAD

**Issue by weikinhuang** [xoseperez/espurna#2323]
**Is your feature request related to a problem? Please describe.**
I would like to be able to have prometheus scrape metrics of my IOT devices such as outlets' power usage.

**Describe the solution you'd like**
Present a page that can be enabled that would output all stats available for prometheus to scrape.

**Describe alternatives you've considered**
Right now I have a node server that aggregates all the api calls that are available for reading power, voltage, total kw since power on, etc and formats them into a prometheus scrape-able format.

Since I am already running the infrastructure for prometheus, I would like to avoid having another datasource that I have to manage (like influxdb).

**Additional context**
Example dashboards that can be built if metrics can be ingested easily:

![image](https://user-images.githubusercontent.com/794658/90303364-73996d80-de7b-11ea-8e9b-3cc725e6d653.png)

**Comment by mcspr** [comment]
Can you share the adapter layer? What format is required, exactly?

Also note that after https://github.com/xoseperez/espurna/commit/f3c185cc7367ed6cf3cef0887a7d5dc01acea197 you can call `/magnitudes?apikey=...` which will dump tuples of `["magnitude-name", last-reading, last-report]`. I am not attached to the scheme used there

**Comment by weikinhuang** [comment]
The output should look like this, the proxy server is just a simple node app that makes use of the prometheus lib, and a few http requests

```
# HELP espurna_relay0 Relay 0 is on
# TYPE espurna_relay0 gauge
espurna_relay0 1

# HELP espurna_current The current (A)
# TYPE espurna_current gauge
espurna_current 2.012

# HELP espurna_voltage The voltage (V)
# TYPE espurna_voltage gauge
espurna_voltage 120

# HELP espurna_power Real power usage (W)
# TYPE espurna_power gauge
espurna_power 225

# HELP espurna_reactive Volt Amp reactive power
# TYPE espurna_reactive gauge
espurna_reactive 92

# HELP espurna_apparent The magnitude of complex power
# TYPE espurna_apparent gauge
espurna_apparent 241

# HELP espurna_factor The ratio of active power to apparent power
# TYPE espurna_factor gauge
espurna_factor 92

# HELP espurna_energy Total energy usage since boot (kWh)
# TYPE espurna_energy counter
espurna_energy 577.722
```

The documentation is located here, https://prometheus.io/docs/instrumenting/writing_exporters/ but the general idea is:
```
# Description
# Data type
name{label=foo} VALUE
```

**Comment by weikinhuang** [comment]
The `HELP` and `TYPE` comments are optional

**Comment by mcspr** [comment]
So the plan is to add:
- `<host>:80/metrics` endpoint
- endpoint handler that gathers relays + sensors (+ other relevant info?) as `<name> <space> <value>`
backbone sort of like the existing Homeassistant discovery (see HASS in WebUI and generate cfg as an example), but with up-to-date data

Do we need `espurna_...` prefix, or have it configurable / at all?
Suffixes are weird, too, if prefixes are used - we need some other name for `MAGNITUDE_COUNT` b/c we will use the built-in name `"count"`

**Comment by weikinhuang** [comment]
no prefix needed, that's totally optional, it doesn't need to be configurable, as prometheus usually adds additional labels to the data

**Comment by mcspr** [comment]
Just got around to do this. See #2332
Everything seems to work with the test Prometheus instance.

I'll need to dig a bit deeper for the proper support of decimal places, right now it's just up to .000

*edit:* Also, missing HTTP auth / api_key / etc.
Mainly, b/c I can't seem to find any mention of it in the Prometheus docs. Not sure if this matters that much, though

**Comment by weikinhuang** [comment]
prometheus supports query params https://prometheus.io/docs/prometheus/latest/configuration/configuration/ via `params:`

**Comment by mcspr** [comment]
Meaning, like this?
```yaml
scrape_config:
  - job_name: 'espurna'

    basic_auth:
      username: 'admin'
      password: 'fibonacci'

    static_configs:
      - targets: ['192.168.4.2:80']
```
Or, for API
```yaml
scrape_config:
  - job_name: 'espurna'
    metrics_path: '/api/metrics'
    params:
      apikey: ['1234567890']

    ...
```

idk why Prometheus docs give me such a hard time, sry for *dumb* statements :)

**Comment by weikinhuang** [comment]
correct
appreciate you taking the time to add this feature though!

**Comment by weikinhuang** [comment]
Thanks @mcspr!

**Comment by mcspr** [comment]
Mini update in dev, latest commit adds additional check for initial values on device boot so it does not report them as nan / 0.0 and wait until they switch to numeric value.
Also note that values are based on `apiRealTime` setting:
- when `0` it returns latest reading
- when `1` - latest 'report' (i.e. filtered value, based on the `snsReport` counter)
