### ISSUE TITLE
Cron to work for 2 minutes and stop every 5 minutes

### ISSUE THREAD

**Issue by naal71** [xoseperez/espurna#2336]
Hello, I was looking in issues but i didnt found anything...

The question is very simple.
Its to control a motor that pumps water. I want to make a cronjob that switch on every 5 minutes the motor but switch off when the motor when is working for 2 minutes.

The reason is because I dont want tu burn the motor.

Thanks in advance.

**Comment by mcspr** [comment]
Existing scheduler only works with fixed wall clock time and does not support something like cron */5 syntax or similar. Plus, you need to depend on relay status, not sure what configuration would achieve that 🤔 

However, we do have these:
https://github.com/xoseperez/espurna/wiki/RPN-Rules, `-DRPN_RULES_SUPPORT=1` and see Rules panel / add these keys manually.

RPN rules are stack based and are executed whenever we have updated variables (starting with `$`, or something triggers it manually in the code). Expressions are read left-to-right, token is either added to the stack as number / boolean / string or executes some sort of function. For example:
```
> rpnRule0 => "$relay0 end 5000u oneshot_ms 2 0 relay"
> rpnRule1 => "$relay0 not end 10000u oneshot_ms 2 0 relay"
```
- `$relay0` reads the status of relay 0, which updates every relay change
- `end` reads top of the stack as boolean and stops the rule when token resolves to `false`
- `relay` accepts status as int, 2 means toggle and 0 is the relay ID
- `oneshot_ms` starts a timer when encountered. Assuming the left-most part of the expression remains true and `end` does not quit it, when timer expires we toggle the relay

So we end up with a system which toggles between $relay0 true or false lines, setting a one-shot timer each time to toggle relay into the other state. When $relay0 is ON, we wait 5seconds and toggle it OFF. When OFF, we wait 10 seconds and toggle.
