### ISSUE TITLE
How to use custom libraries and show sensor data on display, serial, and send via MQTT.

### ISSUE THREAD

**Issue by vdj69** [xoseperez/espurna#2358]
**Question**
I need your help to understand how to add custom libraries and where to write code for using it. For example, I want to add an LCD library and i2c based sensor library then I want to fetch the I2c sensor data and show the data to the LCD and serial. At last, send the data via MQTT? 

**Device information**
ESP8266-E

* *Desktop operating system*
Windows10

* *Browser & version*
Chrome

* *IDE & version*
PlatformIO

**Comment by mcspr** [comment]
Check out:
https://github.com/xoseperez/espurna/issues/2345#issuecomment-691596745
https://github.com/xoseperez/espurna/blob/dev/code/espurna/sensors/DummySensor.h

*edit:* for the display part, perhaps see https://github.com/xoseperez/espurna/pull/2319
thermostat is a rough approach. but, you can also check out how [domoticz integration works with the sensor data](https://github.com/xoseperez/espurna/blob/1d895d98b801baf5cba6b2c876589ad63e177a50/code/espurna/domoticz.cpp#L217)
