### ISSUE TITLE
Sonoff Pow R2 Switch problem

### ISSUE THREAD

**Issue by NakkeNakuttaja** [xoseperez/espurna#2371]
When Pow R2 lose connection router it cut to power on relay and same happens when push reboot button. Boot mode is "Locked ON" and On MQTT disconnect is "Don't Change" I tryed every options and no difference. ESPurna version is 1.14.1

**Comment by mcspr** [comment]
Note of the template, `info` would've shown the crash exception :/
Based on the previous issues like https://github.com/xoseperez/espurna/issues/1236 should be fixed with development builds.
