### ISSUE TITLE
Question LSC Filament A60 Dimmable Bulb espurna firmware 

### ISSUE THREAD

**Issue by erwinjong** [xoseperez/espurna#2374]
i cannot find anything about LSC lightbulb but do see the LSC LCD strip is supported.
Is there perhaps a generic firmware that would fit for this LSC lightbulb ?

GPIO12PWM2
GPIO14PWM1

{"NAME":"LSC Filam E27","GPIO":[0,0,0,0,0,0,0,0,38,0,37,0,0],"FLAG":0,"BASE":18}

**Comment by mcspr** [comment]
Check out https://github.com/xoseperez/espurna/blob/dev/code/espurna/config/hardware.h
https://github.com/xoseperez/espurna/blob/aebefdf941b30d3db57c1dda4f2a2f7ea8e9d8c4/code/espurna/config/hardware.h#L4011-L4028
I believe this matches the template.

You can use this specific pre-build .bin or any other one that includes `LIGHT_PROVIDER_DIMMER` and override GPIOs at runtime by setting `ltDimmerGPIO0`, `ltDimmerGPIO1` and `ltDimmerGPIO2` to the `12`, `14` and `153` respectively (last one means 'NONE' to avoid setting any other pins, but the first 2)
There's also a brief explanation for buttons & switches here -> https://github.com/xoseperez/espurna/wiki/Buttons-and-switches#tasmota-templates, but it does not include lights atm. Will need to update that to include lights though
