### ISSUE TITLE
Sinric Google Home Integration

### ISSUE THREAD

**Issue by ronaldocb** [xoseperez/espurna#2376]
How about implementing Sinric (https://github.com/kakopappa/sinric/wiki) integration for Google Home? The device is being detected by the Google Home App easily.

**Comment by mcspr** [comment]
The most up-to-date code seems to be in Sinricpro, from the same developers?
https://github.com/kakopappa/sinric/issues/369
https://github.com/sinricpro/esp8266-esp32-sdk
https://sinricpro.github.io/esp8266-esp32-sdk/

Feel free to submit a PR!

(and it also worth noting of #846, although sinric support can also work with alexa)
