### ISSUE TITLE
How to package html files in binary file to release?

### ISSUE THREAD

**Issue by Caffreyfans** [xoseperez/espurna#2380]
*Before creating a new issue please check that you have:*

* *searched the existing [issues](https://github.com/xoseperez/espurna/issues) (both open and closed)*
* *searched the [wiki](https://github.com/xoseperez/espurna/wiki)*
* *asked for help in the [chat](https://gitter.im/tinkerman-cat/espurna)*
* *done the previous things again :)*

*Fulfilling this template will help developers and contributors help you. Try to be as specific and extensive as possible. If the information provided is not enough the issue will likely be closed.*

*You can now remove this line and the above ones. Text in italic is meant to be replaced by your own words. If any of the sections below are not relevant to the issue (for instance, the screenshots) then you can delete them.*

**Question**
*A clear and concise description of what the problem/doubt is.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Device information**
*Copy-paste here the information as it is outputted by the device. You can get this information by typing `info` via serial, terminal or in the debug tab in the web UI. The relevant information is that surrounded by the scissors-cut lines (`---8<-------`).*
*If you cannot get this info from the device, please answer this questions:*
* *Arduino Core version*
* *ESPurna version*
* *Flash mode*
* *Device brand, model and version*

**Tools used**
* *Desktop operating system*
* *Browser & version*
* *IDE & version*
* *Compiler & version (if not embedded in IDE)*

**Additional context**
*Add any other context about the problem here.*
Hi espurna author:
    I want to learn use html template for UI. I'm trying to make binary file like yours, but I have no idea how to realize it. Would you share how do you do?

**Comment by Caffreyfans** [comment]
Related discussions have been found(#455)

**Comment by mcspr** [comment]
There's also a brief description at the wiki:
https://github.com/xoseperez/espurna/wiki/WebInterface#web-interface-build-process
The whole process is done via gulpjs:
https://github.com/xoseperez/espurna/blob/dev/code/gulpfile.js
