### ISSUE TITLE
Product compatibility.

### ISSUE THREAD

**Issue by alvinstarr** [xoseperez/espurna#2382]
I just reflashed a litesun LQ-2-W3  and  appears to work with litesun-la-wf3.bin
It has not been an exhaustive test but I can control the power plug.

**Comment by mcspr** [comment]
Added to the https://github.com/xoseperez/espurna/wiki/Hardware page as https://github.com/xoseperez/espurna/wiki/Hardware-Litesun-LQ-2-W3
If you happen to have any photos, product-pages, urls related to the device, pls update the linked page!
(images can be drag-n-dropped here to preserve URLs at githubuserfiles)
