### ISSUE TITLE
Web Interface BACKUP options not bringing all configured switches

### ISSUE THREAD

**Issue by romrp** [xoseperez/espurna#2384]
Hello,

Created a binary with platformIO with my configuration for a NodeMCU with a 4 port relay attached to it. The switches work. When downloading the BACKUP to modify it, only part of the switches are shown.

My general.h file had the following options:

#elif defined(NODEMCU_LOLIN)

    // Info
    #define MANUFACTURER        "NODEMCU"
    #define DEVICE              "LOLIN"

    // Buttons
    #define BUTTON1_PIN         0
    #define BUTTON2_PIN         9
    #define BUTTON3_PIN         10
    #define BUTTON4_PIN         14
    #define BUTTON1_CONFIG      BUTTON_PUSHBUTTON | BUTTON_DEFAULT_HIGH
    #define BUTTON2_CONFIG      BUTTON_PUSHBUTTON | BUTTON_DEFAULT_HIGH
    #define BUTTON3_CONFIG      BUTTON_PUSHBUTTON | BUTTON_DEFAULT_HIGH
    #define BUTTON4_CONFIG      BUTTON_PUSHBUTTON | BUTTON_DEFAULT_HIGH
    #define BUTTON1_RELAY       1
    #define BUTTON2_RELAY       2
    #define BUTTON3_RELAY       3
    #define BUTTON4_RELAY       4

    // Hidden button will enter AP mode if dblclick and reset the device when long-long-clicked
    #define RELAY1_PIN          12
    #define RELAY2_PIN          5
    #define RELAY3_PIN          4
    #define RELAY4_PIN          15

    #define RELAY1_TYPE         RELAY_TYPE_NORMAL
    #define RELAY2_TYPE         RELAY_TYPE_NORMAL
    #define RELAY3_TYPE         RELAY_TYPE_NORMAL
    #define RELAY4_TYPE         RELAY_TYPE_NORMAL

    // Light
    #define LED1_PIN            2
    #define LED1_PIN_INVERSE    1

**BUG:** When I download the backup file, it shows only part of the switches:

{
"app": "ESPURNA",
"version": "1.15.0-dev",
"backup": "1",
"timestamp": "2020-10-19 08:10:24",
"adminPass": "***SECRET***",
"boardName": "NODEMCU_LOLIN",
"btnGPIO0": "0",
"btnGPIO1": "9",
"btnRelay0": "0",
"btnRelay1": "2",
"cfg": "5",
"hostname": "ESPURNA-D6569B",
"ledGPIO0": "2",
"ledInv0": "1",
"ledMode0": "1",
"ledRelay0": "0",
"ntpTZ": "CST3",
"pass0": "***SECRET***",
"relayGPIO0": "12",
"relayGPIO1": "5",
"relayType0": "0",
"relayType1": "0",
"ssid0": "***SECRET***",
"timestamp": ""
}

Thank you,

Rom

**Comment by mcspr** [comment]
Settings in the current form are an overlay on top of the build-time flags, JSON output does not include things that are not from the settings data store.
