### ISSUE TITLE
Control Device LED by MQTT

### ISSUE THREAD

**Issue by tita2000** [xoseperez/espurna#2386]
Hello,

instead of having the LED controlled by Wifi status or find me, etc., it would be great to be able to control the LED by MQTT topic e.g. EPURNA-XYNNZ/led. Paylod 1 for LED on and paylod 0 for LED off.

Regards Timo

**Comment by ColinShorts** [comment]
It already does. [See the wiki for details.](https://github.com/xoseperez/espurna/wiki/MQTT#leds)

**Comment by tita2000** [comment]
Thank you, I have been not aware of this feature. Closed.
