### ISSUE TITLE
BME680 support

### ISSUE THREAD

**Issue by Schwenkner** [xoseperez/espurna#2402]
First let me explain somethibg. I like espurna a lot. Unfortunately I'm missing some features. Thats why I implemented them by my own. Therefore I "adopted" your code allmost. And I also use Visual Micro plugin to Visual Studio to develope, I feel more  comfortable with that.

All the sensors I currently use, I have  rewritten. They work fine. But now I'm trying to adopt the BME680. Is this sensor for you already working? I know it is new integrated.

In the code ther is something like:
const uint8_t bsecConfigIaq[] = { 0
  #if BME680_BSEC_CONFIG == BME680_BSEC_CONFIG_GENERIC_18V_3S_4D
    #include <config/generic_18v_3s_28d/bsec_iaq.txt>

But the include files, i.e. <config/generic_18v_3s_28d/bsec_iaq.txt> are not within the repositiory. here on github.

Nevertheless this is not my real problem.
As soon as I add some function calls to bsec, like "iaqSensor.run()" from your code, I get a linker error:
MyScetch.ino.elf section .text will not fit in region iram1_0_seg
I'm compiling for WEMOS D1 mini Pro.

Do you have any hint for my how to solve thsi error?

**Comment by mcspr** [comment]
IAQ config files are from the BSEC library, see it's source dir.
Related to the link error, see: https://community.bosch-sensortec.com/t5/MEMS-sensors-forum/BSEC-library-installation-instructions-for-ESP8266/td-p/14862 for the explanation. Currently released version seems to incorporate the changes, we still use the version that was available when the BME code was added and patch it via https://github.com/xoseperez/espurna/blob/dev/code/scripts/espurna_utils/libalgobsec.py script per environment.
