### ISSUE TITLE
Sonoff POW non persistent after power outage

### ISSUE THREAD

**Issue by pcornill** [xoseperez/espurna#2407]
With Espurna 1.15.0 Sonoff POW R1
I have setup the autosave to 5 reports. Saving is working and restore works after reboot 
BUT NOT after power outage (unplug / plug power) where it resets the Energy.

**Comment by pcornill** [comment]
Anyone with the same issue? Is it a bug or designed that way?

**Comment by mcspr** [comment]
Does it work after this change?
```diff
diff --git a/code/espurna/sensor.cpp b/code/espurna/sensor.cpp
index a8d73272..9261879b 100644
--- a/code/espurna/sensor.cpp
+++ b/code/espurna/sensor.cpp
@@ -2284,6 +2284,7 @@ void _sensorReport(unsigned char index, const sensor_magnitude_t& magnitude) {

 void _sensorInit() {

+    _sensor_save_every = getSetting("snsSave", SENSOR_SAVE_EVERY);
     _sensors_ready = true;

     for (auto& sensor : _sensors) {
```

**Comment by pcornill** [comment]
Thanks for the suggestion but I'm on windows.
Is there a way to have a binary of the latest version?
The one available is 1.14.1 and is one year old.
Maybe I do not set the right parameters in config files?

Otherwise, if you can tell me what needs to be replaced in sensor.cpp?

Thanks for the great support.

________________________________

**Comment by mcspr** [comment]
> Otherwise, if you can tell me what needs to be replaced in sensor.cpp?

Just find the `_sensorInit()` func and insert:
```cpp
    _sensor_save_every = getSetting("snsSave", SENSOR_SAVE_EVERY);
```
at the start of it.

Result should look like the snippet above
(Without the `+`. It is there only to signify the 'addition' of the line to the file)

**Comment by pcornill** [comment]
It was already there ! But I still have the same issue. The saved energy is lost after power outage


________________________________

**Comment by pcornill** [comment]
My issue is not fixed!

________________________________

**Comment by mcspr** [comment]
Have you tried current build?

**Comment by pcornill** [comment]
Crurent build I tried is 1.14.2. Is that the latest? It is one year old

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mcspr** [comment]
Message above reads:
> With Espurna 1.15.0 Sonoff POW R1

So is it 1.14.2 or 1.15.0? 1.15.0 is the current development version, my assumption was that you built it yourself. I see the energy restored with a test device
You can wait for nightly (but it may not be available atm) or build yourself, just see the wiki for instructions

**Comment by mcspr** [comment]
Just in time :) sry for delays

I also wanted to point out that Adafruit's neopixel lib might not be the most efficient one on the platform, you might want to check out either:
- https://github.com/FastLED/FastLED
- https://github.com/Makuna/NeoPixelBus

esp8266 code in the Adafruit was not really updated in any way since 2015

**Comment by pcornill** [comment]
I tested both. The dev load with all default settings except the device type set to POW

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by mcspr** [comment]
But can you try again with the version that was just pushed?
https://github.com/xoseperez/espurna/commit/f166f6c7929108664d539f93a0da3e3fe0df36fa

**Comment by pcornill** [comment]
You can close the issue, IT WORKS!
Thanks a lot

________________________________
