### ISSUE TITLE
POSIX TZ variable for NTP differs from Wiki.

### ISSUE THREAD

**Issue by davebuk** [xoseperez/espurna#2418]
I have been updating a lot of my devices and noticed the NTP section changed a while ago for the time zone setting. A lot of my devices currently show: `CET0CEST,M3.5.0,M10.5.0/3`. Looking at: https://github.com/xoseperez/espurna/wiki/NTP I set: `
#define NTP_TIMEZONE TZ_Europe_London` to one of my build settings. I thought this should change the time zone to: `GMT0BST,M3.5.0/1,M10.5.0`. I can put that time zone data in manually and espurna gets the correct time, but I wanted to specify it correctly in my `custom.h` builds

**Comment by mcspr** [comment]
This must be part of the conversion happening here:
https://github.com/xoseperez/espurna/blob/8e659c94867bc41473ccbc45ff269f63fbd36721/code/espurna/ntp.cpp#L350-L399

If either of `ntpOffset`, `ntpDST` or `ntpRegion` are found in settings, it will construct a `ntpTZ` value based on those + old defaults for the NTP configuration and override the existing setting. `del ntpTZ` should restore the build-time default after the reboot, but I guess it should not overwrite the existing `ntpTZ` value (can't check for build-time though due to the way settings work with custom.h)

**Comment by davebuk** [comment]
I'll try a loading a build to a factory reset device and check it loads the correct values.

**Comment by davebuk** [comment]
https://github.com/xoseperez/espurna/pull/2414#issuecomment-763968914

The NTP server has always worked and been set to the default, but after loading a firmware and defining the time zone in the `custom.h`, the server address has been cleared. I can manually put it back in and it saves.

**Comment by mcspr** [comment]
Current dev now includes these:
https://github.com/xoseperez/espurna/commit/c179467be27b4af990121ee22b6d95001cca61f0
https://github.com/xoseperez/espurna/commit/e8e58b821c88c9dac5bca41a40bb54b83a8b9923

Which should:
- avoid removing existing `ntpTZ` when old cfg vars are detected. I wonder though what is better - somewhat broken conversion (note the transition hour specified after the `/`, when missing default is 2:00) or just remove old settings and use build default, forcing to convert manually through TZ.h
- detect bad values from DHCP and disabling this feature via `ntpDhcp` setting (although, idk if it was just empty ntpServer?)
- detect changes to both tz and server settings

**Comment by davebuk** [comment]
After clearing out the `Time Zone` data from webUI and building my tuya dimmer device using `#define NTP_TIMEZONE			TZ_Europe_London` after boot, NTP keys still show: 
```
> ntpServer => "pool.ntp.org"
> ntpTZ => ""
```

**Comment by mcspr** [comment]
That's a weird one. WebUI sets the key to an empty string instead of deleting.

**Comment by mcspr** [comment]
...which was always the case for the web? I don't think I changed that between 1.14.0 and now (at least I hope so, can't find any `delSetting` in the web source code history). Technically, the expected 'erase-all' interaction is factory reset, which will erase the settings storage forcing each module to use build-time flags as defaults

**Comment by davebuk** [comment]
A full factory reset has sorted it. It's cleared out all the keys and filled in the NTP settings I assumed it would correctly.
