### ISSUE TITLE
Locked out of Gosund with Espurna

### ISSUE THREAD

**Issue by bchoor** [xoseperez/espurna#2427]
I was able to successfully flash espurna to a Gosund plug. Once in, I was able to connect to the SSID and login with admin/fibonacci. For some reason, I had issues setting the new password (required step), and tried a bunch of different ones, until the last one went through. I thought I had "copied it to clipboard", but evidently had not. Now, I'm locked out. I tried the holding the button for 10s, 20s, 30s; and now it won't even let me connect to the SSID. I still see the SSID, but it won't accept "fibonacci" as the password to join anymore. Used iphone and macbook to connect to the SSID.

Any help is appreciated; not sure where else to post this question.

**Comment by mcspr** [comment]
Note that SSID & passphrases are saved in the OS, you might want to remove the 'saved' network so it asks again for the passphrase.
\>10second hold should be enough, but it only reboots when you release the button.
