### ISSUE TITLE
Hassio+Mqtt relay auto off

### ISSUE THREAD

**Issue by ice2009** [xoseperez/espurna#2438]
Hello :) 

I installed espurna firmware on nodemcu esp8266. I configured wifi and mqtt and connect relay. Added espurna to hassio with  espurna config and if i set button in hassio to on after second automatically off but relay still on and if i see in espurna dashboard relay still on.  Anyone could help me ?

**Comment by mcspr** [comment]
How HA was configured - through the config, or the MQTT?
What is the version on the ESPurna?
What is the version of HA?
