### ISSUE TITLE
Backup page on wiki is no longer accessible

### ISSUE THREAD

**Issue by ghost** [xoseperez/espurna#2442]
If you click on Backup link it redirects to wiki's index.

Sorry for this issue but I'm starting with this and it's little bit annoying to find this kind of _troubles_ at the beginning and I don't know how to fix it for myself :P

Thanks in advance.

**Comment by mcspr** [comment]
Wiki history can be inspected locally after `git clone https://github.com/xoseperez/espurna.wiki.git`

d89303c7a3301b6899bab7fcbaf9bfe0a83ca02e removed Backup.md by @Reneefra (surprisingly created the same day), which I restored
