### ISSUE TITLE
Schedule TAB 

### ISSUE THREAD

**Issue by etardioli** [xoseperez/espurna#2448]
Hi, im really really new in Espurna, im trying to replace ESPeasy with some Relay and DHT22.
Why im not seeing the schedule Tab?
![2021-05-14_13h04_02](https://user-images.githubusercontent.com/11684262/118297695-e1c79b00-b4b4-11eb-9482-0531d6c4c9af.png)
Thanks!

**Comment by mcspr** [comment]
This could be reflected in the web developer tools console as some kind of error?
Does this work on nightly builds? 1.14.1 vs current dev diverged a lot, and there were some long standing issues exactly like this

**Comment by etardioli** [comment]
Hi! thks for your time,  to enable schedule maybe needs to be compiled to use GPIO? I try several versions, 1.14.0 - 1.13.5 and none of them has the schedule tab

**Comment by mcspr** [comment]
You should see SCHEDULER in the support: ... list on boot / after calling `info` command.
If you are building yourself, note that old versions building with Core 2.3.0 will experience https://github.com/xoseperez/espurna/issues/1610 and https://github.com/xoseperez/espurna/issues/1614 (may or may not be related though). Or simply lose content b/c of low memory conditions, which is also fixed in development versions

**Comment by etardioli** [comment]
Im not building by myself, the version i've is for wemos d1 mini.

**Comment by mcspr** [comment]
Have you tried nightly builds at https://github.com/mcspr/espurna-nightly-builder/releases?

**Comment by etardioli** [comment]
![2021-05-19_10h23_21](https://user-images.githubusercontent.com/11684262/118820044-47889e00-b88c-11eb-9771-b77457cc7afc.png)
Yes, i tried. Is a step i missing?

**Comment by etardioli** [comment]
support: ALEXA API BUTTON DEBUG_SERIAL DEBUG_TELNET DEBUG_WEB DOMOTICZ HOMEASSISTANT LED MDNS MQTT NTP ARDUINO_OTA OTA_CLIENT RELAY SCHEDULER TELNET TERMINAL THINGSPEAK WEB

**Comment by etardioli** [comment]
![2021-05-19_10h43_21](https://user-images.githubusercontent.com/11684262/118823046-0ba30800-b88f-11eb-9ef9-4c0553a80d49.png)
inspect the gui as u suggested and i think those items are for the Schedule tab,  but is not visible in any browser or device...

**Comment by etardioli** [comment]
![2021-05-19_10h48_04](https://user-images.githubusercontent.com/11684262/118823850-b3b8d100-b88f-11eb-835a-50153f0d994f.png)

**Comment by mcspr** [comment]
There are no relays though:
https://github.com/xoseperez/espurna/blob/3078ad16c7db37f4b4b1b839d87076091dd5c6ef/code/espurna/scheduler.cpp#L153-L156
Panels prefixed with `sch` will be shown only when there is at least one.

e.g. `set relayGpio0 5` to have one on GPIO5 or `set relayDummy 1` for a virtual one, after rebooting it would show schedule & relays panels.

**Comment by etardioli** [comment]
![2021-05-19_12h32_16](https://user-images.githubusercontent.com/11684262/118840983-406a8b80-b89e-11eb-8356-cc80d0ad8610.png)
Thank you very much!
