### ISSUE TITLE
How to open NEO-COOLCAM-NAS-WR01W

### ISSUE THREAD

**Issue by ilker-aktuna** [xoseperez/espurna#2450]
I am trying to flash a NEO-COOLCAM-NAS-WR01W

But I could only unscrew the top cover. I could not figure out how to take the 2 layered board from the plug case.
can anyone point out how to get there as in :
https://github.com/xoseperez/espurna/wiki/Hardware-NEO-COOLCAM-NAS-WR01W

**Comment by ilker-aktuna** [comment]
nevermind I found it on this video:
https://www.youtube.com/watch?v=CV8Y61gEQpQ

**Comment by mcspr** [comment]
(also added the video link to the page, tnx!)
