### ISSUE TITLE
Pzem004t V3 no active power

### ISSUE THREAD

**Issue by fjluquerodriguez** [xoseperez/espurna#2456]
Hi. I've compiled last dev version with pzem004t V3 support. In status page voltage, energy and freq are showed but current and active power isn't showed. Any idea?

[Screenshoot](https://ibb.co/n11NLnT)

I've enabled pzem debug and i think device is sending data about current and power, so maybe the problem is in visualization?:
```

[054559] [PZEM004TV3] Received: F8041408E709AF00000F210000173C000001F4004500002B2E (25 bytes)
[060564] [PZEM004TV3] Received: F8041408E909B400000F3B0000173C000001F4004500001DAA (25 bytes)
[066563] [PZEM004TV3] Received: F8041408EA09B300000F330000173D000001F400450000F907 (25 bytes)
```

Thanks

**Comment by mcspr** [comment]
Are values shown in the `magnitudes` command output?

[Certain values are set to 0 when device has at least one relay](https://github.com/xoseperez/espurna/search?q=SENSOR_POWER_CHECK_STATUS):
https://github.com/xoseperez/espurna/blob/75b51f1e80260e2325709e7426fc5b2ebd88ada9/code/espurna/sensor.cpp#L2821-L2837
and that relay is OFF

**Comment by fjluquerodriguez** [comment]
That its... Disabled relay support and magnites are shown! Thanks
