### ISSUE TITLE
add support for sonoff dualr3

### ISSUE THREAD

**Issue by ghost** [xoseperez/espurna#2458]
Hi, it's possible to add support for [this](https://sonoff.tech/product/diy-smart-switch/dualr3/) device?
or flash with existing firmware for another device?

**Comment by mcspr** [comment]
see https://fccid.io/2APN5DUALR3/Internal-Photos/Internal-Photos-5065762, inside of it is esp32 chip and not the currently supported esp8266
it is *possible* to add support, but just not yet

**Comment by ghost** [comment]
thanks for explained answer.
