### ISSUE TITLE
Schedule UI is broken

### ISSUE THREAD

**Issue by Sag06** [xoseperez/espurna#2459]
06/30/2021 dev compiled here.

Just one switch schedule seems to work.  But if I try to set another switch schedule, “Use UTC time”, “Restore on boot” and “Enabled” buttons from second schedule toggle buttons on first schedule.  Same mess if more than two schedule.

Deleting shedules seem to be broken too. No schedule are shown on UI after deleting them, but if I backup json I can see shedules remain.

**Comment by mcspr** [comment]
> Just one switch schedule seems to work. But if I try to set another switch schedule, “Use UTC time”, “Restore on boot” and “Enabled” buttons from second schedule toggle buttons on first schedule. Same mess if more than two schedule.

see the commit

> Deleting shedules seem to be broken too. No schedule are shown on UI after deleting them, but if I backup json I can see shedules remain.

even after rebooting?

**Comment by mcspr** [comment]
... and 50f247bd185d1067add1d6a2d087b6a296242b91 also addresses deleting everything. It still needs a reboot to do the full clean-up though

**Comment by Sag06** [comment]
Half solved.  07/06/2021 comp.
Now I can add scheduled tasks without messing buttons and save them. They are on json backup and they work. Good.
But on Espurna Web UI I can't see them, even after rebooting. Only green "add switch schedule". Sorry.

**Comment by mcspr** [comment]
does adding comma here show them? there is console error in the browser's js console
```diff
diff --git a/code/espurna/scheduler.cpp b/code/espurna/scheduler.cpp
index 700d71b3..d29a99de 100644
--- a/code/espurna/scheduler.cpp
+++ b/code/espurna/scheduler.cpp
@@ -196,7 +196,7 @@ const char* const schema_keys[] PROGMEM = {
     "schAction",
     "schRestore",
     "schUTC",
-    "schWDs"
+    "schWDs",
     "schHour",
     "schMinute",
 };
```

**Comment by Sag06** [comment]
That did the trick. But "Enabled" buttons appear "No" in spite "schEnabled" keys are "1" on json backup. Changing UI  Enabled buttons to "Yes" led to "No changes detected".

**Comment by mcspr** [comment]
> That did the trick. But "Enabled" buttons appear "No" in spite "schEnabled" keys are "1" on json backup. Changing UI Enabled buttons to "Yes" led to "No changes detected".

Hm. Missed in the .js change (and not really tested properly, as it turns out). Changing .js code is an adventure every time, as the same code for other inputs does not work with toggle buttons :)

**Comment by Sag06** [comment]
Any chance to fix that last schedule issue?

**Comment by mcspr** [comment]
WIP
Checkboxes are also broken in case you delete something in the middle and add a new schedule. The underlying problem is \<label for=...\> tags and respective \<input id=...\> need to be re-generated every time schedules list changes, but I actually ended up rewriting more than just solving that issue alone so I need some time to test it
