### ISSUE TITLE
Using a domoticz device as sensor.

### ISSUE THREAD

**Issue by ghost** [xoseperez/espurna#2462]
Hi,
I have the following question;
Can I use a domoticz (sensor) device and switch a relay when reaching a threshold?

Joop.

**Comment by mcspr** [comment]
Can you explain a bit more? Domoticz (sensor) device, meaning something only existing on the Domoticz server, or the ESPurna sensor entity that could trigger some action upon reaching the specified threshold?
Doesn't the https://github.com/xoseperez/espurna/wiki/RPN-Rules cover this use-case though `$sensor_magnitude_name` variables?

**Comment by ghost** [comment]
At te moment I'm switching the circulation pump of my floorheating system On/Off with a DS18B20 sensor depanding on RPN-Rules.
![Schermafbeelding 2021-08-02 120517](https://user-images.githubusercontent.com/33230021/127844635-f31f7201-a3f4-4817-9b57-7f30dff6e63a.png)
![Schermafbeelding 2021-08-02 121425](https://user-images.githubusercontent.com/33230021/127845717-02993152-a8d5-488a-bcfb-e2153defe691.png)

Now I like to do the same with my zone heatingsystem. But I like to use a virtual (room temp) sensor existing on the Domoticz server to switch On/Off a corresponding zone unit.
![Schermafbeelding 2021-08-02 121049](https://user-images.githubusercontent.com/33230021/127845221-291d1ebf-f117-494d-a68f-777e840109bf.png)

**Comment by mcspr** [comment]
With existing switches code we listen to the `domoticz/out`, but there does not seem to be any sensor updates published from the dcz side [(or any mention in the wiki about this use-case, where we want domoticz to publish data and not receive some input)](https://www.domoticz.com/wiki/MQTT)

Quick test with:
- create mqtt client device
- create dummy switch
- create virtual temp sensor
- update through `curl '127.0.0.1:8080/json.htm?type=command&param=udevice&idx=2&nvalue=0&svalue=31'`

Adding 'notification' for the device also does not do anything but notify the browser window
