### ISSUE TITLE
Only status page works

### ISSUE THREAD

**Issue by Sag06** [xoseperez/espurna#2469]
Actual dev code.
Sonoff Mini flashed from scratch after erasing memory.
Initial page let me change password. But after logging with new user password, only Status tab works. No possible to wifi, etc settings.
![Screenshot_20210830-000112272](https://user-images.githubusercontent.com/17682187/131267276-4f23afc2-06d0-411d-b4c1-fda05a6b5e27.jpg)

**Comment by mcspr** [comment]
jquery was more forgiving with missing elements... commit removes the extra ids, keeping only the '#layout'
also seen by making the browser window narrow enough so that the menu button shows up
