### ISSUE TITLE
Woox R5024 smart wifi socket "dead" after uploading ESPurna

### ISSUE THREAD

**Issue by stiw47** [xoseperez/espurna#2480]
Hi guys. Last night I got Woox R5024. It's running on Tuya platform. I wanted to try my luck with tuya-convert and I had success to convert device via OTA. During tuya-convert running process, I decided to flash ESPurna, not Tasmota. I got device converted with basic minimal firmware which coming with tuya-convert package. I had success to login with default "fibonacci" password, then asked to set my own password as usual and had success to login in web UI, ESPURNA-XXXXXXX SSID, 192.168.4.1

Maybe mistake: I didn't connected device to my home WiFi network, but instead proceeded to flash firmware immediately. I loaded  espurna-1.14.1-smartlife-mini-smart-socket.bin Not sure why that and why not some other, probably because I'm already using mentioned firmware on another WiFi plug I have in home, which is some other model (don't know exactly, Chinese Aliexpress no name, one with cylinder shape and LED RGB ring).

Not sure is this important, but... : So, I loaded firmware via "Browse" button in UI and clicked "Upgrade" button twice, accidentally.

Afterwards, device's LED light is blinking only in slow mode, same as when you plug device and until not connected to WiFi. To be more strange, it blinking some kind of double (like heart beat :) idk how to explain that). 

I was try to hold button for 6-7-10 seconds, hopefully to reset device and put it in pairing mode - no success
I was try to hold button for 40 and more seconds - all same
I was try Tasmota way, to plug/unplug it 6 times and 7th time leave it plugged - all same
Device not giving it's AP in the air
Not connecting to home WiFi of course, cause it was never connected
Have no output electric power at all, so you cannot plug any other device to it, and you cannot turn on/off output power by pressing button

All I have is slow (double) blinking, same as while waiting for WiFi

Question: Did someone had problem like this and did solved it? How?
I am little lazy to opening this device, cause as you all know, it is pretty hard and probably not possible without breaking plastic, and I wouldn't like to use some cracked 220V trap later, so is there maybe some "cheat" which I don't know, that I can reset ESPurna (similar as for Tasmota, plug/unplug 6 times....)?

Thx.

**Comment by CrappyTan** [comment]
Is it broadcasting ssid? If not, try power cycling it 5 times within 5 seconds of each cycle. That's factory reset and it should return. If not, it'll probably need a load via uart.

The fact that the led is blinking suggests its alive.

**Comment by stiw47** [comment]
Hi. Thanks for fast answer. No, it is not broadcasting SSID (already said, sorry if my English is rusty :) )
Now is late, since I already tried various combinations of power cycling and lost patience :) , I opened it at the end. Oposite to my first impression, it wasn't so hard, didn't destroyed it, and will not be unsafe, once when I assemble it :)

Now harder part: Learn how to connect this to USB to serial and what to use to flash it :)

Thanks anyway.

**Comment by mcspr** [comment]
[.bin looks ok, pins match and led+relay+button should all work](https://templates.blakadder.com/woox_R5024.html)
Very fast blinking LEDs *seems* to be related to fact that LED timing is set in clock cycles. It seems the original firmware is using 160MHz CPU setting at boot, while both tuya-convert firmware and us think it's 80MHz, so the math does not match the reality. And since the LEDs are working, I'd expect button press to toggle relay on and off

Notice that the SoftAP passphrase changes after changing the password (unless it was already obvious :)
Double-clicking the button toggles between Station and SoftAP modes. And station should turn the SoftAp anyway b/c there are no settings on the device

> I was try to hold button for 6-7-10 seconds, hopefully to reset device and put it in pairing mode - no success
> I was try to hold button for 40 and more seconds - all same
> I was try Tasmota way, to plug/unplug it 6 times and 7th time leave it plugged - all same

"Tasmota way" does not work with the referenced firmware version, holding button for 10seconds just resets settings and reboots the device. "Pairing mode" only available with -smartconfig or -wps variants.

**Comment by stiw47** [comment]
Thanks for answer, but...
LED is not blinking very fast. It is blinking slow, as when device is waiting for WiFi connection. Only difference is this mine is blinking double every time and has strange "pause" on every 5th blink.
Yes, LED is working and I also expected button press to toggle relay on/off, but this is not happening, it is always off.
Yes, SoftAP passphrase was changed when I changed "fibonacci" password of course, but I have no problem to connect to SoftAP, my problem is that there is no SoftAP at all.

_Double-clicking the button toggles between Station and SoftAP modes_ - didn't knew that, will try, now I'm already little tired and device is messed.

_"Pairing mode" only available with -smartconfig or -wps variants._ - don't know what is this

Anyway, this device will probably go to trash. I soldered wires to VCC, GND, TX and RX. Connected via ESP8266 USB programmer and tried to flash  (connected TX to RX and vice versa). Once when I learnt that button should be held to put device to flash mode, I told to my self: "Great, I am on beginning again, cause holding this button not changing anything :) " But I tried anyway. Tried to hold button while plugging USB to PC and next 5 seconds, tried also to connect GPIO0 with GND.  Tried with Tasmotizer, and Tasmota Web UI flasher from Linux and Windows, tried with Node MCU from Windows, had no success anywhere (connecting forever...)

**Comment by mcspr** [comment]
> But I tried anyway. Tried to hold button while plugging USB to PC and next 5 seconds, tried also to connect GPIO0 with GND

GPIO0 is used to switch to flash mode

- detach power 3v3 / 5v from the board
- connect GND <-> GPIO0
- turn the power on
- remove GPIO0 wire
- flash

You can watch the serial monitor at 74880 baud when turning the power on, esp will print a different banner depending on whether you are holding the gpio0 or not
