### ISSUE TITLE
SonOff POW R2 - No Sensors values

### ISSUE THREAD

**Issue by JM69330** [xoseperez/espurna#2492]
I have flashed the device with espurna-1.14.1-itead-sonoff-pow-r2.bin image. I can change the status of the switch but the values from the sensors are still zero (voltage, current , power,...).

**Comment by JM69330** [comment]
![Capture-sonoff POW R2 Espurna](https://user-images.githubusercontent.com/71646121/147668921-be72b28e-647f-47d9-bc7f-3e99f27c72da.JPG)

**Comment by JM69330** [comment]
Re-openned

**Comment by mcspr** [comment]
Are you sure it is r2? Note of the https://github.com/xoseperez/espurna/issues/1983, I do remember board version confusion in regards to rev2 vs. r2

And the actual pw chip can be seen on the opposite side of the board
https://github.com/xoseperez/espurna/wiki/Hardware-Itead-Sonoff-POW#flashing
https://github.com/xoseperez/espurna/wiki/Hardware-Itead-Sonoff-POW-R2

**Comment by JM69330** [comment]
Thanks for your reply. Yes it is an R2 - see photo

![Sonoff POW R2](https://user-images.githubusercontent.com/71646121/147674952-771ff140-9e3d-4267-b31c-2fed82bb33af.jpg)
o

**Comment by JM69330** [comment]
The sensor chip is CS7759**B**-SO, should I try the previous ESPurna version ?

**Comment by mcspr** [comment]
Not previous, but the current nightly would be a much better test

Only thing that comes to mind from reading the [cse7766 doc](https://dl.itead.cc/S31/CSE7766.pdf) is to update these lines
https://github.com/xoseperez/espurna/blob/ec33ee32422574e769f237e4c5d8c3739ca0b427/code/espurna/sensors/CSE7766Sensor.h#L119

```diff
- _serial->begin(CSE7766_BAUDRATE);
+ _serial->begin(CSE7766_BAUDRATE, SWSERIAL_8E1);
```

*edit: ... and the hw serial, too... *
https://github.com/xoseperez/espurna/blob/ec33ee32422574e769f237e4c5d8c3739ca0b427/code/espurna/sensors/CSE7766Sensor.h#L113
```diff
- Serial.begin(CSE7766_BAUDRATE);
+ Serial.begin(CSE7766_BAUDRATE, SERIAL_8E1);
```

**Comment by JM69330** [comment]
So far I just flash the .bin so I'm now getting the whole files and rebuild the .bin

**Comment by JM69330** [comment]
Fixed !
Not a sw problem. I even checked the sensor chip, the output send data to the ESP. Then I look at the sensor CSE7959B datasheet and I saw the AC line (either the live or neutral) goes to the common so I suspected some internal current loop  then I disconnect the USB adaptor from the the device and the right measurements was displayed correctly. **So my recommendation  : Do not live the USB serial adaptor connected to the device while the AC voltage is applied to the device.**

**Comment by ColinShorts** [comment]
The wiki tells us not to connect to these devices using serial when connected to mains power: https://github.com/xoseperez/espurna/wiki/Hardware

This is for safety reasons, you're lucky you didn't fry something (or yourself)

**Comment by JM69330** [comment]
Thanks Colin,
I didn't see the wiki in detail. However, even if the USB adaptor was disconneted from the PC but connected to the device the measurements were still corrupted. Only when I disconnected the adaptor from the sonoff device the measures were correct.
