### ISSUE TITLE
Alexa doesn't discover Espurna

### ISSUE THREAD

**Issue by vladaman** [xoseperez/espurna#2494]
Version 1.14.1 Espurna cannot be discovered by Amazon echo. I see POST /api requests in debug window yet Alexa reports it did not find any devices.

Might be related to https://github.com/vintlabs/fauxmoESP/issues/166

**Comment by mcspr** [comment]
Should be fixed in dev branch **and** by using updated fauxmoesp?
https://github.com/xoseperez/espurna/pull/2411
(and since 'alexa doesnt discover' could mean absolutely anything, since the actual discovery happens inside the black box that alexa is :)
