### ISSUE TITLE
Alexa 1.15.0-dev.gite271eaa0+nightly20211219

### ISSUE THREAD

**Issue by tonymerce** [xoseperez/espurna#2496]
Hello, I have tried this version in a sonoff T1 and Alexa does not work, apart from connecting it to the wifi, activating alexa and giving it a spurious name, do I need to do something else? in the application of alexa (mobile phone) does not discover any device.

**Comment by tonymerce** [comment]
I've already tried it and it works

**Comment by mcspr** [comment]
Do you mean it started discovering again?

**Comment by tonymerce** [comment]
Yes.
