### ISSUE TITLE
How to connect sonoff pow to cloud with espurna

### ISSUE THREAD

**Issue by RamrajRS** [xoseperez/espurna#2498]
Hello all.

I have been trying out espurna and was able to access its webserver.
I would like to know if the espurna will enable the sonoff pow to connect my cloud.
Thus, an app can remotely access the module.

Thanks in advance.

**Comment by mcspr** [comment]
Not directly, but you can always utilize the fact that MQTT brokers support bi-directional connections - ESPurna device connects to the broker server on LAN, while the broker itself establishes connection to an external server located on the internet

/remote/ at the mosquitto man, for example
https://mosquitto.org/man/mosquitto-conf-5.html

**Comment by RamrajRS** [comment]
@mcspr  I have tried to connect with a cloud mqtt broker. I am not able to get the status connected for mqtt. Please help.
