### ISSUE TITLE
Sonoff TH: Infallibility

### ISSUE THREAD

**Issue by xoseperez** [xoseperez/espurna#25]
Originally reported by: **Pavel Eremin (Bitbucket: [paveleremin](https://bitbucket.org/paveleremin), GitHub: [paveleremin](https://github.com/paveleremin))**

----------------------------------------

Hello everyone,

I've got my first Sonoff TH and I decide to test own firmware before change it to espurna.

1. I setup automatic mode with minTemp and maxTemp - all worked fine

2. Then I turned off the router, and it's continue to work!

The question is: will Sonoff TH continue work without wifi?

If not, I think it's not safe use it with gas boiler, because in this case we have two points of failure: router and mqtt server. @xoseperez what do you thing about it?

**Comment by artua** [comment]
Good day,

Is it somehow available now? I mean scheduling based on sensor value.
Thanks
