### ISSUE TITLE
wrong temperature value with 100k NTC

### ISSUE THREAD

**Issue by hamed-ta** [xoseperez/espurna#2500]
Hello,

I use 100k NTC and a downstream resistor of 10K ohm, to read the LED board temperature, my configs and parameters are as below:

```
#define SENSOR_SUPPORT     1
#define NTC_SUPPORT        1
#define NTC_BETA           3950
#define NTC_R_UP           0
#define NTC_R_DOWN         10000
#define NTC_R0             100000
```

but what I read in 25C room temperature is about 80 Celsius, what is the problem?

here is the NTC that I use:
![Screen Shot 2022-01-21 at 19 40 56](https://user-images.githubusercontent.com/9883945/150560962-e438ea42-691d-423e-aa57-14013cfcd55f.png)

here is my circuit:
![Screen Shot 2022-01-21 at 19 43 24](https://user-images.githubusercontent.com/9883945/150561585-557cfdbf-b1d2-4edc-bd3a-ec77af7f975c.png)

and what I read in room temp:

![Screen Shot 2022-01-21 at 19 45 55](https://user-images.githubusercontent.com/9883945/150561665-9fc439b7-74c2-48f8-bc55-cc7679860263.png)

other configs:

```
#ifndef ANALOG_SUPPORT
#define ANALOG_SUPPORT                  0
#endif

#ifndef ANALOG_SAMPLES
#define ANALOG_SAMPLES                  10      // Number of samples
#endif

#ifndef ANALOG_DELAY
#define ANALOG_DELAY                    0       // Delay between samples in micros
#endif

//Use the following to perform scaling of raw analog values
//   scaledRead = ( factor * rawRead ) + offset
//
//Please take note that the offset is not affected by the scaling factor

#ifndef ANALOG_FACTOR
#define ANALOG_FACTOR                    1.0       // Multiply raw reading by this factor
#endif

#ifndef ANALOG_OFFSET
#define ANALOG_OFFSET                    0.0       // Add this offset to *scaled* value
#endif

// Round to this number of decimals
#ifndef ANALOG_DECIMALS
#define ANALOG_DECIMALS                  2
#endif
```

**Comment by mcspr** [comment]
Physical down & up values might be off? This is c/p from the sensor code
<s>https://godbolt.org/z/qPd3vcTjf</s>
https://godbolt.org/z/8qMn568Kr
Should the downstream resistance be 100k as well?

```
433     350.95  77.8
```
where ADC reading of 433 aka 0.42V results in your number. you can see the result when chancing the Down or Up resistances (in ohm)

**Comment by hamed-ta** [comment]
This still doesn't work in the latest commit, I checked everything, measured resistances, and even calculate the NTC Beta, but still, this calculates the wrong temp. 

what should be the problem?

![Screen Shot 2022-04-29 at 18 43 31](https://user-images.githubusercontent.com/9883945/165961849-a8dfba27-7f8e-41a8-8e18-17519a1e38db.png)
![Screen Shot 2022-04-29 at 18 35 35](https://user-images.githubusercontent.com/9883945/165960411-58a7c74b-316e-4b3a-9ca0-c4f7ec217b01.png)
![Screen Shot 2022-04-29 at 18 35 44](https://user-images.githubusercontent.com/9883945/165960422-ee7774a0-dad3-4010-945d-fc386fb56a26.png)

**Comment by mcspr** [comment]
^ see the godbolt link above with the code reproducing the values from the sensor, and how things change depending on the rdown value (constants at the top)
shouldn't it be 100k down as well?

**Comment by hamed-ta** [comment]
> ^ see the godbolt link above with the code reproducing the values from the sensor, and how things change depending on the rdown value (constants at the top) shouldn't it be 100k down as well?

No, the R down can't be 100K because in that way the divided voltage would be higher than 1V which ADC can measure.

**Comment by mcspr** [comment]
What voltage are you seeing right now, with 10k and with 100k?

**Comment by hamed-ta** [comment]
> What voltage are you seeing right now, with 10k and with 100k?

In room temp (26 Celcius), it's about 0.39V which is correct, and the corresponding ADC value is about 416 which is correct so the problem can only be the temp calculation.

![Screen Shot 2022-05-02 at 20 44 20](https://user-images.githubusercontent.com/9883945/166268986-0f1a01f8-1163-4005-8b83-25b58bd51cd6.png)
