### ISSUE TITLE
RFBridge reboots when saving learned code

### ISSUE THREAD

**Issue by Zodiac-69** [xoseperez/espurna#2502]
On espurna-1.15.0-dev.gitf01ea1ce+nightly20220116-itead-sonoff-rfbridge-direct, when i save a learned code, the RFBrige will reboot without saving the code.
I reverted back to the stable release, 1.14.1 and the code is saved without any issues

**Comment by mcspr** [comment]
Missing 'data' value would explain it
https://github.com/xoseperez/espurna/blob/f01ea1ce822478d0adb7c9a88c17a90ae4782655/code/html/custom.js#L2253-L2256
https://github.com/xoseperez/espurna/blob/f01ea1ce822478d0adb7c9a88c17a90ae4782655/code/espurna/rfbridge.cpp#L383
So we receive whatever arduinojson decides to generate via `.as<const char*>()` when the key is missing

Minor note, LEARN immediately saves things for you after it receives something, so pressing SAVE is useless there.
Will need to tweak LEARN -> SAVE thing as well, so there's no SAVE besides the general settings one...
