### ISSUE TITLE
Alexa doesn't find my devices

### ISSUE THREAD

**Issue by albafer** [xoseperez/espurna#2504]
Hi everyone!

I'm trying to connect my device to Alexa but I don't fint the way to do it. 

My device is a Blitwolf SHP6 with 1.14.1 espurna version. I have activated the "alexa discovery" option but nothing happens. 

Do you have any information or trick to help me? 

Thanks in advance!!

**Comment by mcspr** [comment]
Try nightly?

https://github.com/xoseperez/espurna/issues/2494
https://github.com/xoseperez/espurna/issues/2493
