### ISSUE TITLE
Websocket error in new devices

### ISSUE THREAD

**Issue by hamed-ta** [xoseperez/espurna#2509]
When I flash a new device before configuring the wifi client I get this error, but after configuring client mode this gets away.

![Screen Shot 1401-01-26 at 21 44 18](https://user-images.githubusercontent.com/9883945/163602032-de4eea48-c3e3-4a1c-8fbf-3d1584496d9e.png)

what is this for?

**Comment by mcspr** [comment]
WebUI script failed somewhere. As the message suggests, take a look at Developer Tools. Console will have the specific code line of the exception, un-minifying the code you will see the context inside of  code/html/custom.js that calls forEach

**Comment by davebuk** [comment]
Are you trying this on a small screen, phone maybe? I have this on certain pages when on my phone. When I've tried on a full browser or 'view as desktop' on my phone it's fine.

**Comment by mcspr** [comment]
Developer tools include 'remote debugging' in case this happens on a phone
https://developer.chrome.com/docs/devtools/remote-debugging/
https://firefox-source-docs.mozilla.org/devtools-user/remote_debugging/debugging_firefox_for_android_with_webide/index.html

I'd assume the issue is related to an empty WiFi config.
btw... What browser, version and platform / OS? Which pages?

**Comment by hamed-ta** [comment]
> Are you trying this on a small screen, phone maybe? I have this on certain pages when on my phone. When I've tried on a full browser or 'view as desktop' on my phone it's fine.

No on a desktop computer and with the Chrome browser. I will send add some pictures of the developer console.

**Comment by davebuk** [comment]
Sorry, didn't look closely on my error. Mines to do with the toggle menu :-)

```
TypeError: Cannot read properties of null (reading 'classList')
    at HTMLDivElement.toggleMenu (http://192.168.1.34/:17:31055)

For more info see the Developer Tools console.
```
That was on version: 1.15.0-dev.gita55cf0b8

But seems fine on another device running: 1.15.0-dev.gitd5273513

**Comment by mcspr** [comment]
pretty sure the @davebuk issue was solved some time around January this year (https://github.com/xoseperez/espurna/commit/4c178948b5f5af48a4710548ba7c962f57f59b66)

@hamed-ta what commit are you running? can you also show the output of the c/p and running this snippet in the console?
```js
for (let style of document.styleSheets) { for (let rule of style.cssRules) { if (rule.cssText.includes("module-")) { console.log(rule.selectorText); } } }
```

**Comment by hamed-ta** [comment]
> pretty sure the @davebuk issue was solved some time around January this year ([4c17894](https://github.com/xoseperez/espurna/commit/4c178948b5f5af48a4710548ba7c962f57f59b66))
> 
> @hamed-ta what commit are you running? can you also show the output of the c/p and running this snippet in the console?
> 
> ```js
> for (let style of document.styleSheets) { for (let rule of style.cssRules) { if (rule.cssText.includes("module-")) { console.log(rule.selectorText); } } }
> ```

Sure, I use this commit [c9ba70a](https://github.com/xoseperez/espurna/commit/c9ba70a7f0d795fcc2254d77f9bd6142ee5d66ac)

![Screen Shot 1401-01-29 at 22 09 42](https://user-images.githubusercontent.com/9883945/163849526-12613a09-1bb2-4673-a117-8d1fb5b87e6b.png)

**Comment by mcspr** [comment]
Try with the latest dev version

**Comment by hamed-ta** [comment]
> Try with the latest dev version

I have made several changes in different files, it is not easy to merge with the new version, what tools do you recommend to compare all the files of in whole?

I also added another button action to put the device to sleep and wake it up with the interrupt of the same button, do you thing it is good to be added to the project?

**Comment by mcspr** [comment]
> I have made several changes in different files, it is not easy to merge with the new version, what tools do you recommend to compare all the files of in whole?

https://www.sublimemerge.com/
https://code.visualstudio.com/
(or, just git cli :)

> I also added another button action to put the device to sleep and wake it up with the interrupt of the same button, do you thing it is good to be added to the project?

Sure. Preferably as a pull request.

**Comment by hamed-ta** [comment]
> Try with the latest dev version

Yes, It is solved in the latest version.
