### ISSUE TITLE
Sensor corrections don't seem to be working in 1.15.0-dev.gitc980acbd.

### ISSUE THREAD

**Issue by davebuk** [xoseperez/espurna#2520]
I have just built a firmware with version 1.15.0-dev.gitc980acbd but adjustments to the corrections in sensor values don't effect the webui or MQTT value for that magnitude.

Changing say temp#0 to -5 usimg the webui says that the new value has saved and `tmpCorrection0 => "-5"` in shown in `keys` but the actual value in the 'STATUS' page doesn't change.

**Comment by mcspr** [comment]
Should be fixed in b5e467d4513d46f2dc739fcea951a210eec56c5e

**Comment by davebuk** [comment]
Fixed
