### ISSUE TITLE
PZEM004T V3 software serial doesn't appear to work on latest dev build.

### ISSUE THREAD

**Issue by davebuk** [xoseperez/espurna#2528]
I have tried updating a device to the latest `dev` build but it can't now find the PZEM004TV3 device connected to it. I have the original build `1.15.0-dev.gitd5273513` working fine with the following definitions:

```
#elif defined(DB_WEMOS_PZEMV3)

    #define MANUFACTURER            "WEMOS"
    #define DEVICE                  "PZEM004TV3"    // Software Serial

    // My config
    #define ALEXA_SUPPORT           0
    #define DOMOTICZ_SUPPORT        0
    #define HOMEASSISTANT_SUPPORT   0
    #define THINGSPEAK_SUPPORT      0
    #define NTP_TIMEZONE            TZ_Europe_London
    
    // Buttons
    #define BUTTON1_PIN             0    // D3
    #define BUTTON1_CONFIG          BUTTON_PUSHBUTTON | BUTTON_DEFAULT_HIGH | BUTTON_SET_PULLUP
    
    // LEDs
    #define LED1_PIN                2 // D4
    #define LED1_PIN_INVERSE        1
    
    // Extras
    #define PZEM004TV30_SUPPORT     1
    #define PZEM004TV30_USE_SOFT    1
    #define PZEM004TV30_TX_PIN    14 // D5
    #define PZEM004TV30_RX_PIN    12 // D6
    #define SENSOR_POWER_CHECK_STATUS    0
```
Using the latest dev build the sensor output shows all values as `undefined` and the debug shows:
 
`[SENSOR] Could not read from PZEM004T V3.0 @ SwSerial, 0xf8 (Other / Unknown error)`

I thought it might be an error at:
https://github.com/xoseperez/espurna/blob/e9de3d44354b4b6b2e3c9a22310485ebc6859ebf/code/espurna/sensors/PZEM004TV30Sensor.h#L39 
but changing to `{ PZEM004TV30_TX_PIN }` doesn't make a difference.

Is there anything that could have changed since Sep 2021 for the V3 PZEM004T?

**Comment by mcspr** [comment]
looks like e4b068ec7d7173b457c5e616814069a3a55cde8b
serial port is never initialized, `begin(Baudrate);` should happen somewhere

```diff
diff --git a/code/espurna/sensor.cpp b/code/espurna/sensor.cpp
index 43a7b621..86a6f9e3 100644
--- a/code/espurna/sensor.cpp
+++ b/code/espurna/sensor.cpp
@@ -2385,7 +2385,10 @@ void load() {
         sensor->setDebug(
             getSetting("pzemv30Debug", PZEM004TV30Sensor::DefaultDebug));

-        add(sensor);
+        if (sensor) {
+            port->begin(PZEM004TV30Sensor::Baudrate);
+            add(sensor);
+        }
     }
 #endif
 }
```
?

**Comment by davebuk** [comment]
I don't suppose it's as simple as adding that line back into the code?

**Comment by mcspr** [comment]
See the commit, above is invalid b/c `port` no longer points to anything at that point in the code :oops:
