### ISSUE TITLE
Nous A1T OTA flashing from Tasmota to ESPURNA?

### ISSUE THREAD

**Issue by Homer-Sim** [xoseperez/espurna#2531]
Hello,
I bought some Nous A1T which come flashed already with Tasmota.
I am more used to ESPURNA and all my other plugs running it.

Might it be possible to "give" Tasmota just a espurna firmware to reflash it?
Which firmware would be fitting?

Thanks

**Comment by mcspr** [comment]
We have a slightly different approach at configuration, but most things stay the same. If the idea is to flash something pre-built, take a look at hardware.h for a compatible pin selection and grab the matching .bin from release page (preferably, the snapshot one, in case it somehow breaks during or after the process b/c of slight incompatibilities and SDK differences)

https://nous.technology/product/a1t/template.html
GPIO0 is a pushbutton
GPIO4, GPIO5 and GPIO12 are used for HLW8012-compatible BL0937 chip. Note SELi aka SEL(ect) i(nverted) 
GPIO13 is an inverted LED
GPIO14 is a relay

e.g. this AVATTO one
https://github.com/xoseperez/espurna/blob/844f20003ded9e00c26c8c845e097ec50308bc31/code/espurna/config/hardware.h#L2906-L2937
or KMC 70012
https://github.com/xoseperez/espurna/blob/844f20003ded9e00c26c8c845e097ec50308bc31/code/espurna/config/hardware.h#L2043-L2071

or, just build it using these values

**Comment by Homer-Sim** [comment]
Great, I will check that.

Can I use the upload new firmware option within tasmota to flash espurna firmware?

**Comment by mcspr** [comment]
I don't remember any problems doing that the last time I tried it (but, it has been a while). iirc Tasmota updater may not like anything *but* Tasmota binaries, but recent builds introduced a way to circumvent that.

**Comment by Homer-Sim** [comment]
Hello,

is this the right firmware bin for the Avatto?
[espurna-1.15.0-dev.git97a4e0a8+github20220819-avatto-power-plug-wifi.bin](https://github.com/xoseperez/espurna/releases/download/github20220819/espurna-1.15.0-dev.git97a4e0a8+github20220819-avatto-power-plug-wifi.bin)

Which firmware should I upload first if I am running in space issues?

This is how it looks like in tasmota:
![grafik](https://user-images.githubusercontent.com/13933431/185743536-3c00faf3-497c-4db6-ab50-60143d332f80.png)

**Comment by Homer-Sim** [comment]
Ok, I dared to flash it.
First with a minimalistic tasmota and then with the above written espurna bin.

I see a WIFI espurna but with fibonacci I can not connect.
Connection refused ...

Any ideas? Help is highly appreciated.

**Comment by mcspr** [comment]
Connection refused on WiFi or the Web page? Even after device power off -> on cycle?
I have noticed captive portal issue, so automatic login might not work correctly. WebUI needs admin as username and fibonacci as password

**Comment by Homer-Sim** [comment]
connecting the WIFI is refused.
I plugged it out/in no changes. LED is flashing 3 times then after a while once slow and 3 times faster .... if this helps

**Comment by Homer-Sim** [comment]
So it seems it is bricked?! I am not able to open and solder something to the plug.....

**Comment by mcspr** [comment]
Does the button work, switching the relay?

Blinking LED just means that the WiFi access point is working
Does it connect to WiFi on a different device?

**Comment by Homer-Sim** [comment]
Button seems to work, I can hear a click but with a delay

I have different plugs which are working fine (with ESPURNA) and previously with this plug it worked with tasmota

**Comment by Homer-Sim** [comment]
Sometimes there appears a second WIFI:
It is not working to connect too
Button seems to work, I can hear a click but with a delay

![grafik](https://user-images.githubusercontent.com/13933431/185809916-dcfb96db-50ee-4f82-ab0a-5f31f1d44812.png)

**Comment by mcspr** [comment]
The issue here is I have no idea why it would not connect :/
Click is the relay, yes, but does it *stay on*? If, for example, we have a software crash it would not connect due to that. Just to understand the state the device is currently in.

edit: local tests with nodemcu board are also successful, can't really debug since everything works just fine*
* flashing tasmota.bin via serial
* connecting to AP and setting up network, reboot
* OTA'ing tasmota-minimal.bin, reboot
* connecting to local network, OTA'ing espurna-1.15.0-dev.git97a4e0a8+github20220819-nodemcu-lolin.bin
* after upload, it detects tasmota via rtcmem info (logs show `[006711] [BOARD] TASMOTA OTA, resetting...`) and reboots once more
* AP is brought up, connecting to it works and I can see webui

**Comment by Homer-Sim** [comment]
I am on a business trip but on weekend I will check if the power supply is interrupting frequently. Which would give us the indicator for a rebooting loop, right?!
But as long as I am not able to connect by wifi it is useless for me, right?!

**Comment by mcspr** [comment]
> Which would give us the indicator for a rebooting loop, right?!

Exactly. And the button behaviour, too.

**Comment by Homer-Sim** [comment]
OK, I did the test.
after plugging in it takes ~20-30 seconds then the button is switching and light (I attached a simple light to it) is shining.
After additional ~max 5 sec light is going out
Once I was able to connect to the plug and the logindata window appeared but then it switched off again.

Anything else I can do except throwing it into the bin?

Is it possible/existing to use a script which is connecting/logging in and do a "trick"? Something like new firmware or preventing reboot?

**Comment by mcspr** [comment]
There are at least two issues at play and I have not noticed / considered
- energy monitor counter has a bug that resets the device (and a not really obvious one, even with all of compilation warnings enabled). e704efffb42d1ad667ce3833c0d4025912b05a5d will fix that
- because the reset is due to the hardware watchdog trigger, current implementation erased our internal 'reboot counter' value causing effectively a non-stop reboot cycle without a way to recover and it will never trigger SAFE mode. 7659a63441a7fafff30a274caad65db44de7983a removes this handling of hwdt resets

The script approach may work. I suppose directly uploading stuff to `/upgrade` endpoint would do the trick with a fixed .bin, but I am not really sure if it will upload everything in one go or not. At least everything related to updates happens separately from the sensor code that fails.

Will need to trigger a new build here.
*edit: reverting to -core .bin will definitely work in the mean time*

**Comment by Homer-Sim** [comment]
>  _edit: reverting to -core .bin will definitely work in the mean time_
Which one would you suggest? And, sorry for this maybe silly question,  how do I upload to /upgrade folder?
Is there a howto any where?

**Comment by mcspr** [comment]
> > _edit: reverting to -core .bin will definitely work in the mean time_
> Which one would you suggest? And, sorry for this maybe silly question,  how do I upload to /upgrade folder?
> Is there a howto any where?

See https://github.com/xoseperez/espurna/wiki/OTA#updating-via-http

**Comment by Homer-Sim** [comment]
I have the issue that I am not able to  write a script to connect to ESPURNA WIFI and if established to upload the core bin.

Is there something I can use?

**Comment by mcspr** [comment]
`netsh wlan` on Windows, `nmcli` (or `wpa_cli`) on Linux, `networksetup` on macos?
all seem to have a common SSID + PASSPHRASE connection option

**Comment by Homer-Sim** [comment]
I managed to do a connection to espurna with nmcli

Which core bin should I use?

This one?

espurna-1.14.1-espurna-core-4MB.bin

**Comment by mcspr** [comment]
1.15 one for 1MB, latest snapshot; to avoid version downgrades

**Comment by Homer-Sim** [comment]
espurna-1.15.0-dev.git0e48dab5+github220830-espurna-core-4MB.bin 
This one?

**Comment by Homer-Sim** [comment]
I tried it and received this:

```
Device 'wlx74da386523be' successfully activated with 'b630acbc-216d-4263-a6be-ed6cc53fb8d6'.
PING 192.168.4.1 (192.168.4.1) 56(84) bytes of data.
64 bytes from 192.168.4.1: icmp_seq=1 ttl=255 time=75.5 ms

--- 192.168.4.1 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 75.544/75.544/75.544/0.000 ms
ERROR: No magic byte / invalid flash config
```

What does the ERROR Message means?

The firmware bin I received this way:

wget https://github.com/xoseperez/espurna/releases/download/github220830/espurna-1.15.0-dev.git0e48dab5+github220830-espurna-core-4MB.bin

**Comment by mcspr** [comment]
See above, you need 1MB - the same as the one used to build avatto .bin
https://github.com/xoseperez/espurna/blob/8bfc0c4882fb1e4a2cbd3174db54c19d039dcf94/code/platformio.ini#L777-L779

You could still use curl to download, just add `-L` so redirects work. And `-O` to replicate wget behaviour setting download output

**Comment by Homer-Sim** [comment]
I tried again, but it stoppes for hours
![grafik](https://user-images.githubusercontent.com/13933431/188321138-e92ddf75-4657-4ab2-a355-1e5d9dc69ab1.png)

This is my bash script:

```
#!/bin/bash


nmcli dev wifi connect ESPURNA-A11CFB password "fibonacci"
ping -c 1 192.168.4.1
curl -XPOST --digest -uadmin:fibonacci \
  -H "Content-Type: multipart/form-data" \
  -F "filename=@/home/homer/espurna-1.15.0-dev.git0e48dab5+github220830-espurna-core-1MB.bin" \
  http://192.168.4.1/upgrade
```

**Comment by Homer-Sim** [comment]
How do I know the file is uploaded and it will be flashing the plug with the core version?
Do I need to unplug/plug to start this update process?

**Comment by mcspr** [comment]
-core does not have led configured, so missing wifi notification and a longer working AP when its done and already running that new version.
no unplug necessary, process happens immediately after updater receives the file. only question is whether it has time to proceed with actually writing it over the existing app. I wonder if espota.py might work better (see desc on the OTA wiki page)

**Comment by Homer-Sim** [comment]
![grafik](https://user-images.githubusercontent.com/13933431/188457533-596832ee-a7b2-4d20-b2ce-85709cc1093d.png)

**Comment by Homer-Sim** [comment]
It seems that it worked now.

What should be the next steps?

**Comment by mcspr** [comment]
Upload the latest snapshot instead of the old and broken one :)

**Comment by Homer-Sim** [comment]
Just to be sure, 
this one I used previously: espurna-1.15.0-dev.git97a4e0a8+github20220819-avatto-power-plug-wifi.bin
Is this the broken one?

And this one I should try now?:
espurna-1.15.0-dev.git0e48dab5+github220830-avatto-power-plug-wifi.bin

**Comment by mcspr** [comment]
> And this one I should try now?:
espurna-1.15.0-dev.git0e48dab5+github220830-avatto-power-plug-wifi.bin

Yes. Same device config, with the included fixes I mentioned in https://github.com/xoseperez/espurna/issues/2531#issuecomment-1231024234 (as seen in commit log)

**Comment by Homer-Sim** [comment]
GREAT and big thanks for your support 
It is working.

BUT one question if I am changing hostname under GENERAL it is not saving it.
Bug or Feature?

**Comment by Homer-Sim** [comment]
This made it work:

curl -F "data={\"app\":\"ESPURNA\",\"hostname\":\"Dose-WZ-LampeSO\"};type=application/json" --digest -u admin:sdsdsdwd http://192.168.100.213/config

**Comment by mcspr** [comment]
> BUT one question if I am changing hostname under GENERAL it is not saving it.
Bug or Feature?

Definitely a bug in WebUI scripts since `/config` works, will check it out. And probably not the only text entry not working.
