### ISSUE TITLE
Bricked device after flash to 1.15?

### ISSUE THREAD

**Issue by MOST2K2** [xoseperez/espurna#2536]
### Device

Avatar AWP08L

### Version

1.15

### Question

I have flashed the device to firmware 1.15.0
But only telnet is available.
Command ota http://192.168.0.10:13334/espurna1.bin
+OK
   [750438] [EEPROM] Disabling EEPROM rotation
   [750438] [OTA] Downloading /apktool/espurna1.bin
   [750519] [OTA] ERROR: No magic byte / invalid flash config[750520]

Info:
ESPURNA 1.15.0-dev.git0e48dab5+github220830 built 2022-08-30 00:50:31
mcu: esp8266 chipid: A4CF12C3B3F2 freq: 80mhz
sdk: 2.2.2-dev(38a443e) core: 2.7.4
md5: 6a1eaac87dea640a7bc91c77a30a79b7

support: DEBUG_TELNET MDNS ARDUINO_OTA OTA_CLIENT TELNET TERMINAL
               system: OK boot counter: 1

Any way to get it working ? Thanks!

**Comment by mcspr** [comment]
You are running 'minimal' version atm

I dont see AWP08L in our devices list. What is the output of `storage`?
Flash error may come from mis-matching 1MB / 2MB / 4MB variants we have. If that is the case, `gzip` the firmware file before flashing it via `ota`
Also, `ota` is a fairly limited http client. For one, it does not support redirects so it may break at that point.

And you should still be able to use `espota.py`

**Comment by MOST2K2** [comment]
Thanks. I want to revert back to tasmota.
Should that work when gzipped?
Trying 192.168.0.210...
Connected to 192.168.0.210.
Escape character is '^]'.
last reset reason: Power On
extra info: Power On

storage
flash chip ID: 0x144068
speed: 40000000
mode: DOUT
size: 1048576 (SPI), 1048576 (SDK)
app    [00000000...0005C000) (376832 bytes)
ota    [0005C000...000FA000) (647168 bytes)
eeprom [000FA000...000FC000) (8192 bytes)
sdk    [000FC000...00100000) (16384 bytes)
+OK

**Comment by MOST2K2** [comment]
I tried different combinations with gzipped bin  but nothing works, always the same error. 
With espota.py i get this.
09:37:52 [INFO]: Starting on 0.0.0.0:26974
09:37:52 [INFO]: Upload size: 487824
09:37:52 [INFO]: Sending invitation to: 192.168.0.210
Authenticating...FAIL
09:37:52 [ERROR]: Authentication Failed

Telnet output:
[OTA] Authentification 0, updater code 0

Any help is appreciated.

**Comment by mcspr** [comment]
If you previously used WebUI and changed the device password, use that one
If you have any firewalls enabled, make sure it does not prevent espota.py from opening a TCP listening port
Continuing with `ota` attempts, `python -mhttp.server -d ./` on local network is definitely known to work
Don't attempt to flash tasmota-minimal, it won't pick up any settings and recovering from that would be even trickier

And for the future I'd also suggest to switch to -webui variant of our minimal images :)

**Comment by MOST2K2** [comment]
Thank you! Got it working now. Tried a different web server over python (as you suggested) and ota update from telnet was working.

espota.py was not working with fibonacci or my specific password.
Thanks for help!
