### ISSUE TITLE
undefined reference to `settings::StringView::equals(settings::StringView) const'

### ISSUE THREAD

**Issue by amarendrapramanik** [xoseperez/espurna#2540]
### Device

ESP8266

### Version

1.14.1

### Bug description

undefined reference to `settings::StringView::equals(settings::StringView) const' while compiling types.h.

Tried to find definition of equals but did not found. Am I missing something.

**Comment by mcspr** [comment]
There is no StringView in 1.14.1, please read the version field description
If you update our sources by c/p .zip contents ('Download ZIP' on the home page), you might have problems with old files getting compiled. It should always be a brand new directory.
Plus, what are the other N lines around the error also matters
