### ISSUE TITLE
Wifi High Gain to be re-instated

### ISSUE THREAD

**Issue by xoseperez** [xoseperez/espurna#255]
Originally reported by: **Erwin (Bitbucket: [elonden](https://bitbucket.org/elonden), GitHub: [elonden](https://github.com/elonden))**

----------------------------------------

As a request as per Issue #204 would it be possible to have this returned for the Sonoff POW. I have a few on the edge of WIFI reception and the high gain setting offers the solution.

**Comment by nettuno77** [comment]
> 
> 
> According to this issue here: [esp8266/Arduino#764](https://github.com/esp8266/Arduino/issues/764), the default value of the transmission power is set to max. So this option would only be useful to decrease the output power and save a few mW.

Another useful question is that reducing transmission power can prevent interference to near connected sensors. For eample, I tested a pir with nodemcu, ant it periodically send a false positive. Simply reducing tramission power, it works like a charm!
