### ISSUE TITLE
Setting `#define DEBUG_SERIAL_SUPPORT 0` no longer stops serial port.

### ISSUE THREAD

**Issue by davebuk** [xoseperez/espurna#2556]
### Device

Sonoff Basic

### Version

1.15.0-dev.git1169be25

### Question

Defining `#define DEBUG_SERIAL_SUPPORT 0` used to stop serial debug from running to allow GPIO 1 to be used for other inputs. Building with the above version gives me a sensor error (DALLAS temp sensor) saying GPIO is already in use.

I guessed it was something to do with the serial port and found `#define UART_SUPPORT 1` in `code/espurna/config/general.h`. By setting definition as `#define UART_SUPPORT 0` it now works again.

Should we use `UART_SUPPORT 0` rather than `DEBUG_SERIAL_SUPPORT 0` when using the Tx/Rx pins for other functions?

**Comment by mcspr** [comment]
> Should we use UART_SUPPORT 0 rather than DEBUG_SERIAL_SUPPORT 0 when using the Tx/Rx pins for other functions?

Yes, but also note `DEBUG_SERIAL_PORT` value and corresponding `UART#_TX_PIN` and `UART#_RX_PIN`. Setting both to something else , including `GPIO_NONE`, also works.

**Comment by davebuk** [comment]
So:
```
    #define UART_SUPPORT        0
    #define UART1_TX_PIN        GPIO_NONE
    #define UART1_RX_PIN        GPIO_NONE
```
Should we also include:
```
#define DEBUG_SERIAL_SUPPORT 0

and

#define TERMINAL_SERIAL_SUPPORT  0
```
I'll look to update [https://github.com/xoseperez/espurna/blob/dev/code/espurna/config/custom.h.example](url) at some point.

**Comment by mcspr** [comment]
Right now it is has different behaviour based on 'softness' of UART <-> MODULE dependency
See https://github.com/xoseperez/espurna/tree/dev/code/espurna/config/dependencies.h

Disabling UART support disables DEBUG and TERMINAL in the header
Having overlapping PORT value with some of known ...\_PORT entries will disable them as well
Plus, some things like MQTT and RFBRIDGE enable UART support

**Comment by mcspr** [comment]
.h updated, closing
