### ISSUE TITLE
bin file corresponding to the sonoff S26 model

### ISSUE THREAD

**Issue by tonymerce** [xoseperez/espurna#2560]
### Device

Sonoff S26

### Version

1.15.0

### Question

Hello everyone, can you tell me which bin file corresponds to the Sonoff S26 device in any of its variants?
Thanks in advance

**Comment by mcspr** [comment]
S20?
https://github.com/xoseperez/espurna/wiki/Hardware-Itead-S26

**Comment by Sag06** [comment]
Yes, I use S20 and it works.
