### ISSUE TITLE
ad-hoc network available even if connected to infrastructure

### ISSUE THREAD

**Issue by adoeller** [xoseperez/espurna#2571]
### Device

itead-s20

### Version

1.15.0-dev.git312c3ef2+github221212

### Bug description

ad-hoc network available even if connected to infrastructure

### Steps to reproduce

device is in network ESSID A
stronger network ESDID A offered
switch off stronger netzwork A
restart original network A, i.e. for a minutes there is no network whatsoever available

=> device will connect to original network A but still offer ad-hoc wifi

**Comment by mcspr** [comment]
By offered you mean it decides to re-connect and in the middle of it there is a disconnect? Why do we need 2, and is it different with just one A disappearing?
Fallback AP may appear, but there is a 60s timeout if there are no clients connected (see `wifi` and `wifi.stations` commands output)

**Comment by adoeller** [comment]
No, I mean that ad-hoc and infrastructure will be permanently available. Even after 15 minutes.

**Comment by mcspr** [comment]
Sounds like a bug in timers, then. Just not yet seeing the trigger...
*edit* ...but, re-scheduling from fallback::check() seems like the most obvious suspect here...
