### ISSUE TITLE
MAXCIO WDE004: Physical HW button and LED do not respond/display

### ISSUE THREAD

**Issue by richtoy** [xoseperez/espurna#2573]
### Device

MAXCIO WDE004

### Version

1.15.0-dev.git909949b5+github230112

### Bug description

I have two of these devices, a Sonoff S20 and 3 Neo coolcam NAS_WR01W and all were updated from 1.14 to the latest beta firmware.

Updates went fine and all devices respond to web interface and HA.

However, the physical button on the two MAXCIO WDE004 does not respond (switch the relay) and neither does the LED reflect the switch position if it is actuated remotely from the web interface or HA.

All devices have the same config, i.e. default + hostname modifiactions + MQTT & HA settings

### Steps to reproduce

See above

### Build tools used

N/A

### Any relevant log output (when available)

```shell
Just ask
```

**Comment by mcspr** [comment]
fbd4a9c1 should fix the .bin

*edit: note the index*
```
set uartTx0 153
set uartRx0 153
reset
```
Button needs UART disabled. For the time being, these would stop it from claiming the IO pin
(Web DEBUG or netcat to port 23)

From our defaults, LED on GPIO13 indicates WiFi state... just switch it to a different mode?
```
set ledMode0 relay
reload
```
