### ISSUE TITLE
Thermostat remote temperature is not setting

### ISSUE THREAD

**Issue by GardnerAlex** [xoseperez/espurna#2585]
### Device

NodeMCU V3; Wemos D1 Mini

### Version

1.15.0-dev.git2e19de7a

### Question

I'm trying to set up remote temperature for thermostat module.

Apparently I'm doing something wrong

1) Setting Remote sensor name as `ALGARD-54EC98` (my device name with thermo sensor)
2) Can see in logs: 
`[131574] [MQTT] Received ALGARD-54EC98/data => {"datetime":"2023-03-25 07:20:03","mac":"C8:C9:A3:54:EC:98","host":"ALGARD-54EC98","ip":"192.168.1.90","id":118,"temperature":25.00}`
3) Than nothing

Previously it was partially working with DHT-22 remote sensor, but it was setting humidity instead of temperature value
The JSON message was in topic `ALGARD-54EC98/data`:
`{"datetime":"2023-03-25 06:32:44","mac":"C8:C9:A3:54:EC:98","host":"ALGARD-54EC98","ip":"192.168.1.90","id":21,"temperature":25,"humidity":25}`

### Here are screenshot of Thermostat settings:
![image](https://user-images.githubusercontent.com/55346898/227704374-16d7cef3-d8e1-4a0d-97b7-80ed3b1ed6ad.png)
### Debug console:
![image](https://user-images.githubusercontent.com/55346898/227704405-87742196-620b-4fa9-b02a-8f4a52736f65.png)

**Comment by mcspr** [comment]
Nothing wrong, just invalid key being used.

> it was setting humidity instead of temperature value

Some time ago topic handling was changed, where it should've retrieved 'temperature' string it got 'humidity' (meaning *topic-string-at-magnitude-index* for the *local* device, where temperature is 0th and humidity is 1st magnitude; temperature ID is 1, so humidity was used)
