### ISSUE TITLE
Version 15 Domoticz S26

### ISSUE THREAD

**Issue by tonymerce** [xoseperez/espurna#2596]
### Device

Sonoff S26

### Version

1.15.0

### Bug description

With version 1.15.0, the idx is not saved in the domoticz section. I had to put 1.13.5.

**Comment by mcspr** [comment]
> With version 1.15.0, the idx is not saved in the domoticz section. I had to put 1.13.5.

Note that previously configured things would've worked just fine, only UI reported invalid settings. See `get dczRelay0` and `get dczRelayIdx0` output in terminal. `...Idx0` is the correct setting, fixed above.

Version downgrade is a dangerous thing, especially between versions that have two different ESP8266 SDKs. I would not really recommend doing it often (...unless it also erases the flash of the device. both our settings, and SDK via `erase.config` or esptool write setting)
