### ISSUE TITLE
Sonoff Pow 3 (POWR316D) support

### ISSUE THREAD

**Issue by vreesie18** [xoseperez/espurna#2597]
### Description

Is there any chance for support for the Sonoff  Pow 3 (POWR316D) device on a short notice ?

**Comment by mcspr** [comment]
Check out https://templates.blakadder.com/sonoff_POWR316D.html
This is ESP32 device, we are still on ESP8266 builds. Pending #687 (...and since it has to do with a major software stack changes)

**Comment by vreesie18** [comment]
Thanks, already running Tasmota now on this device (seems only option for now). Actually I left Tasmota on all my devices in favor of Espurna. Unexplainable hick-ups (power drops) in Tasmota made me decide to do this.
