### ISSUE TITLE
Espurna and XKC-Y25-NPN non-contact liquid level sensor

### ISSUE THREAD

**Issue by analistamarcioprado** [xoseperez/espurna#2604]
### Device

NodeMCU

### Question

Good morning community.

I'm trying to use the Espuna with NodeMCU Lolin v3 and an XKC-Y25-NPN non-contact liquid level sensor.

I compiled Espurna with 1 INPUT type digital sensor (D1) and connected the sensor to pin D1.

However, strange behavior is occurring.

Espurna only detects the liquid once. It goes from state 0 to 1 and does not return to state 0, even if you are not detecting liquid.

The Espurna only returns to state 0 if you physically disconnect the sensor and connect it again.

Please, can anyone help me?

Thank you very much in advance.

**Comment by mcspr** [comment]
I would guess there is no pull-up or down for the input?

https://github.com/xoseperez/espurna/wiki/Sensors#generic-digital-sensor does mention internal pull-up, but it might not work as expected on all boards (as I do remember that Wemos and Nodemcu include their own internal pull-ups on some of the pins)

**Comment by mcspr** [comment]
Another thing to note is read & report, and the time it takes for 1.0 to change into 0.0

By default, readings happen every 6s. Reporting - every 10 successful readings. When values are read, raw value (either 1.0 or 0.0 in case of digital sensor) are passed into a filter. And, by default, this filter is 'max'.

```
get digitalFilter0
> digitalFilter0 => max (default)
```

Meaning, if it registers 1.0 at least once during read & report cycle - read and reported value become 1.0 until the next one (i.e. now + 60seconds)

Setting it to 'last' instead would show real read values and report the latest read value during the read & report cycle.
```
set digitalFilter0 last
reset
```
(reboots the device)
