### ISSUE TITLE
Domoticz/MQTT sensor "svalue" missing when sending MQTT message (truncated)

### ISSUE THREAD

**Issue by toniSg** [xoseperez/espurna#2605]
### Device

Wemos D1 Mini

### Version

1.16.0-dev.git864ba0a1

### Bug description

When using Espurna to report incremental count events (water metering) to Domoticz (via MQTT) no counts are actually accumulated by Domoticz.

Following some investigations, it appears the mqtt message sent by Espurna is truncated and only carries the "nvalue" : **{"idx":52,"nvalue":0}** while the expected syntax is like **{"idx":52,"nvalue":0,"svalue":"0"}**.

By digging further, I'm suspecting a wrong allocation size of the StaticJsonBuffer (code/espurna/domoticz.cpp line 338) which is too short causing the third assignement (line 342: _root[F("svalue")] = svalue;_) to fail. I've increased the StaticJsonBuffer size (adding 64) to include the string duplication and it works.

### Steps to reproduce

- Compile Espurna with EVENTS_SUPPORT=1
- Enable and configure Domoticz and MQTT
- Looking at the Debug log will show the truncated JSON : [103911] [MQTT] Sending domoticz/in => {"idx":52,"nvalue"} (PID 1)
- 

### Build tools used

Custom build using the following platformio_override.ini :
[env:wmeter]
extends = env:esp8266-4m-base
build_src_flags = -DWEMOS_D1_MINI -DUSE_CUSTOM_H -DEVENTS_SUPPORT=1 -DEVENTS_PIN=12 -DEVENTS_INTERRUPT_MODE=3

And the following custom.h:
#define NOWSAUTH
#define ALEXA_SUPPORT 0
#define HOMEASSISTANT_SUPPORT 0
#define THINGSPEAK_SUPPORT 0

--------------------------  ---------------------------------------------------------
PlatformIO Core             6.1.15
Python                      3.12.3-final.0
System Type                 windows_amd64
Platform                    Windows-11
File System Encoding        utf-8
Locale Encoding             cp1252
PlatformIO Core Directory   C:\Users\x\.platformio
PlatformIO Core Executable  C:\Users\x\.platformio\penv\Scripts\platformio.exe
Python Executable           C:\Users\x\.platformio\penv\Scripts\python.exe
Global Libraries            0
Development Platforms       2
Tools & Toolchains          7
--------------------------  ---------------------------------------------------------

**Comment by mcspr** [comment]
> By digging further, I'm suspecting a wrong allocation size of the StaticJsonBuffer (code/espurna/domoticz.cpp line 338) which is too short causing the third assignement (line 342: root[F("svalue")] = svalue;) to fail. I've increased the StaticJsonBuffer size (adding 64) to include the string duplication and it works.

...or removing F(...) around the string, going back to cstring as-is. Assigned value size is static already, so should be back to normal that way
Looking at b23137f414358f73fe30089c94fd8bdd8b6f49ad this is just trading 12bytes of ram for an awkward buffer management :/
