### ISSUE TITLE
thingspeak settings are not showing the actual sensors configured

### ISSUE THREAD

**Issue by tibi03** [xoseperez/espurna#2614]
### Device

nodemcu lolin

### Version

1.17.0-dev

### Bug description

i am using 2 sensors BMP280 and MAX6675 on default pins readings are good but in thingspeak settings the sensors are not displayed and canont di the mapping with channels: 
![image](https://github.com/user-attachments/assets/95128b10-3e2c-40d7-9ae8-a97f1044a490)
![image](https://github.com/user-attachments/assets/b29bf918-7ba9-4181-9e51-700f5719c670)

**Comment by mcspr** [comment]
Should be fixed in current dev @ https://github.com/xoseperez/espurna/commit/08c4cdd3c02bfa1daca46bea9d638efeca0f2149 ?
Input names should now properly set the 'magnitude' id to render
