### ISSUE TITLE
WiFI settings not possible with V1.17 - clears always the SSID field after few seconds

### ISSUE THREAD

**Issue by knopserl** [xoseperez/espurna#2615]
### Device

AISIRER AWP07L

### Version

1.17-dev

### Bug description

when connection to the AP 192.168.4.1 for initial WiFi configuration it shows all networks and when I enter the SSDI and the WiFi password, it always makes the SSID field empty in about 5 seconds and even if I'm fast enough to copy the SSID and password and save it, it does never stores any WiFi settings although it says changes saved but the the SSID slot is always empty. 
I have set the correct pins and via the 192.168.4.1 AP, switch on/off works and also voltage readings seems to be ok.

### Steps to reproduce

power on and it always shows ESPURNA_<chipid> and let me connect and open the Web UI but never allows WiFi settings

### Build tools used

I used VS Code and PIO all latest version. Build was successful and also the upload initially via soldered serial adapter

**Comment by mcspr** [comment]
> I used VS Code and PIO all latest version

fyi you can always embed wifi settings (or often any other setting, for that matter) and skip the webui step when flashing the device
https://github.com/xoseperez/espurna/wiki/WiFi
