### ISSUE TITLE
Web interface does not load on Safari (1.10.0)

### ISSUE THREAD

**Issue by xoseperez** [xoseperez/espurna#295]
Originally reported by: **Vishal Chaudhary (Bitbucket: [vishix](https://bitbucket.org/vishix), GitHub: [vishix](https://github.com/vishix))**

----------------------------------------

The web interface does not load at all on safari. Ver 1.10.0

**Comment by andreaslink-de** [comment]
Did I get it right, this was identidfied and fixed, in which version is this iOS fix finally included?

And sad, I was looking for me in here, can you rename the match you have between Bitbucket and github? On Bitbucket I'm "andreaslink" but on github only "andreaslink-de" was free, so the name you merged me, is existing, but it is not me :-/.

**Comment by xoseperez** [comment]
I have opened a new issue regarding this problem.

@andreaslink-de  I'm sorry about the names. The script I used assumed that if the name was the same on both platforms it should be the same person. I just could not contact anyone asking for your GitHub names...

**Comment by mikkorantalainen** [comment]
> ![Screen Shot 2017-12-08 at 21.03.57.png](https://camo.githubusercontent.com/a4fb71d9eed3796ae03e510db9f4c01dcf6baac7/68747470733a2f2f6269746275636b65742e6f72672f7265706f2f4b42796441792f696d616765732f3630303530303032312d53637265656e25323053686f74253230323031372d31322d3038253230617425323032312e30332e35372e706e67)
> 
> Here is error log from browser. This is from dev branch, from normal branch I only get 1 message, but the message is exactly same.

I got that kind of error messages when the parent web page as using Basic Auth and it turned out that Safari was the only browser that did NOT send the same Basic Auth headers to websocket connections.
