### ISSUE TITLE
How to update wiki?

### ISSUE THREAD

**Issue by xoseperez** [xoseperez/espurna#305]
Originally reported by: **Alex Goris (Bitbucket: [vyruz1986](https://bitbucket.org/vyruz1986), GitHub: [vyruz1986](https://github.com/vyruz1986))**

----------------------------------------

Hi there,

An issue is probably not the right place to ask this, but how do I update the wiki?
I forked this repo and added support for a Wemos D1 mini with DHT22 shield (copy/pasta of relay shield with minor changes) and I'd like to make a PR to get this back upstream.
However I'd like to update the wiki as well so the board is immediately documented. I can't seem to clone your wiki repository (which is separate from code anyway it seems?)

**Comment by vincegre** [comment]
Should be updated for Github now that you left Bitbucket for espurna :)
