### ISSUE TITLE
password reset

### ISSUE THREAD

**Issue by xoseperez** [xoseperez/espurna#308]
Originally reported by: **ThatOneGuy (Bitbucket: [Grimmy347](https://bitbucket.org/Grimmy347), GitHub: [Grimmy347](https://github.com/Grimmy347))**

----------------------------------------

I have forgotten my password to my sonoff basic.  How can I change/reset it?  I have reflashed it but nothing seems to reset the password.  is there a way I can see what it is manually through code?

**Comment by beng7** [comment]
> Yeah, that's a way, albeit a drastic one. Another option would have been to log via telnet and reset it there.

Hi
Can you please tell me what is the command to do so, i would like to avoid having to reflash?
Thanks in advance

**Comment by mcspr** [comment]
> > Yeah, that's a way, albeit a drastic one. Another option would have been to log via telnet and reset it there.
> 
> Hi
> Can you please tell me what is the command to do so, i would like to avoid having to reflash?
> Thanks in advance

@beng7 `factory.reset`, then `reset`. if there is a physical button, hold it for >10 seconds and release
