### ISSUE TITLE
wifi behaviour

### ISSUE THREAD

**Issue by xoseperez** [xoseperez/espurna#331]
Originally reported by: **Oskari Rauta (Bitbucket: [oskarirauta](https://bitbucket.org/oskarirauta), GitHub: [oskarirauta](https://github.com/oskarirauta))**

----------------------------------------

If connection to Wifi AP is interrupted ( for example in case where router has rebooted ) - device running espurna creates it's own wifi and sticks there.

In this case, home automation is no longer an option, since device is no longer in LAN. If there are APs setup for device, once in a while, these should be searched and device should try joining to them.

**Comment by mcspr** [comment]
Closing, #449 describes this as resolved

**Comment by luisgcu** [comment]
Hello guys, 
I have  3 sonoff devices running the following espurna version and I have that exact problem, devices are losing wifi credential, I think it happens after I have restarted my router. It happens very often .
![image](https://user-images.githubusercontent.com/11203310/49688995-69d93780-fae8-11e8-952f-1d0ba51a1bd0.png)
By the way @xoseperez  mis respetos para usteded y todos los colaboradores de Espura. Yo le envie mi modesta contribucion. 
Muchas gracias por todo el trabajo para la comunidad!
