### ISSUE TITLE
Magic Home (v1.4 and v2.0) displaying colors wrongly

### ISSUE THREAD

**Issue by xoseperez** [xoseperez/espurna#345]
Originally reported by: **Jannis Lehmann (Bitbucket: [Cludch](https://bitbucket.org/Cludch), GitHub: [Cludch](https://github.com/Cludch))**

----------------------------------------

Hello,

today I flashed both my Magic Home RGB (not RGBW) controller to use espurna. One is version 1.4 and the other 2.0.

But both are displaying the colors not correctly.
The 1.4 shows only green and the brightness slider somehow makes it blue-ish.

The 2.0 shows for green when selecting blue. Shows red when selecting yellow amd channel 4 controls blue.
I tried a few things but was unable to find the issue. Could this be related to the mapped GPIOs or could this even be a hardware failure?

**Comment by xoseperez** [comment]
@Cludch Any update on this? Yesterday I pushed a commit to the dev branch (4b2a4ffaa40aefc3c2a59c754e6b2ce90def3e9b) with support for MagicHome LedController board revision 2.3 which swaps red and green channels compared to 2.0. Maybe that is the reason for this issue?

**Comment by Cludch** [comment]
Will look into this and report back during the weekend.

**Comment by Cludch** [comment]
I'm sorry, I won't have the time to rest this since I removed my stripes and dont have cables soldered to the controller.
My guess is that I broke the controller since it didnt work with other software either.

**Comment by xoseperez** [comment]
Closing it then. Feel free to open it again in the future.
