### ISSUE TITLE
BME280 sensor read Temperature, Humidity, Pressure

### ISSUE THREAD

**Issue by xoseperez** [xoseperez/espurna#353]
Originally reported by: **Stefano Cotterli (Bitbucket: [faina09](https://bitbucket.org/faina09), GitHub: [faina09](https://github.com/faina09))**

----------------------------------------

I have a BME280 sensor linked via wire protocol to GPIO0 (SData) and GPIO2 (SClock) and I tested hardware with the following sample code; after this I can read Pressure, Temp and Humidity values from sensor:

```
#!arduino

#include <Adafruit_BME280.h>

Adafruit_BME280 bme; // I2C

void bme280Setup() {
    Wire.begin(0, 2);
    Wire.setClock(100000);
delay(2ms)
    bme.begin();
float tc = bme.readTemperature();
....
}
.....
```

In ESPurna I set the following defines:

```
#!arduino
#define BMX280_SUPPORT         1
#define I2C_SDA_PIN         0
#define I2C_SCL_PIN         2

```
the i2c bus starts but searches for a BMP280

```
#!arduino

[I2C] Using GPIO0 for SDA and GPIO2 for SCL
[I2C] No devices found
[SENSOR] BMP280 @ I2C (0x00)
[SENSOR]  -> ERROR 6
```

What is wrong or what I missed in my ESPurna configuration?

**Comment by xoseperez** [comment]
@hanyinfo Any update on this?

**Comment by hanyinfo** [comment]
yes... I tried few minutes ago and I can see the values on status page together with 8 switches. I can see Sensors configuration with temperature. Thanks for help!

in hardware.h

#elif defined(GENERIC_8CH)

 #define I2C_SDA_PIN         D3
 #define I2C_SCL_PIN         D4

and in arguino.h
#define BMX280_SUPPORT         1

**Comment by xoseperez** [comment]
Great.

To recap: there is still the issue @fain09 reported. Looks like his BME280 requires some time to warm up before being accessible. I'm receiving another sensor tomorrow. Will try to reproduce the issue.

**Comment by xoseperez** [comment]
With the latest changes in the sensors branch the BMX280Sensor has been tested under pressure, hot-unplugging and plugging it, and it always recovers.
