### ISSUE TITLE
Correction other values than temperature

### ISSUE THREAD

**Issue by xoseperez** [xoseperez/espurna#378]
Originally reported by: **Marek Forkasiewicz (Bitbucket: [fork04](https://bitbucket.org/fork04), GitHub: [fork04](https://github.com/fork04))**

----------------------------------------

Adding ability to correct other values than temperature in "SENSOR CONFIGURATION"

**Comment by mcspr** [comment]
Closing via d9cb35f7814fdb90ca413f7474f0c915a56cbd24
