### ISSUE TITLE
SonOff 4Ch will not update OTA

### ISSUE THREAD

**Issue by xoseperez** [xoseperez/espurna#395]
Originally reported by: **ElMarconi (Bitbucket: [ElMarconi](https://bitbucket.org/ElMarconi), GitHub: [ElMarconi](https://github.com/ElMarconi))**

----------------------------------------

There was an error trying to upload the new image, please try again (ERROR 8).
Reboot does not help either.

**Comment by tita1705** [comment]
Hi, is there an option without flashing again, e.g. by setting the size manually? The problem is that its hard to reach for the module again and hook it to the serial connection. Thanks for your help. regards Timo
