### ISSUE TITLE
MQTT: Feedback when changing relay-button on WebUI

### ISSUE THREAD

**Issue by xoseperez** [xoseperez/espurna#400]
Originally reported by: **Joerg (Bitbucket: [joergjanes](https://bitbucket.org/joergjanes), GitHub: Unknown)**

----------------------------------------

Hi!

I checked the MQTT-messages send by my espurna device (HomeMagic 2.2 LED controller) with mqtt-spy and found no messages reporting the current state of the relay?

Is it possible to add some MQTT feedback messages, when the relay button on the web interface was pressed or the status of the relay has changed?

In tasmota, I got a result-mqtt-message after each status change, so I could display the correct status of the device in my own home automation system ...

Thanks for your support
Joerg

**Comment by xoseperez** [comment]
@bluexp Can we summarize what we have here?

**Comment by bluexp1** [comment]
The problem is that subscription to relay does not work (there is no output) when json payload is enabled.

**Comment by xoseperez** [comment]
When JSON output is enabled there is no relay topic. Relay info is sent to the `{root topic}/data` MQTT topic.

**Comment by bluexp1** [comment]
but this is not expected behavior according to the note on mqtt page: "Subscribtions will still be done to single topics",
Anyway, this could be a feature request.

**Comment by xoseperez** [comment]
Yes, regardless of the "Use JSON payload" value, ESPurna will still subscribe to the single topics. But of course, you should subscribe to the `{root topic}/data` topic to get the messages from ESPurna.

**Comment by xoseperez** [comment]
Closing this. Please feel free to reopen if required.
