### ISSUE TITLE
SONOFF_POW saving Energy #0 state

### ISSUE THREAD

**Issue by xoseperez** [xoseperez/espurna#403]
Originally reported by: **Marek Forkasiewicz (Bitbucket: [fork04](https://bitbucket.org/fork04), GitHub: [fork04](https://github.com/fork04))**

----------------------------------------

Saving periodicaly (with timestamp?) value of Energy #0 locally in flash to prevent data loss after reboot

**Comment by mcspr** [comment]
...it is already working?
Every `ENERGY` magnitude is persisted between clean (not crashes) reboots and optionally saved into the flash as `eneTotalN` where N is global magnitude index when `snsSave` is enabled

Timestamping could use some work, but I think that would be better served via another issue.
