### ISSUE TITLE
MagicHome v2 Led Strip - White Channel

### ISSUE THREAD

**Issue by xoseperez** [xoseperez/espurna#418]
Originally reported by: **Danilo Daloiso (Bitbucket: [Danny89530](https://bitbucket.org/Danny89530), GitHub: [Danny89530](https://github.com/Danny89530))**

----------------------------------------

Hi,
I'm trying to set white channel on Magic Home LedStrip v2 via MQTT but, when i try to obtain white color, I got two different situations:

* If I set RGB values to 255 the led stop working and the lights turns off till one of the three values will be decreased.
* If I set the **<root>/channel/3/set** to 255:
    * If RGB are at 0 Nothing happens
    * If RGB are at not equal to 0, the leds stop working

Regards

**Comment by Danny89530** [comment]
Hi @xoseperez sorry for the delay.
I've modified the configuration as your suggestion, disabling the colorpicker and using the 4 channels dimmers but nothing change. I Think there are no difference modifying the color via MQTT (single color) channel or via these four dimmers.
When I change the value of the 4th dimmer, the White one, nothing happen.

Regards,
Danny

**Comment by xoseperez** [comment]
My guess is that either the board has a different layout or it's faulty.

**Comment by Danny89530** [comment]
IMHO the first one is the answer, that because I've two different MagicHome controllers and both with same _problem_.

**Comment by xoseperez** [comment]
@Danny89530 Can you post a picture of the board here? Both sides

**Comment by xoseperez** [comment]
I'm going to close this since there has been no feedback for months. Please, feel free to reopen if necessary.
