### ISSUE TITLE
Upnp Presentation URL

### ISSUE THREAD

**Issue by xoseperez** [xoseperez/espurna#423]
Originally reported by: **Peter (Bitbucket: [PG1234](https://bitbucket.org/PG1234), GitHub: [PG1234](https://github.com/PG1234))**

----------------------------------------

Hi, can you please add the Upnp presentation Url function. With that it's possible to find the devices in the Windows Network Neighborhood and with Upnp tools. It's small, only some lines of code and helps a lot during commissioning or with DHCP configured devices.

Peter

**Comment by xoseperez** [comment]
Will be released with 1.12.2

**Comment by pit001** [comment]
Hi - it works well !
Looks like this in Win7:

![2018-11-11 07_52_54-netzwerk](https://user-images.githubusercontent.com/9020941/48310045-d06d4300-e586-11e8-818b-7792a5795749.png)

![eigenschaften von espurna_29dbbb_0](https://user-images.githubusercontent.com/9020941/48310046-d531f700-e586-11e8-90e2-07aaefcbe3ce.png)


Two things:
1) It's no tnessesary to report each relay/switch. Only the hole device.
2) Something is wrong with the data (mayby one parameter missing) the simple double click on the icon doesn't open the browser. I will check this.

(The Sonoff GW has no Upnp enabled ?) 

Additional a description field in the Espurna Settings would be interesting. Like 'Switch in the Kitchen'. This could than also be visible in the Upnp Properties. 

Peter

**Comment by philbowles** [comment]
I know I'm a year too late, but if you would prefer them to look like this: 
![image](https://user-images.githubusercontent.com/27769598/72074849-f4472880-32f2-11ea-98b1-9c7bf01cea78.png)

..then let me know: it's pretty easy change...

**Comment by mcspr** [comment]
If you mean Belkin names from the screenshot above, I think those are from Alexa (back when it was announcing as Belkin Wemo and not Hue bridge)
Stuff that was added is enabled via SSDP_SUPPORT=1 define:
https://github.com/xoseperez/espurna/blob/master/code/espurna/ssdp.ino
