### ISSUE TITLE
Could sonoff Rf Bridge send received codes for on/off even if switch already in that state

### ISSUE THREAD

**Issue by xoseperez** [xoseperez/espurna#426]
Originally reported by: **Matt Cholawo (Bitbucket: [MattCholawo](https://bitbucket.org/MattCholawo), GitHub: Unknown)**

----------------------------------------

I'm using the sonoff bridge to receive signals from my pre-existing burglar alarm pir sensors, so that my smart home can know what rooms are occupied.   My pir sensors only send one signal when triggered.  I save the signal sent by the pir sensor as 'On' for a "switch" in the rf bridge, and then listen for that in domoticz.
My issue is that the rf bridge only sends the 'On' signal to domoticz when the switch is set to 'Off'.   So I have to automate turning switches off whenever the rf signal is received to ensure that I can receive an 'On' command by mqtt.
What I'd really like is for the rf bridge to send mqtt when it receives an 'On' rf signal, even if the switch is already 'On'.   
I guess that really this is an issue for me because the software is set up around the notion of 2-value switches, rather than single-value sensors.   Ideally I'd like to split out the 8 switches into 16 discreet things where espurna doesn't care what they are and has no logic for 'On' or 'Off'.   But for now, just the ability for repeat 'On' commands received by the bridge to be sent over mqtt would be really helpful. Thanks!

**Comment by cholawo** [comment]
Thanks @xoseperez I've done precisely that and it's all working well.  I moved all the logic to node red and haven't looked back since!

**Comment by xoseperez** [comment]
Thanks to @Teek5!
