### ISSUE TITLE
wifi AP mode does not accept connections

### ISSUE THREAD

**Issue by xoseperez** [xoseperez/espurna#428]
Originally reported by: **Erwin (Bitbucket: [elonden](https://bitbucket.org/elonden), GitHub: [elonden](https://github.com/elonden))**

----------------------------------------

When flashing a H801 LED controller and restarting it the AP SSID comes up with the previous hostname I'd set. For some reason it does not accept the default wifi password (fibonacci)  and it is also unable to connect to the WIFI access point it previously used.

Is there a way to reset the entire ESP to default in such a way it uses only default settings as per ESPurna code.

**Comment by xoseperez** [comment]
@elonden Any update on this?

**Comment by elonden** [comment]
xose, yetarday I did somemaintenance on my wifi network and the H801 did disconnect. It was only able to reconnect after I manually unplugged the DC power supply, waited for +- 2 minutes, and powered it back up again. The WIFI maintenance took approximately 1 hour in which time no device could connect on 2.4g or 5G. The Sonoff POW's had no issue reconnecting automatically again. The SSID and passwords did not change.

It seems there is still something weird going on in the H801 code.

**Comment by xoseperez** [comment]
There is nothing different wifi-related between the POW and the H801... I would first explore coverage. You can run a wifi scan on both to see what RSSI they have to the router.

**Comment by xoseperez** [comment]
I'm going to close this since there has been no feedback for months. Please, feel free to reopen if necessary.

**Comment by elonden** [comment]
Hello Jose,

My apologies. No worries. Fine to have this closed.
