### ISSUE TITLE
Multiple MQTT reconnects

### ISSUE THREAD

**Issue by xoseperez** [xoseperez/espurna#429]
Originally reported by: **Albert Weterings (Bitbucket: [AlbertWeterings](https://bitbucket.org/AlbertWeterings), GitHub: Unknown)**

----------------------------------------

With the latest version I see multiple reconnects on MQQT witch I did not see in lower versions. Don't know if this is ok?

Attached logging of two devices.

**Comment by xoseperez** [comment]
Closing it for now.
Please, feel free to reopen the issue if happens again so we can do some tests to find out what's going on.

**Comment by AlbertWeterings** [comment]
MQTT Broker reconnection is solved by reading issue #572 reported by gd-99 witch is already closed. It solves this issue after setting IwIP variant to V1.4 Prebuilt MQTT disconnects are gone. Compiled in Arduino IDE with esp8266 Community version 2.4.0.
