### ISSUE TITLE
Sonoff 4Ch Pro random turn on/off

### ISSUE THREAD

**Issue by xoseperez** [xoseperez/espurna#434]
Originally reported by: **Pavel Sláma (Bitbucket: [pilotak](https://bitbucket.org/pilotak), GitHub: [pilotak](https://github.com/pilotak))**

----------------------------------------

Hi,
I just wanted to ask about default configuration of DIP switches. I have K5 to 1111, K6 to 0000 adn S6 to 1, but when switch it on with MQTT group option, it turns off automatically after random time 2 min, 8 min, 10 min but not always. When I switch it on by button and then off it sometime turns on again itlsefs,  again random time mostly 10 sec. Is it something to do with DIP config or is it a bug in code? Thanks

**Comment by xoseperez** [comment]
@pilotak and you don't see that message when subscribed to '#'? Who is sending it?

**Comment by pilotak** [comment]
I am subcribed to to everything (#, QoS:2) and there is no message delivered when debug shows up.

**Comment by xoseperez** [comment]
I can't think of a reason for those messages. It could be a retained message but then it will only show up once on connect, not every 20 seconds.

**Comment by pilotak** [comment]
I just checked, this is a retain message. This would mean that it's either subscribing to "MQTT group" every 20 sec or it's reconnecting to broker every 20 sec

**Comment by xoseperez** [comment]
If it was there would be messages in the debug log showing the reconnect process, same thing for the subscribing... What broker are you using? Maybe it's the QoS. The async-mqtt-client claims it supports QoS 0, 1 and 2 both to publish or subscribe but...

**Comment by chryss44** [comment]
I don’t use any broker :-(
I have just compile 1.12.2 and try to parameter it.
I have complet my issue with log, i hope it help you.

The first Idea are to test SSDP :-)

**Comment by chryss44** [comment]
Sorry, i’ts a mistake, this message are not for this issue.

**Comment by pilotak** [comment]
I'm using mosquitto on raspberry

**Comment by xoseperez** [comment]
I'm lost here. I think the best option is to go back to the basics. I would build and flash a simple MQTT script like this one: https://github.com/marvinroger/async-mqtt-client/blob/master/examples/FullyFeatured-ESP8266/FullyFeatured-ESP8266.ino. Modifying the onMqttConnect method to only subscribe to the topic you are seeing...

**Comment by pilotak** [comment]
This is my setup

![mqtt](https://user-images.githubusercontent.com/8101753/35433337-645bf06c-0283-11e8-91dc-e3ebd5bd6bfd.png)
![switch](https://user-images.githubusercontent.com/8101753/35433338-6479eafe-0283-11e8-8498-da3e7f39a45e.png)

**Comment by xoseperez** [comment]
Sorry, still nothing. If there is something with the firmware I would investigate the async-mqtt-client library. Can you give a try to the example I posted before?

**Comment by pilotak** [comment]
well this is going to be difficult as it's not really accesable and is on remote connection so i can't do it through Arduino IDE because i'm accesing it through VPN -> port forwarding. It will not discover it as remote serial. But i will my best and maybe travel there.

**Comment by xoseperez** [comment]
Do you have the chance to try to reproduce the issue with a local device, something you can play with?

**Comment by pilotak** [comment]
I have not had a change to travel there, so i tried sonoff dual using MQTT group and it works as it should (although with 1.12.3) Unfortunately i don't have any other 4CH Pro to try out

**Comment by xoseperez** [comment]
I'm going to close this since there has been no feedback for months. Please, feel free to reopen if necessary.

**Comment by docsparks** [comment]
using even the stock firmware and latest 1.7.2 firmware , I have an issue with port1 randomly turning on (plug 1?) on my sonoff 4ch pro r2.     any suggestions as to why? no schedule or timer setup, all other switches work correctly.  worth flashing tasmota to test otherwise or possible to have a faulty unit? and feedback would be awesome thank you

**Comment by cracautanu** [comment]
Hey guys, I got the same issue with a sonoff 4 channel pro RF. I installed it on a Nice sliding gate motor and each time I was entering the house, the gate was opening :))) Not the kind of behavior I was expending, but I figured it out. It seemed that the motion sensors of the alarm were triggering the sonoff. The solution was to remove the rf antena from the device. Works like a charm now, the gate won't open when I go to sleep or when I'm visited by thiefs. Cheers!

**Comment by pilotak** [comment]
@cracautanu thanks for the tip! it kind of works now so when it starts to do those things again i will detach the antenna.

**Comment by luislorenzo** [comment]
Hi
I read somewhere that you have to put the "retain" to false to avoid the problem with the MQTT restart.

When the MQTT restart, the system send anohter time the value send previously, another time. If you put the retain to FALSE, this problem with the MQTT restart disapear.

**Comment by pilotak** [comment]
@luislorenzo I use Mosquitto as a broker and there was no restart during that period.
What makes more sense to me is the solution by @cracautanu
