### ISSUE TITLE
TH10 unable to read from AM2301 sensor

### ISSUE THREAD

**Issue by xoseperez** [xoseperez/espurna#444]
Originally reported by: **Bradley Gamble (Bitbucket: [BakaOsaka](https://bitbucket.org/BakaOsaka), GitHub: [BakaOsaka](https://github.com/BakaOsaka))**

----------------------------------------

I have a Sonoff TH10 that I have successfully flashed with the firmware binary ```espurna-1.12.0-itead-sonoff-th.bin```.

I attached my Asair AM2301 Temperature/Humidity sensor to it, expecting to see values in the web interface. However, the device reported "Timeout".

Upon connecting via telnet, I see the following message printed periodically:
```[SENSOR] Error reading data from DHT22 @ GPIO14 (error: 3)```

I believe error 3 refers to the following definition:
```#define SENSOR_ERROR_TIMEOUT        3       // Response from sensor timed out```

As far as I am aware, the AM2301 is a DHT21 as opposed to DHT22, however the protocol is compatible.

**Comment by xoseperez** [comment]
@BakaOsaka any update on this?

**Comment by BakaOsaka** [comment]
I have returned the sensor to the distributor under the assumption that it was faulty - I am happy for this issue to be closed until I can prove that it occurs with new hardware.

**Comment by xoseperez** [comment]
Closing then. Feel free to reopen it if you are still having trouble with the new sensor.

**Comment by s4lva2** [comment]
I have same error with same device (Sonoff TH10 + AM2301)

**Comment by jirisemecky** [comment]
I have the same error too, tbe sensor was working with the original sonoff fitmware.

**Comment by Pijuli** [comment]
I'm also having this issue, but it is intermittent. As I go into the th10 panel it shows the values, then Timeout and after a couple of seconds I get the reading again. 
There's no issue for me, as it works perfect over mqtt but it might have something to do.
If I can provide some log or info it'll be a please

**Comment by henkiejan1** [comment]
Hi,

Sorry for reopen this topic. I have the same error with my TH16 and the Si7021 TH sensor. And i have also to downgrade but that doesn't fix it. I have also not after a short time the values. Nothing, In my log i read this:
[code]
[683568] [SENSOR] Error reading data from DHT22 @ GPIO14 (error: 3)
[689326] [SENSOR] Error reading data from DHT22 @ GPIO14 (error: 3)
[695329] [SENSOR] Error reading data from DHT22 @ GPIO14 (error: 3)
[701336] [SENSOR] Error reading data from DHT22 @ GPIO14 (error: 3)
[707340] [SENSOR] Error reading data from DHT22 @ GPIO14 (error: 3)
[713340] [SENSOR] Error reading data from DHT22 @ GPIO14 (error: 3)
[719591] [SENSOR] Error reading data from DHT22 @ GPIO14 (error: 3)
[725349] [SENSOR] Error reading data from DHT22 @ GPIO14 (error: 3)
[731351] [SENSOR] Error reading data from DHT22 @ GPIO14 (error: 3)
[737354] [SENSOR] Error reading data from DHT22 @ GPIO14 (error: 3)
[743363] [SENSOR] Error reading data from DHT22 @ GPIO14 (error: 3)
[749373] [SENSOR] Error reading data from DHT22 @ GPIO14 (error: 3)
[755624] [SENSOR] Error reading data from DHT22 @ GPIO14 (error: 3)
[/code]

**Comment by henkiejan1** [comment]
@xoseperez thank you for reopen this. I hope that i could give you enough information. If not please ask. :) I am new here so maybe i have something not correct.

**Comment by xoseperez** [comment]
I have just tested it and it worked :disappointed: (I prefer to be able to reproduce bad behaviors...).

Error 3 means TIMEOUT. It could be a sensor failure or a wiring failure. Assuming nothing has changed in the wiring, do you have the chance to test the sensor with another device?

**Comment by mattster98** [comment]
[Solved, for me]  I have been having this same issue, and tried the latest version (1.13.0) on a second unit.  At first I didn't get any sensor reading (same error - 3).  Then I saw a bit of silver showing between the plug and the socket so I pressed the sensor plug in firmly and got another click.  Sensor started working.  I had the cover off, so I could easily see that I had completely inserted it.

I went back to my original unit and tried again (1.12.6) making sure to plug the sensor in all the way, but it still didn't work.  This one still had the cover on.  I pushed even harder to get a good connection and finally got the sensor to work on 1.12.6.

So, for me, this is a hardware issue - the jack requires a lot of pressure to seat fully, and the cover doesn't seem to have enough clearance to allow for this without a lot of effort.  I'll be expanding the hole around that jack to make it easier in the future and more reliable that it will stay completely plugged in.

Image showing the plug up close:
![image](https://user-images.githubusercontent.com/1469426/41855184-023c7cdc-7860-11e8-8234-6234535ab8d0.png)

**Comment by xoseperez** [comment]
Thank you @mattster98, I hope you don't mind I have added your picture to the wiki (of course, with proper attribution).

**Comment by s4lva2** [comment]
wow, my problem is the same, a connection jack issue.  the problem was solved after following  @mattster98's advise
Thanks!

**Comment by henkiejan1** [comment]
Oh i go checking this! You hear from me! :)

**Comment by henkiejan1** [comment]
![afbeelding](https://user-images.githubusercontent.com/40475578/42228032-37d2a752-7ee3-11e8-8b42-10ae7552f6fe.png)

Mines goes to the end in the connector but when i push the connector a little bit to above i get this results! It works. I go try to fix it. So it's not a firmware issue!. Thank you all for your help!! :)

**Comment by xoseperez** [comment]
Closing then!

**Comment by Normalus10** [comment]
Hi i have th10 and si07 sensor, 2 actualy and both not working. Looks like they work first 10 seconds and when humidity gets 98% they both start to show "m0%" wtf is this im piised off

**Comment by ColinShorts** [comment]
@normalus10 it might be better to open a new issue for this. Remember to provide as much detail about the devices as possible - use the template.

**Comment by connected201** [comment]
hi all, i have same problem, this is a new, sonoff TH with AM2301, but i cannot read it!
![firefox_4FPm38yXTM](https://user-images.githubusercontent.com/20506433/65788698-4b6e2680-e164-11e9-90d8-9ca729c120c2.png)

![IMG_20190927_201536](https://user-images.githubusercontent.com/20506433/65788590-16fa6a80-e164-11e9-9850-66df72becf55.jpg)
![IMG_20190927_201628](https://user-images.githubusercontent.com/20506433/65788591-17930100-e164-11e9-850b-57e5e04a1559.jpg)

**Comment by mattster98** [comment]
Anything in the debug output?

**Comment by connected201** [comment]
> 
> 
> Anything in the debug output?
 Error reading data from DHT22 @ GPIO14 (error: 3)

**Comment by mattster98** [comment]
Only a few possibilities in my mind.

1. Plug is still not fully inserted.. really twist and push on it to see if that helps.
2. Sensor is bad in some way (miswired, broken wire, broken)
3. Board is a newer rev and that plug is connected to a different gpio
