### ISSUE TITLE
"Connection repairing"

### ISSUE THREAD

**Issue by xoseperez** [xoseperez/espurna#449]
Originally reported by: **Oskari Rauta (Bitbucket: [oskarirauta](https://bitbucket.org/oskarirauta), GitHub: [oskarirauta](https://github.com/oskarirauta))**

----------------------------------------

I previously posted this issue: #331 

And this is a work-around for the issue.
Option to "force" joining to saved Wi-Fi network (if one is saved) after a time being in AP mode.

In case that for example, kids, use the double tapping feature to enable AP mode.. Or for other reason, AP mode is on (when it should not), and this option is enabled, and AP mode has been on for some time (20 minutes? 30 minutes? 1 hour?) - device will retry to join the wifi network entered in settings.

After all, if you enable AP mode, it is likely, that it was either accidental, or then you are making some changes that cannot be made while joined to "normal wifi" - there's quite a nice set of settings in espurna, but to tell you the truth, there's not much, so even the proposed 20 minutes limit for ap mode, is enough for making changes even though one would change EVERY setting.

**Comment by wsw70** [comment]
Is there a reason why retrying the connection to the AP could not be done continuously every few minutes? Why just once after three minutes?

**Comment by xoseperez** [comment]
If the connection is not successful it will retry again after 3 more minutes, and so on. This as long as it has defined networks in the configuration and there is no active connection to it.

**Comment by wsw70** [comment]
@xoseperez - ah? this is not something I am witnessing with my Sanoff Basic switches. The Sanoff Touch wall switch is OK.

When the WiFi goes down they do not reconnect. I have to power them down (in some cases via a breaker so this is cumbersome) so that they reconnect.

I only see their AP to which BTW I cannot connect - I get an IP (192.168.4.x) but the web page does not open.

I will rebuild the latest firmware tonight and flash it, and be back with the result

**Comment by wsw70** [comment]
OK, all is good.

I recompiled up to https://github.com/xoseperez/espurna/commit/18c9082f89eac39f58dcc7f5af4bd8e11e77ea8e and after switching off the WiFi, seeing the switch go into AP mode, switching back the WiFi - the switch reconnected. I waited 8 minutes (2 x 3 min cycles + "just in case") so the request is not repeated as you said.

Thanks for having followed up my question.
