### ISSUE TITLE
I have no acces to the pull requests site.

### ISSUE THREAD

**Issue by xoseperez** [xoseperez/espurna#451]
Originally reported by: **Cyano95 (Bitbucket: [Cyano95](https://bitbucket.org/Cyano95), GitHub: Unknown)**

----------------------------------------

Hi, this is a very great project. i want to contribute to the project but there is no access for me, how an i send my pull requests ?

**Comment by pelson** [comment]
@xoseperez - I think you can probably close this issue now that it is on GitHub 😉

**Comment by xoseperez** [comment]
The procedure with GitHub is very similar to that on Bitbucket.

Check this documentation for more info: https://help.github.com/articles/creating-a-pull-request-from-a-fork/

Closing.
