### ISSUE TITLE
"NTP server not reachable", compromises time-based features

### ISSUE THREAD

**Issue by xoseperez** [xoseperez/espurna#452]
Originally reported by: **P.B. (Bitbucket: [PieBru](https://bitbucket.org/PieBru), GitHub: [PieBru](https://github.com/PieBru))**

----------------------------------------

Hi Xose, sorry for the partial #238 revival, but the problem persists randomly also in 1.12.1 and it may be crytical for time-based features.

When the error appears, usually immediately at boot, it doesn't recover until the next reset. If it depends on an external library a workaround could be force a reset after N consecutive NTP errors.

No benefits from NTP.setInterval(NTP_UPDATE_INTERVAL / 20, NTP_UPDATE_INTERVAL);

Despite the error, the time is initialized. I added this code at the bottom of loop():

```
#!arduino
    #if DEBUG_SUPPORT
    static unsigned got_year = 0;
    if (got_year < 2018 && year(now()) >= 2018) {
        got_year = year(now()); // Got a sync from some time provider (NTP, RTC, ...)
        DEBUG_MSG_P(PSTR("[MAIN] Time initialized %lu ms after boot, it might be %u-%02u-%02u %02u:%02u:%02u\n")
            , millis(), year(now()), month(now()), day(now())
            , hour(now()), minute(now()), second(now()));
    }
    #endif  // DEBUG_SUPPORT
```

and this is the OK output:

```
#!arduino
[MQTT] MQTT brokers found: 0
[MAIN] Time initialized 7659 ms after boot, it might be 2018-01-21 14:54:53
[NTP] Time: 2018-01-21 14:54:53
[MAIN] System OK
```

but often I get the NTP error (Wemos D1 Mini, default config):

```
#!arduino
[MQTT] MQTT brokers found: 0
[NTP] Error: NTP server not reachable
[NTP] Time: Not set
[NTP] Error: NTP server not reachable
[MAIN] Time initialized 9226 ms after boot, it might be 2018-01-21 14:52:52
[MAIN] System OK
```

This NTP error does not recover even after hours of successful Wifi and MQTT connection, so any time-based feature checking ntpConnected() would not work.

I didn't investigate further, as a trivial solution could be a forced reset.

Piero

**Comment by AlbertWeterings** [comment]
It looks like the "NTP server not reachable" compromises OTA updates. I have numerous devices that fails OTA updates and become corrupted (only upgradable by wired flashing), the NTP module also causes MQTT message delays. For now all my devices that are not time critical I compile without NTP to get them stable.

**Comment by xoseperez** [comment]
There are two possible solutions for this:
* Increase the initial check interval from 15 seconds (current default) to something like 60 seconds.
* Disable NTP checks when OTA is started

The first option is simply changing this line:

https://github.com/xoseperez/espurna/blob/f8907d60395ccfe0d606b4fb24624720fbcd7f51/code/espurna/ntp.ino#L38

to:

`NTP.setInterval(60, NTP_UPDATE_INTERVAL);`

Of course this should be done with a setting in general.h etc.

**Comment by xoseperez** [comment]
You can check the exact version/revision of the libraries I use to compile the release images in the platformio.ini file:

https://github.com/xoseperez/espurna/blob/f8907d60395ccfe0d606b4fb24624720fbcd7f51/code/platformio.ini#L13-L34

The main difference is that I use a fork of German's library that introduces some improvements to the first sync with the NTP server. Likely to be your problem. I did a PR with the changes and German has already merged it but it's in his dev branch, not master yet.

My fork also removes explicit dependency on the Margolis' Time library to use another fork of mine for that one since there is an issue compiling it in Windows machines.

**Comment by AlbertWeterings** [comment]
I spend a few hours experimenting with the "Error: NTP server not reachable" issue and found setting the NTP_TIMEOUT to 2000 in NtpClientLib.h solved the issue for me. With the setting on its original value of 1500 it was reasonable stable at my own NTP server but not on any remote.

Placed a issue in https://github.com/gmag11/NtpClient/issues/56

**Comment by xoseperez** [comment]
I guess your mileage will vary but 2 seconds is plenty of time... Anyway it would be great if @gmag11 could make this setting configurable.

**Comment by xoseperez** [comment]
Closing since there is nothing left to be done atm from the ESPurna point of view. Changes done here are staged for release.
