### ISSUE TITLE
Question about Espurna API update rate

### ISSUE THREAD

**Issue by xoseperez** [xoseperez/espurna#459]
Originally reported by: **Adam Honse (Bitbucket: [CalcProgrammer1](https://bitbucket.org/CalcProgrammer1), GitHub: [CalcProgrammer1](https://github.com/CalcProgrammer1))**

----------------------------------------

I saw your AiLight blog post recently (late last year) and bought two bulbs with the intention of using them in my Christmas light show along with a bunch of WS28xx strings and strips.  After many shipping delays and then trouble flashing the ESP8266, I finally got Espurna uploaded to the bulbs and working.

I'm the developer of an audio visualizer application, initially written for RGB computer peripherals like the Razer Chroma product line, but I wanted to add support for these bulbs in my app.  I'm using the HTTP API and sending a TCP packet to the Espurna controller with the following request:

snprintf(get_request, 1024, "GET /api/color?apikey=2E251541800B8C8B&value=%%23%02X%02X%02X HTTP/1.1\r\nHost: 192.168.3.104\r\n\r\n", GetRValue(color), GetGValue(color), GetBValue(color));

(The API key was randomly generated by the Espurna firmware, the color value is filled in using helper functions to parse a 32 bit color value into the hexadecimal format used in the request string)

I didn't want to pull in a bunch of libraries for HTTP so I'm just opening a TCP socket connection, sending that string, and closing the socket.  This is done in a loop to continuously update the color as my app generates a color based on selected pattern (such as rainbow fade, etc) and audio (color and intensity set based on intensity of bass in the audio).  I have the loop running at 50ms intervals (this setting can be changed by the user).  I've found that at 50ms, occasionally one or both bulbs will "crash" and reboot, which lags out my code, and when the bulbs come back online the switch is set to Off so sending new color commands via API doesn't produce any light.

Do you know what the fastest "safe" update rate is?  Is there anything that could be modified on the firmware side to improve response to fast updates?  I plan to add Espurna RGB support to my app, but I don't want to release it if it's going to crash the firmware often.

**Comment by CalcProgrammer1** [comment]
I'll look at the debug logs tonight.  I tested it more last night and they weren't crashing as much.  If it continues I'll disable some features and see if that helps.

**Comment by xoseperez** [comment]
Any update on this?
