### ISSUE TITLE
Sonoff TH MQTT temperature/humidity

### ISSUE THREAD

**Issue by xoseperez** [xoseperez/espurna#460]
Originally reported by: **Robert Sulek (Bitbucket: [dblf](https://bitbucket.org/dblf), GitHub: [dblf](https://github.com/dblf))**

----------------------------------------

Hi at all, 

After flash  my sonoff th16, all working fine on sonoff web interface.
My sensor is  SI7021:

![esp.png](https://bitbucket.org/repo/KBydAy/images/867995959-esp.png)

After connect to HomeAssistant via MQTT the switch on/off working fine.

```
#!yaml

    state_topic: "Sonoff_TH/relay/0"
    command_topic: "Sonoff_TH/relay/0/set"
    payload_on: "1"
    payload_off: "0"

```
(where Sonoff_TH is {identifier}

But the MQTT never reports the temperature and humidity via MQTT.
Automatic discovery MQTT works only with switch. 
I read issue Issue #339, but my firmware is 1.12.1

Other way - the console on tasmota firmware is a good think to see command send via MQTT to broker.
I can find any example MQTT for sensor espurna firmware.

**Comment by xoseperez** [comment]
You should be receiving messages to "Sonoff_TH/temperature/0" and "Sonoff_TH/humidity/0" every minute (by default configuration).

Automatic discovery only works with switches, you are right.

You can also log into the ESPurna console and see all debug messages, including MQTT messages.

**Comment by RoSulek1** [comment]
Thanks!

The right topic is:

  - platform: mqtt
    name: "YourName"
    state_topic: Sonoff_TH/temperature
    unit_of_measurement: "°C"

  - platform: mqtt
    name: "YourName"
    state_topic: Sonoff_TH/humidity
    unit_of_measurement: "%"


[MQTT] Sending Sonoff_TH/app => ESPURNA (PID 1)
[MQTT] Sending Sonoff_TH/version => 1.12.1 (PID 1)
[MQTT] Sending Sonoff_TH/host => Sonoff_TH (PID 1)
[MQTT] Sending Sonoff_TH/ip => 192.168.0.204 (PID 1)
[MQTT] Sending Sonoff_TH/mac => 68:C6:3A:8B:1C:A5 (PID 1)
[MQTT] Sending Sonoff_TH/rssi => -71 (PID 1)
[MQTT] Sending Sonoff_TH/uptime => 7500 (PID 1)
[MQTT] Sending Sonoff_TH/datetime => 2018-01-25 15:27:21 (PID 1)
[MQTT] Sending Sonoff_TH/freeheap => 21328 (PID 1)
[MQTT] Sending Sonoff_TH/relay/0 => 0 (PID 1)
[MQTT] Sending Sonoff_TH/vcc => 3237 (PID 1)
[MQTT] Sending Sonoff_TH/status => 1 (PID 1)
[MQTT] Sending Sonoff_TH/temperature => 22.0 (PID 1)
[MQTT] Sending Sonoff_TH/humidity => 40 (PID 1)

**Comment by xoseperez** [comment]
Great
