### ISSUE TITLE
WIKI: Hardware markdown

### ISSUE THREAD

**Issue by gn0st1c** [xoseperez/espurna#464]
1) pull requests for wiki is not enabled, will you enable it at some point?

2) at page: https://github.com/xoseperez/espurna/wiki/Hardware
link to boards are like "#markdown-header-tinkermans-espurna-h" where they should be like "#tinkermans-espurna-h"

**Comment by xoseperez** [comment]
Do I have to enable something to allow PR to the wiki repo? I'm sorry, I thought it was already enabled...

I'm changing all those anchors now. Thanks you!

**Comment by gn0st1c** [comment]
https://help.github.com/articles/changing-access-permissions-for-wikis/

**Comment by xoseperez** [comment]
Done!

**Comment by xoseperez** [comment]
Changes to that page are already done too. 
Thanks @gn0st1c
