### ISSUE TITLE
pre-compiled bin files?

### ISSUE THREAD

**Issue by myounges** [xoseperez/espurna#471]
Hello,

First of all thank you very much for your work, I really appreciate your efforts and fully support this initative to switch from bitbucket to github.

Not sure if this is the right channel to ask, but I was wondering if this repository will have a pre-compiled binary library as the old repository had, I found it very useful for the upgrade feature.

Keep up the great work.
Adeu,

**Comment by nkerezov** [comment]
They are there  at the top bottons

**Comment by myounges** [comment]
Hello sorry when I to said binaries I meant the firmware bin files for each hardware model what was in the downloads section.

Are we talking of the same files? Wasn't able to find them.

**Comment by nkerezov** [comment]
Yes,
Ill try to make it easyer since Im using the same method as you and it was the first think I was looking for ;-) 
https://github.com/xoseperez/espurna/releases

**Comment by myounges** [comment]
So embarrassing... Didn't see them. Thank you nkerezov!!!

**Comment by nkerezov** [comment]
Dont worry, I had the same panic atack......

**Comment by xoseperez** [comment]
Thanks @nkerezov !
