### ISSUE TITLE
Reset total energy from web UI

### ISSUE THREAD

**Issue by namezero** [xoseperez/espurna#476]
How to reset the "Energy" value? is there an API ? thanks

**Comment by xoseperez** [comment]
No, there is none. Reset the board 😄

**Comment by namezero** [comment]
the board is in the wall :)
it would be nice to have this as an api service

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-01-27 15:50 GMT+01:00 Xose Pérez <notifications@github.com>:

**Comment by namezero** [comment]
Also the Energy is growing even when relay is OFF, is that the board consumption?

**Comment by xoseperez** [comment]
That and maybe "noise" captured by the HLW8012. The board can use maybe 1W (normally less than that but let's say it's 1W). That's 1 joule every second, 60J per minute. Does that match your observations?

**Comment by namezero** [comment]
That's exactly my observations ! 1J/sec

**Comment by xoseperez** [comment]
You can reset the energy value from the web UI since 1.12.5, see #671 .

**Comment by namezero** [comment]
Is it available from API ?
