### ISSUE TITLE
No Alexa device with actual dev-branch

### ISSUE THREAD

**Issue by flashy02** [xoseperez/espurna#479]
With the actual dev branch Alexa finds no Device. In the Master branch I can add it as power plug. If the Device was added to Alexa with master-branch, you can still use it with Dev branch, but if you delete it you have no chance to add it again.

**Comment by xoseperez** [comment]
It looks like the fauxmoESP library is not compatible with SSDP support introduced with #282 . Both try to use UDP multicast address. I'm disabling SSDP support by default since Alexa support has more users.

**Comment by flashy02** [comment]
Thank you.
