### ISSUE TITLE
Is ESP-32 supported?

### ISSUE THREAD

**Issue by pcornill** [xoseperez/espurna#482]
I have an ESP WROOM32 and get an error when compiling Espurna 1.10:

sketch\config/prototypes.h:6:32: fatal error: user_interface.h: No such file or directory

**Comment by xoseperez** [comment]
Not supported at the moment.

**Comment by pcornill** [comment]
Thanks for you quick feedback 😉


________________________________

**Comment by xoseperez** [comment]
You are welcome. It's something I have in mind, thou.
