### ISSUE TITLE
Error compilation to Arduino IDE

### ISSUE THREAD

**Issue by EvilSlesh** [xoseperez/espurna#489]
BMX280Sensor.h, string: 344
error: return-statement with no value, in function returning 'unsigned char' [-fpermissive]

`if (var1 == 0) return; `
change the string
`if (var1 == 0) return 1;`
builds complete ок

I believe this wrong decision

**Comment by xoseperez** [comment]
Actually it should be:

`if (var1 == 0) return SENSOR_ERROR_I2C`

Fixed in dev.

**Comment by xoseperez** [comment]
This is staged for release.
