### ISSUE TITLE
Cannot build web interface gulp deprecated

### ISSUE THREAD

**Issue by miroslavpetrov** [xoseperez/espurna#493]
https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

The web interface cannot be compiled because of some problem with gulp. I do not really understand the problem but are there any ways to fix it?

**Comment by xoseperez** [comment]
I have removed the explicit dependency on gulp-util (using log feature). It will still install and load if using gulp 3.X as it is now but the code is ready to upgrade to gulp 4.

**Comment by xoseperez** [comment]
Staged for release.
