### ISSUE TITLE
Slampher detected as a "Switch" in HomeAssistant

### ISSUE THREAD

**Issue by serhatozkara** [xoseperez/espurna#494]
First of all, thank you for this awesome project. There is a minor bug in slampher fw. The lights are detected as switch items instead of light items under Home Assistant. This makes sense for relay boards but as slampher is light only, they should be classified as "light" items.

**Comment by xoseperez** [comment]
This makes sense since the Slampher will always be a light.
Pushed to dev branch and staged for release.
