### ISSUE TITLE
Auto-discover in 1.12.3 with sensors ??

### ISSUE THREAD

**Issue by vincegre** [xoseperez/espurna#501]
Hi

As I read somewhere that you had added the auto discover for sensors too, I have built a specific 1.12.3 build with only Dallas DS18B20 support in it. Unhappy the sensor doesn't shop up in Home Assistant unless all ones with switch works without problems !
Is it normal too that value of sensor is not displayed in Espurna web interface ??

In fact by checking on my MQTT broker I noticed it doesn't even send Temperature values on MQTT 👎 

Thanks

Vincèn

**Comment by xoseperez** [comment]
No, it's not normal. Check the boot log, the sensor is either not correctly wired or failing for some other reason. If the sensor fails ESPurna won't push the configuration to HA.

**Comment by vincegre** [comment]
> No, it's not normal. Check the boot log, the sensor is either not correctly wired or failing for some other reason. If the sensor fails ESPurna won't push the configuration to HA.

Found out that sensor was defective :( Replaced by a good one and now it reports correctly temperature !
I'm just having a weird issue not being able to save MQTT/General and Sensors settings in device !! The Save button has no effect on these pages unless it works on others (have been able to setup Wifi with success on it !).

**Comment by xoseperez** [comment]
Do you mean some settings are being correctly saved but others don't?

**Comment by vincegre** [comment]
> Do you mean some settings are being correctly saved but others don't?

Exactly it's really weird and never got that issue before :( I changed of browser just in case and changed of computer too but still same problem ! Don't know what to investigate for that problem :( any ideas ?

**Comment by xoseperez** [comment]
Open a terminal session (via USB or telnet) to the device and check the settings from there. You can type `keys` to get a list of key-values stored. You can also type `get snsRead` to get the current sensor read interval (for instance). You can do that before saving, after saving and after rebooting the board and compare values.

**Comment by vincegre** [comment]
ah thanks yep didn't remember to check in terminal what is happening and it looks like it reboots as soon as I type more than few characters in terminal !!
Debug output is pretty messy, not sure if it can help but I put a copy of it below (I have just deleted Wifi passwd fields ;)


[minicom.txt](https://github.com/xoseperez/espurna/files/1685586/minicom.txt)

**Comment by xoseperez** [comment]
That's not good. The device is crashing for some reason and entering safe mode (that happens after 5 crashes in a row). Can you parse the error stack trace?

**Comment by mcspr** [comment]
minicom.txt suggests this is either NTP related issue with DNS resolving (...Error: NTP Server not reachable...) , or some old bug related to 2.4.0 release / alexa support using old fauxmoesp.

Closing because original issue is resolved (stalebot does not work somehow of issues this old?)
