### ISSUE TITLE
MQTT / KeepAlive : incorrect update settings

### ISSUE THREAD

**Issue by bopnrgi** [xoseperez/espurna#515]
MQTT KeepAlive seems don't be updated correctly. I set 310 seconds. After reboot is 54 seconds.

To reproduce. Enable MQTT, set KeepAlive to 310, save, reboot device. MQTT page display now 53.
Firmware Sonoff TH 1.12.3

Bonus : Is it possible to debug MQTT KeepAlive (via telnet ?) ?

**Comment by xoseperez** [comment]
Indeed, the internal variable that caches the keepalive time was defined as unsigned char, so a max of 255 seconds... I have fixed it and pushed to dev.

**Comment by xoseperez** [comment]
This is staged for release.
