### ISSUE TITLE
5-channel dimmer on H801 is discovered by HomeAssistant as RGB + Switch

### ISSUE THREAD

**Issue by Sanfam** [xoseperez/espurna#516]
I have several H801 modules being successfully discovered by homeassistant.  While they offer 5 individual dimmer channels, they instead register as a combination of one dimmable composite RGBW device and one switchable load.  

Second, and this may be an issue with HomeAssistant itself, but the discovered device links the RGB setting to global power and the W1 channel as a secondary.  If RGB is dimmed to 0, the global power state is switched off regardless of what the W1 channel is set to, turning off all channels and hiding both controls.

Overview:
![image](https://user-images.githubusercontent.com/3504427/35767749-f64d4272-08bf-11e8-97a3-72be77d9d2f3.png)

RGB+W1 Device:
![image](https://user-images.githubusercontent.com/3504427/35767753-05270aa8-08c0-11e8-88c6-4ebf97b9d0e1.png)

5th Channel (W2):
![image](https://user-images.githubusercontent.com/3504427/35767761-1eb47758-08c0-11e8-9dcf-7dcb00954799.png)

**Comment by xoseperez** [comment]
The switchable load is actually created by HA itself when it discovers a wemo-compatible device. You probably have Alexa integration enabled in your ESPurna device and, Apparently, the `wemo` component in home assistant is enabled by default. Check the HA log for something like this:

```
INFO:homeassistant.components.discovery:Found new service: belkin_wemo {'ssdp_description': 'http://192.168.1.10:52000/setup.xml', 'model_number': '1.0', 'mac_address': '', 'model_name': 'Socket', 'host': '192.168.1.10', 'serial': '221703K0B93C93', 'port': 52000, 'name': 'MINI'}
INFO:homeassistant.loader:Loaded wemo from homeassistant.components.wemo
INFO:homeassistant.setup:Setting up wemo
INFO:pywemo.subscribe:Listening on port 8989
INFO:homeassistant.components.wemo:Scanning for WeMo devices.
WARNING:homeassistant.components.wemo:Unable to probe wemo at 192.168.1.10
```

And you are right. Setting the brightness to 0 turns OFF everything. As far as I can tell, this is a "feature" in Home Assistant. Whenever the brightness value is set to 0 it also send an OFF payload to the state_command, and when it's non-zero it sends an ON...

**Comment by joeltetava** [comment]
Is there a website that has the instructions to this?

**Comment by Zixim** [comment]
@joeltetava A link to instructions for configuring the H801 in Home Assistant ?
https://github.com/xoseperez/espurna/wiki/HomeAssistant#link-an-espurna-light-to-home-assistant
