### ISSUE TITLE
Can't differentiate the temperature values of 2 sensors in InfluxDB

### ISSUE THREAD

**Issue by Rapejim** [xoseperez/espurna#528]
I have connected two sensors (Dallas -> GPIO12, and DHT11 -> GPIO12) on a NodeMCU with ESPurna 1.12.3.
And I have configured InfluxDB support well.

But the system save in database, both **_temperature_** values under the same "device"...
![image](https://user-images.githubusercontent.com/7972545/35846347-97cd2ccc-0b16-11e8-8e46-85224727b4b7.png)

and it is impossible differentiate each sensor:
![image](https://user-images.githubusercontent.com/7972545/35847309-5c7ef3fe-0b1a-11e8-8258-379fdf465f79.png)
For example, using Grafana, it do the average of both values always (except when I have disconnected one of sensors).

**Comment by xoseperez** [comment]
There should be another attribute `id` that differentiates both magnitudes.

**Comment by djsomi** [comment]
Device and ID should be definied at the end of the grafana query, something like this:

![multi sensor](https://user-images.githubusercontent.com/19391031/84431186-2a366300-ac2b-11ea-9c05-25361642a8b3.JPG)

Thanks @xoseperez  for this really useful FW!
