### ISSUE TITLE
custom.h precedence

### ISSUE THREAD

**Issue by hazarkarabay** [xoseperez/espurna#530]
Currently `custom.h` is included at top of the `all.h` . This makes impossible to override some (most?) directives; the ones that doesn't have an `#ifdef` check will override the `custom.h` and generate a warning.

I suggest placing the `#include custom.h` at bottom of `all.h`

**Comment by lobradov** [comment]
Makes sense. 
Care to create a PR for it?

**Comment by hazarkarabay** [comment]
Done, closing this.
