### ISSUE TITLE
Sonoff POW reboots when switch is turned ON

### ISSUE THREAD

**Issue by pcornill** [xoseperez/espurna#535]
Since I updated from 1.08 to 1.12 my Sonoff POW reboots few minutes after the switch is ON.
It seems that it works fine when there is no power (just the switch ON without load).
I suspect a correlation to wificonfig as I found several posts on the web related to this behavior.
I noticed that one of my Sonoff basic that was switched ON also rebooted when I tried to reboot my wifi router!

**Comment by xoseperez** [comment]
What do you mean by "wificonfig"? I have two POWs here running without a problem.

**Comment by pcornill** [comment]
I am referring to this thread:

https://github.com/arendst/Sonoff-Tasmota/issues/1034


I tested the last Espurna firmware (1.12) with all my Sonoff Basic, TH and POW and all of them reboot when I switch my wifi router off.

This is something new because I have a Sonoff with an older release that does not reboot.


So I guess something is wrong with my POW wifi and periodically it reboots.


________________________________

**Comment by xoseperez** [comment]
`wificonfig` is a setting in Tasmota, not ESPurna. Will try to reproduce this thou.

**Comment by pcornill** [comment]
Hi, it seems to be gone with 1.12.4

**Comment by xoseperez** [comment]
Closing then.. Feel free to reopen if needed.
