### ISSUE TITLE
I have a question..

### ISSUE THREAD

**Issue by anarro** [xoseperez/espurna#539]
Hi,

(I use a Espurna 1.12.3 firmware.)
I like connect 4 buttons (on a wemos D1 mini) with my homeassistant app., I have configured correctly (I think) in a hardware.h file and and enabled "homeassistant" auto discovery button and use a "homeassistant" prefix in a textbox, but when I check in my MQTT.fx app I never view nothing registred on a "homeassistant" prefix... it's correct?
 
![espurna](https://user-images.githubusercontent.com/8436433/35969088-08e32960-0cc6-11e8-9721-120a8efe6874.jpeg)

**Comment by xoseperez** [comment]
The homeassistant config message is sent on boot or when you enable/disable it. It's only a configuration message, you don't really need it to use ESPurna with HA if you configure it manually.

**Comment by anarro** [comment]
Ok Xose, thank you.
