### ISSUE TITLE
Support for DDNS

### ISSUE THREAD

**Issue by darshkpatel** [xoseperez/espurna#547]
Awesome project mate,
                                      It made me laugh wonder , this would be a perfect firmware for a standalone esp controlling something like Christmas lights , all it needs is DDNS support

A quick Google search lead me to [EasyDDNS](https://github.com/ayushsharma82/EasyDDNS) 

*Feature request*

**Comment by xoseperez** [comment]
Thanks for the suggestion but I don't think this is something to do on a smart device a router or a dedicated home server looks more suitable for this task. After all, it is strongly advised not to expose your smart devices to the internet directly.
