### ISSUE TITLE
REST API returned value

### ISSUE THREAD

**Issue by pcornill** [xoseperez/espurna#548]
Hi Xose,
I'm wondering if there is a reason why Espurna returns '0' when the request is value=1 and returns  '1' when the request is value=0
It looks like it returns the  value of the previous state not the updated one.

**Comment by xoseperez** [comment]
Indeed, it was returning the state of the relay just after enqueuing the relay change but before actually toggling it. I have just committed a fix for this in the dev branch.

**Comment by xoseperez** [comment]
This is staged for release.
