### ISSUE TITLE
i don't understand where are .ino flash for sonoff hardware 4ch

### ISSUE THREAD

**Issue by kunux** [xoseperez/espurna#554]
Hello, 
sorry for this quesion but where can i download sonoff 4ch firmware flash?

**Comment by xoseperez** [comment]
If you are looking for the binary images they are in the [releases](https://github.com/xoseperez/espurna/releases) tab under code.

**Comment by kunux** [comment]
hello xose thanks so much.
:)

**Comment by xoseperez** [comment]
You are welcome
