### ISSUE TITLE
JanGoe Wifi Relay Board - pre build binaries - build configuration

### ISSUE THREAD

**Issue by NemoN** [xoseperez/espurna#555]
Which config has the pre build binary: `espurna-1.12.3-jangoe-wifi-relay.bin`?
`JANGOE_WIFI_RELAY_NC` or `JANGOE_WIFI_RELAY_NO`?
I need the **NO** version.

**Comment by xoseperez** [comment]
It was the NC version. I have uploaded the NO version and changed the name of the old one.

**Comment by NemoN** [comment]
thanks!
