### ISSUE TITLE
Echo 2 plus can't find ESPurna

### ISSUE THREAD

**Issue by ManuelW77** [xoseperez/espurna#563]
Hey there,
i have a ESP8266-12F with the latest ESPurna running. I have it compiled with the
Magic Home V2.3 option.

Everything works well, but Alexa can't find the ESPurna. I try'd it several times, rebooted the ESP, but nothing works. Alexa did not find the ESP.

**Comment by xoseperez** [comment]
ESPurna uses (my own) fauxmoESP library. Some people has reported issues when using it with v2 devices (like Echo 2 Plus) when compiled with Arduino Core v2.4.0. Try compile it using Arduino Core 2.3.0.

https://bitbucket.org/xoseperez/fauxmoesp/issues/39/generation-2-devices-support

**Comment by ManuelW77** [comment]
Thanks it solved the problem. With Core 2.3.0 it works fine. :)

**Comment by xoseperez** [comment]
Good. I'm closing this issue since it should be fixed in the fauxmoESP library issue above.
