### ISSUE TITLE
H801 per channel on/off

### ISSUE THREAD

**Issue by Anroxo** [xoseperez/espurna#565]
Hi!
I tried it with 6 dummy relays and it didn't work. It is okay with 5. For me the it would be best if one relay would switch the RGB channel and two separate  ones the two white channels. Can someone confirm that it does work with 6. Or should I consider it as a hack and wait for better support?

**Comment by xoseperez** [comment]
Right now ESPurna only supports up to 5 dimmer channels but adding more it's a matter of hacking the lightSetup method in light.ino (I think). 

To achieve what you say about having different dummy relays controlling different channels could be achieved using a mapping (like with buttons and relays). Right now the implementation is much simpler (one switch for every channel or one switch for all channels).

**Comment by Anroxo** [comment]
I see. Thanks for the information.

**Comment by ColinShorts** [comment]
@xoseperez as per #830 should this now work as per the comments in relay.ino under RELAY_PROVIDER_LIGHT - dummy relays set to 5 gives a per channel switch, and set to 6 gives a master plus one for each channel?

**Comment by xoseperez** [comment]
Right.

**Comment by ColinShorts** [comment]
Thanks @xoseperez, I've not got around to checking this yet, @anroxo can you test and confirm?

**Comment by xoseperez** [comment]
Will be released soon
