### ISSUE TITLE
WPS wifi configuration

### ISSUE THREAD

**Issue by serra82** [xoseperez/espurna#581]
Is possible configure the WiFi by WPS?

**Comment by xoseperez** [comment]
Not yet. But hopefully soon.

**Comment by xoseperez** [comment]
Working version using v2 of the JustWifi library. But WPS increases the binary image more than ~20kb!!
Check the justwifi2 branch and use `-DJUSTWIFI_ENABLE_WPS`. Testing it right now on several devices and running fine.

**Comment by xoseperez** [comment]
Merged to dev branch. It is NOT enabled by default. WPS increases the binary size a lot. Besides, from the security point of view it's not a good idea (disable your router WPS feature if you can). Anyway you can enable it passing the `-DJUSTWIFI_ENABLE_WPS` build flag. Staged for release.

**Comment by serra82** [comment]
I'm testing wps, added -DJUSTWIFI_ENABLE_WPS and:
#define BUTTON1_LNGCLICK    BUTTON_MODE_WPS
the led start to blink fast, I push the wps button on router, but the smartplug don't connect to the router.

Can you explain the steps to use wps?
Thank you
