### ISSUE TITLE
ESP resets when load connected to HLW8012

### ISSUE THREAD

**Issue by varungujjar** [xoseperez/espurna#587]
Hey @xoseperez  I created a board as per espurna schematics  .. everything works I also get exact current readings  however when a load is connected the device crashes and restarts .. it doesnt happen when no load is connected..  is there something am missing ..  ? tried with interrupt mode on and off for HLW8012 still no luck...  using a  Hi Link 3W AC DC convertor.. is that sufficient or does it need 5W..? 

Edit : I compile the code using Arduino 1.8.5 on windows 10

**Comment by xoseperez** [comment]
I will check the decoupling capacitor for the ESP8266.

**Comment by varungujjar** [comment]
cool.. let me know if you need me try ..?

**Comment by varungujjar** [comment]
@xoseperez  fixed it the 100 nf capacitors have to be placed way closer than i thought.. :)

**Comment by xoseperez** [comment]
Cool. Closing the issue :smile:
