### ISSUE TITLE
mqtt command root/rgb/set does not work on H801

### ISSUE THREAD

**Issue by robin13** [xoseperez/espurna#590]
It is possible to set a colour by using the `root/channel/[0-4]/set` topic, but the `root/rgb/set` does not work (I have tried both numeric `255,0,0` and RGB `#FF0000`).

**Comment by theonedemon** [comment]
if change line espurna/light.ino:39 all works

```
// bool _light_has_color = false;
bool _light_has_color = true; // #FIXME
```

**Comment by xoseperez** [comment]
No need to modify the code, just enable the "Use colorpicker" check in the LIGHT tab of the Web UI. I notice the copy might not be clear so I'm changing it to "Use color".

**Comment by xoseperez** [comment]
This is staged for release.

**Comment by robin13** [comment]
Ah - thank you for the tip @xoseperez :)
