### ISSUE TITLE
sonoff basic dht

### ISSUE THREAD

**Issue by Vadonat** [xoseperez/espurna#603]
Hello!I'm new in here.(sorry for my english if is too bad..).I have two pieces dht22 sensor on two sonoff basic with the latest sonoff basic dht rom.It is working but the sensor randomly goes to timeout.Plug out the cable from the wall is solve the problem.worked a day and after did the same.plug out-plug in solved the problem again but repeating after randomly again.I have a resistor too between the vcc and the data.and the wires are solderet to board directly.pls help me.thank you.

**Comment by xoseperez** [comment]
This is hard to debug. The DHT sensor is stateless, it doesn't have any startup configuration, so if it goes offline and doesn't come back it has to be something external to the sensor code (hardware, interrupts,...). Is it happening with both sensors?

**Comment by Vadonat** [comment]
yes.two sensors reproduce it.sometimes working a day,a week,3-4 hours and randomly do this.the devices are Aosong am2302.

**Comment by K1nslayer** [comment]
I have 2 DHT22's working on Sonoff Basic hardware.  I'm compiling my own firmware and using these:
[https://www.amazon.com/gp/product/B073F472JL/ref=oh_aui_search_detailpage?ie=UTF8&psc=1](url)

**Comment by Vadonat** [comment]
Can't open the link.I'm not a programmer.I just uploaded this awesome rom.:)

**Comment by K1nslayer** [comment]
Fixed Link.  I uploaded 1.12.3 from the release dir to one of my basics.  If it times out, I'll let you know. 
[DHT22 @ Amazon](https://www.amazon.com/gp/product/B073F472JL/ref=oh_aui_search_detailpage?ie=UTF8&psc=1)

**Comment by Vadonat** [comment]
ok.thank you!

**Comment by Vadonat** [comment]
mine is the cheaper version.

**Comment by Vadonat** [comment]
I tried it on 5 volt.there is no timeout now.

**Comment by xoseperez** [comment]
It's a bad quality sensor then, it should work at 3V.

**Comment by Vadonat** [comment]
I will buy normal quality sensors of my next salery..this is a quality issue I think.

**Comment by xoseperez** [comment]
Closing
