### ISSUE TITLE
heartbeat interval and mqtt publish intervals 

### ISSUE THREAD

**Issue by iDeam0316** [xoseperez/espurna#606]
Hi

Can we configure the heartbeat interval through the web UI? Or it has to be a pre-defined value in general.h ? 

And are we going to have the feature which we can configure the interval for each topic  of mqtt msg  ?

Thanks!

**Comment by xoseperez** [comment]
Only available as a build setting atm. Sensor report interval is configured through the web UI, relays and buttons are event based. Only heartbeat interval is fixed.

**Comment by iDeam0316** [comment]
Thank you !
