### ISSUE TITLE
HLW8012 define default calibrated values

### ISSUE THREAD

**Issue by varungujjar** [xoseperez/espurna#610]
Hey @xoseperez  is it possible to define the default calibrated values.. internally ? so we dont have to do the same for other devices.

**Comment by xoseperez** [comment]
ESPurna uses the `HLW8012_CURRENT_R`, `HLW8012_VOLTAGE_R_UP` and `HLW8012_VOLTAGE_R_DOWN` values to calibrate the sensor. They are defined in the `sensor.h` file unless they are defined before, in the `hardware.h` file, for instance. Check the `setResistors` and  `_calculateDefaultMultipliers` methods in the HLW8012 library.

**Comment by gn0st1c** [comment]
@varungujjar : an example can be KMC_70011 (see hardware.h)

shouldn't this issue be closed already?

**Comment by varungujjar** [comment]
@xoseperez  yes this should be closed..
