### ISSUE TITLE
just a Question: emon - energy for plain analog input - DC bias filtering

### ISSUE THREAD

**Issue by gnkarn** [xoseperez/espurna#617]
Jose , i would like to understand if   the analog interface for Emon uses the Emonsensor  ( sampling the sinusoidal signal)  , the reason I'm asking is because it seams it is not "filtering" the DC bias component of the input signal , and also by applying the calibration method ( using zero amps , with the CT out of the wire)  it doesn't correct either .

So in my case with Zero amps , it is always reading 14 amps - ( it is a 30 amps to 1 v sct013)

thank you

**Comment by gnkarn** [comment]
i think i found the problem , will ask later when i reach more clarity, tks

**Comment by xoseperez** [comment]
It is, check these lines:

https://github.com/xoseperez/espurna/blob/bf2ef37b60cac1a258b51309d435f575936cd16c/code/espurna/sensors/EmonSensor.h#L155-L172

**Comment by gnkarn** [comment]
yes, thank you,

it is working , will try to make a calibration tomorrow .

**Comment by xoseperez** [comment]
I guess it's safe to close it now.
