### ISSUE TITLE
Switch Selector in Domoticz

### ISSUE THREAD

**Issue by Mattleyu30** [xoseperez/espurna#620]
Hi, Xose
I'm trying to use the selector button in domoticz with the sonch 4CH with the espurna firmware, but at the time that I had to enter the command http: // or Script: I stopped because I did not find anything on the wiki that told me a script to send from domoticz to espurna for switching off or on.
I had already tried it a long time ago with Espeasy, with a simple http: // command and it worked regularly, but I prefer your firmware much more.
which script can be used to send a command to espurna?

Thanks

**Comment by xoseperez** [comment]
You can use the REST API to send commands to ESPurna via HTTP. Check the documentation here: https://github.com/xoseperez/espurna/wiki/RESTAPI

**Comment by Mattleyu30** [comment]
thanks xose
I try the REST API, but a question, you say that it is already espurna is already configured for Domoticz, but the switch selector in domoticz, has a single IDX and works with% levels. Does Espurna also manage this type of parameter?

**Comment by xoseperez** [comment]
No, the current integration with Domoticz switches only accepts on/off values.

**Comment by Mattleyu30** [comment]
ok Thanks Xose
