### ISSUE TITLE
How do I disable BUTTON_MODE_TOGGLE?

### ISSUE THREAD

**Issue by eercanayar** [xoseperez/espurna#625]
Hi everyone,
I want to disable "toogle relay" function of the main button on espurna. Can I do it with any parameter change or do I need to edit some code and compile my own espurna? Thanks all.

**Comment by Tardymo** [comment]
I'm afraid you will have to edit hardware.h (#define BUTTON1_CLICK   BUTTON_MODE_NONE) and compile your own firmware. Version 2.0 promises configurable hardware through web interface (see #382)
