### ISSUE TITLE
Sonoff Pow without power consumption sends values greater than zero  

### ISSUE THREAD

**Issue by Maergsche** [xoseperez/espurna#635]
The Sonoff Pow transmits power values up to 8 watts even when no electronic devices are connected. It does not matter if the relay is closed (on) or open (off).

I using Version 1.12.4 and services like Alexa and telnet are deactivated. Only MQTT is in use. 

![img_20180306_233742](https://user-images.githubusercontent.com/35492880/37062691-813d0314-2197-11e8-9af6-b4fddc990c79.png)

**Comment by AlbertWeterings** [comment]
The sonoff pow shout not measure any energy when the relay is in off position at that point it short circuit the resistor used to measure energy so the voltage difference on HLW8012 pin 2(vip) and 3(vin) shout be 0volt. The only difference I see in other designs is that sonoff has 100nf capacitors to ground on pin 2 and 3 and in all other designs i see 33nf. It might be possible the HLW8012 is picking up noise.

**Comment by xoseperez** [comment]
Sensor values are filtered using a median filter to remove spurious values but apparently is not enough as the HLW8012 is picking up noise all the time.

**Comment by Tardymo** [comment]
Yes, I can confirm that POW is reporting wattage spikes even when relay is off. I was hoping to trigger off wattage when connected device turns on, so I decreased reporing interval, but it is unuseable with very short intervals as I see up to 30W spikes.

**Comment by AlbertWeterings** [comment]
The pow design has a ceramic capacitor at the AMS1117 this might result in it oscillating @xoseperez In your design with the HLW 8012 what kind of capacitors did you use and do you see the same issue?

**Comment by xoseperez** [comment]
I use tantalum capacitors at the ASM1117 but it does have noise nevertheless. But they are usually ON so I cannot tell if everything is noise or there is actually some residual power usages (LEDs and so).

**Comment by AlbertWeterings** [comment]
@Maergsche Can you please check if your SonOff pow has a CSE7759 power measuring chip or a HLW8012?
