### ISSUE TITLE
enable color picker is lacking the "white channel" for ariluxe27

### ISSUE THREAD

**Issue by gnkarn** [xoseperez/espurna#649]
if color picker is disabled , all 4 channels works fine.

if enable color picker is selected , then only RGB channels are enabled ,and is not possible to interact on white leds  from the status interface.

**Comment by xoseperez** [comment]
I do see the 4th channel slider just below the color picker...

![mini espurna 1 12 5a](https://user-images.githubusercontent.com/706487/37258768-e2adc226-257c-11e8-9727-7f4e76a2dad9.png)

**Comment by xoseperez** [comment]
Closing this since there has been no feedback. Please feel free to reopen if necessary.
