### ISSUE TITLE
Hostname size limitation

### ISSUE THREAD

**Issue by swilson86** [xoseperez/espurna#659]
All Espurna versions > 1.12.1 have a Hostname size limitation of 14 chars (introduced in your JavaScript). Most of my devices have longer names such as "Archway Light left" because Alexa uses the Hostname.

If upgrading to a version > than 1.12.1 any long Hostname that was previously applied will remain in tact. Hmmmm. Is this an oversight? Now I am curious if there is something in Espurna that demands a 14 char limitation.

**Comment by xoseperez** [comment]
It's just cosmetics, I'm removing the limitation since the hostname can now wrap inside the available block in the web UI.

**Comment by swilson86** [comment]
Thanks! Keep up the good work
