### ISSUE TITLE
Bulbs Freezing

### ISSUE THREAD

**Issue by jonny190** [xoseperez/espurna#670]
i have 2 Ai thinker bulbs, 2 magic home rgb and a sonoff touch all running 1.12.4 that seem to freeze after a few minuates and need to be restarted to regain wifi and in the touch's case ability to switch, any ideas?

**Comment by jonny190** [comment]
Just for detail this was only when compiling my own firmware as most of my RGB strips are GRB format when using magic home plus its handy to pre-program config

**Comment by thebradleysanders** [comment]
Please Visit the Releases Page: https://github.com/xoseperez/espurna/releases/
find your device and apply the image to your device with the OTA upload in the Web UI.

There may have been an issue with your self-compiled firmware.

**Comment by xoseperez** [comment]
This could be due to using lwIP 2.0 (unstable). Check #572.
In the [Arduino IDE wiki page](https://github.com/xoseperez/espurna/wiki/ArduinoIDE) it is recommended to use IwIP 1.4 due to stability issues with the latest version.

**Comment by jonny190** [comment]
@thebradleysanders Thanks for you reply, the pre-compiled images seem to be working however i need to compile my own to swap the colors of pins over.

@xoseperez thanks for the heads up i'm compiling my own now and i'll let everyone know how it works after testing

**Comment by jonny190** [comment]
This is corrected issues
