### ISSUE TITLE
SONOFF POW cant calibrate power settings Again :(

### ISSUE THREAD

**Issue by gibbo520** [xoseperez/espurna#676]
https://github.com/xoseperez/espurna/issues/194

Same problem in Version 1.12.4

**Comment by xoseperez** [comment]
Do you mean the calibration values are not persisted?

**Comment by gibbo520** [comment]
Yes !! Again :( 

Il giorno 15 mar 2018, alle ore 22:56, Xose Pérez <notifications@github.com> ha scritto:

Do you mean the calibration values are not persisted?

**Comment by zerog2k** [comment]
I have KMC-70011 (w/ HLW8012), ESPURNA 1.12.5a
Also, unable to calibrate energy monitor settings - they are way off.
Calibration using 50W resistive incandescent light bulb, and calibration settings are not saving/taking effect.

**Comment by gn0st1c** [comment]
@xoseperez : btw, for KMC 70011 HLW8012_VOLTAGE_R_UP is 2 * 1000000 (2 x 105 resistors)

**Comment by xoseperez** [comment]
Staged for release

**Comment by karmacoma92** [comment]
Hi again, something similar is happening in 1.13.1. I just got the POW and it is the first time I use it so I'm not sure if there is any special procedure for the calibration rather than connect it to a bulb, switch it on and write down the vaules under sensors...

**Comment by karmacoma92** [comment]
it looks to me the chip at the back is a CSE7759 and not a CSE7766, could that be the problem?
I have tried with 1.12.6 pow and powr2, 1.13.0 POW and POWR2 and 1.13.1 POW and POWR2, none of them allows me to store the values....
