### ISSUE TITLE
Empty NTP time in debug console

### ISSUE THREAD

**Issue by PieBru** [xoseperez/espurna#691]
Hi, sometimes "[NTP] Time:" console log doesn't show the time.
The aesthetic solution is simple, I didn't drill down the cause as it seems it doesn't give problems elsewhere.
Cheers,
Piero

```
-    DEBUG_MSG_P(PSTR("[NTP] Time: %s\n"), (char *) ntpDateTime().c_str());
+    if (strlen(ntpDateTime().c_str())) {
+        DEBUG_MSG_P(PSTR("[NTP] Time: %s\n"), (char *) ntpDateTime().c_str());
```

**Comment by xoseperez** [comment]
It simply means the NTP module has not yet got a time from the server...
