### ISSUE TITLE
Add support of dual white/cct led strips (H801)

### ISSUE THREAD

**Issue by soprater** [xoseperez/espurna#695]
Hi there,

thanks for your awesome work!
I wanted to use your firmware to control my cct led strips (24V+, CW, WW) with the H801.
When working with Home Assistant (MQTT) I can only work with the _color_temp_command_topic_ when under _Lights>Use color_ is enabled. Unfortunately the values are getting sent on Channel 0/1/2 (RGB) and it would be nice to have a feature to get the values for Cold White and Warm White (on 2 channels).

Example:
![image](https://user-images.githubusercontent.com/15094202/37569092-bddea1de-2add-11e8-97ee-7fabf16355c3.png)
Cold White/Channel 1: 255
Warm White/Channel 2: 0

**Comment by Skaronator** [comment]
The current RGBW implementation isn't that good either. I've enabled this setting in the webinterface:
![image](https://user-images.githubusercontent.com/2886913/38176775-40a1679c-35f5-11e8-828a-ccba56ee1125.png)

And when I set it in the espurna webinterface to perfect white it'll disable the RGB strip but if it isn't perfectly white it will still show the RGB strip at 100% brightness.

@xoseperez You need to convert the RGB value in the webinterface to a RGBW value. Here is a example code in python:
https://github.com/home-assistant/home-assistant/blob/98e4d514a5130b747112cc0788fc2ef1d8e687c9/homeassistant/util/color.py#L372-L381

It is basically get the lowest number and subtract it from all numbers and use it as white value.

**Comment by Skaronator** [comment]
Okay just testing with H801 via MQTT in Home Assistant and IMO the `white_value_state_topic` and `white_value_command_topic` command must be removed to get rid of this slider:

![image](https://user-images.githubusercontent.com/2886913/38176933-5c780248-35f8-11e8-9541-79c76d501a32.png)


And the white value must be extracted from the RGB value and when you have the white color value then you can easily calculate the color temperature to set W1 between 0-255 and W2 between 0-255.

I can help you with the maths if you want :P

**Comment by soprater** [comment]
The icing on the cake would be to "abuse" controllers with more than 4 channels (e.g. H801) to use 2 cct strips at once (2x warm white, 2x cold white). I'd definitely help, but unfortunately I can't program c.

**Comment by Skaronator** [comment]
@soprater 
You can do this already... just disable the RGB thing and control each channel on its own.
![image](https://user-images.githubusercontent.com/2886913/38260757-bb7f451e-3768-11e8-9eef-dbb7bfe2ecb9.png)

**Comment by soprater** [comment]
I mean like receiving color temperatures on 2 different topics (think it's in mired from HA)

**Comment by soprater** [comment]
#754 
Tried my best to support this project.
