### ISSUE TITLE
All LED controllers turned back to AP after a while

### ISSUE THREAD

**Issue by CrispinP** [xoseperez/espurna#697]
All my controllers (8 or 9 of them) suddenly showed up as APs. They all had roughly the same run-time which is around 3-4 weeks.

I power-cycled most of them at the same time (same mains circuit) and they all went back to normal. 
I have two more (Sonof relays) still in AP mode and while they offer an address, I cannot connect to them. 
Anything I can try with the Sonofs to help debug before I cycle them?

**Comment by xoseperez** [comment]
Sorry, somehow this went unnoticed. Has it happened again?
