### ISSUE TITLE
prebuilt binary release for Sonoff SV?

### ISSUE THREAD

**Issue by 040medien** [xoseperez/espurna#698]
Hi!

Would it be possible to add the Sonoff SV to the list of devices you automatically build a binary for?

Many thanks!

Frederik

**Comment by akasma74** [comment]
I emailed Xose about a week ago about lack of the SV target.
You can add the following in your platform.ini:
[env:itead-sonoff-sv]
platform = ${common.platform}
framework = arduino
board = esp01_1m
board_flash_mode = dout
lib_deps = ${common.lib_deps}
lib_ignore = ${common.lib_ignore}
build_flags = ${common.build_flags_1m} -DITEAD_SONOFF_SV
monitor_baud = 115200
extra_scripts = ${common.extra_scripts}
