### ISSUE TITLE
Internal Schedule to set particular Colour / Dimmer setting rather than just ON/OFF

### ISSUE THREAD

**Issue by oxcxsxixbxaxn** [xoseperez/espurna#700]
The built in scheduler is a great addition and would like to suggest request some improvements.
While I have several sOnOff basic switches I mostly use RGB/RGBW lighting and it would be very useful if the internal scheduler could be set to different dimmer / colour levels and maybe even a local device API command.

**Comment by wysiwyng** [comment]
PWM scheduler support was added to the dev branch with commit 8777d29f7c780bc14396a795c947d777b6d97262. You might need to compile the firmware yourself; see the wiki for excellent instructions; or wait until a new release including this feature comes out.

**Comment by oxcxsxixbxaxn** [comment]
Oh good, seems like what I was looking for.  I compile myself but so far been sticking to stable branch.  I'll take a look.  

Thanks

**Comment by oxcxsxixbxaxn** [comment]
Now implemented as dimmable and switchable per channel 0-3.
released as 1.2.6
