### ISSUE TITLE
Lingan SWA1 Button Not Working

### ISSUE THREAD

**Issue by DJBenson** [xoseperez/espurna#718]
I've got a generic plug from Amazon UK which turned out to be a Lingan SWA1. I've flashed the latest build of Espurna to it but the button does not work. The switch is otherwise fully functional.

    #define BUTTON1_PIN         13
    #define BUTTON1_MODE        BUTTON_PUSHBUTTON | BUTTON_DEFAULT_HIGH
    #define BUTTON1_RELAY       1

EDIT: If the switch is on, the hardware switch actually toggles the relay off but not back on again. If I toggle the switch via the web UI, the physical switch turns it back off but never on.

EDIT2: The BUTTON1_MODE appears wrong (or perhaps specific to the model I have) but I needed to use;

#define BUTTON1_MODE        BUTTON_PUSHBUTTON | BUTTON_SET_PULLUP | BUTTON_DEFAULT_HIGH

To get the switch to respond to both on and off presses.

**Comment by gn0st1c** [comment]
i'll try this with my SWA1 tonight.

**Comment by gn0st1c** [comment]
@DJBenson : with your button1 definition, it works for me too. i've already have a PR fixing this.

btw, from now on, i'll also put the image of version information of the pcb (if available). this may help tracking issues faster/better.

e.g.
https://github.com/xoseperez/espurna/wiki/Hardware-Tonbux-XS-SSA06

**Comment by DJBenson** [comment]
Glad it worked for you too.

**Comment by xoseperez** [comment]
The PR looks good. Just a small glitch to be fixed and it will be merged.

**Comment by DJBenson** [comment]
This plug is labelled as having power monitor capabilities, and there seems to be support for it in the OEM firmware - does anybody have any info on what is required (if anything) to get the power monitor to work with espurna?

**Comment by xoseperez** [comment]
What power monitor chip does it have? I can't find any info on the Internet...

**Comment by DJBenson** [comment]
That was the question really, there is a thread on a well-known UK bargain site which mentions that the official app has power monitoring built in but I can't find any evidence of their being power monitoring outside of that thread. I'm inclined to say it doesn't support it but then I'm intrigued how the WeConn app is reporting energy usage.

**Comment by xoseperez** [comment]
No evidence. Maybe @gn0st1c can tell us if there is any suspicious chip inside...

**Comment by gn0st1c** [comment]
the swa1 device i have, has two separate pcbs inside.

one with esp and other is power+relay. they are connected to each other with only 3 wires. (vcc, gnd, relay toggle). power side has only one IC, thx208. (switching power supply ic)

so at least for the one i got, there is no power monitor.

p.s.: due to some health issues, i should be away from light sources (computers etc) for a while. once i'm well again, i'll check the other swa1 clones i've to see if they are any different.

**Comment by xoseperez** [comment]
Thanks @gn0st1c. Take care!

Closing, since this was merged with #721 into 1.12.5.
