### ISSUE TITLE
quinled switch

### ISSUE THREAD

**Issue by tarbax** [xoseperez/espurna#729]
I'm want to get a seperated switch for each channel so i can work with two different LED-Stripes.
At the Moment there is only one ON/OFF switch witch powers all channels the same way. that is good for color temperature changing led stripes. but i want to controll 2 different led stripes from one controller. i used the latest pre compiled version. (espurna-1.12.4-intermittech-quinled.bin)

**Comment by xoseperez** [comment]
You can do that but you will have to build your own image. Look for this code in the `hardware.h` file:

https://github.com/xoseperez/espurna/blob/fa20c47f2905c46628cbdde475e899ecc30368a3/code/espurna/config/hardware.h#L1207-L1231

And change the DUMMY_RELAY_COUNT to 2. This will create a separate toggle for each channel.
