### ISSUE TITLE
.gitignore extended for vscode

### ISSUE THREAD

**Issue by gimi87** [xoseperez/espurna#731]
Hello :) Can you extended the .gitignore file as described below? I am using Visual Studio Code and it always wants to change this file.

.clang_complete
.DS_Store
.gcc-flags.json
.pioenvs
.piolibdeps
.python-version
.travis.yml
.vscode
.vscode/.browse.c_cpp.db*
.vscode/c_cpp_properties.json
.vscode/extensions.json
.vscode/launch.json
.vscode/settings.json
custom.h
core_version.h

**Comment by lobradov** [comment]
can you create a PR?

**Comment by gn0st1c** [comment]
how about just;

```
# ignore all files & folders beginning with a dot
.*

# but don't ignore .gitignore
!/.gitignore
```

**Comment by xoseperez** [comment]
@gn0st1c I think it's easier to track the ignores than the exceptions (you just missed .travis.yml).

@gimi87 I would add the entire .vscode folder.

```
.clang_complete
core_version.h
custom.h
.DS_Store
.gcc-flags.json
.pioenvs
.piolibdeps
.python-version
.travis.yml
.vscode
```

**Comment by gimi87** [comment]
It still adds those lines:
```
.vscode/.browse.c_cpp.db*
.vscode/c_cpp_properties.json
.vscode/launch.json
```

**Comment by xoseperez** [comment]
How's that? Those files are under the .vscode folder...

**Comment by gn0st1c** [comment]
@xoseperez : that was my thoughts exactly :)
but, i can relate to @gimi87

for some reason, visual studio (for mac) appends those file names to .gitignore, even if the .gitignore already includes those file names.

**Comment by xoseperez** [comment]
OK, I guess we should kneel to MS wishes :smile:

**Comment by xoseperez** [comment]
Staged for release
