### ISSUE TITLE
Web UI issues / questions

### ISSUE THREAD

**Issue by gimi87** [xoseperez/espurna#732]
I am building the firmware with the "custom.h" and "core_version.h" files where the devices have a prepared configuration by preprocessor instructions. Next i am uploading via ota and doing a factory reset, which should run the pre-build configuration. And then i am noticing:

1) After overriding "MQTT_USER" preprocessor define, the MQTT is working, but in the web UI I see "Leave blank if no user".
2) SONOFF_BASIC shows in the web UI's "HTTP port" field value: admin (it should show 80). I can't change this value.
3) H801 shows in the web UI's "Hostname" field value: admin (it should show ESPURNA_xxxxxx). I can't change this value.

Additional question: Is there any chance to change the hostname via "#define" preprocessor instruction?
PS. I am using latest sources.

**Comment by mcspr** [comment]
First one yeah, thats a mqtt module bug only sending values to web from runtime settings and not built-in ones.

I cannot see 2 or 3 with factory reset device:
![keys](https://user-images.githubusercontent.com/132763/37970368-f856498e-31db-11e8-81d9-09804f216df2.png)
![general](https://user-images.githubusercontent.com/132763/37969940-c49bbbe8-31da-11e8-908c-80438c5c1c7c.png)
![admin](https://user-images.githubusercontent.com/132763/37970274-c2143e44-31db-11e8-8934-0539248cf6e8.png)

Can you show relevant parts of your custom headers and output of `keys` command? Can be run from Debug tab. Should be 1 key at most - hostname.

**Comment by gimi87** [comment]
Thanks, that gave me a clue. It turned out that the Chrome was autofilling the fields with "admin" :). Right now only the first point is valid.
And i am still waiting for chance to change hostname by "#define".

**Comment by xoseperez** [comment]
Thank you @mcspr ! Merged and ready to release.

**Comment by xoseperez** [comment]
Staged for release
