### ISSUE TITLE
RGBWW 801 Controller - fadeing speed

### ISSUE THREAD

**Issue by bigd-73** [xoseperez/espurna#739]
hi,

where can i change the fadeing speed for the 801 rgbww controller if i switched the light on or off?

regards
mario

**Comment by Sanfam** [comment]
@bigd-73 , there are two constants you should be able to override that govern transition speed.  I believe both of these are configured in the compiled code and are found within [code/espurna/config/general.h](https://github.com/xoseperez/espurna/blob/master/code/espurna/config/general.h#L703):
```
#define LIGHT_TRANSITION_STEP   10          // Time in millis between each transtion step
#define LIGHT_TRANSITION_STEPS  50          // Number of steps to acomplish transition
```

Reducing the number of milliseconds between steps or reducing the number of steps should speed up each transition, while increasing these values should slow it down.

**Comment by xoseperez** [comment]
Staged for release

**Comment by bigd-73** [comment]
Hallo!

Thank you for integrating the feature in version 1.12.5. But where in the WebUI can I find the functions?

Regard
