### ISSUE TITLE
Web user/pw does not work

### ISSUE THREAD

**Issue by BrianRayJ** [xoseperez/espurna#742]
Hello,

I flashed the Sonoff 4ch Pro with espurna (directly used the bin file from SonOTA, but the user/pw admin/Fibonacci does not work.  Is there a way to bypass this screen, or has the user/pw changed?

Thanks.

**Comment by xoseperez** [comment]
It's "fibonacci", lowercase.

**Comment by BrianRayJ** [comment]
Hi, thanks for your response.  This is what I tried.  It just doesn't work.  I was hoping maybe there was something in the 4 channel pro binary that was different.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by gn0st1c** [comment]
@BrianRayJ : erasing the flash and flashing espurna again should fix your problem.

**Comment by BrianRayJ** [comment]
I have just finished reflashing, and it still does not allow me to login.  Probably a dumb question, but could this be an issue with the "R2" version of the board that I have?  

I'm going to quickly try tasmota or something just to make sure it is accepting the firmware properly.

**Comment by gn0st1c** [comment]
i mention ["erasing the flash"](https://github.com/xoseperez/espurna/wiki/Binaries#erase-the-flash) because i, once, had the same problem.

i don't know what's different about R2 but as long as the pin usage are the same, it wouldn't be an issue.

**Comment by xoseperez** [comment]
@BrianRayJ What binary are you using, or are you building the code yourself? There is nothing specific to the R2 that could cause this issue.

**Comment by darshkpatel** [comment]
Happened with me when I flashed over a previous firmware with a different password , I'd suggest erasing the whole flash and then flashing the binary
