### ISSUE TITLE
espurna is very unstable on my device

### ISSUE THREAD

**Issue by LubergAlexander** [xoseperez/espurna#743]
Hi,

my settings:
board: https://github.com/ArnieX/swifitch
hardware.h:
```
#elif defined(SWIFITCH)

#define MANUFACTURER          "SWIFITCH"
#define DEVICE                "SWIFITCH"

#define BUTTON1_PIN         4 // D2
#define BUTTON1_MODE        BUTTON_SWITCH | BUTTON_SET_PULLUP | BUTTON_DEFAULT_HIGH

#define BUTTON1_RELAY       1
#define RELAY1_PIN          5 // D1
#define RELAY1_TYPE         RELAY_TYPE_NORMAL

#define LED1_PIN            12 // D6
#define LED1_PIN_INVERSE    1
```
platformio.ini:
```
[env:swifitch]
platform = espressif8266
board = nodemcuv2
framework = arduino
board_flash_mode = dout
lib_deps = ${common.lib_deps}
lib_ignore = ${common.lib_ignore}
build_flags = ${common.build_flags_1m} -DSWIFITCH -DDHT_SUPPORT=1 -DDHT_PIN=2 -DDHT_TYPE=DHT_CHIP_DHT11
monitor_baud = 115200
extra_scripts = ${common.extra_scripts}
```

My button on D2 is a regular toggle light switch. I have a DHT11 sensor on pin 2.

build worked fine and I have flashed the firmware. It looks like its working, web ui is available, connected to wifi, the button works correctly, but everything is very unstable, for example, I can toggle the light a few times and then it get stuck, ui becomes unresponsive, sometimes flipping the switch physically helps, sometimes doesn't. After multiple hours of running it quickly toggles the relay sometimes which briefly turns the light on and off.

I tried to debug that by enabling telnet on the UI, but saving options which go through websockets doesn't work, and I can't enable it. The same thing happens with MQTT settings, I tried to set my local mqtt host there, and clicking save does nothing - after refreshing the screen, settings are back to disabled.

Does anyone have an idea why that happens? the chip is the same in most of the supported boards, so I guess I have incorrect build settings? Hardware should be fine because it works stable and correctly with simpler(https://github.com/LubergAlexander/swifitch-software) firmware.

Technical data from main UI screen:
<img width="710" alt="screen shot 2018-03-31 at 9 26 23 am" src="https://user-images.githubusercontent.com/968570/38165262-ac53a2c4-34c5-11e8-9deb-a95038e5c622.png">

**Comment by xoseperez** [comment]
Yes, dev branch is currently unstable. I'm working on it.

**Comment by LubergAlexander** [comment]
I have just tried master branch and it behaves exactly the same, do you have any tips?

**Comment by LubergAlexander** [comment]
@xoseperez also, I have initially flashed it OTA(because the previous firmware had this setup). Do you think it makes sense to disconnect the device and reflash using USB programmer?

**Comment by xoseperez** [comment]
There should be no difference between an OTA-flashed and a wired-flashed device. But I don't recommend using dev version on "production" devices and even less on devices like light bulbs that might require rewiring to recover from a bad flash.

**Comment by LubergAlexander** [comment]
I have now switched to master, but it still works the same way..

**Comment by K1nslayer** [comment]
Sync back to 1.12.4 it is very stable.  Something is bad with 1.12.5.
or get a binary from [here:](https://github.com/xoseperez/espurna/releases)

**Comment by LubergAlexander** [comment]
@xoseperez surprisingly, after I have switched to espressiff8266 1.6.0(arduino core 2.4.0) it works perfectly fine
