### ISSUE TITLE
-DBMX280_SUPPORT=1 for SONOFF-BASIC

### ISSUE THREAD

**Issue by phototobi** [xoseperez/espurna#756]
Hi,
i really love to get help flashing espurna on sonoff basic with BMX280_SUPPORT

I´ve changed the sensor config like i did for dallas and dht support and tried to change the env:itead-sonoff-basic-dht] exchanging -DDHT_SUPPORT=1 with -DBMX280_SUPPORT=1 without success.
Maybe you can add env:itead-sonoff-basic-bmx280 in platformio.ini and help me to get it work.

Thanks in adavance.
Tobias

I´ve already flashed 5 basics for my house, 4 for my fathers house and 4 for families chalet on isle of rugia, baltic sea. It is amazing!

**Comment by xoseperez** [comment]
There is a PR waiting to be merged that will allow you to easily create custom builds. This is a better approach since we want the platformio.ini file to stop growing and as you can imagine adding any possible sensor combination there is simply not feasible or scalable.
