### ISSUE TITLE
Support for Itead Sonoff Pow R2

### ISSUE THREAD

**Issue by ruimarinho** [xoseperez/espurna#761]
The new revision of the Sonoff Pow (R2) is [now available](https://www.itead.cc/sonoff-pow-r2.html). Support for its new features such as live current and live voltage support would be great.

**Comment by xoseperez** [comment]
The POW R2 is based on the CSE7766 power monitor chip (the same in the Sonoff S31). Preliminary support for it is in the sensors branch. I'm awaiting my POW R2 to arrive so I can test it.

**Comment by ruimarinho** [comment]
Fantastic. Can't wait to load Espurna on it :) thank you.

**Comment by ColinShorts** [comment]
I just took delivery of two of them, adjusted the sensor defines, built and flashed. So far the one I'm testing seems to work ok 😀
Thanks Xose!

**Comment by xoseperez** [comment]
@ColinShorts Maybe you can share your configuration?

**Comment by ColinShorts** [comment]
I didn't go too far into it, really just what you hinted at from the current sensors branch:

`$ git diff
diff --git a/code/espurna/config/hardware.h b/code/espurna/config/hardware.h
index 440249e..a319a43 100644
--- a/code/espurna/config/hardware.h
+++ b/code/espurna/config/hardware.h
@@ -372,12 +372,17 @@
     #define LED1_PIN_INVERSE    0
 
     // HLW8012
-    #ifndef HLW8012_SUPPORT
-    #define HLW8012_SUPPORT     1
-    #endif
-    #define HLW8012_SEL_PIN     5
-    #define HLW8012_CF1_PIN     13
-    #define HLW8012_CF_PIN      14
+//    #ifndef HLW8012_SUPPORT
+//    #define HLW8012_SUPPORT     1
+//    #endif
+//    #define HLW8012_SEL_PIN     5
+//    #define HLW8012_CF1_PIN     13
+//    #define HLW8012_CF_PIN      14
+
+    // CSE7766
+    #define CSE7766_SUPPORT         1
+    #define CSE7766_PIN             1
+
 
 #elif defined(ITEAD_SONOFF_DUAL)
`
I've not been into the garage to find an old incandescent bulb to generate a test load, but a phone charger (5V, 2A) was drawing around 13W, so not far from what I'd expect.

**Comment by ColinShorts** [comment]
@xoseperez OK, I can confirm that the first unit reported 58W for a 60W bulb, voltage reported at 238V, so for my purposes at least it is accurate enough. From the few minutes I was observing the watts value didn't seem to populate very well all of the time, but the KWh value seemed to be increasing at around what seemed correct - pretty small increases at that power draw :grinning: 

I know you've got one/some on the way, so I'm happy to wait for you to do the needful, but I'm also willing to generate the config and submit a PR over the weekend - I'll need to spend some time with my good lady, and maybe get some shelves up.

**Comment by ColinShorts** [comment]
Managed to avoid shelves, and submitted a PR while the good lady had a nap 😀 It all seems a bit smoother with the automated checks in place.

**Comment by xoseperez** [comment]
Released with 1.12.6

**Comment by philsson** [comment]
Loaded two of these today with the precompiled binary. I was able to connect to configure both in initial AP mode and enter the credentials for my WiFi. They don't connect to the WiFi but stay in AP mode. The web gui is not reachable (seems down). Both behave the same. 
Konfigurera one of them to have switch on at boot and it seems that unit is in a bootloop but stops switching the relay on/off after some time.

**Comment by ColinShorts** [comment]
It sounds like the unit that stops switching after some time has gone into
safe mode.

I haven't physically installed my R2 units yet (I got them for washing
machine and tumble dryers that need to be pulled out to install), but I'd
suggest that you try flashing an older build than the current one to see if
you find the same issue. I have had some odd things with sonoff t1's that
were "resolved" by configuring on an older version and then updating to
current. Probably unrelated, but might help identify where the problem
started.

If you can confirm what release you are on I can try to reproduce it.

-Colin

**Comment by philsson** [comment]
Thanks for your analysis ColinShorts. I was running 1.12.6 (latest?). I'll try an older build and see how it goes.

**Comment by nilz90** [comment]
installed two of them today. Just flashed the pre build images on it. Everything just works fine except power measurement.
Voltage - works fine
Active Power - 0    no changes under load
Energy - 0 no changes under load

any idea?

**Comment by ColinShorts** [comment]
You might need to roll your own firmware then... You can use git to checkout to a specific commit and then build using platformio, Arduino, etc.

**Comment by philsson** [comment]
Ruimarinho's description fits well on my units as well. No rush to build, I can wait for a new binary no problem. Running tasmota in the mean time.

**Comment by Jaimillo** [comment]
Hi.
I am starting to use Espurna and use a Sonoff Poe R2 device.

Next to the power pins and Tx / Rx, there are ports I04 and I05.
The question I have is whether you can use one of these two ports to connect the data pin of an external sensor (type DHT22) or you have to solder another pin somewhere in the printed circuit, to use another port.

**Comment by Jaimillo** [comment]
I answer myself (I have not been able to stand it and I've got to try it).

Using the PlatformIO platform, I activated the DHT22 sensor on the I5 pin (this is the first time I did it and it has cost me a little) and it works perfectly.
