### ISSUE TITLE
How to approach firmware customization?

### ISSUE THREAD

**Issue by wsw70** [xoseperez/espurna#765]
I have successfully flashed ESPurna on various devices (Sonoff Basic, Touch and a WiFi light). It works great.

Since the usage of these devices is predefined (they switch on, off, set colors, etc.), everything is already in ESPurna and I manage the messaging via MQTT.

I now have a NodeMCU device: 
 
![img_20180407_160432](https://user-images.githubusercontent.com/1345886/38455838-d9e240fc-3a7d-11e8-9854-906c4805ac99.jpg)

This is a nice device because it is powered by a battery (at the back there is a place for a 18650 battery) and I would like to attach a humidity detector to it (or whatever else).

The thing is: I do not know where to start to upload the actual code to

- read the pin values
- send to MQTT the status via WiFi

The coding itself is less of a problem (I use Python or Node, but C will be fine as well) but rather where to put it is. Is it supposed to be in the firmware itself? Loaded on the side?

I know this is a very general question and I would be glad to learn and turn it into a tutorial for newbies like me (and either host it myself or add it to the tutorial section here) - I would just need a few pointers where to start, specifically where the operational code would go (readouts, network messaging).

Any help would be greatly appreciated!

**Comment by mcspr** [comment]
I'd look at some other humidity sensor examples for plain arduino with `digitalRead` / `analogRead` on pins. As reference there are multiple other types of [sensors supported by espurna](https://github.com/xoseperez/espurna/tree/dev/code/espurna/sensors/).

As another example - button module (*code/espurna/button.ino*) and it's library [DebounceEvent](https://bitbucket.org/xoseperez/debounceevent) can give insight about why treating `digitalRead` for pushbuttons as truth every single time may not be enough and how it sends data to the mqtt.

And make sure to make cheat-sheet about gpio numbers and nodemcu pins :) D3 is GPIO0 etc.
