### ISSUE TITLE
Question about Sonoff TH

### ISSUE THREAD

**Issue by paveleremin** [xoseperez/espurna#766]
Any body know what should be done to get dry contacts instead of main voltage at Sonoff TH?

**Comment by paveleremin** [comment]
I found only this information:
![38470656-e4a18600-3b6e-11e8-86aa-8916e842fce0 1](https://user-images.githubusercontent.com/5212490/38500801-1e4e2282-3c14-11e8-8f5c-12d2e3a4e2a0.png)
Here is my implementation:
![38470757-0be99b5c-3b70-11e8-9d89-f3f076f359e7 1](https://user-images.githubusercontent.com/5212490/38500816-294891b8-3c14-11e8-9d6b-5d6c47f3f241.JPG)
but seems still mains at the output
@xoseperez maybe you know?

**Comment by gn0st1c** [comment]
description looks good, implementation not so much. (looks like there is solder residue around the relay contact and the Live In fuse track). Make sure there is enough gap in between. 

![sonoff-th16-relay](https://user-images.githubusercontent.com/12406166/38502281-a876a076-3c17-11e8-8ea7-13aa8d378416.jpg)

**Comment by gn0st1c** [comment]
@paveleremin : my suggestion would be just desolder the relay. cut the tracks. resolder relay back.
