### ISSUE TITLE
Arilux LC-01

### ISSUE THREAD

**Issue by gn0st1c** [xoseperez/espurna#797]
LC-01 is RGB only.
where did this WHITE channel came from? is there another LC-01 with RGBW? (google shows only RGB versions)

https://github.com/xoseperez/espurna/blob/072dd04aafd43079aba5470f8e385552816011bf/code/espurna/config/hardware.h#L1278

**Comment by xoseperez** [comment]
Mmm... probably a copy+paste. Safe to remove I guess.

**Comment by xoseperez** [comment]
Staged for release. Closing.
