### ISSUE TITLE
Name of Espurna device should not be forced to upper case

### ISSUE THREAD

**Issue by swilson86** [xoseperez/espurna#799]
The name of a Espurna device shows up when viewing the pages in upper case at the top left of each screen. On the General page the correct upper/lower case name appears under Hostname. MQTT and other programs are case sensitive. It's a minor annoyance to have to go to the General / Hostname page to recall whether a device is named "Bar Light left" or "Bar Light Left" for example. Not a big issue, but an easy fix for the next release. Thanks!

**Comment by xoseperez** [comment]
Staged for release. Closing.
