### ISSUE TITLE
MQTT not connecting on POW

### ISSUE THREAD

**Issue by steff517** [xoseperez/espurna#804]
Hi,
I'm not able to get the Sonoff POW connected to MQTT (mosquitto). I'm running 1.12.5 and it keeps disconnnecting.
On the same device verstion 1.12.3 is running correctly and it connects to the very same server (and same credentials) without issues. The connection is plain text (without TLS) from the same Wifi.

**Comment by AlexMekkering** [comment]
I don't have any issues connecting my Sonoff POW (1.12.5) to mosquitto. Did you check the mosquitto logs?
