### ISSUE TITLE
Schedule Dimmer only operates Channel#0

### ISSUE THREAD

**Issue by oxcxsxixbxaxn** [xoseperez/espurna#807]
Using a magichome 2.0 and finally go around to updating firmware to try the schedule-able dimmer support, but it seems to not be much use as the only channel offered is channel#0.
Am I missing something? would like to be able to schedule any of the 4 channels (RGBW) not just RED.

**Comment by xoseperez** [comment]
It does show up for me. Can you check if there is any javascript error in your browser?

Anyway I've made some changes to the code.

**Comment by oxcxsxixbxaxn** [comment]
Now showing all 4 Channels, numbered 0-3 and working well.  Thanks
Web page dialog still refers to "Channel 4"...
