### ISSUE TITLE
Support for Arilux LC-XX RF remote

### ISSUE THREAD

**Issue by remay** [xoseperez/espurna#820]
There's a good description of the full range of Arilux AL-LCxx controllers (aka Magichome 1.4 or 2.0 in this repository) here: https://github.com/mertenats/Arilux_AL-LC0X .   This is a placeholder enhancement request to add support for RF remote supplied with the LC09/LC10/LC11 models.

**Comment by Fietspomp86** [comment]
#469 

Already posted this issue :-)
