### ISSUE TITLE
WebSocket API

### ISSUE THREAD

**Issue by adrianromero** [xoseperez/espurna#825]
I have a sonoff basic with the espurna firmware installed, and Iam using the REST API to switch it on and off, but I would like also to be notified if the relay status change. I inspected the web interface and I found it uses websockets to get a notification when the status of the relay changes so I assume the firmware already comes with this functionality out of the box.

My question is. Is there documentation about how to use websockets? It would be great to be able to use websockets to interact with espurna.

Thanks in advance

**Comment by lobradov** [comment]
Hi Adrian,

people usually use MQTT for controlling relays and getting notification of
status changes, but REST API/WebSocket is definitely another option.
Unfortunately, WebSocket part doesn't seem to be documented as present, but
you can help change that by starting a Wiki page (new page called
"WebSocket" under "Integrations" seems like a good place) and documenting
your findings.

As for relays and their WebSocket exposure, I suggest you check
`code/espurna/relay.ino` and find what you need.

Thanks!
