### ISSUE TITLE
Sonoff T1

### ISSUE THREAD

**Issue by seetendra** [xoseperez/espurna#829]
Hello Guys
Iam trying getting the sonoff T1 3 Gang Uk version to work with Espurna
It had Tasmota in it which i flashed using SonOTA 
But it was my bad i flashed the wrong firmware instead of Sonoff T1 i flashed the Sonoff Touch
and it stopped working. (this was when i was moving from Tasmota to Espurna)
I have now flashed again esptool.exe 
but now it is not showing me the SoftAPmode any more it is just a blue light blinking and nothing else it happening.
When i press and hold the button 1 continuous  i get 1 beep and then 2 beep and the the button goes off.
What am i doing wrong?
BTW the buttons work fine now after the flash with serial else it was just the First button.

**Comment by xoseperez** [comment]
Do you still have access via serial? If so try getting the debug log to see what's going on. You can use terminal commands to configure the wifi credentials from the console. Check this: https://github.com/xoseperez/espurna/wiki/Terminal

**Comment by seetendra** [comment]
Sure let me try and i will get back to you with the logs

**Comment by seetendra** [comment]
@xoseperez  I just tried to flash the Ti again and this time iam able to get all the buttons to work but for some reason iam not able to get device to come in SoftAP mode to configure it
Looks very strange.

**Comment by xoseperez** [comment]
Yes, the logs can help find out what going wrong...

**Comment by seetendra** [comment]
Any Guide on how to do a log capture using serial

**Comment by xoseperez** [comment]
Just connect the wire like you did when you first flashed it and then open a terminal session to it. You can use the Arduino IDE "serial monitor" or other equivalent tools like minicom, picocom, screen,... for linux/mac. If using a different OS search for serial monitor tools. Whatever tool you use, ensure you set it to 115200 baud.

**Comment by seetendra** [comment]
Ok i will give it a try right now
I use Atom on a mac most of the times.

**Comment by seetendra** [comment]
@xoseperez  Hey sorry for the delay in getting back to you with the details
Here you go

This the is error iam getting 

epc1=0x4022db40, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000000, depc=0x00000000
Fatal exception (0):

**Comment by xoseperez** [comment]
Well I will need a little more info. If you can capture the log just before the exception and the exception stack it could be a start point...

**Comment by seetendra** [comment]
I don't see any thing except this and this keeps repeating all over again.
I did try the reset command 
I will check again once i reach back home and see if we can get some more info

**Comment by seetendra** [comment]
Please close the issue
Iam going make some update in the WIKI
