### ISSUE TITLE
Bug: Stress test of set channel on Sonoff bulb failed

### ISSUE THREAD

**Issue by dddsssasa** [xoseperez/espurna#832]
I'm testing stability of mqtt on diffrent devices and one test doesnt pass (On sonoff bulb). 

How to reproduce it:

send 5000 messages mqtt_topic=sh-device/lm-bulb/channel/0/set, payload=150 to sonoff bulb and run test for 10 times. One attemp of 10 cause device crash and must be hard reset (ping doesnt reposponse). In other attemps bulb began response after 5 seconds.

Used Mqtt broker: ActiveMQ or Mosquitto

**Comment by xoseperez** [comment]
ESPurna is not meant for this kind of use.
