### ISSUE TITLE
wifi:201: error: 'DNSServer' does not name a type  DNSServer _wifi_dnsServer;

### ISSUE THREAD

**Issue by chryss44** [xoseperez/espurna#843]
Hi guy,
I have tried to compile 1.12.6 and have this error, witch library can i change to have no error ?
Do you have repository with link to all necessary library  ?

**Comment by dartfrogdk** [comment]
i updated the justwifi lib still get 'DNSServer' does not name a type

**Comment by mcspr** [comment]
@dartfrogdk justiwifi removed it 
since, espurna included it instead: https://github.com/xoseperez/espurna/commit/6a12c0228719a4bade4376394a165ea0990ed311

**Comment by xoseperez** [comment]
Yes, update both the library and your ESPurna working copy, please.

**Comment by dartfrogdk** [comment]
updated and working thanks

**Comment by xoseperez** [comment]
Great
