### ISSUE TITLE
SWITCH STATE WHEN MQTT DISCONECTED NOT WORKING

### ISSUE THREAD

**Issue by luizhdinizf** [xoseperez/espurna#845]
I Need a way that when my wifi falls or for any other reason the conection to the broker fails, the esp must turn off all the relays, there is an option on the web interface but if i change it, and then save, the browser gives me a popup no changes detected, it seens that its not implemented or unflaged in the compilation?

**Comment by Audiobuzz** [comment]
Confirmed with my sonoff-pow-2 that updating this setting to "Turn the switch ON", doesn't get saved. Even with a save and then a reboot this setting reverts back to "Don't Change"

**Comment by xoseperez** [comment]
There was a wrong naming in the HTML... fixed in dev branch.
