### ISSUE TITLE
Double-quoted unuit_of_measurement in Home Assistant MQTT discovery

### ISSUE THREAD

**Issue by PhilRW** [xoseperez/espurna#849]
Using the 1.12.6 Sonoff S31 firmware, I added the device to Home Assistant via MQTT discovery. Everything works well except the sensor measurement units contain quotations:

`2018-05-09 12:02:01 DEBUG (MainThread) [homeassistant.components.mqtt] Received message on homeassistant/sensor/ESPURNA_ABCDEF_3/config: b'{"name":"ESPURNA_ABCDEF energy","platform":"mqtt","device_class":"sensor","state_topic":"ESPURNA_ABCDEF/energy","unit_of_measurement":"\\"kWh\\""}'`

**Comment by xoseperez** [comment]
Merged into dev.
Thank you!
