### ISSUE TITLE
TYWE3S Support

### ISSUE THREAD

**Issue by sandman72** [xoseperez/espurna#852]
I had some time today to play around with an EStink Wifi Smart plug strip ( https://amzn.to/2I9477J ). It's based on the TYW3S wifi controller modules that have an ESP8266 chip in them. 

These work just like generic ESP8266 1M boards, but I had to manually reset it just before uploading.
Here is the TYWE3S module pinout for reference:

![tywe3s](https://user-images.githubusercontent.com/26872898/39893768-1cddd5f6-54a5-11e8-8d5b-014e61d1eb3f.jpg)

Here is a hardware definition for it if anyone is interested: 
   
    // ESTINK 4 USB ports plus 3 Relay
    #elif defined(ESTINK_WIFI_RELAY)

    // Info
    #define MANUFACTURER        "ESTINK"
    #define DEVICE              "WIFI_RELAY"

    // Buttons
    #define BUTTON1_PIN         16
    #define BUTTON1_MODE        BUTTON_PUSHBUTTON | BUTTON_DEFAULT_HIGH
    //    #define BUTTON1_RELAY       1

    // Relays
    #define RELAY1_PIN          14  // USB power
    #define RELAY2_PIN          13  // power plug 1
    #define RELAY3_PIN          4   // power plug 2
    #define RELAY4_PIN          15  // power plug 3
	
    #define RELAY1_TYPE         RELAY_TYPE_NORMAL
    #define RELAY2_TYPE         RELAY_TYPE_NORMAL
    #define RELAY3_TYPE         RELAY_TYPE_NORMAL
    #define RELAY4_TYPE         RELAY_TYPE_NORMAL

    // LEDs
    #define LED1_PIN            0   // power led
    #define LED2_PIN            12  // power plug 1
    #define LED3_PIN            3	// power plug 2
    #define LED4_PIN            5   // power plug 3

    #define LED1_PIN_INVERSE    1
    #define LED2_PIN_INVERSE    1
    #define LED3_PIN_INVERSE    1
    #define LED4_PIN_INVERSE    1
	
    #define LED2_MODE	LED_MODE_FOLLOW
    #define LED3_MODE	LED_MODE_FOLLOW
    #define LED4_MODE	LED_MODE_FOLLOW
	
    #define LED2_RELAY	2
    #define LED3_RELAY	3
    #define LED4_RELAY	4

**Comment by xoseperez** [comment]
Nice. Do you want to do a PR with your configuration?

**Comment by sandman72** [comment]
I haven't setup a git repo for it. It might be best/easiest if you just add it to the configuration.h

**Comment by xoseperez** [comment]
No problem. I can add it myself. Thank you!

**Comment by xoseperez** [comment]
Staged for release
