### ISSUE TITLE
Update of Hardware Itead Sonoff RF Bridge Direct Hack page for R2 boards

### ISSUE THREAD

**Issue by wildwiz** [xoseperez/espurna#858]
Here are the new images to be added to the wiki for the revised page:
https://github.com/wildwiz/espurna/wiki/update-sonoff-bridge-images.tar.gz
the old images rf-hack-* can be deleted

The [page update](../wiki/Hardware-Itead-Sonoff-RF-Bridge---Direct-Hack) resolves the issue #854

**Comment by xoseperez** [comment]
Done, thank you!
