### ISSUE TITLE
Programmatically disable relay

### ISSUE THREAD

**Issue by LubergAlexander** [xoseperez/espurna#860]
Is it possible to mark a switch as always on or off via UI? Some of my switches control outlets, and it would be cool to be able to accept the button input(to bind some other action via MQTT), but to NOT switch the relay associated with the button.

I can, of course, upload a custom firmware, but it would be more convenient to do it at runtime.

**Comment by xoseperez** [comment]
You can define a button not linked to any switch so you will still have button event reports via MQTT and at the same time you can have the relay set to a certain value. But yes, it still requires you to change the settings in the hardware.h file and upload your own image...

**Comment by LubergAlexander** [comment]
Alright! will do it this way then.

**Comment by Fusseldieb** [comment]
That would be neat. We need an option to disable those relais programatically.
