### ISSUE TITLE
SonOff RF switch: how to pair remote

### ISSUE THREAD

**Issue by Ivasar** [xoseperez/espurna#868]
A newbie question (probably) from a newbie user (definitely).
I have a SonOff RF WiFi Switch flashed with the latest "espurna-1.12.6-itead-sonoff-rf.bin".
I am having problems to pair it with any RF remote. I can't find instructions about how to make it go into pairing mode.
I have read in some of the solved issues here that the espurna firmware does not change the RF capabilities of these units, is that correct? That would explain why it is not covered in the documentation here... :-)
Can anyone point me then in the direction of the "how to" information? Anyone that has one of these thingies that can help me?
Best regards,
Ivasar

**Comment by Ivasar** [comment]
Thanks for the reply, wildwiz. But I don't understand what you mean with "the RF page".
My intention is not going beyond, just making a simple remote work, but I will take a look at the link you provided because one never knows... :)

**Comment by wildwiz** [comment]
My bad Ivasar ... I read Sonoff RF *Bridge*, not Sonoff RF *Switch* !!!

**Comment by Ivasar** [comment]
Ah, yeah ok, no problem. Yep, finding a lot of references for the bridge, but not much for the switch. A couple comments about how it is paired like the Slampher (and even the Touchs), but can't make it work with a double clic on the button or anything (basically, never get a "red blink" on this unit).

**Comment by xoseperez** [comment]
You are right, since ESPurna does not change the code in the microcontroller that manages the RF the pairing process is the same as in the stock unit. The documentation on how to do it is iin the Itead wiki page: https://www.itead.cc/wiki/Sonoff_RF
