### ISSUE TITLE
Failsafe mode in response to MQTT disconnect or last will topic event

### ISSUE THREAD

**Issue by Audiobuzz** [xoseperez/espurna#869]
I've been looking through the web interface and the documentation and I'm yet to see this as an option.

I use sonoff devices to control a number of items in the house but there are still failure cases that might leave the devices either running for too long, or not running at all. In particular I use Home Assistant to turn on things like sprinker circuits, or pool pumps, or to turn off fridges overnight (non-critical ones).

What would be great would be to be able to define a failsafe state (much like the power on state) that is triggered based on either disconnection from wifi, disconnection from the MQTT broker, or in response to an MQTT last will and testiment (LWT) topic being published. Home assistant allows the definition of a LWT but this seems to be a single global LWT that occurs when it dies or disconnects. Being able to configure ESPURNA to subscribe to a particular topic and revert to failsafe mode (configurable either on or off per relay) would be a great step towards being more robust as a complete system.

If this work isn't planned or hasn't been done yet then I'll look at doing the development work and creating a pull request but I don't want to double up on someone elses effort.

Thanks

Jarrad

**Comment by xoseperez** [comment]
Currently there is no way to subscribe to specific topics... so you will basically need a "translator" that listens to your HA LWT and translate forward it to your device(s) to turn them ON/OFF or whatever you want. In my case I would do it from outside (Node-RED for instance).
