### ISSUE TITLE
Underscores should be disallowed or at least warned in hostname

### ISSUE THREAD

**Issue by iMartyn** [xoseperez/espurna#874]
Underscores have a reserved meaning in DNS, they also cause certain devices (notably some android phones) to not see the AP.

This creates problems downstream, so we should warn users at the very least that the hostname is likely to cause problems.

**Comment by xoseperez** [comment]
I have added checks to the hostname following these rules: 
"RFCs mandate that a hostname's labels may contain only the ASCII letters 'a' through 'z' (case-insensitive), the digits '0' through '9', and the hyphen. Hostname labels cannot begin or end with a hyphen. No other symbols, punctuation characters, or blank spaces are permitted."
