### ISSUE TITLE
influxdb send sensor by id is not working

### ISSUE THREAD

**Issue by lfarkas** [xoseperez/espurna#882]
this is the code snippet from influxdb.ino:
```
bool idbSend(const char * topic, unsigned char id, const char * payload) {
    char measurement[64];
    snprintf(measurement, sizeof(measurement), "%s,id=%d", topic, id);
    return idbSend(topic, payload);
}
```
it's clear that it's only change the measurement and do nothing with this result. it should have to send the measurement  as the topic in the last line.

**Comment by xoseperez** [comment]
You are right. Fixed in dev. Thank you!
