### ISSUE TITLE
rf bridge and energenie remotes

### ISSUE THREAD

**Issue by EmmanuelLM** [xoseperez/espurna#885]
Hello, I have successfully installed ESPurna on RF Bridge R2 v1.0 and flash the direct firmware.
I am using some energenie wall sockets with an rf remote.
The Espurna learns the code perfectly (on: C00100001800A1C0A3; off: C00100001800A1C0A2), and when I press the remote I can see the switch toggle in the web interface.

My issue is: the Espurna is unable to play the codes to toggle the sockets :-( I can see the little red light on the board flashing when it sends the code but nothing happens.

Any help would be appreciated!

**Comment by wildwiz** [comment]
Hi, since you have installed the direct firmware, I am assuming that you have also applied the hardware changes. The codes you receive confirm that the RX signal reaches the ESP8285.

The first thing that comes to mind to me is that maybe you didn't cut the trace between the EFM8BB1 and the transmitter. In that case, the signal from ESP8285 would be entirely blocked and no transmission can happen. 

A relatively simple way to check if the pulses get there is to temporary put an LED between the TX side (the point marked R13 on the mod page) of the resistor you added and ground. This will temporary block the tramsitter, but you should see the led flashing when the ESP8285 wants to transmit to RF.

If that is ok, it would be great to have a dump of the rf pulses to analyze it (either as a sampling of the waveform of the whole transmission or as sequence of pulse timings of the same). I have a pending PR that can put the modified bridge in RF trace mode and extract the timings directly from its radio. You can find it here https://github.com/wildwiz/espurna/tree/on-rx-dump and the documentation is here #864

**Comment by EmmanuelLM** [comment]
HI, I double checked all the tracks with a multimeter and they are cut :-)
I will try the LED debug and then send you the traces... int he meantime I tried to reflash the chip and now I cannot connect to the AP :-S .... will be back when it is fixed

**Comment by EmmanuelLM** [comment]
OK, debug one: 
- the LED flashes
BRB, for debug 2

**Comment by EmmanuelLM** [comment]
hmm, there is a compile error with the code - something with the googletest library... that's the end of my capabilities I'm afraid...

**Comment by wildwiz** [comment]
Here is a build of the *-direct version with the diagnostic patch applied.  
Please remember that is is a dev version, not an official release.  
https://raw.githubusercontent.com/wiki/wildwiz/espurna/files/espurna-1.12.6-itead-sonoff-rfbridge-direct-dignostic-ota.bin

**Comment by EmmanuelLM** [comment]
Ok, will try that

**Comment by EmmanuelLM** [comment]
Ok, thanks for providing the debug firmware, much appreciated!
The Espurna has learned both codes. Here is the debug when I press the remote button (on then off), which the Espurna detects fine:

[131115] [WEBSOCKET] Requested action: dbgcmd
[133978] [RFBRIDGE] RF buffer dump is enabled, quenching is on
[133981] [RFBRIDGE] RF buffer count: 50, data:  6637 659 173 245 582 662 181 242 594 237 593 242 591 244 589 652 182 651 183 648 186 238 599 234 596 234 599 236 596 237 595 237 599 643 188 236 598 645 188 236 599 234 598 235 597 645 188 645 186 234
[134130] [RFBRIDGE] Received code: 00A1C0A3
[134132] [RFBRIDGE] Action 0xA4
[134133] [RFBRIDGE] Forward message 'C00100001800A1C0A3'
[134134] [RFBRIDGE] Trying to match code A1C0A3
[134136] [RFBRIDGE] Match ON code for relay 0
[134141] [RELAY] #0 scheduled ON in 0 ms
[134154] [RELAY] #0 set to ON
[135157] [RELAY] Saving mask: 1
[140553] [RFBRIDGE] RF buffer count: 50, data:  6630 668 166 256 580 655 179 244 585 252 585 247 586 247 586 660 172 658 177 653 182 240 595 237 596 237 596 236 595 241 594 238 594 649 184 238 594 652 183 238 597 236 598 236 594 649 185
[141629] [RELAY] Saving mask: 0
[146610] [WEBSOCKET] Requested action: dbgcmd

And here is the output when I use the Espurna to toggle On and then Off:

[371082] [WEBSOCKET] Requested action: relay
[371085] [RELAY] #0 scheduled ON in 0 ms
[371090] [RELAY] #0 set to ON
[371093] [RFBRIDGE] Enqueuing MESSAGE 'C00100001800A1C0A3' 4 time(s)
[372543] [RELAY] Saving mask: 1
[380065] [WEBSOCKET] Requested action: relay
[380068] [RELAY] #0 scheduled OFF in 0 ms
[380071] [RELAY] #0 set to OFF
[380074] [RFBRIDGE] Enqueuing MESSAGE 'C00100001800A1C0A2' 4 time(s)
[381524] [RELAY] Saving mask: 0

**Comment by EmmanuelLM** [comment]
Looking at this, I wonder if I have a dud board? should RFBRIDGE show the RF data when sending?

**Comment by wildwiz** [comment]
the processor cannot sense the RF input pin while sending because ... well, it is dedicating to the output pin in that moment. It is normal that you dont's see the RF dump.I will have a look to the timings of this RC and try to see what's going on !

**Comment by EmmanuelLM** [comment]
Fyi, I tested with a different board (just in case), and get the same
result.

**Comment by wildwiz** [comment]
I have found what's the issue ... working on a patch !

**Comment by EmmanuelLM** [comment]
Amazing! If I can help in any way, let me know!

**Comment by ruben0909** [comment]
Same here! Thank you. :D

**Comment by wildwiz** [comment]
Hi, I have just built a _*test*_ firmware that should work for the pulses you sent to me. Would you please give it a try and see if it really does ? You find it here: https://raw.githubusercontent.com/wiki/wildwiz/espurna/files/espurna-1.12.6-itead-sonoff-rfbridge-direct-885-test.bin

**Comment by EmmanuelLM** [comment]
No problem, will test in the next hour or so.

**Comment by EmmanuelLM** [comment]
It works!!!!! you're a genius!! Beer's on its way :)
