### ISSUE TITLE
REST API: one common status page

### ISSUE THREAD

**Issue by lfarkas** [xoseperez/espurna#886]
currently is very complicated to query all sensors data ie.

- first  call /apis
- then call all api endpoint and each call gives only one value.

eg it'd be very useful if i can call a /api/status which gives a "real" json result with all sensor data.

**Comment by lfarkas** [comment]
of course it could be a graphql api which would be more user friendly but in this simple case may a rest api would be enough. for the only the query will be important (and wouldn't like to call 3-10 http request just to get 3-10 simple value. i review the current influxdb interface and decided that i'd rather write my own telegraf input plugin. but with this so many call it's rather annoying...
anyway setting all parameters which one can also modify on the web interface would be useful.

**Comment by thebradleysanders** [comment]
Enhancement: Add RSSI, Uptime, avg load... To rest api similar to how data is transmitted to MQTT.
This would be a great addition as I want to build a status panel in PHP to see all my Sonoffs without the need of MQTT. Thank you.

**Comment by Cabalist** [comment]
RSSI would be great!

**Comment by mcspr** [comment]
ref. https://github.com/xoseperez/espurna/pull/2332
