### ISSUE TITLE
Led in LED_MODE_WIFI does not blink properly when in AP

### ISSUE THREAD

**Issue by g-arais** [xoseperez/espurna#900]
I think the problem is in the return of the wifiConnected () function in ledLoop().

It is returning false when in AP mode. I solved by changing the code to:
`if (_ledMode(i) == LED_MODE_WIFI) {`
`if (wifiConnected()) {`
`                if (WiFi.getMode() == WIFI_AP) {`
`                    _ledBlink(i, 900, 100);`
`                } else {`
`                    _ledBlink(i, 4900, 100);`
`                }`
`            } else {`
`                _ledBlink(i, 500, 500);`
`            }`
`        }`
Anyone else noticed this?

**Comment by xoseperez** [comment]
You are right... but this code is going through a major refactor right now. I will check the new code does not have this issue, thank you!
