### ISSUE TITLE
H-801 with newest firmware resets with string lights

### ISSUE THREAD

**Issue by jmlankford** [xoseperez/espurna#904]
I have flashed several H-801 devices successfully, and have had set them up to control general RGBW light strips with no issues. The Espurna firmware is incredibly well written and powerful. 

When I take a flashed H-801 and use it to drive a 48ft Feit RGBW string light set (hanging bulbs), I'm able to set basic colors (Red, Blue Green, and any mix between the three), but once I begin changing the settings to include white, the entire light string begins flashing bright white, accompanied by the H-801 red LED flashing at the same rhythm. This continues until I unplug the lights from the unit. 

Note: it will continue if I try to reboot from the web interface, and it will continue if I cut power, wait, and plug back it. It only stops blinking if I disconnect the lights. 

Is this a voltage issue? Are the lights calling for too much and confusing the controller? Is there a setting that mitigates against this? I have tried multiple controllers that successfully control normal strip lights without issue on the strip lights, but this issue persists when I switch over to the string lights. All of them have this blinking lights problem. Am I missing something completely?

**Comment by timgray** [comment]
That is absolutely a power issue. 48 feet is a LOT of power used,  your power supply is most likely not big enough,   I'd start at 5 amps.  but here is another problem,  I would not trust the transistors in the 801 to drive 5 amps without failing.   cut the string in 1/2 and get 2 801's  one to drive each half.

**Comment by jmlankford** [comment]
On one hand, that's strange, as the OEM supply for this light strip is 3A output. On the other hand, as you said, 48 feet is long I suppose. Even though the lights may not be drawing anywhere near 5A, I do realize that with it being such a long cable, I may experience other issues. 

What I don't get is:

1.) This only happens with white. If I drive the color lights 100%, they're fine. If I drive the color lights to 0% and the white to something small like 1%, it craps out, and the lights begin flashing bright, along with the H801. 

2.) This is not a question of skepticism, but a question of curiosity: once the blinking begins, unplugging the H801 from the power supply does not remedy it. I cannot reset it from the web (UI goes offline). The only way to resolve it is to unplug the string of lights from the device itself. Why is that?

**Comment by timgray** [comment]
I am using the latest on 2 801’s on a pair of 10ft rgb was strips and had that exact problem with a weak power supply.  It was not delivering a solid 12-13 volts at the far end causing those less to draw way more amps due to. The lower voltage.    One other thought is the light string was not designed to have color and white at the same time with the white less higher power consumption.  What if you manually power the 12v and the white line on its own and measure current?

**Comment by flashy02** [comment]
I can only repeat the statement of timgray. My try of using one 5A 12V power supply for round about 24m RGBW stripes (4xH801) ended in flashing lights (the setup befor with this supply an Mi-Light controllers worked fine).  Now, the Setup with 4x 12v 5A supplies works fine with H801. I think this behaviour is a voltage sensitivity of the H801/ESP8266.
