### ISSUE TITLE
Implement IR transmit

### ISSUE THREAD

**Issue by izharm** [xoseperez/espurna#907]
Hi,

the wiki says "Enable IR Receiver / Transmitter support".  Does the code actually supports IR transmission ? 
If so, anyone can exp[lain how to use this feature ?

thanks,

**Comment by xoseperez** [comment]
I'm sorry, the wiki was wrong. It only support IR receiving at the moment, although the library is capable of transmitting, this option is not implemented.

**Comment by xoseperez** [comment]
Current version in `dev` branch supports MQTT-to-IR messages (and the other way around), see the ir.ino module header for information about the payload format.
