### ISSUE TITLE
Sonoff pow adding function. IF ACTIVE POWER < 10W* switch on for 6seconds* , *=adjustable. 

### ISSUE THREAD

**Issue by cent0** [xoseperez/espurna#908]
hello it is possible to add the following function to bypass the excess energy, if active energy is lower than a certain value that can be set manually, then switch on for certain seconds. if active energy is greater than the set value switch off.
(Raccomandation this pow measure direct energy meter and this line have grid tie connected with limiter,the relay is for adding extra load , and the time 6 second minimal is for waiting inverter response retraction, if the sun hare insufficient active power is >10W* the relay switch off and disconnect extra load)
This function is more appreciate for bypass Mqtt and domoticz.and one raspberry

😀
This is one other idea for extra function
In case it would also be possible to send a switch on or a switch off addressed to another settable id switch.

More appreciate suggestion for data modification in the source.
Best regards

**Comment by xoseperez** [comment]
Pretty specific. I would do that logic somewhere else. Not hard to implement with Node-RED, for instance...

**Comment by cent0** [comment]
since to send to other devices you are advised to use node-red. it would be at least possible to insert the relay activation function if the active current is <10W* ?

Or help for find code to mod and compile. Without graphic html
Best regards.

**Comment by cent0** [comment]
> Pretty specific. I would do that logic somewhere else. Not hard to implement with Node-RED, for instance...

Hi nodered need one raspberry or one other cpu for database and more...

I need only read the MAGNITUDE_POWER_ACTIVE
And add one istance ...if magnitude ....>?....
     
SEND ONE STRING  HTTP.BEGIN

Thank you
