### ISSUE TITLE
POW R2 no measurement

### ISSUE THREAD

**Issue by nilz90** [xoseperez/espurna#916]
installed two of them today. Just flashed the pre build images on it. Everything just works fine except power measurement.
Voltage - works fine
Active Power - 0 no changes under load
Energy - 0 no changes under load

any idea?

edit:
#867

got it.

build it with the dev branch. Maybe delete the prebuild version for the powR2 until you release 1.12.7 :)

**Comment by xoseperez** [comment]
By default ESPurna will report current and power to 0 if the relay is OFF. Please check if this is your case.

**Comment by gabrielklein** [comment]
Same issue, with the CSE7759B Pow R2 2017-11-30. Everything is reported as 0.
Please note that switching it on/off has no effect on the module.
Pressing the button on the module switch it on/off but is not reported to the web ui.

I work on the latest version using PlatformIO. I have a PowV1 and it's working perfectly.

**Comment by jjviton** [comment]
Hi,

I´m facing a similar issue, I´m not able to read the Power paramater of my flashed POW.

Enviroment: SONOFF POW R2 // Espurna version 1,13 // sensor chip CSE7759

I´ve read in other thread about change parameter using terminal. 

Could you please advise me how to fix this issue?

Thanks in advance.
