### ISSUE TITLE
MagicHome : no wifi

### ISSUE THREAD

**Issue by choriz80** [xoseperez/espurna#920]
Hi

I have same issue like  #210 with magic home.

Firmware flash ok, after restart no wifi.

I erased bios with esptool with success, and then flash again but same result no wifi.

So i 'm a bit lost... hope you could you help me ?

Information on magicHome : Model ESP8285MOD Vendor : ESP-M2
I tried with success with Tasmota (unfortunaltly not interresting)

Regards

**Comment by xoseperez** [comment]
It will be useful to have the debug log while booting and trying to connect to the wifi. Can you open a serial monitor (115200bps) to the device and copy-paste the log here?
