### ISSUE TITLE
no Wifi Connection with 32 characters SSID

### ISSUE THREAD

**Issue by MousterMaener** [xoseperez/espurna#921]
Something like "G9u89POv7zE0nEWgY1J5M1w94kuT0Jt" [32 characters] as SSID is not working. The Device (Itead S20 with espurna-1.12.6-itead-s20.bin) can not connect to the Access Point. Shorter SSIDs with the exact same configuration except the SSID length are working fine. 63 characters for Access Point password is working corretly with espurna.

I had similar issues with [tasmota](https://github.com/arendst/Sonoff-Tasmota/issues/1943). Thats why I tried espurna.

**Comment by xoseperez** [comment]
Leaving it on hold until fixed in the Arduino Core.
