### ISSUE TITLE
ArduinoJson 6.0.x break compilation

### ISSUE THREAD

**Issue by jnogues** [xoseperez/espurna#924]
Hi Xose. If I update ArduinoJson library from 5.13.2 to 6.0.x , I can't compile espurna.

Thanks

**Comment by Allwize** [comment]
Current stable version is still ArduinoJson 5.13.2. 6.0.X is in beta stage.
Anyway I'll take a look to fix possible issues when it gets released.

**Comment by xoseperez** [comment]
Current stable version is still 5.13.2.
6.X is in beta stage but I will take a look to fix possible future issues.
