### ISSUE TITLE
Sonoff T1 UK

### ISSUE THREAD

**Issue by 70newbie** [xoseperez/espurna#925]
Hi Guys, hope the community can help me.
Bought a Sonoff T1 UK single switch version this month and trying to flash it with tasmota version 5.14 and arduino. Read on the wiki page that I need to put this into flash mode, but unsure how to do this. Ive read that I need to ground GPI0 to ground which is achieved by connecting it to FDTI via USB port on PC and then holding touch panel switch and pressing the little button at the bottom and then releasing small button followed by touch button, is that correct? or do I hold a ground wire to R19 on the circuit board for a few seconds? 
2nd question How will I know its in flash mode?
Any help would be grateful as I,ve already bricked one device.

**Comment by ColinShorts** [comment]
Connect the ftdi
Wait for the WiFi light to blink a few times.
Press and hold button 1 (leftmost)
Press button 4 (small push button below), wait for button 1 (2, and 3 if present) to glow dinky then release button 4.
Flash it.

It might take a few attempts, if you still have problems remove and replace the ftdi cable (USB side) and try again.

There's no need to use additional wires to ground gpio0.

**Comment by 70newbie** [comment]
Thanks Colin I will try that when I get back home. So i was on the right track. Thanks for replying so quickly

**Comment by 70newbie** [comment]
Hi Colin. Yep that works, just needed to know I was in the right direction. After a few attempts removed and replaced the ftdi cable into the usb slot and it worked. Now have a tasmotized switch. Thanks again

**Comment by ColinShorts** [comment]
I should probably point out that you're on the wrong forum for tasmota support, but the flashing procedure is the same at this stage 😁.

Happy to close this issue @70newbie?
