### ISSUE TITLE
[Q] Is it possible to configure the firmware via an API?

### ISSUE THREAD

**Issue by wsw70** [xoseperez/espurna#927]
My intention would be to create a post-upgrade centralized distribution of settings to all my ESPURNA devices. I currently have some of the setting hard coded in the firmware but in any case I would like to be able to easily change them  (or harmonize them or whatever).

I know that there is an API which allows to control some of the functions (operational mainly - that is switch on/off, etc.).

Since the settings are controlled by a web interface, I imagine that reverse-engineering it will be doable but I would like first to check whether there are API calls documented (in a way or another, even in code) which could be used,

**Comment by xoseperez** [comment]
See #335
