### ISSUE TITLE
API While using JSON

### ISSUE THREAD

**Issue by thebradleysanders** [xoseperez/espurna#929]
While Making a call to **10.0.0.x/api/rgb?apikey=password** with header **"Accept: application/json"**
the returned data is: **{ "rgb": #FF0000 }**

The RGB value needs to be within double quotes since it is a string. Thanks! -Brad

**Comment by xoseperez** [comment]
Fixed in dev branch. Staged to be released.

**Comment by thebradleysanders** [comment]
xoseperez, thank you.
