### ISSUE TITLE
How to activate RF on 4ch pro r2

### ISSUE THREAD

**Issue by fpalinf** [xoseperez/espurna#936]
Is there a way to activate RF on sonoff 4ch pro r2 ?

I flashed with espurna-1.12.6-itead-sonoff-4ch-pro.bin and cannot find the option.

Or should I rebuild with some specific flags ?

Regards,

**Comment by xoseperez** [comment]
Not 100% sure, I have not tested the R2, but I'd say the RF is handled by the secondary chip, so there is nothing to do from the ESPurna point of view. Pairing and toggling via RF should work the same way it does with the stock firmware.

Check the wiki page for the device: https://github.com/xoseperez/espurna/wiki/Hardware-Itead-Sonoff-4CH-Pro---R2

**Comment by fpalinf** [comment]
My mistake. I thought the rf433 on ch4 was equivalent to the rf433 bridge.
From what I understand the board can only receive and not send commands. 
Would it be still possible to have the same learning capabilities than we see on thr rf433 bridge ? (To see the learned frame ?)
If not how to dissociate the button so getting the rf433 frame will not trigger the relay command ?

**Comment by xoseperez** [comment]
No, the secondary chip only reports the equivalent to button presses and relay statuses, no frames. The only way is to modify the firmware in that chip to make it work like a transparent bridge and handle all logic in the ESP8266. Very much like what has been done with custom firmware for the EFM8 in the RF Bridge. But that's a whole project...
