### ISSUE TITLE
Astronomical feature

### ISSUE THREAD

**Issue by Geroldswil** [xoseperez/espurna#943]
For the schedules, it would be extremely nice to be able to program the events also depending on sunrise or sunset. Eg sunrise -2h or sunset +0.5h for garden illumination etc. 

See also: https://en.wikipedia.org/wiki/Sunrise_equation

Thx

**Comment by mcspr** [comment]
Per #2417, `SUNRISE` and `SUNSET` can be used instead of `HH:MM`
https://github.com/xoseperez/espurna/wiki/SCHEDULER#keywords
