### ISSUE TITLE
wiity cloud ap issue

### ISSUE THREAD

**Issue by unique904** [xoseperez/espurna#944]
im unable to get the witty cloud to work with any espurna fw as well as the specific gizwiz fw
there looks to be an issue with the wifi AP
[000407] [WIFI] MODE AP --------------------------------------
[000407] [WIFI] SSID  ESPURNA_######
[000410] [WIFI] PASS  fibonacci
[000413] [WIFI] IP    0.0.0.0
[000415] [WIFI] MAC   ##:##:##:##:##:##
[000419] [WIFI] ----------------------------------------------
[000425] [MDNS] FAIL
[060003] [MAIN] System OK

**Comment by xoseperez** [comment]
Do you mean it does not work with any of the two firmware images? Have you tested a simple wifi sketch?

**Comment by unique904** [comment]
Just tested the pre released bin files including the core 1mb and core 4mb
Not got as far as using sketch’s

I have loaded espeasy on to it with out any issues so does seam to b a problem with the .bin release
Kind Regards

Craig Bennett

On 15 Jun 2018, at 06:48, Xose Pérez <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you mean it does not work with any of the two firmware images? Have you tested a simple wifi sketch?

**Comment by swilson86** [comment]
I was unaware of pre released bin files, but it brings up an interesting point. They should be labeled Alpha or Beta bin files and some of us can quickly test them to ensure that fixes and enhancements are working prior to a major release. It would be a disaster should a new release fail everyone.

**Comment by unique904** [comment]
Sorry that’s my mistake I meant to say the prebuilt release https://github.com/xoseperez/espurna/releases/



Kind Regards

Craig Bennett

On 15 Jun 2018, at 10:47, swilson86 <notifications@github.com<mailto:notifications@github.com>> wrote:


I was unaware of pre released bin files, but it brings up an interesting point. They should be labeled Alpha or Beta bin files and some of us can quickly test them to ensure that fixes and enhancements are working prior to a major release. It would be a disaster should a new release fail everyone.

**Comment by xoseperez** [comment]
Yes, there are no pre-release binaries (so far) and if there were I would probably not publish them in the same place as the "stable" releases.

**Comment by swilson86** [comment]
Hmmmm Xose. Your caveat "so far" is interesting. I am anxious for example to test the fix on the S31 power measurements. I check daily like a child on Christmas morning to see if 1.12.17 is ready. If I knew how to compile pre-releases or test Beta/Alpha binaries that would be wonderful. This typo mentioning pre-releases brings up an excellent point.

**Comment by mcspr** [comment]
@xoseperez @swilson86 Funny you should ask... builds for issue at hand (dev): https://github.com/mcspr/espurna-travis-test/releases/tag/20180617.3

It was a cloned repository to test parallel jobs for travis releases, but they are still janky for building large amount of images (93 already!) because they cannot easily share already built webui / arduino installation / arduino libraries. And there is an earlier try at https://github.com/mcspr/espurna-travis-test/releases/tag/20180617, until the cache situation gone wrong and it stopped building mid-process.
