### ISSUE TITLE
Sonoff switches option "On MQTT disconnect"

### ISSUE THREAD

**Issue by Interpyme** [xoseperez/espurna#964]
There is a little bug that does not allow to save this option if you want to turn the switch OFF on MQTT disconnect, it reverts to Don´t change primary option.

http://prntscr.com/jxhuut

Thanks for your great work!!

**Comment by xoseperez** [comment]
This is fixed in dev branch: #845

**Comment by C64Axel** [comment]
Hi.
This Bug is also in V1.13.5.
When button SAVE pressed the options for the Switches are reverted to "Don't change" in the config.

Great Work
