### ISSUE TITLE
Sonoff 4CH Pro Wiki page missing?

### ISSUE THREAD

**Issue by akosmaroy** [xoseperez/espurna#974]
Hi,

On the Wiki on the hardware page: https://github.com/xoseperez/espurna/wiki/Hardware  there is a link to a Sonoff 4CH Pro device:
https://github.com/xoseperez/espurna/wiki/Hardware-Itead-Sonoff-4CH-Pro

but it seems this page doesn't exist? when clicking on it, one is lead to an empty page

I wonder what am I missing?

best regards,

Akos

**Comment by akosmaroy** [comment]
via Google I found this page: https://github.com/xoseperez/espurna/wiki/Hardware-Itead-Sonoff-4CH-Pro---R2

**Comment by xoseperez** [comment]
Thank you, I have fixed the link.
