### ISSUE TITLE
Struggling with RF Bridge

### ISSUE THREAD

**Issue by Slowsteve** [xoseperez/espurna#978]
Hi, I have carried out the hardware modifications and flashed the rf bridge with espurna-1.12.6-itead-sonoff-rfbridge-direct.bin. I am able to learn codes for the same remotes that were previously recognised by the unmodified version but don't seem to have any additional functionality. When I type in any of the "OxA?" commands or "OxB1" commands I get the exact same reply:- 
   [WEBSOCKET] Requested action: dbgcmd
                                                                       and no additional responce.
Are there any settings I need to apply and does the position of the on-board switch matter?
I would really appreciate any help as I have  tried to search out a soloution.
Thankyou.

**Comment by xoseperez** [comment]
RFBRIDGE_DIRECT image won't work with the original commands, instead, it will directly talk to the transceiver using the `rcswitch` library.

**Comment by Slowsteve** [comment]
Thanks for your reply. So, there is no user intervention needed, the bridge will either learn or not? Also, what about the physical switch position? 


Sent from Samsung tablet.
-------- Original message --------From: Xose Pérez <notifications@github.com> Date: 23/06/2018  18:52  (GMT+00:00) To: xoseperez/espurna <espurna@noreply.github.com> Cc: Slowsteve <steve.j.filer@gmail.com>, Author <author@noreply.github.com> Subject: Re: [xoseperez/espurna] Struggling with RF Bridge (#978) 
RFBRIDGE_DIRECT image won't work with the original commands, instead, it will directly talk to the transceiver using the rcswitch library.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/xoseperez/espurna/issues/978#issuecomment-399696897","url":"https://github.com/xoseperez/espurna/issues/978#issuecomment-399696897","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/xoseperez/espurna","title":"xoseperez/espurna","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/xoseperez/espurna"}},"updates":{"snippets":[{"icon":"PERSON","message":"@xoseperez in #978: RFBRIDGE_DIRECT image won't work with the original commands, instead, it will directly talk to the transceiver using the `rcswitch` library."}],"action":{"name":"View Issue","url":"https://github.com/xoseperez/espurna/issues/978#issuecomment-399696897"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [xoseperez/espurna] Struggling with RF Bridge (#978)",
"sections": [
{
"text": "",
"activityTitle": "**Xose Pérez**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@xoseperez",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"xoseperez/espurna\",\n\"issueId\": 978,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"xoseperez/espurna\",\n\"issueId\": 978\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/xoseperez/espurna/issues/978#issuecomment-399696897"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 349385989\n}"
}
],
"themeColor": "26292E"
}

**Comment by xoseperez** [comment]
That's right, with this hack the RFBridge will behave like any other device with direct (hence the name) connection to the transceiver.

Since you have cut the traces between the ESP8266 and the secondary microcontroller the switch has only the duty to connect or disconnect the programmer header in the board, you can leave it to programming position all the time.

**Comment by Slowsteve** [comment]
Thankyou
