### ISSUE TITLE
GIZWITS_WITTY_CLOUD sensors do not appear

### ISSUE THREAD

**Issue by AlbertWeterings** [xoseperez/espurna#981]
I have a few GIZWITS_WITTY_CLOUD devices build firmware in Arduino IDE.
Switch #0 and the channels appear in the web interface but no sign of the analog sensor and some Dallas sensors I have connected to it. Also the sensor menu item is missing. The values of the sensors are available in the MQTT messages

I'm building V1.13.0 dev

**Comment by AlbertWeterings** [comment]
Found where the issue is coming from but don't have a solution. This occurs due to "static/index.light.html.gz.h" is used in web.ino if I uncomment "static/index.light.html.gz.h" and use "static/index.sensor.html.gz.h" in the web interface shows the sensors but Lights it then gone.

It seems not possible to have both.

**Comment by xoseperez** [comment]
I see. The thing is that the Witty is a light (so LIGHT_PROVIDER != LIGHT_PROVIDER_NONE). If you add sensors to it if will still use the `static/index.light.html.gz.h`. The solution is to add a `static/index.all.html.gz.h` image and load it when this happens. I'd like to create individual images for each device but that would add too much build time at the moment and increase the build complexity. It's something to reconsider in the future.

**Comment by AlbertWeterings** [comment]
Initially it is a RGB light with a analog sensor. Maybe it is a idea to be able to configure it as it is now, and have a option to configure it as a device with sensors and just 3 LEDs with a on off switch.

I use it with a Dallas sensors and according to the readout of the sensor I have the LED light red, green or blue.

**Comment by AlbertWeterings** [comment]
Disabling in hardware.h
//    #define RELAY_PROVIDER      RELAY_PROVIDER_LIGHT
//    #define LIGHT_PROVIDER      LIGHT_PROVIDER_DIMMER

Brings up the sensors. I will have to check if it is still possible now to control the RGB LED via MQTT if that works in my application this is a good solution.

**Comment by xoseperez** [comment]
I have the fix, I'm checking if other boards have been affected too..

**Comment by xoseperez** [comment]
@AlbertWeterings Can you test the code in the `dev` branch?

**Comment by AlbertWeterings** [comment]
Just flashed it in one device and it now shows both light and sensors. In the morning I will flash it in all devices that are using multiple modules.

**Comment by AlbertWeterings** [comment]
Ok during compiling for RFBRIDGE I run into a error.
web:44: error: operator '==' has no left operand
 #if ITEAD_SONOFF_RFBRIDGE == 1
exit status 1
operator '==' has no left operand

Changing line 44 to "#if ITEAD_SONOFF_RFBRIDGE" is solving this issue
