### ISSUE TITLE
how can i remove an unactive switch from HA MQTT server

### ISSUE THREAD

**Issue by vuiperez** [xoseperez/espurna#982]
i add one switch with auto discovery MQTT to HA but now i remove itand the switch still is on HA how to remove?

**Comment by mcspr** [comment]
You need to restart HA for switch to disappear.

If switch was removed without turning off discovery from espurna side... you can get the switch back on the network and turn the "Discover" switch off in the hass section of web interface. Or run the `ha.clear` command via serial / telnet.

Discovery data is persisted on mqtt server under `homeassistant/switch/{DEVICE-HOSTNAME}_0/config` topic. Send empty message to it with retain flag on to clear it.
