### ISSUE TITLE
Wireless router connection delay

### ISSUE THREAD

**Issue by analistamarcioprado** [xoseperez/espurna#985]
Good evening.

I have one small problem:

I have 4 Sonoff Pow connected to a Wireless network. When the power runs out, all the equipment obviously turns off.

When the power comes back, the 4 Sonoff Pows connect faster than the wireless router.

As a router is not yet ready, Sonoff does not find the wireless SSID and each works as if it were an AP. In this way I lose the connection with them.

Is there any way to slow the Sonoff ligament? Or at least the connection to the AP?

Thank you.

**Comment by xoseperez** [comment]
As @AlbertWeterings the devices should retry connecting after 3 minutes.

**Comment by analistamarcioprado** [comment]
Ah yes, @xoseperez . In the tests I did I did not wait for the 3 minutes.

Thank you @AlbertWeterings .

This afternoon I'm going to test.

**Comment by analistamarcioprado** [comment]
Analyzing the posts again @xoseperez  I realized that I did not understand well. Is this functionality already implemented?

**Comment by frankforpresident** [comment]
@xoseperez, Any plans in making this setting configurable? It would be nice if we could set this retry to 1 minute or what every you like.

**Comment by analistamarcioprado** [comment]
It would be perfect if we could set this time.
