### ISSUE TITLE
Setting up latching relays

### ISSUE THREAD

**Issue by pyrosmiley** [xoseperez/espurna#994]
Can you provide any clarification as to how to configure for latching relays? I've done my best based on the info proved on the [associated wiki page](https://github.com/xoseperez/espurna/wiki/Buttons-and-switches), but I'm still struggling with how espurna handles multiple GPIO pins that represent one switch. As of right now, I have a `custom.h` file set up that includes the following:
```
// Info
#define MANUFACTURER        "NodeMCU"
#define DEVICE              "v2"

// Relays
#define RELAY1_PIN          9
#define RELAY1_TYPE         RELAY_TYPE_LATCHED

#define RELAY2_PIN          10
#define RELAY2_TYPE         RELAY_TYPE_LATCHED 
```
In the web interface, this gives me a device with `Switch #0` on GPIO 12 and `Switch #1` on GPIO 10. Seems like I'm on the right track but to be honest I'm in a little over my head, and extremely lost. What's the best way to set it up, and to call a pulse on the `set` and `reset` pins via MQTT? I have another device set up just fine with a few normally open relays, but this needs to be battery-powered and these latching solenoids hurt my brain......

**Comment by xoseperez** [comment]
Latched relays must be defined like this:

```
     // Relays
    #define RELAY1_PIN          13
    #define RELAY1_TYPE         RELAY_TYPE_LATCHED
    #define RELAY1_RESET_PIN    12
```

It could also be RELAY_TYPE_LATCHED_INVERSE if the logic is reversed
