### ISSUE TITLE
RF Bridge + MQTT + Amazon Echo

### ISSUE THREAD

**Issue by raghunav** [xoseperez/espurna#995]
I have a Sonoff RF bridge with Espurna Firmware and successfully paired Sonoff RF PIR sensors. I do not have any RF switches paired to the Bridge.

I was planning to use the switches as dummy switches to be paired with Amazon Echo but without luck.
The 8 default switches a discovered by Amazon Echo but the ON/OFF are not being set by Alexa.

Is there a way to use these switches as I would then have 8 dummy wemo switches for me to do some actions with HA/Pimatic software. Any pointers on this will be of great help.

**Comment by xoseperez** [comment]
Is there something on the debug log that would help us find out what's going wrong? You said the switches are discovered by Alexa, there should be some feedback on the log when you trigger them using Alexa.
