### ISSUE TITLE
cant find TravisCI.bin

### ISSUE THREAD

**Issue by nkerezov** [xoseperez/espurna#997]
Sorry for another stupid question from me ,but in the hardware.h file I can see very interesting for my needs set ups : Travis C1,C2 and C3. My problem is that I dont see them in the bin files ,or at least not with the same names. As someone that cant use Atom ( sorry ,I really dont have the time to learn such a complex stuff right now) , the .bin files is the way to go for me....
Thank you for understanding and BIG thanks for all your e efforts!!!
Nikolay

**Comment by xoseperez** [comment]
Those are testing environment to run on Travis CI, they are not releasable. Binaries cover the most standard cases, if you need something specific you can build your own image.
